sm_dance_bot::KeyboardClient Class Reference
#include <keyboard_client.h>
Public Member Functions
KeyboardClient ()
virtual ~KeyboardClient ()
virtual void initialize () override
void onKeyboardMessage (const std_msgs::UInt16 &unicode_keychar)
template<typename TEv >
void postKeyEvent ()
Public Attributes
boost::signals2::signal< void(char keypress)> OnKeyPress
boost::signals2::scoped_connection c_
Private Attributes
bool initialized_
Additional Inherited Members
Detailed Description
Definition at line 149 of file keyboard_client.h.
Constructor & Destructor Documentation
sm_dance_bot::KeyboardClient::KeyboardClient () [inline]
Definition at line 155 of file keyboard_client.h.
        {
                initialized_ = false;
        }
virtual sm_dance_bot::KeyboardClient::~KeyboardClient () [inline], [virtual]
Definition at line 160 of file keyboard_client.h.
        {
        }
Member Function Documentation
virtual void sm_dance_bot::KeyboardClient::initialize () [inline], [override], [virtual]
Reimplemented from smacc::SmaccSubscriberClient< KeyboardClient, std_msgs::UInt16 >.
Definition at line 164 of file keyboard_client.h.
References smacc::SmaccSubscriberClient< KeyboardClient, std_msgs::UInt16 >::initialize(), and keyboard_node::msg.
        {
                
      SmaccSubscriberClient<KeyboardClient, std_msgs::UInt16>::initialize
      ();
                if (!this->initialized_)
                {
                        c_ = this->onMessageReceived.connect([this](auto
      msg) {
                                this->onKeyboardMessage(msg);
                                this->initialized_ = true;
                        });
                }
        }
void sm_dance_bot::KeyboardClient::onKeyboardMessage (const std_msgs::UInt16 & unicode_keychar) [inline]
Definition at line 178 of file keyboard_client.h.
        {
                char character = (char)unicode_keychar.data;
                ROS_WARN("detected keyboard: %c", character);
                if (character == 'a')
                        postKeyEvent<EvKeyPressA<KeyboardClient>>();
                else if (character == 'b')
                        postKeyEvent<EvKeyPressB<KeyboardClient>>();
                else if (character == 'c')
                        postKeyEvent<EvKeyPressC<KeyboardClient>>();
                else if (character == 'd')
                        postKeyEvent<EvKeyPressD<KeyboardClient>>();
                else if (character == 'e')
                        postKeyEvent<EvKeyPressE<KeyboardClient>>();
                else if (character == 'f')
                        postKeyEvent<EvKeyPressF<KeyboardClient>>();
                else if (character == 'g')
                        postKeyEvent<EvKeyPressG<KeyboardClient>>();
                else if (character == 'h')
                        postKeyEvent<EvKeyPressH<KeyboardClient>>();
                else if (character == 'y')
                        postKeyEvent<EvKeyPressI<KeyboardClient>>();
                else if (character == 'j')
                        postKeyEvent<EvKeyPressJ<KeyboardClient>>();
                else if (character == 'k')
                        postKeyEvent<EvKeyPressK<KeyboardClient>>();
                else if (character == 'l')
                        postKeyEvent<EvKeyPressL<KeyboardClient>>();
                else if (character == 'm')
                        postKeyEvent<EvKeyPressM<KeyboardClient>>();
                else if (character == 'n')
                        postKeyEvent<EvKeyPressN<KeyboardClient>>();
                else if (character == 'o')
                        postKeyEvent<EvKeyPressO<KeyboardClient>>();
                else if (character == 'p')
                        postKeyEvent<EvKeyPressP<KeyboardClient>>();
                else if (character == 'q')
                        postKeyEvent<EvKeyPressQ<KeyboardClient>>();
                else if (character == 'r')
                        postKeyEvent<EvKeyPressR<KeyboardClient>>();
                else if (character == 's')
                        postKeyEvent<EvKeyPressS<KeyboardClient>>();
                else if (character == 't')
                        postKeyEvent<EvKeyPressT<KeyboardClient>>();
                else if (character == 'u')
                        postKeyEvent<EvKeyPressU<KeyboardClient>>();
                else if (character == 'v')
                        postKeyEvent<EvKeyPressV<KeyboardClient>>();
                else if (character == 'w')
                        postKeyEvent<EvKeyPressW<KeyboardClient>>();
                else if (character == 'x')
                        postKeyEvent<EvKeyPressX<KeyboardClient>>();
                else if (character == 'y')
                        postKeyEvent<EvKeyPressY<KeyboardClient>>();
                else if (character == 'z')
                        postKeyEvent<EvKeyPressZ<KeyboardClient>>();
                OnKeyPress(character);
        }
template<typename TEv > void sm_dance_bot::KeyboardClient::postKeyEvent () [inline]
Definition at line 240 of file keyboard_client.h.
References smacc::demangleSymbol().
        {
                ROS_WARN("KeyboardClient ev: %s", smacc::demangleSymbol(typeid(TEv).
      name()).c_str());
                auto event = new TEv();
                this->postEvent(event);
        }
Member Data Documentation
boost::signals2::scoped_connection sm_dance_bot::KeyboardClient::c_
Definition at line 153 of file keyboard_client.h.
bool sm_dance_bot::KeyboardClient::initialized_ [private]
Definition at line 248 of file keyboard_client.h.
boost::signals2::signal<void(char keypress)> sm_dance_bot::KeyboardClient::OnKeyPress
Definition at line 152 of file keyboard_client.h.
Referenced by sm_dance_bot::SbKeyboard::onEntry().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/substate_behaviors/keyboard/keyboard_client.h