smacc::LogicUnit Class Reference
#include <logic_unit_base.h>
Classes
struct AddTEventType
Public Member Functions
LogicUnit ()
virtual void onInitialized ()
template<typename TEventList >
void initialize (ISmaccState *ownerState, TEventList *)
template<typename TEvent >
void notifyEvent (TEvent *ev)
virtual void onEventNotified (const std::type_info *eventType)
template<typename T , typename TClass >
void createEventCallback (void(TClass::*callback)(T *), TClass *object)
template<typename T >
void createEventCallback (std::function< void(T *)> callback)
void update ()
virtual bool triggers ()=0
template<typename TEv >
void declarePostEvent (typelist< TEv >)
Public Attributes
ISmaccState * ownerState
std::function< void()> postEventFn
std::vector< const std::type_info * > eventTypes
std::map< const std::type_info *, std::function< void(void *)> > eventCallbacks_
Detailed Description
Definition at line 19 of file logic_unit_base.h.
Constructor & Destructor Documentation
smacc::LogicUnit::LogicUnit ()
Definition at line 6 of file logic_unit_base.cpp.
{
}
Member Function Documentation
template<typename T , typename TClass > void smacc::LogicUnit::createEventCallback (void(TClass::*)(T *) callback, TClass * object) [inline]
Definition at line 80 of file logic_unit_base.h.
    {
        const auto* eventtype = &typeid(T);
        this->eventCallbacks_[eventtype]= [=](void* msg)
        {
            T* evptr = (T*)msg;
            (object->*callback)(evptr);
        };
    }
template<typename T > void smacc::LogicUnit::createEventCallback (std::function< void(T *)> callback) [inline]
Definition at line 91 of file logic_unit_base.h.
    {
        const auto* eventtype = &typeid(T);
        this->eventCallbacks_[eventtype]= [=](void* msg)
        {
            T* evptr = (T*)msg;
            callback(evptr);
        };
    }
template<typename TEv > void smacc::LogicUnit::declarePostEvent (typelist< TEv >)
Definition at line 134 of file smacc_state_impl.h.
{
    this->postEventFn = [this]() {
        ROS_INFO_STREAM("[Logic Unit Base] postingfn posting event: " << demangleSymbol<TEv>());
        auto *ev = new TEv();
        this->ownerState->getStateMachine().postEvent(ev);
    };
}
template<typename TEventList > void smacc::LogicUnit::initialize (ISmaccState * ownerState, TEventList *) [inline]
Definition at line 49 of file logic_unit_base.h.
    {
        this->ownerState = ownerState;
        
        using boost::mpl::_1;
        using wrappedList = typename boost::mpl::transform<TEventList, _1>::type;
        AddTEventType<TEventList> op(this);
        boost::mpl::for_each<wrappedList>(op);
        
        this->onInitialized();
    }
template<typename TEvent > void smacc::LogicUnit::notifyEvent (TEvent * ev) [inline]
Definition at line 62 of file logic_unit_base.h.
    {
        auto tid = &(typeid(TEvent));
        if (std::find(eventTypes.begin(), eventTypes.end(), tid) !=
      eventTypes.end())
        {
            this->onEventNotified(tid);
            this->update();
            if(eventCallbacks_.count(tid))
            {
                eventCallbacks_[tid]((void*)ev);
            }
        }
    }
void smacc::LogicUnit::onEventNotified (const std::type_info * eventType) [virtual]
Reimplemented in smacc::LuEventCountdown, and smacc::LuAllEventsGo.
Definition at line 14 of file logic_unit_base.cpp.
{
}
void smacc::LogicUnit::onInitialized () [virtual]
Reimplemented in smacc::LuEventCountdown, and smacc::LuAllEventsGo.
Definition at line 10 of file logic_unit_base.cpp.
{
}
virtual bool smacc::LogicUnit::triggers () [pure virtual]
Implemented in smacc::LuConditional, smacc::LuEventCountdown, and smacc::LuAllEventsGo.
Referenced by update().
void smacc::LogicUnit::update ()
Definition at line 18 of file logic_unit_base.cpp.
References postEventFn, and triggers().
{
    if (this->triggers())
    {
        ROS_INFO("Logic unit base REALLY TRIGGERS!!");
        this->postEventFn();
    }
}
Member Data Documentation
std::map<const std::type_info *, std::function<void(void*)> > smacc::LogicUnit::eventCallbacks_
Definition at line 25 of file logic_unit_base.h.
std::vector<const std::type_info *> smacc::LogicUnit::eventTypes
Definition at line 24 of file logic_unit_base.h.
Referenced by smacc::LuAllEventsGo::onInitialized(), smacc::LuEventCountdown::onInitialized(), and smacc::LogicUnit::AddTEventType< TEventList >::operator()().
ISmaccState* smacc::LogicUnit::ownerState
Definition at line 22 of file logic_unit_base.h.
std::function<void()> smacc::LogicUnit::postEventFn
Definition at line 23 of file logic_unit_base.h.
Referenced by update().
The documentation for this class was generated from the following files:
smacc/include/smacc/logic_units/logic_unit_base.h
smacc/include/smacc/impl/smacc_state_impl.h
smacc/src/smacc/logic_unit_base.cpp