smacc::Orthogonal Class Reference
#include <smacc_orthogonal.h>
Public Member Functions
void setStateMachine (ISmaccStateMachine *value)
void addClientBehavior (std::shared_ptr< smacc::SmaccClientBehavior > statebehavior)
void onEntry ()
void onExit ()
virtual std::string getName () const
template<typename TObjectTag , typename TClient , typename... TArgs>
std::shared_ptr< TClient > createClient (TArgs...args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
const std::vector< std::shared_ptr< smacc::ISmaccClient > > & getClients ()
const std::vector< std::shared_ptr< smacc::SmaccClientBehavior > > & getClientBehaviors () const
template<typename TClientBehavior >
TClientBehavior * getClientBehavior ()
Private Member Functions
virtual void onInitialize ()
Private Attributes
ISmaccStateMachine * stateMachine_
std::vector< std::shared_ptr< smacc::SmaccClientBehavior > > clientBehaviors_
std::vector< std::shared_ptr< smacc::ISmaccClient > > clients_
Detailed Description
Definition at line 8 of file smacc_orthogonal.h.
Member Function Documentation
void smacc::Orthogonal::addClientBehavior (std::shared_ptr< smacc::SmaccClientBehavior > statebehavior)
Definition at line 13 of file orthogonal.cpp.
References clientBehaviors_, getName(), and stateMachine_.
{
    if (clBehavior != nullptr)
    {
        ROS_INFO("Setting Ortho %s State behavior: %s", this->getName().c_str(), clBehavior->getName
      ().c_str());
        clBehavior->stateMachine_ = this->stateMachine_;
        clBehavior->currentOrthogonal = this;
        clientBehaviors_.push_back(clBehavior);
    }
    else
    {
        ROS_INFO("Not behavioral State by orthogonal");
    }
}
template<typename TObjectTag , typename TClient , typename... TArgs> std::shared_ptr< TClient > smacc::Orthogonal::createClient (TArgs... args)
Definition at line 17 of file smacc_orthogonal_impl.h.
References smacc::introspection::demangleType().
{
    static_assert(std::is_base_of<Orthogonal, TObjectTag>::value, "The object Tag must be the orthogonal
       type where the client was created");
    if(typeid(*this) != typeid(TObjectTag))
    {
        ROS_ERROR_STREAM("Error creating client. The object Tag must be the type of the orthogonal where
       the client was created:" << demangleType(typeid(*this)) << ". The object creation was skipped and
       a nullptr was returned");
        return nullptr;
    }
    
    ROS_INFO("[%s] creates a client of type '%s' and object tag '%s'",
             demangleType(typeid(*this)).c_str(),
             demangledTypeName<TClient>().c_str(),
             demangledTypeName<TObjectTag>().c_str());
    auto client = std::make_shared<TClient>(args...);
    client->setStateMachine(stateMachine_);
    client->template configureEventSourceTypes<TObjectTag, TClient>();
    clients_.push_back(client);
    return client;
}
template<typename TClientBehavior > TClientBehavior* smacc::Orthogonal::getClientBehavior () [inline]
Definition at line 41 of file smacc_orthogonal.h.
References clientBehaviors_, and onInitialize().
    {
        for (auto &cb : this->clientBehaviors_)
        {
            auto *ret = dynamic_cast<TClientBehavior *>(cb.get());
            if (ret != nullptr)
            {
                return ret;
            }
        }
        return nullptr;
    }
const std::vector<std::shared_ptr<smacc::SmaccClientBehavior> >& smacc::Orthogonal::getClientBehaviors () const [inline]
Definition at line 35 of file smacc_orthogonal.h.
References clientBehaviors_.
    {
        return this->clientBehaviors_;
    }
const std::vector<std::shared_ptr<smacc::ISmaccClient> >& smacc::Orthogonal::getClients () [inline]
Definition at line 30 of file smacc_orthogonal.h.
References clients_.
    {
        return clients_;
    }
std::string smacc::Orthogonal::getName () const [virtual]
Definition at line 33 of file orthogonal.cpp.
References smacc::introspection::demangleSymbol().
Referenced by addClientBehavior(), onEntry(), and onExit().
{
    return demangleSymbol(typeid(*this).name());
}
void smacc::Orthogonal::onEntry ()
Definition at line 38 of file orthogonal.cpp.
References clientBehaviors_, and getName().
{
    if (clientBehaviors_.size() > 0)
    {
        for (auto &clBehavior : clientBehaviors_)
        {
            ROS_INFO("Orthogonal %s OnEntry, current Behavior: %s",
                     this->getName().c_str(),
                     clBehavior->getName().c_str());
            clBehavior->onEntry();
        }
    }
    else
    {
        ROS_INFO("Orthogonal %s OnEntry", this->getName().c_str());
    }
}
void smacc::Orthogonal::onExit ()
Definition at line 57 of file orthogonal.cpp.
References clientBehaviors_, and getName().
{
    if (clientBehaviors_.size() > 0)
    {
        for (auto &clBehavior : clientBehaviors_)
        {
            ROS_INFO("Orthogonal %s OnExit, current Behavior: %s", this->getName().c_str(),
      clBehavior->getName().c_str());
            clBehavior->onExit();
        }
        clientBehaviors_.clear();
    }
    else
    {
        ROS_INFO("Orthogonal %s OnExit", this->getName().c_str());
    }
}
void smacc::Orthogonal::onInitialize () [private], [virtual]
Reimplemented in sm_dance_bot_2::OrNavigation, sm_dance_bot::OrNavigation, sm_dance_bot_2::OrObstaclePerception, sm_three_some::OrUpdatablePublisher, sm_dance_bot::OrTemperatureSensor, sm_three_some::OrSubscriber, sm_dance_bot::OrObstaclePerception, sm_dance_bot::OrService3, sm_dance_bot::OrUpdatablePublisher, sm_three_some::OrKeyboard, sm_three_some::OrTimer, sm_viewer_sim::OrNavigation, sm_dance_bot::OrLED, sm_dance_bot::OrStringPublisher, sm_dance_bot::OrTimer, and sm_atomic::OrTimer.
Definition at line 29 of file orthogonal.cpp.
Referenced by getClientBehavior(), and setStateMachine().
{
}
template<typename SmaccClientType > void smacc::Orthogonal::requiresClient (SmaccClientType *& storage)
Definition at line 54 of file smacc_orthogonal_impl.h.
Referenced by smacc::SmaccClientBehavior::requiresClient().
{
    for (auto &client : clients_)
    {
        storage = dynamic_cast<SmaccClientType *>(client.get());
        if (storage != nullptr)
            return;
    }
}
template<typename SmaccComponentType > void smacc::Orthogonal::requiresComponent (SmaccComponentType *& storage)
Definition at line 41 of file smacc_orthogonal_impl.h.
{
    if (stateMachine_ == nullptr)
    {
        ROS_ERROR("Cannot use the requiresComponent funcionality from an orthogonal before onInitialize");
    }
    else
    {
        stateMachine_->requiresComponent(storage);
    }
}
void smacc::Orthogonal::setStateMachine (ISmaccStateMachine * value)
Definition at line 7 of file orthogonal.cpp.
References onInitialize(), and stateMachine_.
Referenced by smacc::ISmaccStateMachine::createOrthogonal().
{
    this->stateMachine_ = value;
    this->onInitialize();
}
Member Data Documentation
std::vector<std::shared_ptr<smacc::SmaccClientBehavior> > smacc::Orthogonal::clientBehaviors_ [private]
Definition at line 60 of file smacc_orthogonal.h.
Referenced by addClientBehavior(), getClientBehavior(), getClientBehaviors(), onEntry(), and onExit().
std::vector<std::shared_ptr<smacc::ISmaccClient> > smacc::Orthogonal::clients_ [private]
Definition at line 62 of file smacc_orthogonal.h.
Referenced by getClients().
ISmaccStateMachine* smacc::Orthogonal::stateMachine_ [private]
Definition at line 58 of file smacc_orthogonal.h.
Referenced by addClientBehavior(), and setStateMachine().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_orthogonal.h
smacc/include/smacc/impl/smacc_orthogonal_impl.h
smacc/src/smacc/orthogonal.cpp