smacc::SmaccActionClientBase< ActionType > Class Template Reference
#include <smacc_action_client_base.h>
Public Types
typedef actionlib::SimpleActionClient< ActionType > ActionClient
typedef actionlib::SimpleActionClient< ActionType > GoalHandle
typedef ActionClient::SimpleDoneCallback SimpleDoneCallback
typedef ActionClient::SimpleActiveCallback SimpleActiveCallback
typedef ActionClient::SimpleFeedbackCallback SimpleFeedbackCallback
Public Member Functions
ACTION_DEFINITION (ActionType)
SmaccActionClientBase ()
virtual ~SmaccActionClientBase ()
virtual void initialize () override
template<typename EvType >
void postResultEvent (ResultConstPtr result)
template<typename TDerived , typename TObjectTag >
void assignToOrthogonal ()
template<typename T >
boost::signals2::connection onSucceeded (void(T::*callback)(ResultConstPtr &), T *object)
template<typename T >
boost::signals2::connection onSucceeded (std::function< void(ResultConstPtr &)> callback)
template<typename T >
boost::signals2::connection onAborted (void(T::*callback)(ResultConstPtr &), T *object)
template<typename T >
boost::signals2::connection onAborted (std::function< void(ResultConstPtr &)> callback)
template<typename T >
boost::signals2::connection onPreempted (void(T::*callback)(ResultConstPtr &), T *object)
template<typename T >
boost::signals2::connection onPreempted (std::function< void(ResultConstPtr &)> callback)
template<typename T >
boost::signals2::connection onRejected (void(T::*callback)(ResultConstPtr &), T *object)
template<typename T >
boost::signals2::connection onRejected (std::function< void(ResultConstPtr &)> callback)
virtual void cancelGoal () override
virtual SimpleClientGoalState getState () override
void sendGoal (Goal &goal)
Static Public Member Functions
static std::string getEventLabel ()
Public Attributes
boost::optional< std::string > name_
rosnamespace path
smacc::SmaccSignal< void(const ResultConstPtr &)> onSucceeded_
smacc::SmaccSignal< void(const ResultConstPtr &)> onAborted_
smacc::SmaccSignal< void(const ResultConstPtr &)> onPreempted_
smacc::SmaccSignal< void(const ResultConstPtr &)> onRejected_
std::function< void(ResultConstPtr)> postSuccessEvent
std::function< void(ResultConstPtr)> postAbortedEvent
std::function< void(ResultConstPtr)> postPreemptedEvent
std::function< void(ResultConstPtr)> postRejectedEvent
std::function< void(FeedbackConstPtr)> postFeedbackEvent
SimpleDoneCallback done_cb
SimpleActiveCallback active_cb
SimpleFeedbackCallback feedback_cb
Protected Member Functions
void onFeedback (const FeedbackConstPtr &feedback_msg)
void onResult (const SimpleClientGoalState &state, const ResultConstPtr &result_msg)
Protected Attributes
std::shared_ptr< ActionClient > client_
Detailed Description
template<typename ActionType>
*
class smacc::SmaccActionClientBase< ActionType >
Definition at line 13 of file smacc_action_client_base.h.
Member Typedef Documentation
template<typename ActionType> typedef actionlib::SimpleActionClient<ActionType> smacc::SmaccActionClientBase< ActionType >::ActionClient
Definition at line 18 of file smacc_action_client_base.h.
template<typename ActionType> typedef actionlib::SimpleActionClient<ActionType> smacc::SmaccActionClientBase< ActionType >::GoalHandle
Definition at line 19 of file smacc_action_client_base.h.
template<typename ActionType> typedef ActionClient::SimpleActiveCallback smacc::SmaccActionClientBase< ActionType >::SimpleActiveCallback
Definition at line 22 of file smacc_action_client_base.h.
template<typename ActionType> typedef ActionClient::SimpleDoneCallback smacc::SmaccActionClientBase< ActionType >::SimpleDoneCallback
Definition at line 21 of file smacc_action_client_base.h.
template<typename ActionType> typedef ActionClient::SimpleFeedbackCallback smacc::SmaccActionClientBase< ActionType >::SimpleFeedbackCallback
Definition at line 23 of file smacc_action_client_base.h.
Constructor & Destructor Documentation
template<typename ActionType> smacc::SmaccActionClientBase< ActionType >::SmaccActionClientBase () [inline]
Definition at line 25 of file smacc_action_client_base.h.
        : ISmaccActionClient()
    {
    }
template<typename ActionType> virtual smacc::SmaccActionClientBase< ActionType >::~SmaccActionClientBase () [inline], [virtual]
Definition at line 36 of file smacc_action_client_base.h.
    {
    }
Member Function Documentation
template<typename ActionType> smacc::SmaccActionClientBase< ActionType >::ACTION_DEFINITION (ActionType)
template<typename ActionType> template<typename TDerived , typename TObjectTag > void smacc::SmaccActionClientBase< ActionType >::assignToOrthogonal () [inline]
Definition at line 85 of file smacc_action_client_base.h.
    {
        // we create here all the event factory functions capturing the TObjectTag
        postSuccessEvent = [=](auto msg) { this->
      postResultEvent<EvActionSucceeded<TDerived, TObjectTag>>(msg); };
        postAbortedEvent = [=](auto msg) { this->
      postResultEvent<EvActionAborted<TDerived, TObjectTag>>(msg); };
        postPreemptedEvent = [=](auto msg) { this->
      postResultEvent<EvActionPreempted<TDerived, TObjectTag>>(msg); };
        postRejectedEvent = [=](auto msg) { this->
      postResultEvent<EvActionRejected<TDerived, TObjectTag>>(msg); };
        postFeedbackEvent = [=](auto msg) {
            auto actionFeedbackEvent = new EvActionFeedback<Feedback, TObjectTag>();
            actionFeedbackEvent->client = this;
            actionFeedbackEvent->feedbackMessage = *msg;
            this->postEvent(actionFeedbackEvent);
            ROS_DEBUG("[%s] FEEDBACK EVENT", demangleType(typeid(*this)).c_str());
        };
        done_cb = boost::bind(&
      SmaccActionClientBase<ActionType>::onResult, this, _1, _2);
        //active_cb;
        feedback_cb = boost::bind(&
      SmaccActionClientBase<ActionType>::onFeedback, this, _1);
    }
template<typename ActionType> virtual void smacc::SmaccActionClientBase< ActionType >::cancelGoal () [inline], [override], [virtual]
Implements smacc::ISmaccActionClient.
Definition at line 153 of file smacc_action_client_base.h.
    {
        ROS_INFO("Cancelling goal of %s", this->getName().c_str());
        client_->cancelGoal();
    }
template<typename ActionType> static std::string smacc::SmaccActionClientBase< ActionType >::getEventLabel () [inline], [static]
Definition at line 30 of file smacc_action_client_base.h.
    {
        auto type = TypeInfo::getTypeInfoFromType<ActionType>();
        return type->getNonTemplatetypename();
    }
template<typename ActionType> virtual SimpleClientGoalState smacc::SmaccActionClientBase< ActionType >::getState () [inline], [override], [virtual]
Implements smacc::ISmaccActionClient.
Definition at line 159 of file smacc_action_client_base.h.
    {
        return client_->getState();
    }
template<typename ActionType> virtual void smacc::SmaccActionClientBase< ActionType >::initialize () [inline], [override], [virtual]
Reimplemented from smacc::ISmaccClient.
Reimplemented in smacc::SmaccMoveBaseActionClient.
Definition at line 43 of file smacc_action_client_base.h.
Referenced by smacc::SmaccMoveBaseActionClient::initialize().
    {
        if (!name_)
        {
            name_ = demangleSymbol(typeid(*this).name());
            std::vector<std::string> strs;
            boost::split(strs, *name_, boost::is_any_of("::"));
            std::string classname = strs.back();
            name_ = classname;
        }
        client_ = std::make_shared<ActionClient>(*name_);
    }
template<typename ActionType> template<typename T > boost::signals2::connection smacc::SmaccActionClientBase< ActionType >::onAborted (void(T::*)(ResultConstPtr &) callback, T * object) [inline]
Definition at line 118 of file smacc_action_client_base.h.
    {
        return stateMachine_->createSignalConnection(
      onAborted_, callback, object);
    }
template<typename ActionType> template<typename T > boost::signals2::connection smacc::SmaccActionClientBase< ActionType >::onAborted (std::function< void(ResultConstPtr &)> callback) [inline]
Definition at line 124 of file smacc_action_client_base.h.
    {
        return stateMachine_->createSignalConnection(
      onAborted_, callback);
    }
template<typename ActionType> void smacc::SmaccActionClientBase< ActionType >::onFeedback (const FeedbackConstPtr & feedback_msg) [inline], [protected]
Definition at line 183 of file smacc_action_client_base.h.
    {
        postFeedbackEvent(feedback_msg);
    }
template<typename ActionType> template<typename T > boost::signals2::connection smacc::SmaccActionClientBase< ActionType >::onPreempted (void(T::*)(ResultConstPtr &) callback, T * object) [inline]
Definition at line 130 of file smacc_action_client_base.h.
    {
        return stateMachine_->createSignalConnection(
      onPreempted_, callback, object);
    }
template<typename ActionType> template<typename T > boost::signals2::connection smacc::SmaccActionClientBase< ActionType >::onPreempted (std::function< void(ResultConstPtr &)> callback) [inline]
Definition at line 136 of file smacc_action_client_base.h.
    {
        return stateMachine_->createSignalConnection(
      onPreempted_, callback);
    }
template<typename ActionType> template<typename T > boost::signals2::connection smacc::SmaccActionClientBase< ActionType >::onRejected (void(T::*)(ResultConstPtr &) callback, T * object) [inline]
Definition at line 142 of file smacc_action_client_base.h.
    {
        return stateMachine_->createSignalConnection(
      onRejected, callback, object);
    }
template<typename ActionType> template<typename T > boost::signals2::connection smacc::SmaccActionClientBase< ActionType >::onRejected (std::function< void(ResultConstPtr &)> callback) [inline]
Definition at line 148 of file smacc_action_client_base.h.
    {
        return stateMachine_->createSignalConnection(
      onRejected, callback);
    }
template<typename ActionType> void smacc::SmaccActionClientBase< ActionType >::onResult (const SimpleClientGoalState & state, const ResultConstPtr & result_msg) [inline], [protected]
Definition at line 188 of file smacc_action_client_base.h.
    {
        // auto *actionResultEvent = new EvActionResult<TDerived>();
        // actionResultEvent->client = this;
        // actionResultEvent->resultMessage = *result_msg;
        const auto &resultType = this->getState();
        ROS_INFO("[%s] request result: %s", this->getName().c_str(), resultType.toString().c_str());
        if (resultType == actionlib::SimpleClientGoalState::SUCCEEDED)
        {
            ROS_INFO("[%s] request result: Success", this->getName().c_str());
            onSucceeded_(result_msg);
            postSuccessEvent(result_msg);
        }
        else if (resultType == actionlib::SimpleClientGoalState::ABORTED)
        {
            ROS_INFO("[%s] request result: Aborted", this->getName().c_str());
            onAborted_(result_msg);
            postAbortedEvent(result_msg);
        }
        else if (resultType == actionlib::SimpleClientGoalState::REJECTED)
        {
            ROS_INFO("[%s] request result: Rejected", this->getName().c_str());
            onRejected_(result_msg);
            postRejectedEvent(result_msg);
        }
        else if (resultType == actionlib::SimpleClientGoalState::PREEMPTED)
        {
            ROS_INFO("[%s] request result: Preempted", this->getName().c_str());
            onPreempted_(result_msg);
            postPreemptedEvent(result_msg);
        }
        else
        {
            ROS_INFO("[%s] request result: NOT HANDLED TYPE: %s", this->getName().c_str(),
      resultType.toString().c_str());
        }
    }
template<typename ActionType> template<typename T > boost::signals2::connection smacc::SmaccActionClientBase< ActionType >::onSucceeded (void(T::*)(ResultConstPtr &) callback, T * object) [inline]
Definition at line 106 of file smacc_action_client_base.h.
Referenced by smacc::WaypointNavigator::sendNextGoal().
    {
        return stateMachine_->createSignalConnection(
      onSucceeded_, callback, object);
    }
template<typename ActionType> template<typename T > boost::signals2::connection smacc::SmaccActionClientBase< ActionType >::onSucceeded (std::function< void(ResultConstPtr &)> callback) [inline]
Definition at line 112 of file smacc_action_client_base.h.
    {
        return stateMachine_->createSignalConnection(
      onSucceeded_, callback);
    }
template<typename ActionType> template<typename EvType > void smacc::SmaccActionClientBase< ActionType >::postResultEvent (ResultConstPtr result) [inline]
Definition at line 75 of file smacc_action_client_base.h.
    {
        auto *ev = new EvType();
        ev->client = this;
        ev->resultMessage = *result;
        ROS_INFO("Posting EVENT %s", demangleSymbol(typeid(ev).name()).c_str());
        this->postEvent(ev);
    }
template<typename ActionType> void smacc::SmaccActionClientBase< ActionType >::sendGoal (Goal & goal) [inline]
Definition at line 164 of file smacc_action_client_base.h.
Referenced by sm_atomic::CbState1::goToEndPoint(), sm_dance_bot::CbNavigateGlobalPosition::goToRadialStart(), sm_dance_bot::CbToolStop::onEntry(), sm_dance_bot::CbToolStart::onEntry(), sm_dance_bot::CbUndoPathBackwards::onEntry(), sm_dance_bot::CbRotate::onEntry(), sm_dance_bot::CbNavigateForward::onEntry(), sm_dance_bot::CbNavigateBackwards::onEntry(), and smacc::WaypointNavigator::sendNextGoal().
    {
        ROS_INFO_STREAM("Sending goal to actionserver located in " << *(this->
      name_) << "\"");
        if (!client_->isServerConnected())
        {
            ROS_INFO("%s [at %s]: not connected with actionserver, waiting ...",
      getName().c_str(), getNamespace().c_str());
            client_->waitForServer();
        }
        ROS_INFO_STREAM(getName() << ": Goal Value: " << std::endl
                                  << goal);
        client_->sendGoal(goal, done_cb, active_cb,
      feedback_cb);
    }
Member Data Documentation
template<typename ActionType> SimpleActiveCallback smacc::SmaccActionClientBase< ActionType >::active_cb
Definition at line 71 of file smacc_action_client_base.h.
template<typename ActionType> std::shared_ptr<ActionClient> smacc::SmaccActionClientBase< ActionType >::client_ [protected]
Definition at line 181 of file smacc_action_client_base.h.
template<typename ActionType> SimpleDoneCallback smacc::SmaccActionClientBase< ActionType >::done_cb
Definition at line 70 of file smacc_action_client_base.h.
template<typename ActionType> SimpleFeedbackCallback smacc::SmaccActionClientBase< ActionType >::feedback_cb
Definition at line 72 of file smacc_action_client_base.h.
template<typename ActionType> boost::optional<std::string> smacc::SmaccActionClientBase< ActionType >::name_
rosnamespace path
Definition at line 41 of file smacc_action_client_base.h.
template<typename ActionType> smacc::SmaccSignal<void(const ResultConstPtr &)> smacc::SmaccActionClientBase< ActionType >::onAborted_
Definition at line 58 of file smacc_action_client_base.h.
template<typename ActionType> smacc::SmaccSignal<void(const ResultConstPtr &)> smacc::SmaccActionClientBase< ActionType >::onPreempted_
Definition at line 59 of file smacc_action_client_base.h.
template<typename ActionType> smacc::SmaccSignal<void(const ResultConstPtr &)> smacc::SmaccActionClientBase< ActionType >::onRejected_
Definition at line 60 of file smacc_action_client_base.h.
template<typename ActionType> smacc::SmaccSignal<void(const ResultConstPtr &)> smacc::SmaccActionClientBase< ActionType >::onSucceeded_
Definition at line 57 of file smacc_action_client_base.h.
template<typename ActionType> std::function<void(ResultConstPtr)> smacc::SmaccActionClientBase< ActionType >::postAbortedEvent
Definition at line 64 of file smacc_action_client_base.h.
template<typename ActionType> std::function<void(FeedbackConstPtr)> smacc::SmaccActionClientBase< ActionType >::postFeedbackEvent
Definition at line 68 of file smacc_action_client_base.h.
template<typename ActionType> std::function<void(ResultConstPtr)> smacc::SmaccActionClientBase< ActionType >::postPreemptedEvent
Definition at line 65 of file smacc_action_client_base.h.
template<typename ActionType> std::function<void(ResultConstPtr)> smacc::SmaccActionClientBase< ActionType >::postRejectedEvent
Definition at line 66 of file smacc_action_client_base.h.
template<typename ActionType> std::function<void(ResultConstPtr)> smacc::SmaccActionClientBase< ActionType >::postSuccessEvent
Definition at line 63 of file smacc_action_client_base.h.
The documentation for this class was generated from the following file:
smacc/include/smacc/client_bases/smacc_action_client_base.h