forward_global_planner::ForwardGlobalPlanner Class Reference
#include <forward_global_planner.h>
Public Member Functions
ForwardGlobalPlanner ()
bool makePlan (const geometry_msgs::PoseStamped &start, const geometry_msgs::PoseStamped &goal, std::vector< geometry_msgs::PoseStamped > &plan)
bool makePlan (const geometry_msgs::PoseStamped &start, const geometry_msgs::PoseStamped &goal, std::vector< geometry_msgs::PoseStamped > &plan, double &cost)
void initialize (std::string name, costmap_2d::Costmap2DROS *costmap_ros_)
Private Attributes
ros::NodeHandle nh_
ros::Publisher planPub_
costmap_2d::Costmap2DROS * costmap_ros_
stored but almost not used
double skip_straight_motion_distance_
double puresSpinningRadStep_
Detailed Description
Definition at line 14 of file forward_global_planner.h.
Constructor & Destructor Documentation
forward_global_planner::ForwardGlobalPlanner::ForwardGlobalPlanner ()
Definition at line 21 of file forward_global_planner.cpp.
References puresSpinningRadStep_, and skip_straight_motion_distance_.
    :nh_("~/ForwardGlobalPlanner")
{
    skip_straight_motion_distance_ = 0.2; //meters
    puresSpinningRadStep_ = 1000; // rads
}
Member Function Documentation
void forward_global_planner::ForwardGlobalPlanner::initialize (std::string name, costmap_2d::Costmap2DROS * costmap_ros_)
Definition at line 28 of file forward_global_planner.cpp.
References nh_, planPub_, puresSpinningRadStep_, and skip_straight_motion_distance_.
{
    planPub_ = nh_.advertise<nav_msgs::Path>("global_plan", 1);
    skip_straight_motion_distance_ = 0.2; //meters
    puresSpinningRadStep_ = 1000; // rads
}
bool forward_global_planner::ForwardGlobalPlanner::makePlan (const geometry_msgs::PoseStamped & start, const geometry_msgs::PoseStamped & goal, std::vector< geometry_msgs::PoseStamped > & plan)
Definition at line 43 of file forward_global_planner.cpp.
References smacc_move_base_client::makePureSpinningSubPlan(), smacc_move_base_client::makePureStraightSubPlan(), planPub_, forward_global_planner::PLUGINLIB_EXPORT_CLASS(), puresSpinningRadStep_, and skip_straight_motion_distance_.
Referenced by makePlan().
{
    //ROS_WARN_STREAM("Forward global plan goal: " << goal);
    //three stages: 1 - heading to goal position, 2 - going forward keep orientation, 3 - heading to goal
       orientation
    // 1 - heading to goal position
    // orientation direction
    double dx = goal.pose.position.x - start.pose.position.x;
    double dy = goal.pose.position.y - start.pose.position.y;
    double lenght = sqrt(dx*dx + dy*dy);
    geometry_msgs::PoseStamped prevState;
    if (lenght > skip_straight_motion_distance_)
    {
        // skip initial pure spinning and initial straight motion
        //ROS_INFO("1 - heading to goal position pure spinning");
        double heading_direction = atan2(dy, dx);
        prevState = smacc_move_base_client::makePureSpinningSubPlan
      (start,heading_direction,plan,puresSpinningRadStep_);
        //ROS_INFO("2 - going forward keep orientation pure straight");
        prevState = smacc_move_base_client::makePureStraightSubPlan
      (prevState, goal.pose.position, lenght, plan);
    }
    else
    {
        prevState = start;
    }
    //ROS_INFO("3 - heading to goal orientation");
    double goalOrientation = angles::normalize_angle(tf::getYaw(goal.pose.orientation));
    smacc_move_base_client::makePureSpinningSubPlan(
      prevState,goalOrientation,plan,puresSpinningRadStep_);
    
    nav_msgs::Path planMsg;
    planMsg.poses = plan;
    planMsg.header.stamp = ros::Time::now();
    planMsg.header.frame_id="/odom";
    planPub_.publish(planMsg);
    //ROS_INFO_STREAM("global forward plan: " << planMsg);
    return true;
}
bool forward_global_planner::ForwardGlobalPlanner::makePlan (const geometry_msgs::PoseStamped & start, const geometry_msgs::PoseStamped & goal, std::vector< geometry_msgs::PoseStamped > & plan, double & cost)
Definition at line 35 of file forward_global_planner.cpp.
References makePlan().
{
    cost = 0;
    makePlan(start, goal, plan);
}
Member Data Documentation
costmap_2d::Costmap2DROS* forward_global_planner::ForwardGlobalPlanner::costmap_ros_ [private]
stored but almost not used
Definition at line 34 of file forward_global_planner.h.
ros::NodeHandle forward_global_planner::ForwardGlobalPlanner::nh_ [private]
Definition at line 29 of file forward_global_planner.h.
Referenced by initialize().
ros::Publisher forward_global_planner::ForwardGlobalPlanner::planPub_ [private]
Definition at line 31 of file forward_global_planner.h.
Referenced by initialize(), and makePlan().
double forward_global_planner::ForwardGlobalPlanner::puresSpinningRadStep_ [private]
Definition at line 38 of file forward_global_planner.h.
Referenced by ForwardGlobalPlanner(), initialize(), and makePlan().
double forward_global_planner::ForwardGlobalPlanner::skip_straight_motion_distance_ [private]
Definition at line 36 of file forward_global_planner.h.
Referenced by ForwardGlobalPlanner(), initialize(), and makePlan().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/custom_planners/forward_global_planner/include/forward_global_planner/forward_global_planner.h
smacc_client_library/move_base_z_client/custom_planners/forward_global_planner/src/forward_global_planner.cpp