smacc::SmaccTopicSubscriberClient< MessageType > Class Template Reference
#include <smacc_topic_subscriber.h>
Public Member Functions
SmaccTopicSubscriberClient ()
virtual ~SmaccTopicSubscriberClient ()
virtual void initialize ()
Public Attributes
boost::signals2::signal< void(const MessageType &)> onFirstMessageReceived
boost::signals2::signal< void(const MessageType &)> onMessageReceived
boost::optional< std::string > topicName
boost::optional< int > queueSize
Protected Attributes
ros::NodeHandle nh_
Private Member Functions
void messageCallback (const MessageType &msg)
Private Attributes
ros::Subscriber sub_
bool firstMessage_
bool initialized_
Detailed Description
template<typename MessageType>
*
class smacc::SmaccTopicSubscriberClient< MessageType >
Definition at line 22 of file smacc_topic_subscriber.h.
Constructor & Destructor Documentation
template<typename MessageType> smacc::SmaccTopicSubscriberClient< MessageType >::SmaccTopicSubscriberClient () [inline]
Definition at line 31 of file smacc_topic_subscriber.h.
  {
    initialized_ = false;
  }
template<typename MessageType> virtual smacc::SmaccTopicSubscriberClient< MessageType >::~SmaccTopicSubscriberClient () [inline], [virtual]
Definition at line 36 of file smacc_topic_subscriber.h.
  {
    sub_.shutdown();
  }
Member Function Documentation
template<typename MessageType> virtual void smacc::SmaccTopicSubscriberClient< MessageType >::initialize () [inline], [virtual]
Reimplemented from smacc::ISmaccClient.
Reimplemented in dance_bot::KeyboardClient, smacc::SensorClient< MessageType >, and smacc::SensorClient< sensor_msgs::Temperature >.
Definition at line 41 of file smacc_topic_subscriber.h.
Referenced by smacc::SensorClient< sensor_msgs::Temperature >::initialize().
  {
    if (!initialized_)
    {
      firstMessage_ = true;
      if (!queueSize)
        queueSize = 1;
      if (!topicName)
      {
        ROS_ERROR("topic client with no topic name set. Skipping subscribing");
      }
      else
      {
        ROS_INFO_STREAM("[" << this->getName() << "] Subscribing to topic: " <<
      topicName);
        sub_ = nh_.subscribe(*topicName, *queueSize, &
      SmaccTopicSubscriberClient<MessageType>::messageCallback
      , this);
        this->initialized_ = true;
      }
    }
  }
template<typename MessageType> void smacc::SmaccTopicSubscriberClient< MessageType >::messageCallback (const MessageType & msg) [inline], [private]
Definition at line 72 of file smacc_topic_subscriber.h.
  {
    if (firstMessage_)
    {
      auto event = new EvTopicInitialMessage<SmaccTopicSubscriberClient<MessageType>>();
      this->postEvent(event);
      this->onFirstMessageReceived(msg);
      firstMessage_ = false;
    }
    auto *ev2 = new EvTopicMessage<SmaccTopicSubscriberClient<MessageType>>();
    this->postEvent(ev2);
    onMessageReceived(msg);
  }
Member Data Documentation
template<typename MessageType> bool smacc::SmaccTopicSubscriberClient< MessageType >::firstMessage_ [private]
Definition at line 69 of file smacc_topic_subscriber.h.
template<typename MessageType> bool smacc::SmaccTopicSubscriberClient< MessageType >::initialized_ [private]
Definition at line 70 of file smacc_topic_subscriber.h.
template<typename MessageType> ros::NodeHandle smacc::SmaccTopicSubscriberClient< MessageType >::nh_ [protected]
Definition at line 65 of file smacc_topic_subscriber.h.
template<typename MessageType> boost::signals2::signal<void(const MessageType &)> smacc::SmaccTopicSubscriberClient< MessageType >::onFirstMessageReceived
Definition at line 25 of file smacc_topic_subscriber.h.
Referenced by smacc::SensorTopic< sensor_msgs::Temperature >::onEntry().
template<typename MessageType> boost::signals2::signal<void(const MessageType &)> smacc::SmaccTopicSubscriberClient< MessageType >::onMessageReceived
Definition at line 26 of file smacc_topic_subscriber.h.
Referenced by smacc::SensorTopic< sensor_msgs::Temperature >::onEntry().
template<typename MessageType> boost::optional<int> smacc::SmaccTopicSubscriberClient< MessageType >::queueSize
Definition at line 29 of file smacc_topic_subscriber.h.
template<typename MessageType> ros::Subscriber smacc::SmaccTopicSubscriberClient< MessageType >::sub_ [private]
Definition at line 68 of file smacc_topic_subscriber.h.
template<typename MessageType> boost::optional<std::string> smacc::SmaccTopicSubscriberClient< MessageType >::topicName
Definition at line 28 of file smacc_topic_subscriber.h.
The documentation for this class was generated from the following file:
smacc/include/smacc/interface_components/smacc_topic_subscriber.h