smacc::SmaccClientBehavior Class Reference
#include <smacc_client_behavior.h>
Public Member Functions
SmaccClientBehavior ()
virtual ~SmaccClientBehavior ()
std::string getName () const
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Public Attributes
ISmaccStateMachine * stateMachine_
ISmaccState * currentState
smacc::Orthogonal * currentOrthogonal
Private Member Functions
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
Friends
class ISmaccState
Detailed Description
Definition at line 8 of file smacc_client_behavior.h.
Constructor & Destructor Documentation
smacc::SmaccClientBehavior::SmaccClientBehavior ()
Definition at line 5 of file smacc_substate_behavior.cpp.
References currentState, and stateMachine_.
{
    stateMachine_ = nullptr;
    currentState = nullptr;
}
smacc::SmaccClientBehavior::~SmaccClientBehavior () [virtual]
Definition at line 11 of file smacc_substate_behavior.cpp.
{
    ROS_WARN("Client behavior deallocated.");
}
Member Function Documentation
template<typename TObjectTag , typename TDerived > void smacc::SmaccClientBehavior::configureEventSourceTypes () [private]
Definition at line 55 of file smacc_client_behavior_impl.h.
{}
std::string smacc::SmaccClientBehavior::getName () const
Definition at line 16 of file smacc_substate_behavior.cpp.
References smacc::demangleSymbol().
Referenced by onEntry(), and onExit().
{
    return demangleSymbol(typeid(*this).name());
}
void smacc::SmaccClientBehavior::onEntry () [virtual]
Reimplemented in smacc::SensorTopic< ClientType >, smacc::SensorTopic< ClTemperatureSensor >, smacc::SensorTopic< ClLaserSensor >, sm_dance_bot::move_base_z_client::CbNavigateBackwards, sm_dance_bot::move_base_z_client::CbNavigateForward, move_base_z_client::CbNavigateBackwards, sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition, move_base_z_client::CbNavigateForward, move_base_z_client::CbNavigateGlobalPosition, sm_dance_bot::move_base_z_client::CbRotate, move_base_z_client::CbRotate, sm_dance_bot::service3_client::CbService3, sm_dance_bot::string_publisher_client::CbStringPublisher, sm_dance_bot::move_base_z_client::CbUndoPathBackwards, sm_dance_bot::ros_publisher_client::CbUpdatableStringPublisher, ros_publisher_client::CbDefaultPublishLoop, sm_dance_bot::lidar_client::CbLidarSensor, sm_three_some::keyboard_client::CbDefaultKeyboardBehavior, move_base_z_client::CbUndoPathBackwards, sm_dance_bot::tool_client::CbToolStart, sm_dance_bot::tool_client::CbToolStop, sm_three_some::subscriber_client::CbDefaultSubscriberBehavior, ros_timer_client::CbTimerCountdownLoop, sm_three_some::subscriber_client::CbWatchdogSubscriberBehavior, ros_timer_client::CbTimerCountdownOnce, ros_publisher_client::CbMutedBehavior< RosMsgType >, ros_publisher_client::CbPublishOnce< RosMsgType >, and ros_timer_client::CbTimer.
Definition at line 21 of file smacc_substate_behavior.cpp.
References getName().
{
    ROS_INFO("SmaccClientBehavior %s onEntry", this->getName().c_str());
}
void smacc::SmaccClientBehavior::onExit () [virtual]
Reimplemented in sm_dance_bot::move_base_z_client::CbNavigateBackwards, sm_dance_bot::move_base_z_client::CbNavigateForward, move_base_z_client::CbNavigateBackwards, move_base_z_client::CbNavigateForward, sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition, move_base_z_client::CbNavigateGlobalPosition, smacc::SensorTopic< ClientType >, smacc::SensorTopic< ClTemperatureSensor >, smacc::SensorTopic< ClLaserSensor >, sm_dance_bot::string_publisher_client::CbStringPublisher, sm_dance_bot::ros_publisher_client::CbUpdatableStringPublisher, sm_dance_bot::tool_client::CbToolStart, sm_dance_bot::tool_client::CbToolStop, ros_timer_client::CbTimerCountdownLoop, ros_timer_client::CbTimerCountdownOnce, and ros_timer_client::CbTimer.
Definition at line 26 of file smacc_substate_behavior.cpp.
References getName().
{
    ROS_INFO("SmaccClientBehavior %s onExit", this->getName().c_str());
}
template<typename EventType > void smacc::SmaccClientBehavior::postEvent (const EventType & ev)
Definition at line 10 of file smacc_client_behavior_impl.h.
References smacc::ISmaccStateMachine::postEvent(), and stateMachine_.
{
    if (stateMachine_ == nullptr)
    {
        ROS_ERROR("The client behavior cannot post events before being assigned to an orthogonal. Ignoring
       post event call.");
    }
    else
    {
        stateMachine_->postEvent(ev);
    }
}
template<typename EventType > void smacc::SmaccClientBehavior::postEvent ()
Definition at line 23 of file smacc_client_behavior_impl.h.
References stateMachine_.
Referenced by smacc::SensorTopic< ClLaserSensor >::configureEventSourceTypes(), and sm_three_some::keyboard_client::CbDefaultKeyboardBehavior::postKeyEvent().
{
    if (stateMachine_ == nullptr)
    {
        ROS_ERROR("The client behavior cannot post events before being assigned to an orthogonal. Ignoring
       post event call.");
    }
    else
    {
        stateMachine_->template postEvent<EventType>();
    }
}
template<typename SmaccClientType > void smacc::SmaccClientBehavior::requiresClient (SmaccClientType *& storage)
Definition at line 36 of file smacc_client_behavior_impl.h.
References currentOrthogonal, and smacc::Orthogonal::requiresClient().
Referenced by ros_timer_client::CbTimer::onEntry(), ros_timer_client::CbTimerCountdownOnce::onEntry(), ros_timer_client::CbTimerCountdownLoop::onEntry(), sm_dance_bot::tool_client::CbToolStart::onEntry(), sm_dance_bot::tool_client::CbToolStop::onEntry(), move_base_z_client::CbUndoPathBackwards::onEntry(), sm_three_some::keyboard_client::CbDefaultKeyboardBehavior::onEntry(), sm_dance_bot::move_base_z_client::CbUndoPathBackwards::onEntry(), sm_dance_bot::ros_publisher_client::CbUpdatableStringPublisher::onEntry(), sm_dance_bot::string_publisher_client::CbStringPublisher::onEntry(), move_base_z_client::CbRotate::onEntry(), sm_dance_bot::move_base_z_client::CbRotate::onEntry(), move_base_z_client::CbNavigateGlobalPosition::onEntry(), move_base_z_client::CbNavigateForward::onEntry(), sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::onEntry(), move_base_z_client::CbNavigateBackwards::onEntry(), sm_dance_bot::move_base_z_client::CbNavigateForward::onEntry(), sm_dance_bot::move_base_z_client::CbNavigateBackwards::onEntry(), and smacc::SensorTopic< ClLaserSensor >::onEntry().
{
    currentOrthogonal->requiresClient(storage);
}
template<typename SmaccComponentType > void smacc::SmaccClientBehavior::requiresComponent (SmaccComponentType *& storage)
Definition at line 42 of file smacc_client_behavior_impl.h.
References smacc::ISmaccStateMachine::requiresComponent(), and stateMachine_.
{
    if (stateMachine_ == nullptr)
    {
        ROS_ERROR("Cannot use the requiresComponent funcionality before asigning the client behavior to an
       orthogonal. Try using the OnEntry method to capture required components.");
    }
    else
    {
        stateMachine_->requiresComponent(storage);
    }
}
Friends And Related Function Documentation
friend class ISmaccState [friend]
Definition at line 48 of file smacc_client_behavior.h.
Member Data Documentation
smacc::Orthogonal* smacc::SmaccClientBehavior::currentOrthogonal
Definition at line 20 of file smacc_client_behavior.h.
Referenced by requiresClient().
ISmaccState* smacc::SmaccClientBehavior::currentState
Definition at line 18 of file smacc_client_behavior.h.
Referenced by move_base_z_client::CbRotate::onEntry(), sm_dance_bot::move_base_z_client::CbRotate::onEntry(), move_base_z_client::CbNavigateForward::onEntry(), move_base_z_client::CbNavigateBackwards::onEntry(), sm_dance_bot::move_base_z_client::CbNavigateForward::onEntry(), sm_dance_bot::move_base_z_client::CbNavigateBackwards::onEntry(), move_base_z_client::CbNavigateGlobalPosition::readStartPoseFromParameterServer(), sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::readStartPoseFromParameterServer(), and SmaccClientBehavior().
ISmaccStateMachine* smacc::SmaccClientBehavior::stateMachine_
Definition at line 15 of file smacc_client_behavior.h.
Referenced by sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::goToRadialStart(), ros_timer_client::CbTimerCountdownOnce::onTimerTick(), ros_timer_client::CbTimerCountdownLoop::onTimerTick(), postEvent(), requiresComponent(), and SmaccClientBehavior().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_client_behavior.h
smacc/include/smacc/impl/smacc_client_behavior_impl.h
smacc/src/smacc/smacc_substate_behavior.cpp