Rotate Class Reference
#include <rotate.h>
Public Member Functions
Rotate ()
Rotate (float rotate_degree)
virtual void onEntry () override
Public Attributes
tf::TransformListener listener
smacc::SmaccMoveBaseActionClient * moveBaseClient_
smacc_planner_switcher::PlannerSwitcher * plannerSwitcher_
boost::optional< float > rotateDegree
Detailed Description
Definition at line 11 of file rotate.h.
Constructor & Destructor Documentation
Rotate::Rotate () [inline]
Definition at line 22 of file rotate.h.
  {
  }
Rotate::Rotate (float rotate_degree) [inline]
Definition at line 27 of file rotate.h.
  {
    rotateDegree = rotate_degree;
  }
Member Function Documentation
virtual void Rotate::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 32 of file rotate.h.
References smacc::SmaccSubStateBehavior::currentState, smacc::ISmaccState::param(), smacc::SmaccSubStateBehavior::requiresComponent(), rotateDegree, smacc::SmaccActionClientBase< ActionType >::sendGoal(), and smacc_planner_switcher::PlannerSwitcher::setForwardPlanner().
  {
    double angle_increment_degree;
    if(!rotateDegree)
    {
        this->currentState->param("angle_increment_degree", angle_increment_degree, 90.0);
    }
    else
    {
       angle_increment_degree = *rotateDegree;
    }
    this->requiresComponent(moveBaseClient_ , ros::NodeHandle("move_base"))
      ;
    this->requiresComponent(plannerSwitcher_, ros::NodeHandle("move_base")
      );
    
    //this->plannerSwitcher_->setDefaultPlanners();
    this->plannerSwitcher_->setForwardPlanner();
    //this should work better with a coroutine and await
    ros::Rate rate(10.0);
    geometry_msgs::Pose currentPoseMsg;
    while (ros::ok())
    {
        tf::StampedTransform currentPose;
        try{
          listener.lookupTransform("/odom", "/base_link",
                                ros::Time(0), currentPose);
          tf::poseTFToMsg (currentPose, currentPoseMsg);
        break;
        }
        catch (tf::TransformException ex){
        ROS_ERROR("%s",ex.what());
        ros::Duration(1.0).sleep();
        }
    }
    smacc::SmaccMoveBaseActionClient::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    auto currentAngle = tf::getYaw(currentPoseMsg.orientation);
    auto targetAngle = currentAngle + angle_increment_degree *M_PI/180.0;
    goal.target_pose.pose.orientation =tf::createQuaternionMsgFromYaw(targetAngle);
    goal.target_pose.pose.position = currentPoseMsg.position;
    ROS_WARN_STREAM("rotate behavior current_state : " << currentPoseMsg);
    ROS_WARN_STREAM("rotate behavior target : " << goal.target_pose.pose);
    ROS_INFO("forward behavior: sending forward goal");
    moveBaseClient_->sendGoal(goal);
  }
Member Data Documentation
tf::TransformListener Rotate::listener
Definition at line 14 of file rotate.h.
smacc::SmaccMoveBaseActionClient* Rotate::moveBaseClient_
Definition at line 16 of file rotate.h.
smacc_planner_switcher::PlannerSwitcher* Rotate::plannerSwitcher_
Definition at line 18 of file rotate.h.
boost::optional<float> Rotate::rotateDegree
Definition at line 20 of file rotate.h.
Referenced by onEntry().
The documentation for this class was generated from the following file:
smacc_sm_examples/sm_radial_motion/include/sm_radial_motion/substates_behaviors/navigation/rotate.h