sm_dance_bot::CbNavigateForward Class Reference
#include <cb_navigate_forward.h>
Public Member Functions
CbNavigateForward (float forwardDistance)
CbNavigateForward ()
virtual void onEntry () override
virtual void onExit () override
CbNavigateForward (float forwardDistance)
CbNavigateForward ()
virtual void onEntry () override
virtual void onExit () override
Public Attributes
boost::optional< float > forwardDistance
boost::optional< float > forwardSpeed
tf::TransformListener listener
smacc::ClMoveBaseZ * moveBaseClient_
odom_tracker::OdomTracker * odomTracker_
Detailed Description
Definition at line 12 of file cb_navigate_forward.h.
Constructor & Destructor Documentation
sm_dance_bot::CbNavigateForward::CbNavigateForward (float forwardDistance) [inline]
Definition at line 24 of file cb_navigate_forward.h.
References forwardDistance.
    {
        this->forwardDistance = forwardDistance;
    }
sm_dance_bot::CbNavigateForward::CbNavigateForward () [inline]
Definition at line 29 of file cb_navigate_forward.h.
    {
    }
sm_dance_bot::CbNavigateForward::CbNavigateForward (float forwardDistance) [inline]
Definition at line 26 of file cb_navigate_forward.h.
References forwardDistance.
    {
        this->forwardDistance = forwardDistance;
    }
sm_dance_bot::CbNavigateForward::CbNavigateForward () [inline]
Definition at line 31 of file cb_navigate_forward.h.
    {
    }
Member Function Documentation
virtual void sm_dance_bot::CbNavigateForward::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 33 of file cb_navigate_forward.h.
References odom_tracker::OdomTracker::clearPath(), smacc::SmaccClientBehavior::currentState, forwardDistance, odomTracker_, smacc::ISmaccState::param(), smacc::ClMoveBaseZ::plannerSwitcher_, odom_tracker::RECORD_PATH_FORWARD, smacc::SmaccClientBehavior::requiresClient(), smacc::SmaccActionClientBase< ActionType >::sendGoal(), odom_tracker::OdomTracker::setStartPoint(), and odom_tracker::OdomTracker::setWorkingMode().
    {
        // straight motion distance
        double dist;
        if (!forwardDistance)
        {
            this->currentState->param("straight_motion_distance", dist, 3.5);
        }
        else
        {
            dist = *forwardDistance;
        }
        ROS_INFO_STREAM("Straight motion distance: " << dist);
        this->requiresClient(moveBaseClient_);
        auto odomTracker_ = this->getComponent<odom_tracker::OdomTracker>();
        //this should work better with a coroutine and await
        ros::Rate rate(10.0);
        tf::StampedTransform currentPose;
        while (ros::ok())
        {
            try
            {
                listener.lookupTransform("/odom", "/base_link",
                                         ros::Time(0), currentPose);
                break;
            }
            catch (tf::TransformException ex)
            {
                ROS_ERROR("%s", ex.what());
                ros::Duration(1.0).sleep();
            }
        }
        tf::Transform forwardDeltaTransform;
        forwardDeltaTransform.setIdentity();
        forwardDeltaTransform.setOrigin(tf::Vector3(dist, 0, 0));
        tf::Transform targetPose = currentPose * forwardDeltaTransform;
        smacc::ClMoveBaseZ::Goal goal;
        goal.target_pose.header.frame_id = "/odom";
        goal.target_pose.header.stamp = ros::Time::now();
        tf::poseTFToMsg(targetPose, goal.target_pose.pose);
        ROS_INFO_STREAM("TARGET POSE FORWARD: " << goal.target_pose.pose);
        ros::Duration(10).sleep();
        this->odomTracker_->clearPath();
        geometry_msgs::PoseStamped currentPoseMsg;
        currentPoseMsg.header.frame_id = "/odom";
        currentPoseMsg.header.stamp = ros::Time::now();
        tf::poseTFToMsg(currentPose, currentPoseMsg.pose);
        this->odomTracker_->setStartPoint(currentPoseMsg);
        this->odomTracker_->setWorkingMode(
      odom_tracker::WorkingMode::RECORD_PATH_FORWARD);
        moveBaseClient_->plannerSwitcher_->setForwardPlanner();
        moveBaseClient_->sendGoal(goal);
    }
virtual void sm_dance_bot::CbNavigateForward::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 35 of file cb_navigate_forward.h.
References odom_tracker::OdomTracker::clearPath(), smacc::SmaccClientBehavior::currentState, forwardDistance, smacc::ISmaccClient::getComponent(), smacc::ISmaccState::param(), smacc::ClMoveBaseZ::plannerSwitcher_, odom_tracker::RECORD_PATH_FORWARD, smacc::SmaccClientBehavior::requiresClient(), smacc::SmaccActionClientBase< ActionType >::sendGoal(), odom_tracker::OdomTracker::setStartPoint(), and odom_tracker::OdomTracker::setWorkingMode().
    {
        // straight motion distance
        double dist;
        if (!forwardDistance)
        {
            this->currentState->param("straight_motion_distance", dist, 3.5);
        }
        else
        {
            dist = *forwardDistance;
        }
        ROS_INFO_STREAM("Straight motion distance: " << dist);
        this->requiresClient(moveBaseClient_);
        odomTracker_ = moveBaseClient_->getComponent<
      odom_tracker::OdomTracker>();
        //this should work better with a coroutine and await
        ros::Rate rate(10.0);
        tf::StampedTransform currentPose;
        while (ros::ok())
        {
            try
            {
                listener.lookupTransform("/odom", "/base_link",
                                         ros::Time(0), currentPose);
                break;
            }
            catch (tf::TransformException ex)
            {
                ROS_ERROR("%s", ex.what());
                ros::Duration(1.0).sleep();
            }
        }
        tf::Transform forwardDeltaTransform;
        forwardDeltaTransform.setIdentity();
        forwardDeltaTransform.setOrigin(tf::Vector3(dist, 0, 0));
        tf::Transform targetPose = currentPose * forwardDeltaTransform;
        smacc::ClMoveBaseZ::Goal goal;
        goal.target_pose.header.frame_id = "/odom";
        goal.target_pose.header.stamp = ros::Time::now();
        tf::poseTFToMsg(targetPose, goal.target_pose.pose);
        ROS_INFO_STREAM("TARGET POSE FORWARD: " << goal.target_pose.pose);
        ros::Duration(10).sleep();
        odomTracker_->clearPath();
        geometry_msgs::PoseStamped currentPoseMsg;
        currentPoseMsg.header.frame_id = "/odom";
        currentPoseMsg.header.stamp = ros::Time::now();
        tf::poseTFToMsg(currentPose, currentPoseMsg.pose);
        odomTracker_->setStartPoint(currentPoseMsg);
        odomTracker_->setWorkingMode(
      odom_tracker::WorkingMode::RECORD_PATH_FORWARD);
        moveBaseClient_->plannerSwitcher_->setForwardPlanner();
        moveBaseClient_->sendGoal(goal);
    }
virtual void sm_dance_bot::CbNavigateForward::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 99 of file cb_navigate_forward.h.
References odom_tracker::IDLE, odomTracker_, and odom_tracker::OdomTracker::setWorkingMode().
    {
        this->odomTracker_->setWorkingMode(
      odom_tracker::WorkingMode::IDLE);
    }
virtual void sm_dance_bot::CbNavigateForward::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 102 of file cb_navigate_forward.h.
References odom_tracker::IDLE, and odom_tracker::OdomTracker::setWorkingMode().
    {
        this->odomTracker_->setWorkingMode(
      odom_tracker::WorkingMode::IDLE);
    }
Member Data Documentation
boost::optional< float > sm_dance_bot::CbNavigateForward::forwardDistance
Definition at line 15 of file cb_navigate_forward.h.
Referenced by CbNavigateForward(), and onEntry().
boost::optional< float > sm_dance_bot::CbNavigateForward::forwardSpeed
Definition at line 18 of file cb_navigate_forward.h.
tf::TransformListener sm_dance_bot::CbNavigateForward::listener
Definition at line 20 of file cb_navigate_forward.h.
smacc::ClMoveBaseZ * sm_dance_bot::CbNavigateForward::moveBaseClient_
Definition at line 22 of file cb_navigate_forward.h.
odom_tracker::OdomTracker* sm_dance_bot::CbNavigateForward::odomTracker_
Definition at line 24 of file cb_navigate_forward.h.
Referenced by onEntry(), and onExit().
The documentation for this class was generated from the following file:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_navigate_forward.h