sm_three_some::keyboard_client::CbDefaultKeyboardBehavior Class Reference
#include <cb_default_keyboard_behavior.h>
Public Member Functions
void onEntry ()
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
void OnKeyPress (char character)
template<typename TEv >
void postKeyEvent ()
Public Attributes
ClKeyboard * ClKeyboard_
boost::signals2::scoped_connection c_
std::function< void(char)> postEventKeyPress
Detailed Description
Definition at line 12 of file cb_default_keyboard_behavior.h.
Member Function Documentation
template<typename TObjectTag , typename TDerived > void sm_three_some::keyboard_client::CbDefaultKeyboardBehavior::configureEventSourceTypes () [inline]
Definition at line 31 of file cb_default_keyboard_behavior.h.
    {
        postEventKeyPress = [=](char character) {
            if (character == 'a')
                postKeyEvent<EvKeyPressA<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'b')
                postKeyEvent<EvKeyPressB<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'c')
                postKeyEvent<EvKeyPressC<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'd')
                postKeyEvent<EvKeyPressD<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'e')
                postKeyEvent<EvKeyPressE<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'f')
                postKeyEvent<EvKeyPressF<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'g')
                postKeyEvent<EvKeyPressG<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'h')
                postKeyEvent<EvKeyPressH<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'y')
                postKeyEvent<EvKeyPressI<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'j')
                postKeyEvent<EvKeyPressJ<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'k')
                postKeyEvent<EvKeyPressK<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'l')
                postKeyEvent<EvKeyPressL<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'm')
                postKeyEvent<EvKeyPressM<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'n')
                postKeyEvent<EvKeyPressN<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'o')
                postKeyEvent<EvKeyPressO<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'p')
                postKeyEvent<EvKeyPressP<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'q')
                postKeyEvent<EvKeyPressQ<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'r')
                postKeyEvent<EvKeyPressR<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 's')
                postKeyEvent<EvKeyPressS<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 't')
                postKeyEvent<EvKeyPressT<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'u')
                postKeyEvent<EvKeyPressU<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'v')
                postKeyEvent<EvKeyPressV<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'w')
                postKeyEvent<EvKeyPressW<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'x')
                postKeyEvent<EvKeyPressX<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'y')
                postKeyEvent<EvKeyPressY<CbDefaultKeyboardBehavior, TObjectTag>>();
            else if (character == 'z')
                postKeyEvent<EvKeyPressZ<CbDefaultKeyboardBehavior, TObjectTag>>();
        };
    }
void sm_three_some::keyboard_client::CbDefaultKeyboardBehavior::onEntry () [inline], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 18 of file cb_default_keyboard_behavior.h.
References OnKeyPress(), sm_three_some::keyboard_client::ClKeyboard::OnKeyPress, and smacc::SmaccClientBehavior::requiresClient().
    {
        this->requiresClient(ClKeyboard_);
        c_ = this->ClKeyboard_->OnKeyPress.connect(
            [this](char character) {
                this->OnKeyPress(character);
            });
    }
void sm_three_some::keyboard_client::CbDefaultKeyboardBehavior::OnKeyPress (char character) [inline]
Definition at line 89 of file cb_default_keyboard_behavior.h.
References postEventKeyPress.
Referenced by onEntry().
    {
        postEventKeyPress(character);
    }
template<typename TEv > void sm_three_some::keyboard_client::CbDefaultKeyboardBehavior::postKeyEvent () [inline]
Definition at line 95 of file cb_default_keyboard_behavior.h.
References smacc::demangleSymbol(), and smacc::SmaccClientBehavior::postEvent().
    {
        ROS_WARN("CbDefaultKeyboardBehavior %ld ev: %s", (long)(void *)this,
      smacc::demangleSymbol(typeid(TEv).name()).c_str());
        auto event = new TEv();
        this->postEvent(event);
    }
Member Data Documentation
boost::signals2::scoped_connection sm_three_some::keyboard_client::CbDefaultKeyboardBehavior::c_
Definition at line 16 of file cb_default_keyboard_behavior.h.
ClKeyboard* sm_three_some::keyboard_client::CbDefaultKeyboardBehavior::ClKeyboard_
Definition at line 15 of file cb_default_keyboard_behavior.h.
std::function<void(char)> sm_three_some::keyboard_client::CbDefaultKeyboardBehavior::postEventKeyPress
Definition at line 28 of file cb_default_keyboard_behavior.h.
Referenced by OnKeyPress().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_three_some/include/sm_three_some/clients/keyboard_client/client_behaviors/cb_default_keyboard_behavior.h