NavigateForward Class Reference
#include <navigate_forward.h>
Public Member Functions
NavigateForward (float forwardDistance)
NavigateForward ()
virtual void onEntry () override
Public Attributes
boost::optional< float > forwardDistance
boost::optional< float > forwardSpeed
tf::TransformListener listener
smacc::SmaccMoveBaseActionClient * moveBaseClient_
smacc_odom_tracker::OdomTracker * odomTracker_
smacc_planner_switcher::PlannerSwitcher * plannerSwitcher_
Detailed Description
Definition at line 10 of file navigate_forward.h.
Constructor & Destructor Documentation
NavigateForward::NavigateForward (float forwardDistance) [inline]
Definition at line 27 of file navigate_forward.h.
References forwardDistance.
  {
    this->forwardDistance = forwardDistance;
  }
NavigateForward::NavigateForward () [inline]
Definition at line 32 of file navigate_forward.h.
  {
  }
Member Function Documentation
virtual void NavigateForward::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 37 of file navigate_forward.h.
References smacc_odom_tracker::OdomTracker::clearPath(), smacc::SmaccSubStateBehavior::currentState, forwardDistance, smacc::ISmaccState::param(), smacc_odom_tracker::RECORD_PATH_FORWARD, smacc::SmaccSubStateBehavior::requiresComponent(), smacc::SmaccActionClientBase< ActionType >::sendGoal(), smacc_planner_switcher::PlannerSwitcher::setForwardPlanner(), smacc_odom_tracker::OdomTracker::setStartPoint(), and smacc_odom_tracker::OdomTracker::setWorkingMode().
  {
    // straight motion distance
    double dist;
    if(!forwardDistance)
    {
      this->currentState->param("straight_motion_distance", dist, 3.5);
    }
    else
    {
      dist = *forwardDistance;
    }
        
    ROS_INFO_STREAM("Straight motion distance: " << dist);
    this->requiresComponent(moveBaseClient_ ,ros::NodeHandle("move_base"));
    this->requiresComponent(odomTracker_);
    this->requiresComponent(plannerSwitcher_ , ros::NodeHandle("move_base"
      ));
    //this should work better with a coroutine and await
    ros::Rate rate(10.0);
    tf::StampedTransform currentPose;
    while (ros::ok())
    {
        try{
        listener.lookupTransform("/odom", "/base_link",
                                ros::Time(0), currentPose);
         break;
        }
        catch (tf::TransformException ex){
        ROS_ERROR("%s",ex.what());
        ros::Duration(1.0).sleep();
        }
    }
    tf::Transform forwardDeltaTransform;
    forwardDeltaTransform.setIdentity();
    forwardDeltaTransform.setOrigin(tf::Vector3(dist, 0, 0));
    tf::Transform targetPose = currentPose * forwardDeltaTransform;
    
    smacc::SmaccMoveBaseActionClient::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    tf::poseTFToMsg(targetPose, goal.target_pose.pose);
    
    ROS_INFO_STREAM("TARGET POSE FORWARD: " << goal.target_pose.pose);
    ros::Duration(10).sleep();
    this->odomTracker_->clearPath();
    
    geometry_msgs::PoseStamped currentPoseMsg;
    currentPoseMsg.header.frame_id = "/odom";
    currentPoseMsg.header.stamp = ros::Time::now();
    tf::poseTFToMsg(currentPose, currentPoseMsg.pose);
    this->odomTracker_->setStartPoint(currentPoseMsg);
    this->odomTracker_->setWorkingMode(
      smacc_odom_tracker::WorkingMode::RECORD_PATH_FORWARD);
    this->plannerSwitcher_->setForwardPlanner();
    moveBaseClient_->sendGoal(goal);
  }
Member Data Documentation
boost::optional<float> NavigateForward::forwardDistance
Definition at line 14 of file navigate_forward.h.
Referenced by NavigateForward(), and onEntry().
boost::optional<float> NavigateForward::forwardSpeed
Definition at line 17 of file navigate_forward.h.
tf::TransformListener NavigateForward::listener
Definition at line 19 of file navigate_forward.h.
smacc::SmaccMoveBaseActionClient* NavigateForward::moveBaseClient_
Definition at line 21 of file navigate_forward.h.
smacc_odom_tracker::OdomTracker* NavigateForward::odomTracker_
Definition at line 23 of file navigate_forward.h.
smacc_planner_switcher::PlannerSwitcher* NavigateForward::plannerSwitcher_
Definition at line 25 of file navigate_forward.h.
The documentation for this class was generated from the following file:
smacc_sm_examples/sm_radial_motion/include/sm_radial_motion/substates_behaviors/navigation/navigate_forward.h