smacc::SmaccSubStateBehavior Class Reference
#include <smacc_substate_behavior.h>
Public Member Functions
SmaccSubStateBehavior ()
virtual ~SmaccSubStateBehavior ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage, bool verbose=false)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool verbose=false)
std::string getName () const
virtual void onEntry ()
virtual void onExit ()
Public Attributes
ISmaccStateMachine * stateMachine
ISmaccState * currentState
smacc::Orthogonal * currentOrthogonal
Detailed Description
Definition at line 31 of file smacc_substate_behavior.h.
Constructor & Destructor Documentation
smacc::SmaccSubStateBehavior::SmaccSubStateBehavior ()
Definition at line 5 of file smacc_substate_behavior.cpp.
References currentState, and stateMachine.
{
    stateMachine = nullptr;
    currentState = nullptr;
}
smacc::SmaccSubStateBehavior::~SmaccSubStateBehavior () [virtual]
Definition at line 11 of file smacc_substate_behavior.cpp.
{
    ROS_WARN("Substate behavior deallocated.");
}
Member Function Documentation
std::string smacc::SmaccSubStateBehavior::getName () const
Definition at line 16 of file smacc_substate_behavior.cpp.
References smacc::demangleSymbol().
Referenced by onEntry(), onExit(), and requiresComponent().
{
    return demangleSymbol(typeid(*this).name());
}
void smacc::SmaccSubStateBehavior::onEntry () [virtual]
Reimplemented in smacc::Timer, sm_dance_bot::SbNavigateBackwards, sm_dance_bot::SbNavigateForward, sm_dance_bot::SbNavigateGlobalPosition, smacc::SensorTopic< Derived, MessageType, ClientType >, smacc::SensorTopic< SbConditionTemperatureSensor, sensor_msgs::Temperature, TemperatureSensor >, smacc::SensorTopic< SbLidarSensor, sensor_msgs::LaserScan, LaserSensor >, smacc::Keyboard, sm_dance_bot::SbRotate, sm_dance_bot::Service3Behavior, sm_dance_bot::SbStringPublisher, sm_dance_bot::SbLidarSensor, sm_dance_bot::SbUndoPathBackwards, sm_dance_bot::SbKeyboard, sm_dance_bot::SbTimer, sm_dance_bot::SbToolStart, sm_dance_bot::SbToolStop, sm_three_some::SbBehavior1, sm_atomic::SbState1, sm_three_some::SbBehavior1b, sm_three_some::SbBehavior2b, and sm_three_some::SbBehavior2.
Definition at line 21 of file smacc_substate_behavior.cpp.
References getName().
Referenced by requiresComponent().
{
    ROS_INFO("SmaccSubStateBehavior %s onEntry", this->getName().c_str());
}
void smacc::SmaccSubStateBehavior::onExit () [virtual]
Reimplemented in sm_dance_bot::SbNavigateBackwards, sm_dance_bot::SbNavigateForward, sm_dance_bot::SbNavigateGlobalPosition, smacc::SensorTopic< Derived, MessageType, ClientType >, smacc::SensorTopic< SbConditionTemperatureSensor, sensor_msgs::Temperature, TemperatureSensor >, smacc::SensorTopic< SbLidarSensor, sensor_msgs::LaserScan, LaserSensor >, smacc::Timer, smacc::Keyboard, sm_dance_bot::SbStringPublisher, sm_dance_bot::SbTimer, sm_dance_bot::SbToolStart, and sm_dance_bot::SbToolStop.
Definition at line 26 of file smacc_substate_behavior.cpp.
References getName().
Referenced by requiresComponent().
{
    ROS_INFO("SmaccSubStateBehavior %s onExit", this->getName().c_str());
}
template<typename EventType > void smacc::SmaccSubStateBehavior::postEvent (const EventType & ev) [inline]
Definition at line 50 of file smacc_substate_behavior.h.
References smacc::ISmaccStateMachine::postEvent().
Referenced by sm_dance_bot::SbTimer::onEntry(), smacc::SensorTopic< SbLidarSensor, sensor_msgs::LaserScan, LaserSensor >::onEntry(), and sm_dance_bot::SbKeyboard::postKeyEvent().
    {
        if (stateMachine == nullptr)
        {
            ROS_ERROR("The substate behavior cannot post events before being assigned to an orthogonal.
       Ignoring post event call.");
        }
        else
        {
            stateMachine->postEvent(ev);
        }
    }
template<typename SmaccClientType > void smacc::SmaccSubStateBehavior::requiresClient (SmaccClientType *& storage, bool verbose = false) [inline]
Definition at line 63 of file smacc_substate_behavior.h.
References smacc::Orthogonal::requiresClient().
Referenced by sm_atomic::SbState1::onEntry(), sm_dance_bot::SbTimer::onEntry(), sm_dance_bot::SbToolStart::onEntry(), sm_dance_bot::SbToolStop::onEntry(), sm_dance_bot::SbKeyboard::onEntry(), sm_dance_bot::SbUndoPathBackwards::onEntry(), sm_dance_bot::SbStringPublisher::onEntry(), sm_dance_bot::SbRotate::onEntry(), smacc::SensorTopic< SbLidarSensor, sensor_msgs::LaserScan, LaserSensor >::onEntry(), sm_dance_bot::SbNavigateGlobalPosition::onEntry(), sm_dance_bot::SbNavigateForward::onEntry(), and sm_dance_bot::SbNavigateBackwards::onEntry().
    {
        currentOrthogonal->requiresClient(storage, verbose);
    }
template<typename SmaccComponentType > void smacc::SmaccSubStateBehavior::requiresComponent (SmaccComponentType *& storage, bool verbose = false) [inline]
Definition at line 69 of file smacc_substate_behavior.h.
References getName(), onEntry(), onExit(), and smacc::ISmaccStateMachine::requiresComponent().
Referenced by sm_dance_bot::SbUndoPathBackwards::onEntry(), sm_dance_bot::SbNavigateGlobalPosition::onEntry(), sm_dance_bot::SbNavigateForward::onEntry(), and sm_dance_bot::SbNavigateBackwards::onEntry().
    {
        if (stateMachine == nullptr)
        {
            ROS_ERROR("Cannot use the requiresComponent funcionality before asigning the substate behavior
       to an orthogonal. Try using the OnEntry method to capture required components.");
        }
        else
        {
            stateMachine->requiresComponent(storage, verbose);
        }
    }
Member Data Documentation
smacc::Orthogonal* smacc::SmaccSubStateBehavior::currentOrthogonal
Definition at line 43 of file smacc_substate_behavior.h.
ISmaccState* smacc::SmaccSubStateBehavior::currentState
Definition at line 41 of file smacc_substate_behavior.h.
Referenced by sm_dance_bot::SbRotate::onEntry(), sm_dance_bot::SbNavigateForward::onEntry(), sm_dance_bot::SbNavigateBackwards::onEntry(), sm_dance_bot::SbNavigateGlobalPosition::readStartPoseFromParameterServer(), and SmaccSubStateBehavior().
ISmaccStateMachine* smacc::SmaccSubStateBehavior::stateMachine
Definition at line 38 of file smacc_substate_behavior.h.
Referenced by sm_dance_bot::SbNavigateGlobalPosition::goToRadialStart(), and SmaccSubStateBehavior().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_substate_behavior.h
smacc/src/smacc/smacc_substate_behavior.cpp