sm_dance_bot_2::cl_lidar::CpLidarSensorData Class Reference
#include <cp_lidar_data.h>
Public Member Functions
virtual void initialize (smacc::ISmaccClient *owner) override
void storeMessage (const sensor_msgs::LaserScan &scanmsg)
Public Attributes
sensor_msgs::LaserScan lastMessage_
float forwardObstacleDistance
Additional Inherited Members
Detailed Description
Definition at line 8 of file cp_lidar_data.h.
Member Function Documentation
virtual void sm_dance_bot_2::cl_lidar::CpLidarSensorData::initialize (smacc::ISmaccClient * owner) [inline], [override], [virtual]
Reimplemented from smacc::ISmaccComponent.
Definition at line 14 of file cp_lidar_data.h.
References smacc::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), and storeMessage().
  {
    auto client_ = dynamic_cast<
      smacc::SmaccSubscriberClient<sensor_msgs::LaserScan> *>
      (owner);
    client_->onMessageReceived(&CpLidarSensorData::storeMessage
      , this);
  }
void sm_dance_bot_2::cl_lidar::CpLidarSensorData::storeMessage (const sensor_msgs::LaserScan & scanmsg) [inline]
Definition at line 20 of file cp_lidar_data.h.
Referenced by initialize().
  {
    this->lastMessage_ = scanmsg;
    this->forwardObstacleDistance = scanmsg.ranges[scanmsg.ranges.size() / 2];
  }
Member Data Documentation
float sm_dance_bot_2::cl_lidar::CpLidarSensorData::forwardObstacleDistance
Definition at line 12 of file cp_lidar_data.h.
Referenced by sm_dance_bot_2::radial_motion_states::SsrRadialEndPoint::onInitialize().
sensor_msgs::LaserScan sm_dance_bot_2::cl_lidar::CpLidarSensorData::lastMessage_
Definition at line 11 of file cp_lidar_data.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_dance_bot_2/include/sm_dance_bot_2/clients/cl_lidar/components/cp_lidar_data.h