smacc_odom_tracker::OdomTracker Class Reference
This class track the required distance of the cord based on the external localization system.
#include <odom_tracker.h>
Public Member Functions
OdomTracker ()
void initialize (std::string nodeName)
Must be called at the begining of the execution.
virtual void processOdometryMessage (const nav_msgs::Odometry &odom)
odom callback: Updates the path - this must be called periodically for each odometry message.
void setWorkingMode (WorkingMode workingMode)
void setPublishMessages (bool value)
void pushPath ()
void popPath ()
void clearPath ()
void setStartPoint (const geometry_msgs::PoseStamped &pose)
nav_msgs::Path getPath ()
Protected Member Functions
virtual void rtPublishPaths (ros::Time timestamp)
virtual bool updateForward (const nav_msgs::Odometry &odom)
virtual bool updateBackward (const nav_msgs::Odometry &odom)
Protected Attributes
std::shared_ptr< realtime_tools::RealtimePublisher< nav_msgs::Path > > robotBasePathPub_
ros::Subscriber odomSub_
double minPointDistanceForwardThresh_
How much distance there is between two points of the path.
double minPointDistanceBackwardThresh_
Meters.
double minPointAngularDistanceForwardThresh_
rads
double minPointAngularDistanceBackwardThresh_
rads
bool publishMessages
nav_msgs::Path baseTrajectory_
Processed path for the mouth of the reel.
WorkingMode workingMode_
std::vector< nav_msgs::Path > pathStack_
bool subscribeToOdometryTopic_
std::mutex m_mutex_
Detailed Description
This class track the required distance of the cord based on the external localization system.
Definition at line 34 of file odom_tracker.h.
Constructor & Destructor Documentation
smacc_odom_tracker::OdomTracker::OdomTracker ()
Definition at line 11 of file odom_tracker.cpp.
References publishMessages, smacc_odom_tracker::RECORD_PATH_FORWARD, subscribeToOdometryTopic_, and workingMode_.
{
    workingMode_ = WorkingMode::RECORD_PATH_FORWARD;
    publishMessages = true;
    subscribeToOdometryTopic_ = true;
}
Member Function Documentation
void smacc_odom_tracker::OdomTracker::clearPath ()
Definition at line 108 of file odom_tracker.cpp.
References baseTrajectory_, m_mutex_, and rtPublishPaths().
Referenced by sm_dance_bot::CbNavigateForward::onEntry(), and sm_dance_bot::CbNavigateBackwards::onEntry().
{
    std::lock_guard<std::mutex> lock(m_mutex_);
    baseTrajectory_.poses.clear();
    rtPublishPaths(ros::Time::now());
}
nav_msgs::Path smacc_odom_tracker::OdomTracker::getPath ()
Definition at line 129 of file odom_tracker.cpp.
References baseTrajectory_, and m_mutex_.
Referenced by sm_dance_bot::CbUndoPathBackwards::onEntry().
{
    std::lock_guard<std::mutex> lock(m_mutex_);
    return this->baseTrajectory_;
}
void smacc_odom_tracker::OdomTracker::initialize (std::string nodeName)
Must be called at the begining of the execution.
init()
Definition at line 23 of file odom_tracker.cpp.
References minPointAngularDistanceBackwardThresh_, minPointAngularDistanceForwardThresh_, minPointDistanceBackwardThresh_, minPointDistanceForwardThresh_, odomSub_, processOdometryMessage(), robotBasePathPub_, and subscribeToOdometryTopic_.
Referenced by sm_dance_bot::NavigationOrthogonal::onInitialize().
{
    ros::NodeHandle nh(nodeName);
    ROS_WARN("Initializing Odometry Tracker");
    if(!nh.getParam("min_point_distance_forward_thresh",
      minPointDistanceForwardThresh_))
    {
        minPointDistanceForwardThresh_ = 0.005; // 1 mm
    }
    if(!nh.getParam("min_point_distance_backward_thresh",
      minPointDistanceBackwardThresh_))
    {
        minPointDistanceBackwardThresh_ = 0.05; // 1 mm
    }
    if(!nh.getParam("min_point_angular_distance_forward_thresh",
      minPointAngularDistanceForwardThresh_))
    {
        minPointAngularDistanceForwardThresh_ = 0.15 ; // degree
    }
    if(!nh.getParam("min_point_angular_distance_backward_thresh",
      minPointAngularDistanceBackwardThresh_))
    {
        minPointAngularDistanceBackwardThresh_ = 0.15 ; // degree
    }
    if(this->subscribeToOdometryTopic_)
    {
        odomSub_= nh.subscribe("odom", 1, &
      OdomTracker::processOdometryMessage, this);
    }
    robotBasePathPub_ = std::make_shared<realtime_tools::RealtimePublisher<nav_msgs::Path>
      >(nh, "odom_tracker_path", 1);
}
void smacc_odom_tracker::OdomTracker::popPath ()
Definition at line 94 of file odom_tracker.cpp.
References baseTrajectory_, m_mutex_, and pathStack_.
Referenced by OdomTrackerActionServer::execute().
{
    ROS_INFO("odom_tracker m_mutex acquire");
    std::lock_guard<std::mutex> lock(m_mutex_);
    
    if(!pathStack_.empty())
    {
        baseTrajectory_.poses = pathStack_.back().poses;
        pathStack_.pop_back();
    }
    ROS_INFO("odom_tracker m_mutex release");
}
void smacc_odom_tracker::OdomTracker::processOdometryMessage (const nav_msgs::Odometry & odom) [virtual]
odom callback: Updates the path - this must be called periodically for each odometry message.
processOdometryMessage()
Definition at line 253 of file odom_tracker.cpp.
References smacc_odom_tracker::CLEAR_PATH_BACKWARD, m_mutex_, publishMessages, smacc_odom_tracker::RECORD_PATH_FORWARD, rtPublishPaths(), updateBackward(), updateForward(), and workingMode_.
Referenced by initialize().
{
    //ROS_INFO("odom_tracker m_mutex acquire");
    std::lock_guard<std::mutex> lock(m_mutex_);
    if(workingMode_ == WorkingMode::RECORD_PATH_FORWARD)
    {
        updateForward(odom);
    }
    else if (workingMode_ == WorkingMode::CLEAR_PATH_BACKWARD)
    {
        updateBackward(odom);
    }
    //ROS_WARN("odomTracker odometry callback");
    if(publishMessages)
    {
        rtPublishPaths(odom.header.stamp);
    }
    //ROS_INFO("odom_tracker m_mutex release");
}
void smacc_odom_tracker::OdomTracker::pushPath ()
Definition at line 85 of file odom_tracker.cpp.
References baseTrajectory_, m_mutex_, and pathStack_.
Referenced by OdomTrackerActionServer::execute().
{
    ROS_INFO("odom_tracker m_mutex acquire");
    std::lock_guard<std::mutex> lock(m_mutex_);
    pathStack_.push_back(baseTrajectory_);
    baseTrajectory_.poses.clear();
    ROS_INFO("odom_tracker m_mutex release");
}
void smacc_odom_tracker::OdomTracker::rtPublishPaths (ros::Time timestamp) [protected], [virtual]
rtPublishPaths() Copy trajectory
Definition at line 140 of file odom_tracker.cpp.
References baseTrajectory_, keyboard_node::msg, and robotBasePathPub_.
Referenced by clearPath(), and processOdometryMessage().
{
    if(robotBasePathPub_->trylock())
    {
        nav_msgs::Path& msg = robotBasePathPub_->msg_;
        msg = baseTrajectory_;
        msg.header.stamp = timestamp;
        robotBasePathPub_->unlockAndPublish();
    }
}
void smacc_odom_tracker::OdomTracker::setPublishMessages (bool value)
setPublishMessages()
Definition at line 77 of file odom_tracker.cpp.
References m_mutex_, and publishMessages.
Referenced by OdomTrackerActionServer::execute().
{
    //ROS_INFO("odom_tracker m_mutex acquire");
    std::lock_guard<std::mutex> lock(m_mutex_);
    publishMessages = value;
    //ROS_INFO("odom_tracker m_mutex release");
}
void smacc_odom_tracker::OdomTracker::setStartPoint (const geometry_msgs::PoseStamped & pose)
Definition at line 116 of file odom_tracker.cpp.
References baseTrajectory_, and m_mutex_.
Referenced by sm_dance_bot::CbNavigateForward::onEntry(), and sm_dance_bot::CbNavigateBackwards::onEntry().
{
    std::lock_guard<std::mutex> lock(m_mutex_);
    if(baseTrajectory_.poses.size() >0)
    {
        baseTrajectory_.poses[0]=pose;
    }
    else
    {
        baseTrajectory_.poses.push_back(pose);
    }
}
void smacc_odom_tracker::OdomTracker::setWorkingMode (WorkingMode workingMode)
setWorkingMode()
Definition at line 63 of file odom_tracker.cpp.
References m_mutex_, and workingMode_.
Referenced by OdomTrackerActionServer::execute(), sm_dance_bot::CbUndoPathBackwards::onEntry(), sm_dance_bot::CbNavigateGlobalPosition::onEntry(), sm_dance_bot::CbNavigateForward::onEntry(), sm_dance_bot::CbNavigateBackwards::onEntry(), sm_dance_bot::CbNavigateForward::onExit(), and sm_dance_bot::CbNavigateBackwards::onExit().
{
    //ROS_INFO("odom_tracker m_mutex acquire");
    std::lock_guard<std::mutex> lock(m_mutex_);
    ROS_INFO("[OdomTracker] setting working mode to: %d", (uint8_t)workingMode);
    workingMode_ = workingMode;
    //ROS_INFO("odom_tracker m_mutex release");
}
bool smacc_odom_tracker::OdomTracker::updateBackward (const nav_msgs::Odometry & odom) [protected], [virtual]
updateBackward() Track robot base pose
Not removing point because it is enough far from the last cord point
Definition at line 158 of file odom_tracker.cpp.
References baseTrajectory_, minPointDistanceBackwardThresh_, and smacc_odom_tracker::p2pDistance().
Referenced by processOdometryMessage().
{
    // we initially accept any message if the queue is empty
    geometry_msgs::PoseStamped base_pose;
    
    base_pose.pose = odom.pose.pose;
    base_pose.header = odom.header;
    baseTrajectory_.header = odom.header;
    bool acceptBackward = false;
    bool pullingerror = false;
    if(baseTrajectory_.poses.empty())
    {
        acceptBackward=false;
    }
    else
    {
        const geometry_msgs::Point& prevPoint = baseTrajectory_.poses.back().pose.position;
        const geometry_msgs::Point& currePoint = base_pose.pose.position;
        double lastpointdist = p2pDistance(prevPoint, currePoint);
        
        acceptBackward = !baseTrajectory_.poses.empty()
                        && lastpointdist < minPointDistanceBackwardThresh_;
        pullingerror = lastpointdist > 2 * minPointDistanceBackwardThresh_;
    }
    //ROS_INFO("Backwards, last distance: %lf < %lf accept: %d", dist, minPointDistanceBackwardThresh_,
       acceptBackward);
    if (acceptBackward)
    {
        baseTrajectory_.poses.pop_back();
    }
    else if (pullingerror) {
        ROS_INFO_THROTTLE(2,"Incorrect backwards motion.");
    }
    else
    {
    }
    return acceptBackward;
}
bool smacc_odom_tracker::OdomTracker::updateForward (const nav_msgs::Odometry & odom) [protected], [virtual]
updateForward() Track robot base pose
Definition at line 206 of file odom_tracker.cpp.
References baseTrajectory_, minPointDistanceForwardThresh_, and smacc_odom_tracker::p2pDistance().
Referenced by processOdometryMessage().
{
    geometry_msgs::PoseStamped base_pose;
    base_pose.pose = odom.pose.pose;
    base_pose.header = odom.header;
    baseTrajectory_.header = odom.header;
    bool enqueueOdomMessage = false;
    double dist = -1;
    if(baseTrajectory_.poses.empty())
    {
        enqueueOdomMessage = true;
    }
    else
    {
        const geometry_msgs::Point& prevPoint = baseTrajectory_.poses.back().pose.position;
        const geometry_msgs::Point& currePoint = base_pose.pose.position;
        dist = p2pDistance(prevPoint, currePoint);
        //ROS_WARN("dist %lf vs min %lf", dist, minPointDistanceForwardThresh_);
        if(dist > minPointDistanceForwardThresh_)
        {
            enqueueOdomMessage = true;
        }
        else
        {
            //ROS_WARN("skip odom, dist: %lf", dist);
            enqueueOdomMessage = false;
        }
    }
    if(enqueueOdomMessage)
    {
        baseTrajectory_.poses.push_back(base_pose);
    }
    return enqueueOdomMessage;
}
Member Data Documentation
nav_msgs::Path smacc_odom_tracker::OdomTracker::baseTrajectory_ [protected]
Processed path for the mouth of the reel.
Definition at line 109 of file odom_tracker.h.
Referenced by clearPath(), getPath(), popPath(), pushPath(), rtPublishPaths(), setStartPoint(), updateBackward(), and updateForward().
std::mutex smacc_odom_tracker::OdomTracker::m_mutex_ [protected]
Definition at line 118 of file odom_tracker.h.
Referenced by clearPath(), getPath(), popPath(), processOdometryMessage(), pushPath(), setPublishMessages(), setStartPoint(), and setWorkingMode().
double smacc_odom_tracker::OdomTracker::minPointAngularDistanceBackwardThresh_ [protected]
rads
Definition at line 101 of file odom_tracker.h.
Referenced by initialize().
double smacc_odom_tracker::OdomTracker::minPointAngularDistanceForwardThresh_ [protected]
rads
Definition at line 98 of file odom_tracker.h.
Referenced by initialize().
double smacc_odom_tracker::OdomTracker::minPointDistanceBackwardThresh_ [protected]
Meters.
Definition at line 95 of file odom_tracker.h.
Referenced by initialize(), and updateBackward().
double smacc_odom_tracker::OdomTracker::minPointDistanceForwardThresh_ [protected]
How much distance there is between two points of the path.
Definition at line 92 of file odom_tracker.h.
Referenced by initialize(), and updateForward().
ros::Subscriber smacc_odom_tracker::OdomTracker::odomSub_ [protected]
Definition at line 88 of file odom_tracker.h.
Referenced by initialize().
std::vector<nav_msgs::Path> smacc_odom_tracker::OdomTracker::pathStack_ [protected]
Definition at line 113 of file odom_tracker.h.
Referenced by popPath(), and pushPath().
bool smacc_odom_tracker::OdomTracker::publishMessages [protected]
Definition at line 106 of file odom_tracker.h.
Referenced by OdomTracker(), processOdometryMessage(), and setPublishMessages().
std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::Path> > smacc_odom_tracker::OdomTracker::robotBasePathPub_ [protected]
Definition at line 83 of file odom_tracker.h.
Referenced by initialize(), and rtPublishPaths().
bool smacc_odom_tracker::OdomTracker::subscribeToOdometryTopic_ [protected]
Definition at line 116 of file odom_tracker.h.
Referenced by initialize(), and OdomTracker().
WorkingMode smacc_odom_tracker::OdomTracker::workingMode_ [protected]
Definition at line 111 of file odom_tracker.h.
Referenced by OdomTracker(), processOdometryMessage(), and setWorkingMode().
The documentation for this class was generated from the following files:
smacc_client_library/smacc_navigation/smacc_odom_tracker/include/smacc_odom_tracker/odom_tracker.h
smacc_client_library/smacc_navigation/smacc_odom_tracker/src/odom_tracker.cpp