smacc::SensorTopic< ClientType > Class Template Reference
#include <cb_sensor_base.h>
Public Types
typedef ClientType::TMessageType TMessageType
Public Member Functions
SensorTopic ()
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
template<typename EvType >
void propagateEvent (const TMessageType &msg)
template<typename EvType >
void propagateEvent2 (const ros::TimerEvent &tdata)
virtual void onEntry () override
void onExit ()
virtual void onMessageCallback (const TMessageType &msg)
Static Public Member Functions
static std::string getEventLabel ()
Public Attributes
ClientType * sensor_
std::function< void()> deferedEventPropagation
Detailed Description
template<typename ClientType>
*
class smacc::SensorTopic< ClientType >
Definition at line 9 of file cb_sensor_base.h.
Member Typedef Documentation
template<typename ClientType> typedef ClientType::TMessageType smacc::SensorTopic< ClientType >::TMessageType
Definition at line 12 of file cb_sensor_base.h.
Constructor & Destructor Documentation
template<typename ClientType> smacc::SensorTopic< ClientType >::SensorTopic () [inline]
Definition at line 16 of file cb_sensor_base.h.
  {
    sensor_ = nullptr;
  }
Member Function Documentation
template<typename ClientType> template<typename TObjectTag , typename TDerived > void smacc::SensorTopic< ClientType >::configureEventSourceTypes () [inline]
Definition at line 30 of file cb_sensor_base.h.
  {
    deferedEventPropagation = [=]() {
      // just propagate the client events from this client behavior source.
      sensor_->onMessageReceived(&SensorTopic<ClientType>::propagateEvent
      <EvTopicMessage<TDerived, TObjectTag>>, this);
      sensor_->onFirstMessageReceived(&
      SensorTopic<ClientType>::propagateEvent<
      EvTopicInitialMessage<TDerived, TObjectTag>>, this);
      sensor_->onMessageTimeout(&SensorTopic<ClientType>::propagateEvent2
      <EvTopicMessageTimeout<TDerived, TObjectTag>>, this);
    };
  }
template<typename ClientType> static std::string smacc::SensorTopic< ClientType >::getEventLabel () [inline], [static]
Definition at line 21 of file cb_sensor_base.h.
  {
    // show ros message type
    return demangleSymbol(typeid(TMessageType).name());
  }
template<typename ClientType> virtual void smacc::SensorTopic< ClientType >::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Reimplemented in sm_dance_bot::cl_lidar::CbLidarSensor, and sm_dance_bot_2::cl_lidar::CbLidarSensor.
Definition at line 52 of file cb_sensor_base.h.
Referenced by sm_dance_bot::cl_lidar::CbLidarSensor::onEntry(), and sm_dance_bot_2::cl_lidar::CbLidarSensor::onEntry().
  {
    ROS_INFO("SensorTopic onEntry. Requires client of type '%s'", demangleSymbol<ClientType>().c_str());
    this->requiresClient(sensor_);
    if (sensor_ == nullptr)
    {
      ROS_FATAL_STREAM("Sensor client behavior needs a client of type: " << demangleSymbol<ClientType>() <<
       " but it is not found.");
    }
    else
    {
      deferedEventPropagation();
      ROS_INFO("SensorTopic onEntry. sensor initialize");
      sensor_->initialize();
    }
  }
template<typename ClientType> void smacc::SensorTopic< ClientType >::onExit () [inline], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 70 of file cb_sensor_base.h.
  {
  }
template<typename ClientType> virtual void smacc::SensorTopic< ClientType >::onMessageCallback (const TMessageType & msg) [inline], [virtual]
Definition at line 74 of file cb_sensor_base.h.
  {
    // empty to fill by sensor customization based on inheritance
  }
template<typename ClientType> template<typename EvType > void smacc::SensorTopic< ClientType >::propagateEvent (const TMessageType & msg) [inline]
Definition at line 41 of file cb_sensor_base.h.
  {
    this->postEvent<EvType>();
  }
template<typename ClientType> template<typename EvType > void smacc::SensorTopic< ClientType >::propagateEvent2 (const ros::TimerEvent & tdata) [inline]
Definition at line 47 of file cb_sensor_base.h.
  {
    this->postEvent<EvType>();
  }
Member Data Documentation
template<typename ClientType> std::function<void()> smacc::SensorTopic< ClientType >::deferedEventPropagation
Definition at line 27 of file cb_sensor_base.h.
Referenced by smacc::SensorTopic< ClLaserSensor >::onEntry().
template<typename ClientType> ClientType* smacc::SensorTopic< ClientType >::sensor_
Definition at line 14 of file cb_sensor_base.h.
The documentation for this class was generated from the following file:
smacc_client_library/smacc_interface_components/include/smacc_interface_components/client_behaviors/cb_sensor_base.h