smacc::WaypointEventDispatcher Class Reference
#include <waypoints_event_dispatcher.h>
Public Member Functions
template<typename TDerived , typename TObjectTag >
void initialize (ClMoveBaseZ *client)
void postWaypointEvent (int index)
Private Attributes
std::function< void()> postWaypointFn [WAYPOINTS_EVENTCOUNT]
Detailed Description
Definition at line 42 of file waypoints_event_dispatcher.h.
Member Function Documentation
template<typename TDerived , typename TObjectTag > void smacc::WaypointEventDispatcher::initialize (ClMoveBaseZ * client)
Definition at line 32 of file move_base_action_client_impl.h.
Referenced by smacc::WaypointNavigator::assignToOrthogonal().
{
    configurePostEvWaypoint<EvWaypoint0<TDerived, TObjectTag>>(postWaypointFn, client, 0);
    configurePostEvWaypoint<EvWaypoint1<TDerived, TObjectTag>>(postWaypointFn, client, 1);
    configurePostEvWaypoint<EvWaypoint2<TDerived, TObjectTag>>(postWaypointFn, client, 2);
    configurePostEvWaypoint<EvWaypoint3<TDerived, TObjectTag>>(postWaypointFn, client, 3);
    configurePostEvWaypoint<EvWaypoint4<TDerived, TObjectTag>>(postWaypointFn, client, 4);
    // postWaypointFn[0] = [=]() {
    // client->template postEvent<EvWaypoint0<TDerived, TObjectTag>>();
    // };
    // postWaypointFn[1] = [=]() {
    // client->template postEvent<EvWaypoint1<TDerived, TObjectTag>>();
    // };
}
void smacc::WaypointEventDispatcher::postWaypointEvent (int index)
Definition at line 5 of file waypoints_event_dispatcher.cpp.
References postWaypointFn, and WAYPOINTS_EVENTCOUNT.
Referenced by smacc::WaypointNavigator::onGoalReached().
{
    auto& fn = postWaypointFn[index % WAYPOINTS_EVENTCOUNT];
    if(fn!=nullptr)
        fn();
}
Member Data Documentation
std::function<void()> smacc::WaypointEventDispatcher::postWaypointFn[WAYPOINTS_EVENTCOUNT] [private]
Definition at line 44 of file waypoints_event_dispatcher.h.
Referenced by postWaypointEvent().
The documentation for this class was generated from the following files:
smacc_client_library/smacc_navigation/smacc_navigation_plugin/include/smacc_navigation_plugin/waypoints_event_dispatcher.h
smacc_client_library/smacc_navigation/smacc_navigation_plugin/include/smacc_navigation_plugin/impl/move_base_action_client_impl.h
smacc_client_library/smacc_navigation/smacc_navigation_plugin/src/waypoints_event_dispatcher.cpp