smacc::SmaccTimerClient Class Reference
#include <timer_client.h>
Public Member Functions
SmaccTimerClient (ros::Duration duration, bool oneshot=false)
virtual ~SmaccTimerClient ()
virtual void initialize ()
Public Attributes
boost::signals2::signal< void(EvTimer< SmaccTimerClient > *)> onTimerTick
boost::signals2::scoped_connection c_
Protected Attributes
ros::NodeHandle nh_
ros::Timer timer
ros::Duration duration
bool oneshot
Private Member Functions
void timerCallback (const ros::TimerEvent &timedata)
Detailed Description
Definition at line 27 of file timer_client.h.
Constructor & Destructor Documentation
smacc::SmaccTimerClient::SmaccTimerClient (ros::Duration duration, bool oneshot = false) [inline]
Definition at line 33 of file timer_client.h.
    {
        this->duration = duration;
        this->oneshot = oneshot;
    }
virtual smacc::SmaccTimerClient::~SmaccTimerClient () [inline], [virtual]
Definition at line 39 of file timer_client.h.
    {
        timer.stop();
    }
Member Function Documentation
virtual void smacc::SmaccTimerClient::initialize () [inline], [virtual]
Reimplemented from smacc::ISmaccClient.
Definition at line 44 of file timer_client.h.
References timerCallback().
    {
        timer = nh_.createTimer(duration, boost::bind(&
      SmaccTimerClient::timerCallback, this, _1),
      oneshot);
    }
void smacc::SmaccTimerClient::timerCallback (const ros::TimerEvent & timedata) [inline], [private]
Definition at line 57 of file timer_client.h.
Referenced by initialize().
    {
        //auto *event = new EvTimer<SmaccTimerClient>(this, timedata);
        auto *event = new EvTimer<SmaccTimerClient>();
        this->postEvent(event);
        onTimerTick(event);
    }
Member Data Documentation
boost::signals2::scoped_connection smacc::SmaccTimerClient::c_
Definition at line 31 of file timer_client.h.
ros::Duration smacc::SmaccTimerClient::duration [protected]
Definition at line 53 of file timer_client.h.
ros::NodeHandle smacc::SmaccTimerClient::nh_ [protected]
Definition at line 50 of file timer_client.h.
bool smacc::SmaccTimerClient::oneshot [protected]
Definition at line 54 of file timer_client.h.
boost::signals2::signal<void(EvTimer<SmaccTimerClient> *)> smacc::SmaccTimerClient::onTimerTick
Definition at line 30 of file timer_client.h.
Referenced by sm_dance_bot::SbTimer::onEntry().
ros::Timer smacc::SmaccTimerClient::timer [protected]
Definition at line 52 of file timer_client.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/substate_behaviors/timer/timer_client.h