sm_three_some::keyboard_client::ClKeyboard Class Reference
#include <cl_keyboard.h>
Public Member Functions
ClKeyboard ()
virtual ~ClKeyboard ()
virtual void initialize () override
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
void onKeyboardMessage (const std_msgs::UInt16 &unicode_keychar)
template<typename TEv >
void postKeyEvent ()
Public Attributes
boost::signals2::signal< void(char keypress)> OnKeyPress
boost::signals2::scoped_connection c_
std::function< void(std_msgs::UInt16)> postEventKeyPress
Private Attributes
bool initialized_
Additional Inherited Members
Detailed Description
Definition at line 151 of file cl_keyboard.h.
Constructor & Destructor Documentation
sm_three_some::keyboard_client::ClKeyboard::ClKeyboard () [inline]
Definition at line 157 of file cl_keyboard.h.
        {
                initialized_ = false;
        }
virtual sm_three_some::keyboard_client::ClKeyboard::~ClKeyboard () [inline], [virtual]
Definition at line 162 of file cl_keyboard.h.
        {
        }
Member Function Documentation
template<typename TObjectTag , typename TDerived > void sm_three_some::keyboard_client::ClKeyboard::configureEventSourceTypes () [inline]
Definition at line 183 of file cl_keyboard.h.
        {
                postEventKeyPress = [=](auto unicode_keychar) {
                        char character = (char)unicode_keychar.data;
                        ROS_WARN("detected keyboard: %c", character);
                        if (character == 'a')
                                this->postKeyEvent<EvKeyPressA<ClKeyboard, TObjectTag>>();
                        else if (character == 'b')
                                this->postKeyEvent<EvKeyPressB<ClKeyboard, TObjectTag>>();
                        else if (character == 'c')
                                this->postKeyEvent<EvKeyPressC<ClKeyboard, TObjectTag>>();
                        else if (character == 'd')
                                this->postKeyEvent<EvKeyPressD<ClKeyboard, TObjectTag>>();
                        else if (character == 'e')
                                this->postKeyEvent<EvKeyPressE<ClKeyboard, TObjectTag>>();
                        else if (character == 'f')
                                this->postKeyEvent<EvKeyPressF<ClKeyboard, TObjectTag>>();
                        else if (character == 'g')
                                this->postKeyEvent<EvKeyPressG<ClKeyboard, TObjectTag>>();
                        else if (character == 'h')
                                this->postKeyEvent<EvKeyPressH<ClKeyboard, TObjectTag>>();
                        else if (character == 'y')
                                this->postKeyEvent<EvKeyPressI<ClKeyboard, TObjectTag>>();
                        else if (character == 'j')
                                this->postKeyEvent<EvKeyPressJ<ClKeyboard, TObjectTag>>();
                        else if (character == 'k')
                                this->postKeyEvent<EvKeyPressK<ClKeyboard, TObjectTag>>();
                        else if (character == 'l')
                                this->postKeyEvent<EvKeyPressL<ClKeyboard, TObjectTag>>();
                        else if (character == 'm')
                                this->postKeyEvent<EvKeyPressM<ClKeyboard, TObjectTag>>();
                        else if (character == 'n')
                                this->postKeyEvent<EvKeyPressN<ClKeyboard, TObjectTag>>();
                        else if (character == 'o')
                                this->postKeyEvent<EvKeyPressO<ClKeyboard, TObjectTag>>();
                        else if (character == 'p')
                                this->postKeyEvent<EvKeyPressP<ClKeyboard, TObjectTag>>();
                        else if (character == 'q')
                                this->postKeyEvent<EvKeyPressQ<ClKeyboard, TObjectTag>>();
                        else if (character == 'r')
                                this->postKeyEvent<EvKeyPressR<ClKeyboard, TObjectTag>>();
                        else if (character == 's')
                                this->postKeyEvent<EvKeyPressS<ClKeyboard, TObjectTag>>();
                        else if (character == 't')
                                this->postKeyEvent<EvKeyPressT<ClKeyboard, TObjectTag>>();
                        else if (character == 'u')
                                this->postKeyEvent<EvKeyPressU<ClKeyboard, TObjectTag>>();
                        else if (character == 'v')
                                this->postKeyEvent<EvKeyPressV<ClKeyboard, TObjectTag>>();
                        else if (character == 'w')
                                this->postKeyEvent<EvKeyPressW<ClKeyboard, TObjectTag>>();
                        else if (character == 'x')
                                this->postKeyEvent<EvKeyPressX<ClKeyboard, TObjectTag>>();
                        else if (character == 'y')
                                this->postKeyEvent<EvKeyPressY<ClKeyboard, TObjectTag>>();
                        else if (character == 'z')
                                this->postKeyEvent<EvKeyPressZ<ClKeyboard, TObjectTag>>();
                        OnKeyPress(character); /* */
                };
        }
virtual void sm_three_some::keyboard_client::ClKeyboard::initialize () [inline], [override], [virtual]
Reimplemented from smacc::SmaccSubscriberClient< std_msgs::UInt16 >.
Definition at line 166 of file cl_keyboard.h.
References smacc::SmaccSubscriberClient< std_msgs::UInt16 >::initialize(), and keyboard_node::msg.
        {
                SmaccSubscriberClient<std_msgs::UInt16>::initialize
      ();
                if (!this->initialized_)
                {
                        c_ = this->onMessageReceived.connect([this](auto
      msg) {
                                this->onKeyboardMessage(msg);
                                this->initialized_ = true;
                        });
                }
        }
void sm_three_some::keyboard_client::ClKeyboard::onKeyboardMessage (const std_msgs::UInt16 & unicode_keychar) [inline]
Definition at line 245 of file cl_keyboard.h.
        {
                postEventKeyPress(unicode_keychar);
        }
template<typename TEv > void sm_three_some::keyboard_client::ClKeyboard::postKeyEvent () [inline]
Definition at line 251 of file cl_keyboard.h.
References smacc::demangleSymbol().
        {
                ROS_WARN("ClKeyboard ev: %s", smacc::demangleSymbol(typeid(TEv).name()
      ).c_str());
                auto event = new TEv();
                this->postEvent(event);
        }
Member Data Documentation
boost::signals2::scoped_connection sm_three_some::keyboard_client::ClKeyboard::c_
Definition at line 155 of file cl_keyboard.h.
bool sm_three_some::keyboard_client::ClKeyboard::initialized_ [private]
Definition at line 259 of file cl_keyboard.h.
boost::signals2::signal<void(char keypress)> sm_three_some::keyboard_client::ClKeyboard::OnKeyPress
Definition at line 154 of file cl_keyboard.h.
Referenced by sm_three_some::keyboard_client::CbDefaultKeyboardBehavior::onEntry().
std::function<void(std_msgs::UInt16)> sm_three_some::keyboard_client::ClKeyboard::postEventKeyPress
Definition at line 180 of file cl_keyboard.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_three_some/include/sm_three_some/clients/keyboard_client/cl_keyboard.h