NavigationOrthogonal Class Reference
#include <navigation_orthogonal.h>
Public Member Functions
virtual void onInitialize () override
virtual void onInitialize () override
Detailed Description
Definition at line 5 of file navigation_orthogonal.h.
Member Function Documentation
virtual void NavigationOrthogonal::onInitialize () [inline], [override], [virtual]
Reimplemented from smacc::Orthogonal.
Definition at line 10 of file navigation_orthogonal.h.
References smacc_odom_tracker::OdomTracker::initialize(), and smacc::Orthogonal::requiresComponent().
    {
        auto* client = this->createClient<smacc::SmaccMoveBaseActionClient>();
        client->name_ = "move_base";
        client->initialize();
        smacc_odom_tracker::OdomTracker* odomtracker;
        this->requiresComponent(odomtracker);
        odomtracker->initialize("/");
    }
virtual void NavigationOrthogonal::onInitialize () [inline], [override], [virtual]
Reimplemented from smacc::Orthogonal.
Definition at line 10 of file navigation_orthogonal.h.
References smacc_odom_tracker::OdomTracker::initialize(), and smacc::Orthogonal::requiresComponent().
    {
        auto* client = this->createClient<smacc::SmaccMoveBaseActionClient>();
        client->name_ = "move_base";
        client->initialize();
        smacc_odom_tracker::OdomTracker* odomtracker;
        this->requiresComponent(odomtracker);
        odomtracker->initialize("move_base");
    }
The documentation for this class was generated from the following file:
smacc_client_library/smacc_sensors/examples/timer_substate_example/include/orthogonals/navigation_orthogonal.h