move_base_z_client::CbNavigateForward Class Reference
#include <cb_navigate_forward.h>
Public Member Functions
CbNavigateForward (float forwardDistance)
CbNavigateForward ()
virtual void onEntry () override
virtual void onExit () override
Public Attributes
boost::optional< float > forwardDistance
boost::optional< float > forwardSpeed
tf::TransformListener listener
ClMoveBaseZ * moveBaseClient_
OdomTracker * odomTracker_
Detailed Description
Definition at line 14 of file cb_navigate_forward.h.
Constructor & Destructor Documentation
move_base_z_client::CbNavigateForward::CbNavigateForward (float forwardDistance) [inline]
Definition at line 28 of file cb_navigate_forward.h.
References forwardDistance.
    {
        this->forwardDistance = forwardDistance;
    }
move_base_z_client::CbNavigateForward::CbNavigateForward () [inline]
Definition at line 33 of file cb_navigate_forward.h.
    {
    }
Member Function Documentation
virtual void move_base_z_client::CbNavigateForward::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 37 of file cb_navigate_forward.h.
References smacc::SmaccClientBehavior::currentState, forwardDistance, smacc::ISmaccClient::getComponent(), smacc::ISmaccState::param(), move_base_z_client::ClMoveBaseZ::plannerSwitcher_, smacc::SmaccClientBehavior::requiresClient(), and smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal().
    {
        // straight motion distance
        double dist;
        if (!forwardDistance)
        {
            this->currentState->param("straight_motion_distance", dist, 3.5);
        }
        else
        {
            dist = *forwardDistance;
        }
        ROS_INFO_STREAM("Straight motion distance: " << dist);
        this->requiresClient(moveBaseClient_);
        odomTracker_ = moveBaseClient_->getComponent<OdomTracker>();
        //this should work better with a coroutine and await
        ros::Rate rate(10.0);
        tf::StampedTransform currentPose;
        while (ros::ok())
        {
            try
            {
                listener.lookupTransform("/odom", "/base_link",
                                         ros::Time(0), currentPose);
                break;
            }
            catch (tf::TransformException ex)
            {
                ROS_ERROR("%s", ex.what());
                ros::Duration(1.0).sleep();
            }
        }
        tf::Transform forwardDeltaTransform;
        forwardDeltaTransform.setIdentity();
        forwardDeltaTransform.setOrigin(tf::Vector3(dist, 0, 0));
        tf::Transform targetPose = currentPose * forwardDeltaTransform;
        ClMoveBaseZ::Goal goal;
        goal.target_pose.header.frame_id = "/odom";
        goal.target_pose.header.stamp = ros::Time::now();
        tf::poseTFToMsg(targetPose, goal.target_pose.pose);
        ROS_INFO_STREAM("TARGET POSE FORWARD: " << goal.target_pose.pose);
        ros::Duration(10).sleep();
        odomTracker_->clearPath();
        geometry_msgs::PoseStamped currentPoseMsg;
        currentPoseMsg.header.frame_id = "/odom";
        currentPoseMsg.header.stamp = ros::Time::now();
        tf::poseTFToMsg(currentPose, currentPoseMsg.pose);
        odomTracker_->setStartPoint(currentPoseMsg);
        odomTracker_->setWorkingMode(WorkingMode::RECORD_PATH_FORWARD);
        moveBaseClient_->plannerSwitcher_->setForwardPlanner();
        moveBaseClient_->sendGoal(goal);
    }
virtual void move_base_z_client::CbNavigateForward::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 104 of file cb_navigate_forward.h.
    {
        this->odomTracker_->setWorkingMode(WorkingMode::IDLE);
    }
Member Data Documentation
boost::optional<float> move_base_z_client::CbNavigateForward::forwardDistance
Definition at line 17 of file cb_navigate_forward.h.
Referenced by CbNavigateForward(), and onEntry().
boost::optional<float> move_base_z_client::CbNavigateForward::forwardSpeed
Definition at line 20 of file cb_navigate_forward.h.
tf::TransformListener move_base_z_client::CbNavigateForward::listener
Definition at line 22 of file cb_navigate_forward.h.
ClMoveBaseZ* move_base_z_client::CbNavigateForward::moveBaseClient_
Definition at line 24 of file cb_navigate_forward.h.
OdomTracker* move_base_z_client::CbNavigateForward::odomTracker_
Definition at line 26 of file cb_navigate_forward.h.
The documentation for this class was generated from the following file:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_navigate_forward.h