sm_dance_bot::CbNavigateBackwards Class Reference
#include <cb_navigate_backward.h>
Public Member Functions
CbNavigateBackwards (float backwardDistance)
CbNavigateBackwards ()
virtual void onEntry () override
virtual void onExit () override
CbNavigateBackwards (float backwardDistance)
CbNavigateBackwards ()
virtual void onEntry () override
virtual void onExit () override
Public Attributes
boost::optional< float > backwardDistance
boost::optional< float > backwardSpeed
tf::TransformListener listener
smacc::ClMoveBaseZ * moveBaseClient_
odom_tracker::OdomTracker * odomTracker_
Detailed Description
Definition at line 12 of file cb_navigate_backward.h.
Constructor & Destructor Documentation
sm_dance_bot::CbNavigateBackwards::CbNavigateBackwards (float backwardDistance) [inline]
Definition at line 24 of file cb_navigate_backward.h.
References backwardDistance.
    {
        if (backwardDistance < 0)
        {
            ROS_ERROR("cb backward: distance must be greater or equal than 0");
            this->backwardDistance = 0;
        }
        this->backwardDistance = backwardDistance;
    }
sm_dance_bot::CbNavigateBackwards::CbNavigateBackwards () [inline]
Definition at line 34 of file cb_navigate_backward.h.
    {
    }
sm_dance_bot::CbNavigateBackwards::CbNavigateBackwards (float backwardDistance) [inline]
Definition at line 25 of file cb_navigate_backward.h.
References backwardDistance.
    {
        if (backwardDistance < 0)
        {
            ROS_ERROR("cb backward: distance must be greater or equal than 0");
            this->backwardDistance = 0;
        }
        this->backwardDistance = backwardDistance;
    }
sm_dance_bot::CbNavigateBackwards::CbNavigateBackwards () [inline]
Definition at line 35 of file cb_navigate_backward.h.
    {
    }
Member Function Documentation
virtual void sm_dance_bot::CbNavigateBackwards::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 38 of file cb_navigate_backward.h.
References backwardDistance, odom_tracker::OdomTracker::clearPath(), smacc::SmaccClientBehavior::currentState, odomTracker_, smacc::ISmaccState::param(), smacc::ClMoveBaseZ::plannerSwitcher_, odom_tracker::RECORD_PATH_FORWARD, smacc::SmaccClientBehavior::requiresClient(), smacc::SmaccActionClientBase< ActionType >::sendGoal(), odom_tracker::OdomTracker::setStartPoint(), and odom_tracker::OdomTracker::setWorkingMode().
    {
        // straight motion distance
        double dist;
        if (!backwardDistance)
        {
            this->currentState->param("straight_motion_distance", dist, 3.5);
        }
        else
        {
            dist = *backwardDistance;
        }
        ROS_INFO_STREAM("Straight motion distance: " << dist);
        this->requiresClient(moveBaseClient_);
        auto odomTracker_ = this->getComponent<odom_tracker::OdomTracker>();
        
        //this should work better with a coroutine and await
        ros::Rate rate(10.0);
        tf::StampedTransform currentPose;
        while (ros::ok())
        {
            try
            {
                listener.lookupTransform("/odom", "/base_link",
                                         ros::Time(0), currentPose);
                break;
            }
            catch (tf::TransformException ex)
            {
                ROS_ERROR("%s", ex.what());
                ros::Duration(1.0).sleep();
            }
        }
        tf::Transform forwardDeltaTransform;
        forwardDeltaTransform.setIdentity();
        forwardDeltaTransform.setOrigin(tf::Vector3(-dist, 0, 0));
        tf::Transform targetPose = currentPose * forwardDeltaTransform;
        smacc::ClMoveBaseZ::Goal goal;
        goal.target_pose.header.frame_id = "/odom";
        goal.target_pose.header.stamp = ros::Time::now();
        tf::poseTFToMsg(targetPose, goal.target_pose.pose);
        ROS_INFO_STREAM("TARGET POSE FORWARD: " << goal.target_pose.pose);
        ros::Duration(10).sleep();
        this->odomTracker_->clearPath();
        geometry_msgs::PoseStamped currentPoseMsg;
        currentPoseMsg.header.frame_id = "/odom";
        currentPoseMsg.header.stamp = ros::Time::now();
        tf::poseTFToMsg(currentPose, currentPoseMsg.pose);
        this->odomTracker_->setStartPoint(currentPoseMsg);
        this->odomTracker_->setWorkingMode(
      odom_tracker::WorkingMode::RECORD_PATH_FORWARD);
        moveBaseClient_->plannerSwitcher_->setBackwardPlanner();
        moveBaseClient_->sendGoal(goal);
    }
virtual void sm_dance_bot::CbNavigateBackwards::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 39 of file cb_navigate_backward.h.
References backwardDistance, odom_tracker::OdomTracker::clearPath(), smacc::SmaccClientBehavior::currentState, smacc::ISmaccClient::getComponent(), smacc::ISmaccState::param(), smacc::ClMoveBaseZ::plannerSwitcher_, odom_tracker::RECORD_PATH_FORWARD, smacc::SmaccClientBehavior::requiresClient(), smacc::SmaccActionClientBase< ActionType >::sendGoal(), odom_tracker::OdomTracker::setStartPoint(), and odom_tracker::OdomTracker::setWorkingMode().
    {
        // straight motion distance
        double dist;
        if (!backwardDistance)
        {
            this->currentState->param("straight_motion_distance", dist, 3.5);
        }
        else
        {
            dist = *backwardDistance;
        }
        ROS_INFO_STREAM("Straight motion distance: " << dist);
        this->requiresClient(moveBaseClient_);
        //this should work better with a coroutine and await
        ros::Rate rate(10.0);
        tf::StampedTransform currentPose;
        while (ros::ok())
        {
            try
            {
                listener.lookupTransform("/odom", "/base_link",
                                         ros::Time(0), currentPose);
                break;
            }
            catch (tf::TransformException ex)
            {
                ROS_ERROR("%s", ex.what());
                ros::Duration(1.0).sleep();
            }
        }
        tf::Transform forwardDeltaTransform;
        forwardDeltaTransform.setIdentity();
        forwardDeltaTransform.setOrigin(tf::Vector3(-dist, 0, 0));
        tf::Transform targetPose = currentPose * forwardDeltaTransform;
        smacc::ClMoveBaseZ::Goal goal;
        goal.target_pose.header.frame_id = "/odom";
        goal.target_pose.header.stamp = ros::Time::now();
        tf::poseTFToMsg(targetPose, goal.target_pose.pose);
        ROS_INFO_STREAM("TARGET POSE FORWARD: " << goal.target_pose.pose);
        ros::Duration(10).sleep();
        geometry_msgs::PoseStamped currentPoseMsg;
        currentPoseMsg.header.frame_id = "/odom";
        currentPoseMsg.header.stamp = ros::Time::now();
        tf::poseTFToMsg(currentPose, currentPoseMsg.pose);
        odomTracker_ = moveBaseClient_->getComponent<
      odom_tracker::OdomTracker>();
        this->odomTracker_->clearPath();
        this->odomTracker_->setStartPoint(currentPoseMsg);
        this->odomTracker_->setWorkingMode(
      odom_tracker::WorkingMode::RECORD_PATH_FORWARD);
        moveBaseClient_->plannerSwitcher_->setBackwardPlanner();
        moveBaseClient_->sendGoal(goal);
    }
virtual void sm_dance_bot::CbNavigateBackwards::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 104 of file cb_navigate_backward.h.
References odom_tracker::IDLE, odomTracker_, and odom_tracker::OdomTracker::setWorkingMode().
    {
        this->odomTracker_->setWorkingMode(
      odom_tracker::WorkingMode::IDLE);
    }
virtual void sm_dance_bot::CbNavigateBackwards::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 106 of file cb_navigate_backward.h.
References odom_tracker::IDLE, and odom_tracker::OdomTracker::setWorkingMode().
    {
        this->odomTracker_->setWorkingMode(
      odom_tracker::WorkingMode::IDLE);
    }
Member Data Documentation
boost::optional< float > sm_dance_bot::CbNavigateBackwards::backwardDistance
Definition at line 15 of file cb_navigate_backward.h.
Referenced by CbNavigateBackwards(), and onEntry().
boost::optional< float > sm_dance_bot::CbNavigateBackwards::backwardSpeed
Definition at line 18 of file cb_navigate_backward.h.
tf::TransformListener sm_dance_bot::CbNavigateBackwards::listener
Definition at line 20 of file cb_navigate_backward.h.
smacc::ClMoveBaseZ * sm_dance_bot::CbNavigateBackwards::moveBaseClient_
Definition at line 22 of file cb_navigate_backward.h.
odom_tracker::OdomTracker* sm_dance_bot::CbNavigateBackwards::odomTracker_
Definition at line 23 of file cb_navigate_backward.h.
Referenced by onEntry(), and onExit().
The documentation for this class was generated from the following file:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_navigate_backward.h