ToolActionServer Class Reference
Public Member Functions
ToolActionServer ()
void publishFeedback ()
void execute (const smacc_action_client_generic::ToolControlGoalConstPtr &goal)
void run ()
void publishStateMarker ()
Public Attributes
std::shared_ptr< Server > as_
ros::Publisher stateMarkerPublisher_
smacc_action_client_generic::ToolControlGoal cmd
uint8_t currentState_
Detailed Description
Definition at line 22 of file tool_action_server_node.cpp.
Constructor & Destructor Documentation
ToolActionServer::ToolActionServer () [inline]
constructor()
Definition at line 38 of file tool_action_server_node.cpp.
  {
    currentState_ = smacc_action_client_generic::ToolControlResult::STATE_UNKNOWN;
  }
Member Function Documentation
void ToolActionServer::execute (const smacc_action_client_generic::ToolControlGoalConstPtr & goal) [inline]
execute()
Definition at line 60 of file tool_action_server_node.cpp.
References publishFeedback(), and publishStateMarker().
Referenced by run().
{
  ROS_INFO_STREAM("Tool action server request: "<< *goal);
  cmd = *goal;
  if(goal->command == smacc_action_client_generic::ToolControlGoal::CMD_START)
  {
    currentState_ = smacc_action_client_generic::ToolControlResult::STATE_RUNNING;
  }
  else if (goal->command == smacc_action_client_generic::ToolControlGoal::CMD_STOP)
  {
    currentState_ = smacc_action_client_generic::ToolControlResult::STATE_IDLE;
  }
  // 10Hz internal loop
  ros::Rate rate(20);
  while(ros::ok())
  {
    if(as_->isPreemptRequested())
    {
       // a new request is being executed, we will stop this one
       ROS_WARN("ToolActionServer request preempted. Forgetting older request.");
       as_->setPreempted();
       return;
    }
    
    publishFeedback();
    publishStateMarker();
    rate.sleep();
  }
   // never reach succeded because were are interested in keeping the feedback alive
   as_->setSucceeded();
}
void ToolActionServer::publishFeedback () [inline]
publishFeedback()
Definition at line 48 of file tool_action_server_node.cpp.
Referenced by execute().
{
    smacc_action_client_generic::ToolControlFeedback feedback_msg;
    
    as_->publishFeedback(feedback_msg);
}
void ToolActionServer::publishStateMarker () [inline]
publishStateMarker()
Definition at line 121 of file tool_action_server_node.cpp.
Referenced by execute().
{
    visualization_msgs::Marker marker;
    marker.header.frame_id = "base_link";
    marker.header.stamp = ros::Time::now ();
    marker.ns = "tool_namespace";
    marker.id = 0;
    marker.type = visualization_msgs::Marker::SPHERE;
    marker.action = visualization_msgs::Marker::ADD;
    
    marker.scale.x = 0.2;
    marker.scale.y = 0.2;
    marker.scale.z = 0.2;
    marker.color.a = 1;
    if(currentState_ == smacc_action_client_generic::ToolControlResult::STATE_RUNNING)
    {
      // show green ball
      marker.color.r = 0;
      marker.color.g = 1;
      marker.color.b = 0;
    }
    else if (currentState_ == smacc_action_client_generic::ToolControlResult::STATE_IDLE)
    {
      // show gray ball
      marker.color.r = 0.7;
      marker.color.g = 0.7;
      marker.color.b = 0.7;
    }
    else
    {
      // show black ball
      marker.color.r = 0;
      marker.color.g = 0;
      marker.color.b = 0;
    }
    marker.pose.orientation.w=1;
    marker.pose.position.x=0;
    marker.pose.position.y=0;
    marker.pose.position.z=1;
    visualization_msgs::MarkerArray ma;
    ma.markers.push_back(marker);
    stateMarkerPublisher_.publish(ma);
}
void ToolActionServer::run () [inline]
run()
Definition at line 101 of file tool_action_server_node.cpp.
References execute().
Referenced by main().
{
  ros::NodeHandle n;
  ROS_INFO("Creating tool action server");
  as_ = std::make_shared<Server>(n, "tool_action_server", boost::bind(&
      ToolActionServer::execute, this, _1), false);
  ROS_INFO("Starting Tool Action Server");
  stateMarkerPublisher_ = n.advertise<visualization_msgs::MarkerArray>("tool_markers",
       1);
  as_->start();
  ros::spin();
}
Member Data Documentation
std::shared_ptr<Server> ToolActionServer::as_
Definition at line 25 of file tool_action_server_node.cpp.
smacc_action_client_generic::ToolControlGoal ToolActionServer::cmd
Definition at line 29 of file tool_action_server_node.cpp.
uint8_t ToolActionServer::currentState_
Definition at line 31 of file tool_action_server_node.cpp.
ros::Publisher ToolActionServer::stateMarkerPublisher_
Definition at line 27 of file tool_action_server_node.cpp.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/test/tool_action_server/src/tool_action_server_node.cpp