sm_three_some::KeyboardClient Class Reference
#include <keyboard_client.h>
Public Member Functions
KeyboardClient ()
virtual ~KeyboardClient ()
virtual void initialize () override
template<typename TDerived , typename TObjectTag >
void assignToOrthogonal ()
void onKeyboardMessage (const std_msgs::UInt16 &unicode_keychar)
template<typename TEv >
void postKeyEvent ()
Public Attributes
boost::signals2::signal< void(char keypress)> OnKeyPress
boost::signals2::scoped_connection c_
std::function< void(std_msgs::UInt16)> postEventKeyPress
Private Attributes
bool initialized_
Additional Inherited Members
Detailed Description
Definition at line 149 of file keyboard_client.h.
Constructor & Destructor Documentation
sm_three_some::KeyboardClient::KeyboardClient () [inline]
Definition at line 155 of file keyboard_client.h.
        {
                initialized_ = false;
        }
virtual sm_three_some::KeyboardClient::~KeyboardClient () [inline], [virtual]
Definition at line 160 of file keyboard_client.h.
        {
        }
Member Function Documentation
template<typename TDerived , typename TObjectTag > void sm_three_some::KeyboardClient::assignToOrthogonal () [inline]
Definition at line 181 of file keyboard_client.h.
        {
                postEventKeyPress = [=](auto unicode_keychar) {
                        char character = (char)unicode_keychar.data;
                        ROS_WARN("detected keyboard: %c", character);
                        if (character == 'a')
                                this->postKeyEvent<EvKeyPressA<KeyboardClient, TObjectTag>>();
                        else if (character == 'b')
                                this->postKeyEvent<EvKeyPressB<KeyboardClient, TObjectTag>>();
                        else if (character == 'c')
                                this->postKeyEvent<EvKeyPressC<KeyboardClient, TObjectTag>>();
                        else if (character == 'd')
                                this->postKeyEvent<EvKeyPressD<KeyboardClient, TObjectTag>>();
                        else if (character == 'e')
                                this->postKeyEvent<EvKeyPressE<KeyboardClient, TObjectTag>>();
                        else if (character == 'f')
                                this->postKeyEvent<EvKeyPressF<KeyboardClient, TObjectTag>>();
                        else if (character == 'g')
                                this->postKeyEvent<EvKeyPressG<KeyboardClient, TObjectTag>>();
                        else if (character == 'h')
                                this->postKeyEvent<EvKeyPressH<KeyboardClient, TObjectTag>>();
                        else if (character == 'y')
                                this->postKeyEvent<EvKeyPressI<KeyboardClient, TObjectTag>>();
                        else if (character == 'j')
                                this->postKeyEvent<EvKeyPressJ<KeyboardClient, TObjectTag>>();
                        else if (character == 'k')
                                this->postKeyEvent<EvKeyPressK<KeyboardClient, TObjectTag>>();
                        else if (character == 'l')
                                this->postKeyEvent<EvKeyPressL<KeyboardClient, TObjectTag>>();
                        else if (character == 'm')
                                this->postKeyEvent<EvKeyPressM<KeyboardClient, TObjectTag>>();
                        else if (character == 'n')
                                this->postKeyEvent<EvKeyPressN<KeyboardClient, TObjectTag>>();
                        else if (character == 'o')
                                this->postKeyEvent<EvKeyPressO<KeyboardClient, TObjectTag>>();
                        else if (character == 'p')
                                this->postKeyEvent<EvKeyPressP<KeyboardClient, TObjectTag>>();
                        else if (character == 'q')
                                this->postKeyEvent<EvKeyPressQ<KeyboardClient, TObjectTag>>();
                        else if (character == 'r')
                                this->postKeyEvent<EvKeyPressR<KeyboardClient, TObjectTag>>();
                        else if (character == 's')
                                this->postKeyEvent<EvKeyPressS<KeyboardClient, TObjectTag>>();
                        else if (character == 't')
                                this->postKeyEvent<EvKeyPressT<KeyboardClient, TObjectTag>>();
                        else if (character == 'u')
                                this->postKeyEvent<EvKeyPressU<KeyboardClient, TObjectTag>>();
                        else if (character == 'v')
                                this->postKeyEvent<EvKeyPressV<KeyboardClient, TObjectTag>>();
                        else if (character == 'w')
                                this->postKeyEvent<EvKeyPressW<KeyboardClient, TObjectTag>>();
                        else if (character == 'x')
                                this->postKeyEvent<EvKeyPressX<KeyboardClient, TObjectTag>>();
                        else if (character == 'y')
                                this->postKeyEvent<EvKeyPressY<KeyboardClient, TObjectTag>>();
                        else if (character == 'z')
                                this->postKeyEvent<EvKeyPressZ<KeyboardClient, TObjectTag>>();
                        OnKeyPress(character); /* */
                };
        }
virtual void sm_three_some::KeyboardClient::initialize () [inline], [override], [virtual]
Reimplemented from smacc::SmaccSubscriberClient< std_msgs::UInt16 >.
Definition at line 164 of file keyboard_client.h.
References smacc::SmaccSubscriberClient< std_msgs::UInt16 >::initialize(), and keyboard_node::msg.
        {
                SmaccSubscriberClient<std_msgs::UInt16>::initialize
      ();
                if (!this->initialized_)
                {
                        c_ = this->onMessageReceived.connect([this](auto
      msg) {
                                this->onKeyboardMessage(msg);
                                this->initialized_ = true;
                        });
                }
        }
void sm_three_some::KeyboardClient::onKeyboardMessage (const std_msgs::UInt16 & unicode_keychar) [inline]
Definition at line 243 of file keyboard_client.h.
        {
                postEventKeyPress(unicode_keychar);
        }
template<typename TEv > void sm_three_some::KeyboardClient::postKeyEvent () [inline]
Definition at line 249 of file keyboard_client.h.
References smacc::demangleSymbol().
        {
                ROS_WARN("KeyboardClient ev: %s", smacc::demangleSymbol(typeid(TEv).
      name()).c_str());
                auto event = new TEv();
                this->postEvent(event);
        }
Member Data Documentation
boost::signals2::scoped_connection sm_three_some::KeyboardClient::c_
Definition at line 153 of file keyboard_client.h.
bool sm_three_some::KeyboardClient::initialized_ [private]
Definition at line 257 of file keyboard_client.h.
boost::signals2::signal<void(char keypress)> sm_three_some::KeyboardClient::OnKeyPress
Definition at line 152 of file keyboard_client.h.
Referenced by sm_three_some::CbKeyboard::onEntry().
std::function<void(std_msgs::UInt16)> sm_three_some::KeyboardClient::postEventKeyPress
Definition at line 178 of file keyboard_client.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_three_some/include/sm_three_some/clients/keyboard_client.h