ros_timer_client::CbTimerSingleCountdown Class Reference
#include <cb_timer_single_countdown.h>
Public Member Functions
CbTimerSingleCountdown (unsigned long triggerTickCount)
virtual void onEntry () override
virtual void onExit () override
template<typename TObjectTag , typename TDerived >
void configureEventSourceTypes ()
template<typename T >
boost::signals2::connection onTimerTick (void(T::*callback)(), T *object)
Private Member Functions
void onClientTimerTickCallback ()
Private Attributes
unsigned long tickCounter_
unsigned long tickTriggerCount_
ClRosTimer * timerClient_
std::function< void()> postCountDownEvent_
smacc::SmaccSignal< void()> onTimerTick_
Additional Inherited Members
Detailed Description
Definition at line 8 of file cb_timer_single_countdown.h.
Constructor & Destructor Documentation
ros_timer_client::CbTimerSingleCountdown::CbTimerSingleCountdown (unsigned long triggerTickCount)
Definition at line 6 of file cb_timer_single_countdown.cpp.
    : tickTriggerCount_(triggerTickCount),
      tickCounter_(0)
{
}
Member Function Documentation
template<typename TObjectTag , typename TDerived > void ros_timer_client::CbTimerSingleCountdown::configureEventSourceTypes () [inline]
Definition at line 17 of file cb_timer_single_countdown.h.
References postCountDownEvent_.
    {
        this->postCountDownEvent_ = [=]() {
            this->template postEvent<EvTimer<TDerived, TObjectTag>>();
        };
    }
void ros_timer_client::CbTimerSingleCountdown::onClientTimerTickCallback () [private]
Definition at line 12 of file cb_timer_single_countdown.cpp.
References onTimerTick_, postCountDownEvent_, tickCounter_, and tickTriggerCount_.
Referenced by onEntry().
{
    tickCounter_++;
    if (tickCounter_ % tickTriggerCount_ == 0)
    {
        onTimerTick_();
        postCountDownEvent_();
    }
}
void ros_timer_client::CbTimerSingleCountdown::onEntry () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 23 of file cb_timer_single_countdown.cpp.
References onClientTimerTickCallback(), ros_timer_client::ClRosTimer::onTimerTick(), smacc::SmaccClientBehavior::requiresClient(), and timerClient_.
{
    this->requiresClient(timerClient_);
    timerClient_->onTimerTick(&
      CbTimerSingleCountdown::onClientTimerTickCallback, this);
}
void ros_timer_client::CbTimerSingleCountdown::onExit () [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 29 of file cb_timer_single_countdown.cpp.
{
}
template<typename T > boost::signals2::connection ros_timer_client::CbTimerSingleCountdown::onTimerTick (void(T::*)() callback, T * object) [inline]
Definition at line 25 of file cb_timer_single_countdown.h.
References smacc::ISmaccStateMachine::createSignalConnection(), onTimerTick_, and smacc::SmaccClientBehavior::stateMachine_.
    {
        return stateMachine_->createSignalConnection(
      onTimerTick_, callback, object);
    }
Member Data Documentation
smacc::SmaccSignal<void()> ros_timer_client::CbTimerSingleCountdown::onTimerTick_ [private]
Definition at line 36 of file cb_timer_single_countdown.h.
Referenced by onClientTimerTickCallback(), and onTimerTick().
std::function<void()> ros_timer_client::CbTimerSingleCountdown::postCountDownEvent_ [private]
Definition at line 35 of file cb_timer_single_countdown.h.
Referenced by configureEventSourceTypes(), and onClientTimerTickCallback().
unsigned long ros_timer_client::CbTimerSingleCountdown::tickCounter_ [private]
Definition at line 31 of file cb_timer_single_countdown.h.
Referenced by onClientTimerTickCallback().
unsigned long ros_timer_client::CbTimerSingleCountdown::tickTriggerCount_ [private]
Definition at line 32 of file cb_timer_single_countdown.h.
Referenced by onClientTimerTickCallback().
ClRosTimer* ros_timer_client::CbTimerSingleCountdown::timerClient_ [private]
Definition at line 34 of file cb_timer_single_countdown.h.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc_client_library/ros_timer_client/include/ros_timer_client/client_behaviors/cb_timer_single_countdown.h
smacc_client_library/ros_timer_client/src/ros_timer_client/cb_timer_single_countdown.cpp