ros_timer_client::SmaccTimerClient Class Reference
#include <timer_client.h>
Public Member Functions
SmaccTimerClient (ros::Duration duration, bool oneshot=false)
virtual ~SmaccTimerClient ()
virtual void initialize ()
Public Attributes
boost::signals2::signal< void(EvTimer< SmaccTimerClient > *)> onTimerTick
boost::signals2::scoped_connection c_
Protected Member Functions
void timerCallback (const ros::TimerEvent &timedata)
Protected Attributes
ros::NodeHandle nh_
ros::Timer timer
ros::Duration duration
bool oneshot
Detailed Description
Definition at line 24 of file timer_client.h.
Constructor & Destructor Documentation
ros_timer_client::SmaccTimerClient::SmaccTimerClient (ros::Duration duration, bool oneshot = false)
Definition at line 6 of file timer_client.cpp.
References duration, and oneshot.
{
    this->duration = duration;
    this->oneshot = oneshot;
}
ros_timer_client::SmaccTimerClient::~SmaccTimerClient () [virtual]
Definition at line 12 of file timer_client.cpp.
References timer.
{
    timer.stop();
}
Member Function Documentation
void ros_timer_client::SmaccTimerClient::initialize () [virtual]
Reimplemented from smacc::ISmaccClient.
Definition at line 17 of file timer_client.cpp.
References duration, nh_, oneshot, timer, and timerCallback().
{
    timer = nh_.createTimer(duration, boost::bind(&
      SmaccTimerClient::timerCallback, this, _1),
      oneshot);
}
void ros_timer_client::SmaccTimerClient::timerCallback (const ros::TimerEvent & timedata) [protected]
Definition at line 22 of file timer_client.cpp.
References onTimerTick, and smacc::ISmaccClient::postEvent().
Referenced by initialize().
{
    //auto *event = new EvTimer<SmaccTimerClient>(this, timedata);
    auto *event = new EvTimer<SmaccTimerClient>();
    this->postEvent(event);
    onTimerTick(event);
}
Member Data Documentation
boost::signals2::scoped_connection ros_timer_client::SmaccTimerClient::c_
Definition at line 28 of file timer_client.h.
ros::Duration ros_timer_client::SmaccTimerClient::duration [protected]
Definition at line 40 of file timer_client.h.
Referenced by initialize(), and SmaccTimerClient().
ros::NodeHandle ros_timer_client::SmaccTimerClient::nh_ [protected]
Definition at line 37 of file timer_client.h.
Referenced by initialize().
bool ros_timer_client::SmaccTimerClient::oneshot [protected]
Definition at line 41 of file timer_client.h.
Referenced by initialize(), and SmaccTimerClient().
boost::signals2::signal<void(EvTimer<SmaccTimerClient> *)> ros_timer_client::SmaccTimerClient::onTimerTick
Definition at line 27 of file timer_client.h.
Referenced by ros_timer_client::CbTimer::onEntry(), and timerCallback().
ros::Timer ros_timer_client::SmaccTimerClient::timer [protected]
Definition at line 39 of file timer_client.h.
Referenced by initialize(), and ~SmaccTimerClient().
The documentation for this class was generated from the following files:
smacc_client_library/ros_timer_client/include/ros_timer_client/timer_client.h
smacc_client_library/ros_timer_client/src/ros_timer_client/timer_client.cpp