smacc::ISmaccActionClient Class Reference
#include <smacc_action_client.h>
Public Member Functions
ISmaccActionClient ()
virtual ~ISmaccActionClient ()
virtual void init (ros::NodeHandle &nh) override
virtual void init (ros::NodeHandle &nh, std::string) override
virtual SimpleClientGoalState getState ()=0
virtual bool hasFeedback ()=0
std::string getNamespace () const
Protected Member Functions
virtual void postEvent (SmaccScheduler *scheduler, SmaccScheduler::processor_handle processorHandle)=0
virtual void postFeedbackEvent (SmaccScheduler *scheduler, SmaccScheduler::processor_handle processorHandle)=0
Protected Attributes
std::string name_
Friends
class SignalDetector
Detailed Description
Definition at line 18 of file smacc_action_client.h.
Constructor & Destructor Documentation
smacc::ISmaccActionClient::ISmaccActionClient ()
Definition at line 13 of file smacc_action_client.cpp.
{
}
smacc::ISmaccActionClient::~ISmaccActionClient () [virtual]
Definition at line 17 of file smacc_action_client.cpp.
{
}
Member Function Documentation
std::string smacc::ISmaccActionClient::getNamespace () const [inline]
Definition at line 39 of file smacc_action_client.h.
Referenced by smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::sendGoal().
    {
        return name_;
    }
virtual SimpleClientGoalState smacc::ISmaccActionClient::getState () [pure virtual]
Implemented in smacc::SmaccActionClientBase< ActionType >, smacc::SmaccActionClientBase< smacc_action_client_generic::ToolControlAction >, and smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >.
Referenced by smacc::SignalDetector::finalizeRequest(), and smacc::IActionResult::getResult().
virtual bool smacc::ISmaccActionClient::hasFeedback () [pure virtual]
Implemented in smacc::SmaccActionClientBase< ActionType >, smacc::SmaccActionClientBase< smacc_action_client_generic::ToolControlAction >, and smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >.
void smacc::ISmaccActionClient::init (ros::NodeHandle & nh) [override], [virtual]
Reimplemented from smacc::ISmaccComponent.
Reimplemented in smacc::SmaccActionClientBase< ActionType >, smacc::SmaccActionClientBase< smacc_action_client_generic::ToolControlAction >, and smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >.
Definition at line 21 of file smacc_action_client.cpp.
Referenced by smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::init().
{
    
}
void smacc::ISmaccActionClient::init (ros::NodeHandle & nh, std::string value) [override], [virtual]
Reimplemented from smacc::ISmaccComponent.
Reimplemented in smacc::SmaccActionClientBase< ActionType >, smacc::SmaccActionClientBase< smacc_action_client_generic::ToolControlAction >, and smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >.
Definition at line 26 of file smacc_action_client.cpp.
{
    name_ = nh.getNamespace();
    ROS_DEBUG("Creating Action Client %s", name_.c_str());
}
virtual void smacc::ISmaccActionClient::postEvent (SmaccScheduler * scheduler, SmaccScheduler::processor_handle processorHandle) [protected], [pure virtual]
Implemented in smacc::SmaccActionClientBase< ActionType >, smacc::SmaccActionClientBase< smacc_action_client_generic::ToolControlAction >, and smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >.
Referenced by smacc::SignalDetector::finalizeRequest().
virtual void smacc::ISmaccActionClient::postFeedbackEvent (SmaccScheduler * scheduler, SmaccScheduler::processor_handle processorHandle) [protected], [pure virtual]
Implemented in smacc::SmaccActionClientBase< ActionType >, smacc::SmaccActionClientBase< smacc_action_client_generic::ToolControlAction >, and smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >.
Referenced by smacc::SignalDetector::notifyFeedback().
Friends And Related Function Documentation
friend class SignalDetector [friend]
Definition at line 53 of file smacc_action_client.h.
Member Data Documentation
std::string smacc::ISmaccActionClient::name_ [protected]
Definition at line 51 of file smacc_action_client.h.
Referenced by smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::init(), and smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::sendGoal().
The documentation for this class was generated from the following files:
smacc/include/smacc/interface_components/smacc_action_client.h
smacc/src/smacc/smacc_action_client.cpp