NavigateGlobalPosition Class Reference
#include <navigate_global_position.h>
Public Member Functions
NavigateGlobalPosition ()
NavigateGlobalPosition (float x, float y)
virtual void onEntry ()
void goToRadialStart ()
void readStartPoseFromParameterServer (smacc::SmaccMoveBaseActionClient::Goal &goal)
virtual bool onExit ()
Public Attributes
boost::optional< geometry_msgs::Point > initialPoint
Private Attributes
smacc::SmaccMoveBaseActionClient * moveBaseClient_
smacc_odom_tracker::OdomTracker * odomTracker_
smacc_planner_switcher::PlannerSwitcher * plannerSwitcher_
Detailed Description
Definition at line 10 of file navigate_global_position.h.
Constructor & Destructor Documentation
NavigateGlobalPosition::NavigateGlobalPosition () [inline]
Definition at line 16 of file navigate_global_position.h.
  {
  }
NavigateGlobalPosition::NavigateGlobalPosition (float x, float y) [inline]
Definition at line 21 of file navigate_global_position.h.
References smacc_viewer.xdot.xdot_qt::x, and smacc_viewer.xdot.xdot_qt::y.
  {
    auto p = geometry_msgs::Point();
    p.x = x;
    p.y =y;
    initialPoint = p;
  }
Member Function Documentation
void NavigateGlobalPosition::goToRadialStart () [inline]
Definition at line 48 of file navigate_global_position.h.
References moveBaseClient_, readStartPoseFromParameterServer(), smacc::SmaccActionClientBase< ActionType >::sendGoal(), smacc::ISmaccStateMachine::setGlobalSMData(), and smacc::SmaccSubStateBehavior::stateMachine.
Referenced by onEntry().
  {
    ROS_INFO("Sending Goal to MoveBase");
    smacc::SmaccMoveBaseActionClient::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    readStartPoseFromParameterServer(goal);
    // store the start pose on the state machine storage so that it can
    // be referenced from other states (for example return to radial start)
    this->stateMachine->setGlobalSMData("radial_start_pose", goal.target_pose);
    moveBaseClient_->sendGoal(goal);
  }
virtual void NavigateGlobalPosition::onEntry () [inline], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 29 of file navigate_global_position.h.
References goToRadialStart(), moveBaseClient_, odomTracker_, plannerSwitcher_, smacc_odom_tracker::RECORD_PATH_FORWARD, smacc::SmaccSubStateBehavior::requiresComponent(), smacc_planner_switcher::PlannerSwitcher::setForwardPlanner(), and smacc_odom_tracker::OdomTracker::setWorkingMode().
  {
    ROS_INFO("Entering Navigate Global position");
    // this substate will need access to the "MoveBase" resource or plugin. In this line
    // you get the reference to this resource.
    this->requiresComponent(moveBaseClient_ , ros::NodeHandle("move_base"))
      ;
    this->requiresComponent(odomTracker_);
    this->requiresComponent(plannerSwitcher_ , ros::NodeHandle("move_base"
      ));
    ROS_INFO("Component requirements completed");
    this->plannerSwitcher_->setForwardPlanner();
    this->odomTracker_->setWorkingMode(
      smacc_odom_tracker::WorkingMode::RECORD_PATH_FORWARD);
    goToRadialStart();
  }
virtual bool NavigateGlobalPosition::onExit () [inline], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 82 of file navigate_global_position.h.
  {
    ROS_INFO("Exiting move goal Action Client");
  }
void NavigateGlobalPosition::readStartPoseFromParameterServer (smacc::SmaccMoveBaseActionClient::Goal & goal) [inline]
Definition at line 63 of file navigate_global_position.h.
References smacc::SmaccSubStateBehavior::currentState, smacc::ISmaccState::getParam(), and initialPoint.
Referenced by goToRadialStart().
  {
    if(! initialPoint)
    {
      this->currentState->getParam("start_position_x", goal.target_pose.pose.position.x
      );
      this->currentState->getParam("start_position_y", goal.target_pose.pose.position.y
      );
    }
    else
    {
      goal.target_pose.pose.position= *initialPoint;
    }
    
    goal.target_pose.pose.orientation.w = 1;
    ROS_INFO_STREAM("start position read from parameter server: " << goal.target_pose.pose.position);
  }
Member Data Documentation
boost::optional<geometry_msgs::Point> NavigateGlobalPosition::initialPoint
Definition at line 14 of file navigate_global_position.h.
Referenced by readStartPoseFromParameterServer().
smacc::SmaccMoveBaseActionClient* NavigateGlobalPosition::moveBaseClient_ [private]
Definition at line 90 of file navigate_global_position.h.
Referenced by goToRadialStart(), and onEntry().
smacc_odom_tracker::OdomTracker* NavigateGlobalPosition::odomTracker_ [private]
Definition at line 92 of file navigate_global_position.h.
Referenced by onEntry().
smacc_planner_switcher::PlannerSwitcher* NavigateGlobalPosition::plannerSwitcher_ [private]
Definition at line 94 of file navigate_global_position.h.
Referenced by onEntry().
The documentation for this class was generated from the following file:
smacc_sm_examples/sm_radial_motion/include/sm_radial_motion/substates_behaviors/navigation/navigate_global_position.h