smacc::ISmaccState Class Reference
#include <smacc_state.h>
Public Member Functions
template<typename T >
bool getParam (std::string param_name, T &param_storage)
template<typename T >
void setParam (std::string param_name, T param_val)
template<typename T >
bool param (std::string param_name, T &param_val, const T &default_val) const
virtual ISmaccStateMachine & getStateMachine ()=0
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
void configure (Args &&...args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TLUnit , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TLUnit > createLogicUnit (TEvArgs...args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< LogicUnit > > & getLogicUnits ()
Public Attributes
ros::NodeHandle nh
Protected Attributes
std::vector< std::shared_ptr< LogicUnit > > logicUnits_
Detailed Description
Definition at line 11 of file smacc_state.h.
Member Function Documentation
template<typename TOrthogonal , typename TBehavior , typename... Args> void smacc::ISmaccState::configure (Args &&... args)
Definition at line 38 of file smacc_state_impl.h.
References smacc::ISmaccStateMachine::getOrthogonal(), and getStateMachine().
{
    std::string orthogonalkey = demangledTypeName<TOrthogonal>();
    ROS_INFO("Configuring orthogonal: %s", orthogonalkey.c_str());
    std::shared_ptr<TOrthogonal> orthogonal;
    if (this->getStateMachine().getOrthogonal<TOrthogonal>(orthogonal))
    {
        auto clientBehavior = std::shared_ptr<TBehavior>(new TBehavior(args...));
        clientBehavior->template configureEventSourceTypes<TOrthogonal, TBehavior>();
        orthogonal->addClientBehavior(clientBehavior);
    }
    else
    {
        ROS_ERROR("Skipping client behavior creation. Orthogonal did not exist.");
    }
}
template<typename TLUnit , typename TTriggerEvent , typename TEventList , typename... TEvArgs> std::shared_ptr< TLUnit > smacc::ISmaccState::createLogicUnit (TEvArgs... args)
Definition at line 96 of file smacc_state_impl.h.
References logicUnits_.
{
    auto lu = std::make_shared<TLUnit>(args...);
    TEventList *mock;
    lu->initialize(this, mock);
    lu->declarePostEvent(typelist<TTriggerEvent>());
    logicUnits_.push_back(lu);
    return lu;
}
std::string smacc::ISmaccState::getClassName () [virtual]
Definition at line 6 of file smacc_state.cpp.
References smacc::demangleSymbol().
{
    return demangleSymbol(typeid(*this).name());
}
template<typename T > bool smacc::ISmaccState::getGlobalSMData (std::string name, T & ret)
Definition at line 81 of file smacc_state_impl.h.
References smacc::ISmaccStateMachine::getGlobalSMData(), and getStateMachine().
{
    return this->getStateMachine().getGlobalSMData(name, ret);
}
std::vector<std::shared_ptr<LogicUnit> >& smacc::ISmaccState::getLogicUnits () [inline]
Definition at line 59 of file smacc_state.h.
References logicUnits_.
{ return logicUnits_; }
template<typename T > bool smacc::ISmaccState::getParam (std::string param_name, T & param_storage)
Definition at line 15 of file smacc_state_impl.h.
References nh.
Referenced by sm_dance_bot::CbNavigateGlobalPosition::readStartPoseFromParameterServer().
{
    return nh.getParam(param_name, param_storage);
}
virtual ISmaccStateMachine& smacc::ISmaccState::getStateMachine () [pure virtual]
Implemented in smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >, smacc::SmaccState< StRotateDegrees6, MsDanceBotRunMode >, smacc::SmaccState< SsRadialPattern3, MsDanceBotRunMode, SsrRadialLoopStart >, smacc::SmaccState< StNavigateToWaypoint1, MsDanceBotRunMode >, smacc::SmaccState< SsRadialPattern1, MsDanceBotRunMode, SsrRadialLoopStart >, smacc::SmaccState< Ss1, SmThreeSome, Ssr1 >, smacc::SmaccState< State1, SmAtomicStateMachine >, smacc::SmaccState< SsrRadialEndPoint, SS >, smacc::SmaccState< SsrSPatternRotate4, SS >, smacc::SmaccState< SsrRadialReturn, SS >, smacc::SmaccState< SsrRadialRotate, SS >, smacc::SmaccState< Ssr1, SS >, smacc::SmaccState< State2, SmAtomicStateMachine >, smacc::SmaccState< StNavigateReverse3, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees3, MsDanceBotRunMode >, smacc::SmaccState< StState2, SmThreeSome >, smacc::SmaccState< StNavigateForward1, MsDanceBotRunMode >, smacc::SmaccState< SsRadialPattern2, MsDanceBotRunMode, SsrRadialLoopStart >, smacc::SmaccState< StNavigateReverse2, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees2, MsDanceBotRunMode >, smacc::SmaccState< SsrSPatternRotate2, SS >, smacc::SmaccState< StState3, SmThreeSome >, smacc::SmaccState< SsrRadialLoopStart, SS >, smacc::SmaccState< SsrFPatternReturn1, SS >, smacc::SmaccState< StRotateDegrees5, MsDanceBotRunMode >, smacc::SmaccState< SsrSPatternRotate3, SS >, smacc::SmaccState< StRotateDegrees4, MsDanceBotRunMode >, smacc::SmaccState< St2, MsRunMode >, smacc::SmaccState< SsrSPatternRotate1, SS >, smacc::SmaccState< SsrSPatternForward4, SS >, smacc::SmaccState< SsrSPatternLoopStart, SS >, smacc::SmaccState< StEventCountDown, MsDanceBotRunMode >, smacc::SmaccState< SsrFPatternRotate2, SS >, smacc::SmaccState< SsrSPatternForward3, SS >, smacc::SmaccState< StAcquireSensors, MsDanceBotRunMode >, smacc::SmaccState< Ssr3, SS >, smacc::SmaccState< StNavigateReverse1, MsDanceBotRunMode >, smacc::SmaccState< StRotateDegrees1, MsDanceBotRunMode >, smacc::SmaccState< StNavigateForward2, MsDanceBotRunMode >, smacc::SmaccState< SsrSPatternForward2, SS >, smacc::SmaccState< Ssr2, SS >, smacc::SmaccState< SsrSPatternForward1, SS >, smacc::SmaccState< SsrFPatternForward2, SS >, smacc::SmaccState< SsrFPatternRotate1, SS >, smacc::SmaccState< SsrFPatternForward1, SS >, smacc::SmaccState< SsFPattern1, MsDanceBotRunMode, SsrFPatternStartLoop >, smacc::SmaccState< SsSPattern1, MsDanceBotRunMode, SsrSPatternLoopStart >, smacc::SmaccState< StNavigateToWaypointsX, MsDanceBotRunMode >, smacc::SmaccState< StState1, SmThreeSome >, smacc::SmaccState< MsDanceBotRecoveryMode, SmDanceBot >, smacc::SmaccState< MsDanceBotRunMode, SmDanceBot, StAcquireSensors >, and smacc::SmaccState< SsrFPatternStartLoop, SS >.
Referenced by configure(), getGlobalSMData(), notifyTransitionFromTransitionTypeInfo(), postEvent(), requiresClient(), requiresComponent(), and setGlobalSMData().
template<typename TransitionType > void smacc::ISmaccState::notifyTransition ()
Definition at line 126 of file smacc_state_impl.h.
References notifyTransitionFromTransitionTypeInfo().
{
    auto transitionType = smacc::TypeInfo::getTypeInfoFromType<TransitionType>();
    this->notifyTransitionFromTransitionTypeInfo(transitionType);
}
void smacc::ISmaccState::notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc::TypeInfo > & transitionTypeInfo)
Definition at line 11 of file smacc_state.cpp.
References smacc::ISmaccStateMachine::getCurrentStateInfo(), getStateMachine(), and smacc::ISmaccStateMachine::publishTransition().
Referenced by notifyTransition().
{
    ROS_INFO_STREAM("NOTIFY TRANSITION: " << transitionType->getFullName());
    auto currstateinfo = this->getStateMachine().
      getCurrentStateInfo();
    if (currstateinfo != nullptr)
    {
        //ROS_ERROR_STREAM("CURRENT STATE INFO: " << currstateinfo->fullStateName);
        for (auto &transition : currstateinfo->transitions_)
        {
            std::string transitionCandidateName = transition.transitionTypeInfo->getFullName();
            //ROS_ERROR_STREAM("candidate transition: " << transitionCandidateName);
            if (transitionType->getFullName() == transitionCandidateName)
            {
                this->getStateMachine().publishTransition(transition);
                return;
            }
        }
        // debug information if not found
        ROS_ERROR_STREAM("Transition happened, but there is not any transitioninfo match available");
        for (auto &transition : currstateinfo->transitions_)
        {
            std::string transitionCandidateName = transition.transitionTypeInfo->getFullName();
            ROS_ERROR_STREAM("candidate transition: " << transitionCandidateName);
        }
    }
    else
    {
        ROS_ERROR_STREAM("Transition happened, but current state was not set. Transition candidates:");
    }
}
template<typename T > bool smacc::ISmaccState::param (std::string param_name, T & param_val, const T & default_val) const
Definition at line 31 of file smacc_state_impl.h.
References nh.
Referenced by sm_dance_bot::CbRotate::onEntry(), sm_dance_bot::CbNavigateForward::onEntry(), and sm_dance_bot::CbNavigateBackwards::onEntry().
{
    return nh.param(param_name, param_val, default_val);
}
template<typename EventType > void smacc::ISmaccState::postEvent (const EventType & ev)
Definition at line 119 of file smacc_state_impl.h.
References getStateMachine(), and smacc::ISmaccStateMachine::postEvent().
Referenced by sm_viewer_sim::delayedPostEvent(), smacc::SmaccState< SsrFPatternStartLoop, SS >::throwFinishEvent(), and smacc::SmaccState< SsrFPatternStartLoop, SS >::throwLoopEventFromCondition().
{
    getStateMachine().postEvent(ev);
}
template<typename SmaccClientType > void smacc::ISmaccState::requiresClient (SmaccClientType *& storage)
Definition at line 65 of file smacc_state_impl.h.
References smacc::ISmaccStateMachine::getOrthogonals(), and getStateMachine().
Referenced by sm_dance_bot::StNavigateForward1::onInitialize(), and sm_dance_bot::StNavigateToWaypointsX::onInitialize().
{
    storage = nullptr;
    auto &orthogonals = this->getStateMachine().getOrthogonals();
    for (auto &ortho : orthogonals)
    {
        ortho.second->requiresClient(storage);
        if (storage != nullptr)
            return;
    }
    ROS_ERROR("Client of type '%s' not found in any orthogonal of the current state machine. This may
       produce a segmentation fault if the returned reference is used.", demangleSymbol<SmaccClientType>().c_str());
}
template<typename SmaccComponentType > void smacc::ISmaccState::requiresComponent (SmaccComponentType *& storage)
Definition at line 58 of file smacc_state_impl.h.
References getStateMachine(), and smacc::ISmaccStateMachine::requiresComponent().
{
    this->getStateMachine().requiresComponent(storage);
}
template<typename T > void smacc::ISmaccState::setGlobalSMData (std::string name, T value)
Definition at line 89 of file smacc_state_impl.h.
References getStateMachine(), and smacc::ISmaccStateMachine::setGlobalSMData().
{
    this->getStateMachine().setGlobalSMData(name, value);
}
template<typename T > void smacc::ISmaccState::setParam (std::string param_name, T param_val)
Definition at line 23 of file smacc_state_impl.h.
References nh.
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::SmaccState(), and smacc::SmaccState< SsrFPatternStartLoop, SS >::~SmaccState().
{
    return nh.setParam(param_name, param_val);
}
Member Data Documentation
std::vector<std::shared_ptr<LogicUnit> > smacc::ISmaccState::logicUnits_ [protected]
Definition at line 64 of file smacc_state.h.
Referenced by createLogicUnit(), and getLogicUnits().
ros::NodeHandle smacc::ISmaccState::nh
Definition at line 61 of file smacc_state.h.
Referenced by getParam(), sm_dance_bot::StNavigateToWaypointsX::loadWaypointsFirstTime(), param(), setParam(), and smacc::SmaccState< SsrFPatternStartLoop, SS >::SmaccState().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_state.h
smacc/include/smacc/impl/smacc_state_impl.h
smacc/src/smacc/smacc_state.cpp