smacc::Timer Class Reference
#include <timer_substate.h>
Public Types
typedef TimerTickEvent TickEvent
Public Member Functions
Timer (ros::Duration duration, bool oneshot=false)
void onEntry ()
void onExit ()
void timerCallback (const ros::TimerEvent &timedata)
Public Attributes
ros::NodeHandle nh
ros::Timer timer
ros::Duration duration
bool oneshot
Detailed Description
Definition at line 28 of file timer_substate.h.
Member Typedef Documentation
typedef TimerTickEvent smacc::Timer::TickEvent
Definition at line 32 of file timer_substate.h.
Constructor & Destructor Documentation
smacc::Timer::Timer (ros::Duration duration, bool oneshot = false) [inline]
Definition at line 39 of file timer_substate.h.
  {
    this->duration = duration;
    this->oneshot = oneshot;
  }
Member Function Documentation
void smacc::Timer::onEntry () [inline], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 45 of file timer_substate.h.
References timerCallback().
  {
    timer = nh.createTimer(duration, boost::bind(&
      Timer::timerCallback, this, _1),oneshot);
  }
void smacc::Timer::onExit () [inline], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 50 of file timer_substate.h.
  {
    timer.stop();
  }
void smacc::Timer::timerCallback (const ros::TimerEvent & timedata) [inline]
Definition at line 55 of file timer_substate.h.
References smacc::TimerTickEvent::TimerTickEvent().
Referenced by onEntry().
  {
    TimerTickEvent* event= new TimerTickEvent(this, timedata);
    this->postEvent(event);
  }
Member Data Documentation
ros::Duration smacc::Timer::duration
Definition at line 36 of file timer_substate.h.
ros::NodeHandle smacc::Timer::nh
Definition at line 34 of file timer_substate.h.
bool smacc::Timer::oneshot
Definition at line 37 of file timer_substate.h.
ros::Timer smacc::Timer::timer
Definition at line 35 of file timer_substate.h.
The documentation for this class was generated from the following file:
smacc_client_library/smacc_sensors/examples/timer_substate_example/include/substates_behaviors/navigation/timer_substate.h