smacc::SignalDetector Class Reference
#include <signal_detector.h>
Public Member Functions
SignalDetector (SmaccScheduler *scheduler)
void initialize (ISmaccStateMachine *stateMachine)
void setProcessorHandle (SmaccScheduler::processor_handle processorHandle)
void runThread ()
void join ()
void stop ()
void toString (std::stringstream &ss)
void pollingLoop ()
void pollOnce ()
template<typename EventType >
void postEvent (EventType *ev)
Private Member Functions
void finalizeRequest (ISmaccActionClient *resource)
void notifyFeedback (ISmaccActionClient *resource)
void registerActionClientRequest (ISmaccActionClient *actionClientRequestInfo)
Private Attributes
ISmaccStateMachine * smaccStateMachine_
std::vector< ISmaccActionClient * > openRequests_
double loop_rate_hz
std::atomic< bool > end_
ros::NodeHandle nh_
ros::Publisher statusPub_
SmaccScheduler * scheduler_
SmaccScheduler::processor_handle processorHandle_
boost::thread signalDetectorThread_
Friends
class ISmaccStateMachine
Detailed Description
Definition at line 14 of file signal_detector.h.
Constructor & Destructor Documentation
smacc::SignalDetector::SignalDetector (SmaccScheduler * scheduler)
SignalDetector()
Definition at line 16 of file signal_detector.cpp.
References end_, loop_rate_hz, and scheduler_.
{
    scheduler_ = scheduler;
    loop_rate_hz = 10.0;
    end_= false;
}
Member Function Documentation
void smacc::SignalDetector::finalizeRequest (ISmaccActionClient * client) [private]
finalizeRequest()
Definition at line 107 of file signal_detector.cpp.
References smacc::ISmaccComponent::getName(), smacc::ISmaccActionClient::getState(), openRequests_, smacc::ISmaccActionClient::postEvent(), processorHandle_, and scheduler_.
Referenced by pollOnce(), and postEvent().
{
    ROS_INFO("SignalDetector: Finalizing actionlib request: %s. RESULT: %s", client->getName().c_str(),
      client->getState().toString().c_str());
    auto it = find(openRequests_.begin(), openRequests_.end(), client);
    if (it != openRequests_.end())
    {
        openRequests_.erase(it);
    }
    //boost::intrusive_ptr< IActionResult> actionClientResultEvent = client->createActionResultEvent();
    //actionClientResultEvent->client = client;
    ROS_INFO("SignalDetector: action lib result obtained, posting event");
    client->postEvent(scheduler_, processorHandle_);
    // SmaccScheduler
    //SmaccScheduler::processor_handle
    //scheduler_->queue_event(processorHandle_, actionClientResultEvent);
}
void smacc::SignalDetector::initialize (ISmaccStateMachine * stateMachine)
initialize()
Definition at line 40 of file signal_detector.cpp.
References smaccStateMachine_.
Referenced by smacc::ISmaccStateMachine::ISmaccStateMachine().
{
    smaccStateMachine_ = stateMachine;
}
void smacc::SignalDetector::join ()
join()
Definition at line 70 of file signal_detector.cpp.
References signalDetectorThread_.
{
    signalDetectorThread_.join();
}
void smacc::SignalDetector::notifyFeedback (ISmaccActionClient * client) [private]
notifyFeedback()
Definition at line 90 of file signal_detector.cpp.
References smacc::ISmaccActionClient::postFeedbackEvent(), processorHandle_, and scheduler_.
Referenced by pollOnce(), and postEvent().
{
    //ROS_INFO("Notify feedback");
    //boost::intrusive_ptr< EvActionFeedback > actionFeedbackEvent = new EvActionFeedback();
    //actionFeedbackEvent->client = client;
    client->postFeedbackEvent(scheduler_, processorHandle_);
    //ROS_INFO("Sending feedback event");
    //scheduler_->queue_event(processorHandle_, actionFeedbackEvent);
}
void smacc::SignalDetector::pollingLoop ()
pollingLoop()
Definition at line 173 of file signal_detector.cpp.
References end_, loop_rate_hz, and pollOnce().
Referenced by smacc::run(), and runThread().
{
    ros::NodeHandle nh("~");
    if (!nh.param("signal_detector_loop_freq", this->loop_rate_hz))
    {
    }
    nh.setParam("signal_detector_loop_freq", this->loop_rate_hz);
    ros::Rate r(loop_rate_hz);
    ROS_INFO_STREAM("[SignalDetector] loop rate hz:" << loop_rate_hz);
    while (ros::ok() && !end_)
    {
        ROS_INFO_STREAM_THROTTLE(10, "[SignalDetector] heartbeat");
        pollOnce();
        ros::spinOnce();
        r.sleep();
    }
}
void smacc::SignalDetector::pollOnce ()
poll()
Definition at line 149 of file signal_detector.cpp.
References finalizeRequest(), notifyFeedback(), and openRequests_.
Referenced by pollingLoop().
{
    for (ISmaccActionClient *smaccActionClient : openRequests_)
    {
        // check feedback messages
        if (smaccActionClient->hasFeedback())
        {
            notifyFeedback(smaccActionClient);
        }
        // check result
        auto state = smaccActionClient->getState();
        if (state.isDone())
        {
            finalizeRequest(smaccActionClient);
        }
    }
}
template<typename EventType > void smacc::SignalDetector::postEvent (EventType * ev) [inline]
Definition at line 39 of file signal_detector.h.
References finalizeRequest(), notifyFeedback(), processorHandle_, registerActionClientRequest(), and scheduler_.
Referenced by smacc::ISmaccStateMachine::postEvent().
        {
            boost::intrusive_ptr< EventType> weakPtrEvent = ev;
            this->scheduler_->queue_event(processorHandle_, weakPtrEvent);
        }
void smacc::SignalDetector::registerActionClientRequest (ISmaccActionClient * actionClientRequestInfo) [private]
registerActionClientRequest()
Definition at line 28 of file signal_detector.cpp.
References smacc::ISmaccComponent::getName(), and openRequests_.
Referenced by postEvent(), and smacc::ISmaccStateMachine::registerActionClientRequest().
{
    ROS_INFO("Signal detector is aware of the '-- %s -- action client request'", actionClientRequestInfo->
      getName().c_str());
    openRequests_.push_back(actionClientRequestInfo);
    ROS_INFO("Added to the opened requests list");
}
void smacc::SignalDetector::runThread ()
runThread()
Definition at line 60 of file signal_detector.cpp.
References pollingLoop(), and signalDetectorThread_.
{
    signalDetectorThread_ = boost::thread(boost::bind(&
      SignalDetector::pollingLoop, this));
}
void smacc::SignalDetector::setProcessorHandle (SmaccScheduler::processor_handle processorHandle)
setProcessorHandle()
Definition at line 50 of file signal_detector.cpp.
References processorHandle_.
Referenced by smacc::run().
{
    processorHandle_ = processorHandle;
}
void smacc::SignalDetector::stop ()
stop()
Definition at line 80 of file signal_detector.cpp.
References end_.
Referenced by smacc_viewer.xdot.xdot_qt.Animation::tick(), and smacc_viewer.xdot.xdot.Animation::tick().
{
    end_=true;
}
void smacc::SignalDetector::toString (std::stringstream & ss)
toString()
Definition at line 132 of file signal_detector.cpp.
References openRequests_.
{
    ss << "--------" << std::endl;
    ss << "Open requests" << std::endl;
    for (ISmaccActionClient *smaccActionClient : this->openRequests_)
    {
        auto state = smaccActionClient->getState().toString();
        ss << smaccActionClient->getName() << ": " << state << std::endl;
    }
    ss << "--------";
}
Friends And Related Function Documentation
friend class ISmaccStateMachine [friend]
Definition at line 76 of file signal_detector.h.
Member Data Documentation
std::atomic<bool> smacc::SignalDetector::end_ [private]
Definition at line 61 of file signal_detector.h.
Referenced by pollingLoop(), SignalDetector(), and stop().
double smacc::SignalDetector::loop_rate_hz [private]
Definition at line 59 of file signal_detector.h.
Referenced by pollingLoop(), and SignalDetector().
ros::NodeHandle smacc::SignalDetector::nh_ [private]
Definition at line 63 of file signal_detector.h.
std::vector<ISmaccActionClient*> smacc::SignalDetector::openRequests_ [private]
Definition at line 56 of file signal_detector.h.
Referenced by finalizeRequest(), pollOnce(), registerActionClientRequest(), and toString().
SmaccScheduler::processor_handle smacc::SignalDetector::processorHandle_ [private]
Definition at line 71 of file signal_detector.h.
Referenced by finalizeRequest(), notifyFeedback(), postEvent(), and setProcessorHandle().
SmaccScheduler* smacc::SignalDetector::scheduler_ [private]
Definition at line 69 of file signal_detector.h.
Referenced by finalizeRequest(), notifyFeedback(), postEvent(), and SignalDetector().
boost::thread smacc::SignalDetector::signalDetectorThread_ [private]
Definition at line 73 of file signal_detector.h.
Referenced by join(), and runThread().
ISmaccStateMachine* smacc::SignalDetector::smaccStateMachine_ [private]
Definition at line 53 of file signal_detector.h.
Referenced by initialize().
ros::Publisher smacc::SignalDetector::statusPub_ [private]
Definition at line 65 of file signal_detector.h.
The documentation for this class was generated from the following files:
smacc/include/smacc/signal_detector.h
smacc/src/smacc/signal_detector.cpp