move_base_z_client::CbRotate Class Reference
#include <cb_rotate.h>
Public Member Functions
CbRotate ()
CbRotate (float rotate_degree)
virtual void onEntry () override
Public Attributes
tf::TransformListener listener
ClMoveBaseZ * moveBaseClient_
boost::optional< float > rotateDegree
Detailed Description
Definition at line 13 of file cb_rotate.h.
Constructor & Destructor Documentation
move_base_z_client::CbRotate::CbRotate () [inline]
Definition at line 22 of file cb_rotate.h.
    {
    }
move_base_z_client::CbRotate::CbRotate (float rotate_degree) [inline]
Definition at line 26 of file cb_rotate.h.
    {
        rotateDegree = rotate_degree;
    }
Member Function Documentation
virtual void move_base_z_client::CbRotate::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 31 of file cb_rotate.h.
References smacc::SmaccClientBehavior::currentState, smacc::ISmaccState::param(), move_base_z_client::ClMoveBaseZ::plannerSwitcher_, smacc::SmaccClientBehavior::requiresClient(), rotateDegree, and smacc::SmaccActionClientBase< ActionType >::sendGoal().
    {
        double angle_increment_degree;
        if (!rotateDegree)
        {
            this->currentState->param("angle_increment_degree", angle_increment_degree, 45
      .0);
        }
        else
        {
            angle_increment_degree = *rotateDegree;
        }
        this->requiresClient(moveBaseClient_);
        //this should work better with a coroutine and await
        //this->plannerSwitcher_->setForwardPlanner();
        moveBaseClient_->plannerSwitcher_->setDefaultPlanners();
        ros::Rate rate(10.0);
        geometry_msgs::Pose currentPoseMsg;
        while (ros::ok())
        {
            tf::StampedTransform currentPose;
            try
            {
                listener.lookupTransform("/odom", "/base_link",
                                         ros::Time(0), currentPose);
                tf::poseTFToMsg(currentPose, currentPoseMsg);
                break;
            }
            catch (tf::TransformException ex)
            {
                ROS_ERROR("%s", ex.what());
                ros::Duration(1.0).sleep();
            }
        }
        ClMoveBaseZ::Goal goal;
        goal.target_pose.header.frame_id = "/odom";
        goal.target_pose.header.stamp = ros::Time::now();
        auto currentAngle = tf::getYaw(currentPoseMsg.orientation);
        auto targetAngle = currentAngle + angle_increment_degree * M_PI / 180.0;
        goal.target_pose.pose.position = currentPoseMsg.position;
        goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(targetAngle);
        ROS_INFO_STREAM("current pose: " << currentPoseMsg);
        ROS_INFO_STREAM("goal pose: " << goal.target_pose.pose);
        moveBaseClient_->sendGoal(goal);
    }
Member Data Documentation
tf::TransformListener move_base_z_client::CbRotate::listener
Definition at line 16 of file cb_rotate.h.
ClMoveBaseZ* move_base_z_client::CbRotate::moveBaseClient_
Definition at line 18 of file cb_rotate.h.
boost::optional<float> move_base_z_client::CbRotate::rotateDegree
Definition at line 20 of file cb_rotate.h.
Referenced by onEntry().
The documentation for this class was generated from the following file:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_rotate.h