smacc_viewer.xdot.wxxdot.WxZoomAreaAction Class Reference
Public Member Functions
def drag (self, deltax, deltay)
def draw (self, cr)
def stop (self)
def abort (self)
Additional Inherited Members
Detailed Description
Definition at line 114 of file wxxdot.py.
Member Function Documentation
def smacc_viewer.xdot.wxxdot.WxZoomAreaAction.abort (self)
Definition at line 140 of file wxxdot.py.
  def abort(self):
    self.dot_widget.Refresh()
def smacc_viewer.xdot.wxxdot.WxZoomAreaAction.drag (self, deltax, deltay)
Definition at line 115 of file wxxdot.py.
Referenced by smacc_viewer.xdot.xdot_qt.DragAction.on_motion_notify(), and smacc_viewer.xdot.xdot.DragAction.on_motion_notify().
  def drag(self, deltax, deltay):
    self.dot_widget.Refresh()
def smacc_viewer.xdot.wxxdot.WxZoomAreaAction.draw (self, cr)
Definition at line 118 of file wxxdot.py.
References smacc_viewer.xdot.wxxdot.WxDragAction.prevmousex, smacc_viewer.xdot.wxxdot.WxDragAction.prevmousey, smacc_viewer.xdot.wxxdot.WxDragAction.startmousex, and smacc_viewer.xdot.wxxdot.WxDragAction.startmousey.
  def draw(self, cr):
    cr.save()
    cr.set_source_rgba(.5, .5, 1.0, 0.25)
    cr.rectangle(self.startmousex, self.startmousey,
           self.prevmousex - self.startmousex,
           self.prevmousey - self.startmousey)
    cr.fill()
    cr.set_source_rgba(.5, .5, 1.0, 1.0)
    cr.set_line_width(1)
    cr.rectangle(self.startmousex - .5, self.startmousey - .5,
           self.prevmousex - self.startmousex + 1,
           self.prevmousey - self.startmousey + 1)
    cr.stroke()
    cr.restore()
def smacc_viewer.xdot.wxxdot.WxZoomAreaAction.stop (self)
Definition at line 133 of file wxxdot.py.
References smacc_viewer.xdot.wxxdot.WxDragAction.startmousex, smacc_viewer.xdot.wxxdot.WxDragAction.startmousey, smacc_viewer.xdot.wxxdot.WxDragAction.stopmousex, and smacc_viewer.xdot.wxxdot.WxDragAction.stopmousey.
Referenced by smacc_viewer.xdot.xdot_qt.Animation.tick(), and smacc_viewer.xdot.xdot.Animation.tick().
  def stop(self):
    x1, y1 = self.dot_widget.window2graph(self.startmousex,
                        self.startmousey)
    x2, y2 = self.dot_widget.window2graph(self.stopmousex,
                        self.stopmousey)
    self.dot_widget.zoom_to_area(x1, y1, x2, y2)
The documentation for this class was generated from the following file:
smacc_viewer/src/smacc_viewer/xdot/wxxdot.py