smacc::SbKeyboard Class Reference
#include <sb_keyboard_substate.h>
Public Member Functions
void onEntry ()
bool onExit ()
void OnKeyPress (char character)
template<typename TEv >
void postKeyEvent ()
Public Attributes
KeyboardClient * keyboardClient_
boost::signals2::scoped_connection c_
Detailed Description
Definition at line 11 of file sb_keyboard_substate.h.
Member Function Documentation
void smacc::SbKeyboard::onEntry () [inline], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 17 of file sb_keyboard_substate.h.
References smacc::KeyboardClient::initialize(), OnKeyPress(), smacc::KeyboardClient::OnKeyPress, and smacc::SmaccSubStateBehavior::requiresComponent().
        {
                this->requiresComponent(keyboardClient_);
                keyboardClient_->initialize("/keyboard_unicode", 1);
                c_ = this->keyboardClient_->OnKeyPress.connect(
                    [this](char character) {
                            this->OnKeyPress(character);
                    });
        }
bool smacc::SbKeyboard::onExit () [inline], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 28 of file sb_keyboard_substate.h.
        {
        }
void smacc::SbKeyboard::OnKeyPress (char character) [inline]
Definition at line 32 of file sb_keyboard_substate.h.
Referenced by onEntry().
        {
                if (character == 'a')
                        postKeyEvent<EvKeyPressA<SbKeyboard>>();
                else if (character == 'b')
                        postKeyEvent<EvKeyPressB<SbKeyboard>>();
                else if (character == 'c')
                        postKeyEvent<EvKeyPressC<SbKeyboard>>();
                else if (character == 'd')
                        postKeyEvent<EvKeyPressD<SbKeyboard>>();
                else if (character == 'e')
                        postKeyEvent<EvKeyPressE<SbKeyboard>>();
                else if (character == 'f')
                        postKeyEvent<EvKeyPressF<SbKeyboard>>();
                else if (character == 'g')
                        postKeyEvent<EvKeyPressG<SbKeyboard>>();
                else if (character == 'h')
                        postKeyEvent<EvKeyPressH<SbKeyboard>>();
                else if (character == 'y')
                        postKeyEvent<EvKeyPressI<SbKeyboard>>();
                else if (character == 'j')
                        postKeyEvent<EvKeyPressJ<SbKeyboard>>();
                else if (character == 'k')
                        postKeyEvent<EvKeyPressK<SbKeyboard>>();
                else if (character == 'l')
                        postKeyEvent<EvKeyPressL<SbKeyboard>>();
                else if (character == 'm')
                        postKeyEvent<EvKeyPressM<SbKeyboard>>();
                else if (character == 'n')
                        postKeyEvent<EvKeyPressN<SbKeyboard>>();
                else if (character == 'o')
                        postKeyEvent<EvKeyPressO<SbKeyboard>>();
                else if (character == 'p')
                        postKeyEvent<EvKeyPressP<SbKeyboard>>();
                else if (character == 'q')
                        postKeyEvent<EvKeyPressQ<SbKeyboard>>();
                else if (character == 'r')
                        postKeyEvent<EvKeyPressR<SbKeyboard>>();
                else if (character == 's')
                        postKeyEvent<EvKeyPressS<SbKeyboard>>();
                else if (character == 't')
                        postKeyEvent<EvKeyPressT<SbKeyboard>>();
                else if (character == 'u')
                        postKeyEvent<EvKeyPressU<SbKeyboard>>();
                else if (character == 'v')
                        postKeyEvent<EvKeyPressV<SbKeyboard>>();
                else if (character == 'w')
                        postKeyEvent<EvKeyPressW<SbKeyboard>>();
                else if (character == 'x')
                        postKeyEvent<EvKeyPressX<SbKeyboard>>();
                else if (character == 'y')
                        postKeyEvent<EvKeyPressY<SbKeyboard>>();
                else if (character == 'z')
                        postKeyEvent<EvKeyPressZ<SbKeyboard>>();
        }
template<typename TEv > void smacc::SbKeyboard::postKeyEvent () [inline]
Definition at line 89 of file sb_keyboard_substate.h.
References demangleSymbol(), and smacc::SmaccSubStateBehavior::postEvent().
        {
                ROS_WARN("SbKeyboard %ld ev: %s", (long)(void*)this ,
      demangleSymbol(typeid(TEv).name()).c_str());
                auto event = new TEv();
                this->postEvent(event);
        }
Member Data Documentation
boost::signals2::scoped_connection smacc::SbKeyboard::c_
Definition at line 15 of file sb_keyboard_substate.h.
KeyboardClient* smacc::SbKeyboard::keyboardClient_
Definition at line 14 of file sb_keyboard_substate.h.
The documentation for this class was generated from the following file:
smacc_sm_examples/sm_dance_bot/include/sm_dance_bot/substate_behaviors/keyboard/sb_keyboard_substate.h