sm_dance_bot::SbNavigateGlobalPosition Class Reference
#include <sb_navigate_global_position.h>
Public Member Functions
SbNavigateGlobalPosition ()
SbNavigateGlobalPosition (float x, float y, float yaw)
virtual void onEntry ()
void goToRadialStart ()
void readStartPoseFromParameterServer (smacc::SmaccMoveBaseActionClient::Goal &goal)
virtual void onExit () override
Public Attributes
boost::optional< geometry_msgs::Point > initialPoint
boost::optional< float > initialYaw
Private Attributes
smacc::SmaccMoveBaseActionClient * moveBaseClient_
smacc_odom_tracker::OdomTracker * odomTracker_
Detailed Description
Definition at line 13 of file sb_navigate_global_position.h.
Constructor & Destructor Documentation
sm_dance_bot::SbNavigateGlobalPosition::SbNavigateGlobalPosition () [inline]
Definition at line 19 of file sb_navigate_global_position.h.
  {
  }
sm_dance_bot::SbNavigateGlobalPosition::SbNavigateGlobalPosition (float x, float y, float yaw) [inline]
Definition at line 23 of file sb_navigate_global_position.h.
  {
    auto p = geometry_msgs::Point();
    p.x = x;
    p.y = y;
    initialPoint = p;
    initialYaw = yaw;
  }
Member Function Documentation
void sm_dance_bot::SbNavigateGlobalPosition::goToRadialStart () [inline]
Definition at line 50 of file sb_navigate_global_position.h.
References moveBaseClient_, readStartPoseFromParameterServer(), smacc::SmaccActionClientBase< TDerived, ActionType >::sendGoal(), smacc::ISmaccStateMachine::setGlobalSMData(), and smacc::SmaccSubStateBehavior::stateMachine.
Referenced by onEntry().
  {
    ROS_INFO("Sending Goal to MoveBase");
    smacc::SmaccMoveBaseActionClient::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    readStartPoseFromParameterServer(goal);
    // store the start pose on the state machine storage so that it can
    // be referenced from other states (for example return to radial start)
    this->stateMachine->setGlobalSMData("radial_start_pose", goal.target_pose);
    moveBaseClient_->sendGoal(goal);
  }
virtual void sm_dance_bot::SbNavigateGlobalPosition::onEntry () [inline], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 32 of file sb_navigate_global_position.h.
References goToRadialStart(), moveBaseClient_, odomTracker_, smacc::SmaccMoveBaseActionClient::plannerSwitcher_, smacc_odom_tracker::RECORD_PATH_FORWARD, smacc::SmaccSubStateBehavior::requiresClient(), smacc::SmaccSubStateBehavior::requiresComponent(), and smacc_odom_tracker::OdomTracker::setWorkingMode().
  {
    ROS_INFO("Entering Navigate Global position");
    // this substate will need access to the "MoveBase" resource or plugin. In this line
    // you get the reference to this resource.
    this->requiresClient(moveBaseClient_);
    this->requiresComponent(odomTracker_);
    ROS_INFO("Component requirements completed");
    moveBaseClient_->plannerSwitcher_->setDefaultPlanners();
    this->odomTracker_->setWorkingMode(
      smacc_odom_tracker::WorkingMode::RECORD_PATH_FORWARD);
    goToRadialStart();
  }
virtual void sm_dance_bot::SbNavigateGlobalPosition::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 87 of file sb_navigate_global_position.h.
  {
    ROS_INFO("Exiting move goal Action Client");
  }
void sm_dance_bot::SbNavigateGlobalPosition::readStartPoseFromParameterServer (smacc::SmaccMoveBaseActionClient::Goal & goal) [inline]
Definition at line 65 of file sb_navigate_global_position.h.
References smacc::SmaccSubStateBehavior::currentState, smacc::ISmaccState::getParam(), and initialPoint.
Referenced by goToRadialStart().
  {
    if (!initialPoint)
    {
      this->currentState->getParam("start_position_x", goal.target_pose.pose.position.x
      );
      this->currentState->getParam("start_position_y", goal.target_pose.pose.position.y
      );
      double yaw;
      this->currentState->getParam("start_position_yaw", yaw);
      goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(yaw);
    }
    else
    {
      goal.target_pose.pose.position = *initialPoint;
      goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(*
      initialYaw);
    }
    ROS_INFO_STREAM("start position read from parameter server: " << goal.target_pose.pose.position);
  }
Member Data Documentation
boost::optional<geometry_msgs::Point> sm_dance_bot::SbNavigateGlobalPosition::initialPoint
Definition at line 16 of file sb_navigate_global_position.h.
Referenced by readStartPoseFromParameterServer().
boost::optional<float> sm_dance_bot::SbNavigateGlobalPosition::initialYaw
Definition at line 17 of file sb_navigate_global_position.h.
smacc::SmaccMoveBaseActionClient* sm_dance_bot::SbNavigateGlobalPosition::moveBaseClient_ [private]
Definition at line 95 of file sb_navigate_global_position.h.
Referenced by goToRadialStart(), and onEntry().
smacc_odom_tracker::OdomTracker* sm_dance_bot::SbNavigateGlobalPosition::odomTracker_ [private]
Definition at line 97 of file sb_navigate_global_position.h.
Referenced by onEntry().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/substate_behaviors/navigation/sb_navigate_global_position.h