smacc_viewer.xdot.wxxdot.WxZoomAction Class Reference
Public Member Functions
def drag (self, deltax, deltay)
def stop (self)
Additional Inherited Members
Detailed Description
Definition at line 105 of file wxxdot.py.
Member Function Documentation
def smacc_viewer.xdot.wxxdot.WxZoomAction.drag (self, deltax, deltay)
Definition at line 106 of file wxxdot.py.
Referenced by smacc_viewer.xdot.xdot_qt.DragAction.on_motion_notify(), and smacc_viewer.xdot.xdot.DragAction.on_motion_notify().
  def drag(self, deltax, deltay):
    self.dot_widget.zoom_ratio *= 1.005 ** (deltax + deltay)
    self.dot_widget.zoom_to_fit_on_resize = False
    self.dot_widget.Refresh()
def smacc_viewer.xdot.wxxdot.WxZoomAction.stop (self)
Definition at line 111 of file wxxdot.py.
Referenced by smacc_viewer.xdot.xdot_qt.Animation.tick(), and smacc_viewer.xdot.xdot.Animation.tick().
  def stop(self):
    self.dot_widget.Refresh()
The documentation for this class was generated from the following file:
smacc_viewer/src/smacc_viewer/xdot/wxxdot.py