sm_dance_bot::SbUndoPathBackwards Class Reference
#include <sb_undo_path_backwards.h>
Private Member Functions
virtual void onEntry () override
Private Attributes
tf::TransformListener listener
smacc::SmaccMoveBaseActionClient * moveBaseClient_
smacc_odom_tracker::OdomTracker * odomTracker_
Additional Inherited Members
Detailed Description
Definition at line 10 of file sb_undo_path_backwards.h.
Member Function Documentation
virtual void sm_dance_bot::SbUndoPathBackwards::onEntry () [inline], [override], [private], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 18 of file sb_undo_path_backwards.h.
References smacc_odom_tracker::CLEAR_PATH_BACKWARD, smacc_odom_tracker::OdomTracker::getPath(), smacc::SmaccMoveBaseActionClient::plannerSwitcher_, smacc::SmaccSubStateBehavior::requiresClient(), smacc::SmaccSubStateBehavior::requiresComponent(), smacc::SmaccActionClientBase< TDerived, ActionType >::sendGoal(), and smacc_odom_tracker::OdomTracker::setWorkingMode().
  {
    this->requiresClient(moveBaseClient_);
    this->requiresComponent(odomTracker_);
    nav_msgs::Path forwardpath = this->odomTracker_->getPath();
    //ROS_INFO_STREAM("[UndoPathBackward] Current path backwards: " << forwardpath);
    this->odomTracker_->setWorkingMode(
      smacc_odom_tracker::WorkingMode::CLEAR_PATH_BACKWARD);
    smacc::SmaccMoveBaseActionClient::Goal goal;
    if (forwardpath.poses.size() > 0)
    {
      goal.target_pose = forwardpath.poses.front();
      moveBaseClient_->plannerSwitcher_->setBackwardPlanner();
      moveBaseClient_->sendGoal(goal);
    }
  }
Member Data Documentation
tf::TransformListener sm_dance_bot::SbUndoPathBackwards::listener [private]
Definition at line 12 of file sb_undo_path_backwards.h.
smacc::SmaccMoveBaseActionClient* sm_dance_bot::SbUndoPathBackwards::moveBaseClient_ [private]
Definition at line 14 of file sb_undo_path_backwards.h.
smacc_odom_tracker::OdomTracker* sm_dance_bot::SbUndoPathBackwards::odomTracker_ [private]
Definition at line 16 of file sb_undo_path_backwards.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/substate_behaviors/navigation/sb_undo_path_backwards.h