smacc::ISmaccComponent Class Reference
#include <component.h>
Public Member Functions
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual void init (ros::NodeHandle &nh)
virtual void init (ros::NodeHandle &nh, std::string value)
void setStateMachine (ISmaccStateMachine *stateMachine)
virtual std::string getName () const
template<typename EventType >
void postEvent (const EventType &ev)
Protected Attributes
ISmaccStateMachine * stateMachine_
Detailed Description
Definition at line 11 of file component.h.
Constructor & Destructor Documentation
smacc::ISmaccComponent::ISmaccComponent ()
Definition at line 16 of file smacc_component.cpp.
{
}
smacc::ISmaccComponent::~ISmaccComponent () [virtual]
Definition at line 11 of file smacc_component.cpp.
{
}
Member Function Documentation
std::string smacc::ISmaccComponent::getName () const [virtual]
Reimplemented in smacc::SmaccMoveBaseActionClient, and smacc::SmaccToolActionClient.
Definition at line 36 of file smacc_component.cpp.
References demangleSymbol().
Referenced by smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::cancelGoal(), smacc::SignalDetector::finalizeRequest(), smacc::SmaccServiceClient< std_srvs::SetBool >::initialize(), smacc::SmaccTopicPublisherClient< std_msgs::String >::initialize(), smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::postEvent(), smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::postFeedbackEvent(), smacc::SignalDetector::registerActionClientRequest(), smacc::ISmaccStateMachine::registerActionClientRequest(), and smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::sendGoal().
{
    std::string keyname = demangleSymbol(typeid(*this).name());
    return keyname;
}
void smacc::ISmaccComponent::init (ros::NodeHandle & nh) [virtual]
Reimplemented in smacc::SmaccActionClientBase< ActionType >, smacc::SmaccActionClientBase< smacc_action_client_generic::ToolControlAction >, smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >, and smacc::ISmaccActionClient.
Definition at line 20 of file smacc_component.cpp.
{
    
}
void smacc::ISmaccComponent::init (ros::NodeHandle & nh, std::string value) [virtual]
Reimplemented in smacc::SmaccActionClientBase< ActionType >, smacc::SmaccActionClientBase< smacc_action_client_generic::ToolControlAction >, smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >, smacc_odom_tracker::OdomTracker, smacc::ISmaccActionClient, and smacc_planner_switcher::PlannerSwitcher.
Definition at line 25 of file smacc_component.cpp.
{
    
}
template<typename EventType > void smacc::ISmaccComponent::postEvent (const EventType & ev)
Definition at line 9 of file smacc_component_impl.h.
References smacc::ISmaccStateMachine::postEvent(), and stateMachine_.
    {
        stateMachine_->postEvent(ev);
    }
void smacc::ISmaccComponent::setStateMachine (ISmaccStateMachine * stateMachine)
Definition at line 31 of file smacc_component.cpp.
References stateMachine_.
{
    stateMachine_ = stateMachine;
}
Member Data Documentation
ISmaccStateMachine* smacc::ISmaccComponent::stateMachine_ [protected]
Definition at line 34 of file component.h.
Referenced by postEvent(), smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::sendGoal(), and setStateMachine().
The documentation for this class was generated from the following files:
smacc/include/smacc/component.h
smacc/include/smacc/impl/smacc_component_impl.h
smacc/src/smacc/smacc_component.cpp