smacc_viewer.xdot.wxxdot.WxDotFrame Class Reference
Public Member Functions
def __init__ (self)
def ShowControlsDialog (self, event)
def DoOpenFile (self, event)
def OnExit (self, event)
def set_dotcode (self, dotcode, filename='< stdin >')
def set_xdotcode (self, xdotcode, filename='< stdin >')
def open_file (self, filename)
def set_filter (self, filter)
Public Attributes
widget
Detailed Description
Definition at line 503 of file wxxdot.py.
Constructor & Destructor Documentation
def smacc_viewer.xdot.wxxdot.WxDotFrame.__init__ (self)
Definition at line 504 of file wxxdot.py.
  def __init__(self):
    wx.Frame.__init__(self, None, -1, "Dot Viewer", size=(512,512))
    vbox = wx.BoxSizer(wx.VERTICAL)
    # Construct toolbar
    toolbar = wx.ToolBar(self, -1)
    toolbar.AddLabelTool(wx.ID_OPEN, 'Open File',
        wx.ArtProvider.GetBitmap(wx.ART_FOLDER_OPEN,wx.ART_OTHER,(16,16)))
    toolbar.AddLabelTool(wx.ID_HELP, 'Help',
        wx.ArtProvider.GetBitmap(wx.ART_HELP,wx.ART_OTHER,(16,16)))
    toolbar.Realize()
    self.Bind(wx.EVT_TOOL, self.DoOpenFile, id=wx.ID_OPEN)
    self.Bind(wx.EVT_TOOL, self.ShowControlsDialog, id=wx.ID_HELP)
    # Create dot widge
    self.widget = WxDotWindow(self, -1)
    # Add elements to sizer
    vbox.Add(toolbar, 0, wx.EXPAND)
    vbox.Add(self.widget, 100, wx.EXPAND | wx.ALL)
    self.SetSizer(vbox)
    self.Center()
Member Function Documentation
def smacc_viewer.xdot.wxxdot.WxDotFrame.DoOpenFile (self, event)
Definition at line 540 of file wxxdot.py.
Referenced by smacc_viewer.xdot.wxxdot.WxDotFrame.__init__().
  def DoOpenFile(self,event):
    wcd = 'All files (*)|*|GraphViz Dot Files(*.dot)|*.dot|'
    dir = os.getcwd()
    open_dlg = wx.FileDialog(self, message='Choose a file', defaultDir=dir, defaultFile='',
    wildcard=wcd, style=wx.OPEN|wx.CHANGE_DIR)
    if open_dlg.ShowModal() == wx.ID_OK:
      path = open_dlg.GetPath()
      try:
        self.open_file(path)
      except IOError, error:
        dlg = wx.MessageDialog(self, 'Error opening file\n' + str(error))
        dlg.ShowModal()
      except UnicodeDecodeError, error:
        dlg = wx.MessageDialog(self, 'Error opening file\n' + str(error))
        dlg.ShowModal()
    open_dlg.Destroy()
def smacc_viewer.xdot.wxxdot.WxDotFrame.OnExit (self, event)
Definition at line 561 of file wxxdot.py.
  def OnExit(self, event):
    pass
def smacc_viewer.xdot.wxxdot.WxDotFrame.open_file (self, filename)
Definition at line 574 of file wxxdot.py.
Referenced by smacc_viewer.xdot.wxxdot.WxDotFrame.DoOpenFile(), smacc_viewer.xdot.xdot.DotWindow.on_open(), smacc_viewer.xdot.xdot_qt.DotWindow.on_open(), and smacc_viewer.xdot.xdot_qt.DotWindow.update_file_menu().
  def open_file(self, filename):
    try:
      fp = file(filename, 'rt')
      self.set_dotcode(fp.read(), filename)
      fp.close()
    except IOError, ex:
      """
      dlg = gtk.MessageDialog(type=gtk.MESSAGE_ERROR,
                  message_format=str(ex),
                  buttons=gtk.BUTTONS_OK)
      dlg.set_title('Dot Viewer')
      dlg.run()
      dlg.destroy()
      """
def smacc_viewer.xdot.wxxdot.WxDotFrame.set_dotcode (self, dotcode, filename = '<stdin>')
Definition at line 564 of file wxxdot.py.
Referenced by smacc_viewer.xdot.wxxdot.WxDotFrame.open_file(), smacc_viewer.xdot.xdot.DotWindow.open_file(), smacc_viewer.xdot.xdot_qt.DotWindow.open_file(), and smacc_viewer.xdot.xdot.DotWidget.reload().
  def set_dotcode(self, dotcode, filename='<stdin>'):
    if self.widget.set_dotcode(dotcode, filename):
      self.SetTitle(os.path.basename(filename) + ' - Dot Viewer')
      self.widget.zoom_to_fit()
def smacc_viewer.xdot.wxxdot.WxDotFrame.set_filter (self, filter)
Definition at line 589 of file wxxdot.py.
  def set_filter(self, filter):
    self.widget.set_filter(filter)
def smacc_viewer.xdot.wxxdot.WxDotFrame.set_xdotcode (self, xdotcode, filename = '<stdin>')
Definition at line 569 of file wxxdot.py.
Referenced by smacc_viewer.xdot.xdot.DotWidget.set_dotcode().
  def set_xdotcode(self, xdotcode, filename='<stdin>'):
    if self.widget.set_xdotcode(xdotcode):
      self.SetTitle(os.path.basename(filename) + ' - Dot Viewer')
      self.widget.zoom_to_fit()
def smacc_viewer.xdot.wxxdot.WxDotFrame.ShowControlsDialog (self, event)
Definition at line 530 of file wxxdot.py.
Referenced by smacc_viewer.xdot.wxxdot.WxDotFrame.__init__().
  def ShowControlsDialog(self,event):
    dial = wx.MessageDialog(None,
        "\
Pan: Arrow Keys\n\
Zoom: PageUp / PageDown\n\
Zoom To Fit: F\n\
Refresh: R",
        'Keyboard Controls', wx.OK)
    dial.ShowModal()
Member Data Documentation
smacc_viewer.xdot.wxxdot.WxDotFrame.widget
Definition at line 521 of file wxxdot.py.
The documentation for this class was generated from the following file:
smacc_viewer/src/smacc_viewer/xdot/wxxdot.py