sm_dance_bot::SbNavigateForward Class Reference
#include <sb_navigate_forward.h>
Public Member Functions
SbNavigateForward (float forwardDistance)
SbNavigateForward ()
virtual void onEntry () override
virtual void onExit () override
Public Attributes
boost::optional< float > forwardDistance
boost::optional< float > forwardSpeed
tf::TransformListener listener
smacc::SmaccMoveBaseActionClient * moveBaseClient_
smacc_odom_tracker::OdomTracker * odomTracker_
Detailed Description
Definition at line 12 of file sb_navigate_forward.h.
Constructor & Destructor Documentation
sm_dance_bot::SbNavigateForward::SbNavigateForward (float forwardDistance) [inline]
Definition at line 26 of file sb_navigate_forward.h.
References forwardDistance.
    {
        this->forwardDistance = forwardDistance;
    }
sm_dance_bot::SbNavigateForward::SbNavigateForward () [inline]
Definition at line 31 of file sb_navigate_forward.h.
    {
    }
Member Function Documentation
virtual void sm_dance_bot::SbNavigateForward::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 35 of file sb_navigate_forward.h.
References smacc_odom_tracker::OdomTracker::clearPath(), smacc::SmaccSubStateBehavior::currentState, forwardDistance, smacc::ISmaccState::param(), smacc::SmaccMoveBaseActionClient::plannerSwitcher_, smacc_odom_tracker::RECORD_PATH_FORWARD, smacc::SmaccSubStateBehavior::requiresClient(), smacc::SmaccSubStateBehavior::requiresComponent(), smacc::SmaccActionClientBase< TDerived, ActionType >::sendGoal(), smacc_odom_tracker::OdomTracker::setStartPoint(), and smacc_odom_tracker::OdomTracker::setWorkingMode().
    {
        // straight motion distance
        double dist;
        if (!forwardDistance)
        {
            this->currentState->param("straight_motion_distance", dist, 3.5);
        }
        else
        {
            dist = *forwardDistance;
        }
        ROS_INFO_STREAM("Straight motion distance: " << dist);
        this->requiresClient(moveBaseClient_);
        this->requiresComponent(odomTracker_);
        //this should work better with a coroutine and await
        ros::Rate rate(10.0);
        tf::StampedTransform currentPose;
        while (ros::ok())
        {
            try
            {
                listener.lookupTransform("/odom", "/base_link",
                                         ros::Time(0), currentPose);
                break;
            }
            catch (tf::TransformException ex)
            {
                ROS_ERROR("%s", ex.what());
                ros::Duration(1.0).sleep();
            }
        }
        tf::Transform forwardDeltaTransform;
        forwardDeltaTransform.setIdentity();
        forwardDeltaTransform.setOrigin(tf::Vector3(dist, 0, 0));
        tf::Transform targetPose = currentPose * forwardDeltaTransform;
        smacc::SmaccMoveBaseActionClient::Goal goal;
        goal.target_pose.header.frame_id = "/odom";
        goal.target_pose.header.stamp = ros::Time::now();
        tf::poseTFToMsg(targetPose, goal.target_pose.pose);
        ROS_INFO_STREAM("TARGET POSE FORWARD: " << goal.target_pose.pose);
        ros::Duration(10).sleep();
        this->odomTracker_->clearPath();
        geometry_msgs::PoseStamped currentPoseMsg;
        currentPoseMsg.header.frame_id = "/odom";
        currentPoseMsg.header.stamp = ros::Time::now();
        tf::poseTFToMsg(currentPose, currentPoseMsg.pose);
        this->odomTracker_->setStartPoint(currentPoseMsg);
        this->odomTracker_->setWorkingMode(
      smacc_odom_tracker::WorkingMode::RECORD_PATH_FORWARD);
        moveBaseClient_->plannerSwitcher_->setForwardPlanner();
        moveBaseClient_->sendGoal(goal);
    }
virtual void sm_dance_bot::SbNavigateForward::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 101 of file sb_navigate_forward.h.
References smacc_odom_tracker::IDLE, and smacc_odom_tracker::OdomTracker::setWorkingMode().
    {
        this->odomTracker_->setWorkingMode(
      smacc_odom_tracker::WorkingMode::IDLE);
    }
Member Data Documentation
boost::optional<float> sm_dance_bot::SbNavigateForward::forwardDistance
Definition at line 15 of file sb_navigate_forward.h.
Referenced by onEntry(), and SbNavigateForward().
boost::optional<float> sm_dance_bot::SbNavigateForward::forwardSpeed
Definition at line 18 of file sb_navigate_forward.h.
tf::TransformListener sm_dance_bot::SbNavigateForward::listener
Definition at line 20 of file sb_navigate_forward.h.
smacc::SmaccMoveBaseActionClient* sm_dance_bot::SbNavigateForward::moveBaseClient_
Definition at line 22 of file sb_navigate_forward.h.
smacc_odom_tracker::OdomTracker* sm_dance_bot::SbNavigateForward::odomTracker_
Definition at line 24 of file sb_navigate_forward.h.
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/substate_behaviors/navigation/sb_navigate_forward.h