smacc_viewer.xdot.xdot.Pen Class Reference
Public Member Functions
def __init__ (self)
def copy (self)
def highlighted (self)
Public Attributes
color
fillcolor
linewidth
fontsize
fontname
dash
Detailed Description
Store pen attributes.
Definition at line 50 of file xdot.py.
Constructor & Destructor Documentation
def smacc_viewer.xdot.xdot.Pen.__init__ (self)
Definition at line 53 of file xdot.py.
    def __init__(self):
        # set default attributes
        self.color = (0.0, 0.0, 0.0, 1.0)
        self.fillcolor = (0.0, 0.0, 0.0, 1.0)
        self.linewidth = 1.0
        self.fontsize = 14.0
        self.fontname = "Times-Roman"
        self.dash = ()
Member Function Documentation
def smacc_viewer.xdot.xdot.Pen.copy (self)
Create a copy of this pen.
Definition at line 62 of file xdot.py.
Referenced by smacc_viewer.xdot.xdot.Pen.highlighted(), and smacc_viewer.xdot.xdot_qt.Pen.highlighted().
    def copy(self):
        """Create a copy of this pen."""
        pen = Pen()
        pen.__dict__ = self.__dict__.copy()
        return pen
def smacc_viewer.xdot.xdot.Pen.highlighted (self)
Definition at line 68 of file xdot.py.
References smacc_viewer.xdot.xdot.Pen.copy().
    def highlighted(self):
        pen = self.copy()
        pen.color = (1, 0, 0, 1)
        pen.fillcolor = (1, .8, .8, 1)
        return pen
Member Data Documentation
smacc_viewer.xdot.xdot.Pen.color
Definition at line 55 of file xdot.py.
smacc_viewer.xdot.xdot.Pen.dash
Definition at line 60 of file xdot.py.
smacc_viewer.xdot.xdot.Pen.fillcolor
Definition at line 56 of file xdot.py.
smacc_viewer.xdot.xdot.Pen.fontname
Definition at line 59 of file xdot.py.
smacc_viewer.xdot.xdot.Pen.fontsize
Definition at line 58 of file xdot.py.
smacc_viewer.xdot.xdot.Pen.linewidth
Definition at line 57 of file xdot.py.
The documentation for this class was generated from the following file:
smacc_viewer/src/smacc_viewer/xdot/xdot.py