sm_dance_bot::CbUndoPathBackwards Class Reference
#include <cb_undo_path_backwards.h>
Private Member Functions
virtual void onEntry () override
virtual void onEntry () override
Private Attributes
tf::TransformListener listener
smacc::ClMoveBaseZ * moveBaseClient_
Additional Inherited Members
Detailed Description
Definition at line 10 of file cb_undo_path_backwards.h.
Member Function Documentation
virtual void sm_dance_bot::CbUndoPathBackwards::onEntry () [inline], [override], [private], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 16 of file cb_undo_path_backwards.h.
References odom_tracker::CLEAR_PATH_BACKWARD, smacc::ClMoveBaseZ::plannerSwitcher_, smacc::SmaccClientBehavior::requiresClient(), and smacc::SmaccActionClientBase< ActionType >::sendGoal().
  {
    this->requiresClient(moveBaseClient_);
    auto* odomTracker_ = this->getComponent<odom_tracker::OdomTracker>();
    nav_msgs::Path forwardpath = this->odomTracker_->getPath();
    //ROS_INFO_STREAM("[UndoPathBackward] Current path backwards: " << forwardpath);
    this->odomTracker_->setWorkingMode(
      odom_tracker::WorkingMode::CLEAR_PATH_BACKWARD);
    smacc::ClMoveBaseZ::Goal goal;
    if (forwardpath.poses.size() > 0)
    {
      goal.target_pose = forwardpath.poses.front();
      moveBaseClient_->plannerSwitcher_->setBackwardPlanner();
      moveBaseClient_->sendGoal(goal);
    }
  }
virtual void sm_dance_bot::CbUndoPathBackwards::onEntry () [inline], [override], [private], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 16 of file cb_undo_path_backwards.h.
References odom_tracker::CLEAR_PATH_BACKWARD, smacc::ISmaccClient::getComponent(), odom_tracker::OdomTracker::getPath(), smacc::ClMoveBaseZ::plannerSwitcher_, smacc::SmaccClientBehavior::requiresClient(), and smacc::SmaccActionClientBase< ActionType >::sendGoal().
  {
    this->requiresClient(moveBaseClient_);
    auto* odomTracker = moveBaseClient_->getComponent<
      odom_tracker::OdomTracker>();
    nav_msgs::Path forwardpath = odomTracker->getPath();
    //ROS_INFO_STREAM("[UndoPathBackward] Current path backwards: " << forwardpath);
    odomTracker->setWorkingMode(odom_tracker::WorkingMode::CLEAR_PATH_BACKWARD
      );
    smacc::ClMoveBaseZ::Goal goal;
    if (forwardpath.poses.size() > 0)
    {
      goal.target_pose = forwardpath.poses.front();
      moveBaseClient_->plannerSwitcher_->setBackwardPlanner();
      moveBaseClient_->sendGoal(goal);
    }
  }
Member Data Documentation
tf::TransformListener sm_dance_bot::CbUndoPathBackwards::listener [private]
Definition at line 12 of file cb_undo_path_backwards.h.
smacc::ClMoveBaseZ * sm_dance_bot::CbUndoPathBackwards::moveBaseClient_ [private]
Definition at line 14 of file cb_undo_path_backwards.h.
The documentation for this class was generated from the following file:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_undo_path_backwards.h