ros_timer_client::ClRosTimer Class Reference
#include <cl_ros_timer.h>
Public Member Functions
ClRosTimer (ros::Duration duration, bool oneshot=false)
virtual ~ClRosTimer ()
virtual void initialize ()
Public Attributes
boost::signals2::signal< void(EvTimer< ClRosTimer > *)> onTimerTick
boost::signals2::scoped_connection c_
Protected Member Functions
void timerCallback (const ros::TimerEvent &timedata)
Protected Attributes
ros::NodeHandle nh_
ros::Timer timer
ros::Duration duration
bool oneshot
Detailed Description
Definition at line 24 of file cl_ros_timer.h.
Constructor & Destructor Documentation
ros_timer_client::ClRosTimer::ClRosTimer (ros::Duration duration, bool oneshot = false)
Definition at line 6 of file timer_client.cpp.
References duration, and oneshot.
{
    this->duration = duration;
    this->oneshot = oneshot;
}
ros_timer_client::ClRosTimer::~ClRosTimer () [virtual]
Definition at line 12 of file timer_client.cpp.
References timer.
{
    timer.stop();
}
Member Function Documentation
void ros_timer_client::ClRosTimer::initialize () [virtual]
Reimplemented from smacc::ISmaccClient.
Definition at line 17 of file timer_client.cpp.
References duration, nh_, oneshot, timer, and timerCallback().
{
    timer = nh_.createTimer(duration, boost::bind(&
      ClRosTimer::timerCallback, this, _1), oneshot);
}
void ros_timer_client::ClRosTimer::timerCallback (const ros::TimerEvent & timedata) [protected]
Definition at line 22 of file timer_client.cpp.
References onTimerTick, and smacc::ISmaccClient::postEvent().
Referenced by initialize().
{
    //auto *event = new EvTimer<ClRosTimer>(this, timedata);
    auto *event = new EvTimer<ClRosTimer>();
    this->postEvent(event);
    onTimerTick(event);
}
Member Data Documentation
boost::signals2::scoped_connection ros_timer_client::ClRosTimer::c_
Definition at line 28 of file cl_ros_timer.h.
ros::Duration ros_timer_client::ClRosTimer::duration [protected]
Definition at line 40 of file cl_ros_timer.h.
Referenced by ClRosTimer(), and initialize().
ros::NodeHandle ros_timer_client::ClRosTimer::nh_ [protected]
Definition at line 37 of file cl_ros_timer.h.
Referenced by initialize().
bool ros_timer_client::ClRosTimer::oneshot [protected]
Definition at line 41 of file cl_ros_timer.h.
Referenced by ClRosTimer(), and initialize().
boost::signals2::signal<void(EvTimer<ClRosTimer> *)> ros_timer_client::ClRosTimer::onTimerTick
Definition at line 27 of file cl_ros_timer.h.
Referenced by ros_timer_client::CbTimer::onEntry(), and timerCallback().
ros::Timer ros_timer_client::ClRosTimer::timer [protected]
Definition at line 39 of file cl_ros_timer.h.
Referenced by initialize(), and ~ClRosTimer().
The documentation for this class was generated from the following files:
smacc_client_library/ros_timer_client/include/ros_timer_client/cl_ros_timer.h
smacc_client_library/ros_timer_client/src/ros_timer_client/timer_client.cpp