smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode > Class Template Reference
#include <smacc_state_base.h>
Classes
struct AddLogicUnitEventType
struct my_context
Public Types
typedef Context TContext
typedef Context::inner_context_type context_type
typedef context_type::state_iterator state_iterator
typedef base_type::outermost_context_base_type outermost_context_base_type
typedef base_type::inner_context_ptr_type inner_context_ptr_type
typedef base_type::context_ptr_type context_ptr_type
typedef base_type::inner_initial_list inner_initial_list
Public Member Functions
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool verbose=false)
virtual ISmaccStateMachine & getStateMachine ()
SmaccState ()=delete
SmaccState (my_context ctx)
std::string getFullPathName ()
std::string getFullName ()
std::string getShortName ()
virtual ~SmaccState ()
void throwFinishEvent ()
void onInitialize ()
void onEntry ()
void onExit ()
void throwLoopEventFromCondition (bool(MostDerived::*conditionFn)())
Static Public Member Functions
template<typename TOrthogonal , typename TBehavior , typename... Args>
static void static_configure (Args &&...args)
template<typename TEventList >
static void iterateLogicUnitEventTypes (SmaccLogicUnitInfo &luinfo)
template<typename TLUnit , typename TTriggerEvent , typename TEventList , typename... TUArgs>
static void static_createLogicUnit (TUArgs...args)
static void initial_deep_construct (outermost_context_base_type &outermostContextBase)
static void deep_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
static inner_context_ptr_type shallow_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
Public Attributes
bool finishStateThrown
InnerInitial * smacc_inner_type
Private Types
typedef sc::simple_state< MostDerived, Context, InnerInitial, historyMode > base_type
Additional Inherited Members
Detailed Description
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history>
*
class smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >
Definition at line 12 of file smacc_state_base.h.
Member Typedef Documentation
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef sc::simple_state<MostDerived, Context, InnerInitial, historyMode> smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::base_type [private]
Definition at line 17 of file smacc_state_base.h.
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef base_type::context_ptr_type smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::context_ptr_type
Definition at line 351 of file smacc_state_base.h.
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef Context::inner_context_type smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::context_type
Definition at line 127 of file smacc_state_base.h.
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef base_type::inner_context_ptr_type smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::inner_context_ptr_type
Definition at line 350 of file smacc_state_base.h.
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef base_type::inner_initial_list smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::inner_initial_list
Definition at line 352 of file smacc_state_base.h.
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef base_type::outermost_context_base_type smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::outermost_context_base_type
Definition at line 349 of file smacc_state_base.h.
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef context_type::state_iterator smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::state_iterator
Definition at line 128 of file smacc_state_base.h.
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef Context smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::TContext
Definition at line 20 of file smacc_state_base.h.
Constructor & Destructor Documentation
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState () [delete]
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState (my_context ctx) [inline]
Definition at line 60 of file smacc_state_base.h.
  {
    finishStateThrown = false;
    ROS_WARN_STREAM("creatingState state: " << demangleSymbol(typeid(MostDerived).name()).
      c_str());
    this->set_context(ctx.pContext_);
    this->getStateMachine().notifyOnStateEntryStart(
      static_cast<MostDerived *>(this));
    //template< class Target >
    //Target state_cast() const;
    ros::NodeHandle contextNh = optionalNodeHandle(ctx.pContext_);
    ROS_DEBUG("context node handle namespace: %s", contextNh.getNamespace().c_str());
    if (contextNh.getNamespace() == "/")
    {
      contextNh = ros::NodeHandle(cleanShortTypeName(typeid(Context)));
    }
    std::string classname = cleanShortTypeName(typeid(MostDerived));
    this->nh = ros::NodeHandle(contextNh.getNamespace() + std::string("/") + classname);
    ROS_DEBUG("nodehandle namespace: %s", nh.getNamespace().c_str());
    this->setParam("created", true);
    // before dynamic onInitialize, we execute the onDefinition behavior configurations
    {
      ROS_INFO("-- STATIC STATE DESCRIPTION --");
      // for (const auto &stateBehaviorsVector : SmaccStateInfo::staticBehaviorInfo)
      // {
      // ROS_INFO_STREAM(" - state info: " << demangleSymbol(stateBehaviorsVector.first->name()));
      // for (auto &bhinfo : stateBehaviorsVector.second)
      // {
      // ROS_INFO_STREAM(" - client behavior: " << demangleSymbol(bhinfo.behaviorType->name()));
      // }
      // }
      const std::type_info *tindex = &(typeid(MostDerived));
      auto &staticDefinedBehaviors = SmaccStateInfo::staticBehaviorInfo[
      tindex];
      auto &staticDefinedLogicUnits = SmaccStateInfo::logicUnitsInfo[tindex];
      for (auto &bhinfo : staticDefinedBehaviors)
      {
        ROS_INFO_STREAM("- Creating static client behavior: " << demangleSymbol(bhinfo.
      behaviorType->name()));
        bhinfo.factoryFunction(this);
      }
      for (auto &lu : staticDefinedLogicUnits)
      {
        ROS_INFO_STREAM("- Creating static logic unit: " << demangleSymbol(lu.logicUnitType->
      name()));
        lu.factoryFunction(this);
      }
      ROS_INFO("---- END STATIC DESCRIPTION");
    }
    static_cast<MostDerived *>(this)->onInitialize();
    this->getStateMachine().notifyOnStateEntryEnd(
      static_cast<MostDerived *>(this));
    //ROS_INFO("Not behavioral State");
    static_cast<MostDerived *>(this)->onEntry();
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> virtual smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::~SmaccState () [inline], [virtual]
Definition at line 157 of file smacc_state_base.h.
  {
    try
    {
      this->getStateMachine().lockStateMachine("state exit");
      auto fullname = demangleSymbol(typeid(MostDerived).name());
      ROS_WARN_STREAM("exiting state: " << fullname);
      this->setParam("destroyed", true);
      this->getStateMachine().notifyOnStateExit(static_cast<MostDerived *>(
      this));
      ROS_WARN_STREAM("state exit: " << fullname);
    }
    catch (...)
    {
    }
    this->getStateMachine().unlockStateMachine("state exit");
  }
Member Function Documentation
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> static void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::deep_construct (const context_ptr_type & pContext, outermost_context_base_type & outermostContextBase) [inline], [static]
Definition at line 361 of file smacc_state_base.h.
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::initial_deep_construct().
  {
    const inner_context_ptr_type pInnerContext(
        shallow_construct(pContext, outermostContextBase));
    base_type::template deep_construct_inner<inner_initial_list>(
        pInnerContext, outermostContextBase);
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> std::string smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getFullName () [inline]
Definition at line 147 of file smacc_state_base.h.
  {
    return demangleSymbol(typeid(MostDerived).name());
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> std::string smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getFullPathName () [inline]
Definition at line 132 of file smacc_state_base.h.
  {
    auto smInfo = this->getStateMachine().info_;
    auto key = typeid(MostDerived).name();
    if (smInfo->states.count(key))
    {
      return smInfo->states[key]->getFullPath();
    }
    else
    {
      return "UnknownFullPath";
    }
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename T > bool smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getGlobalSMData (std::string name, T & ret) [inline]
Definition at line 33 of file smacc_state_base.h.
  {
    return base_type::outermost_context().getGlobalSMData(name, ret);
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> std::string smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getShortName () [inline]
Definition at line 152 of file smacc_state_base.h.
  {
    return cleanShortTypeName(typeid(MostDerived));
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> virtual ISmaccStateMachine& smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getStateMachine () [inline], [virtual]
Implements smacc::ISmaccState.
Definition at line 51 of file smacc_state_base.h.
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::getFullPathName(), smacc::SmaccState< SsrFPatternStartLoop, SS >::SmaccState(), and smacc::SmaccState< SsrFPatternStartLoop, SS >::~SmaccState().
  {
    return base_type::outermost_context();
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> static void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::initial_deep_construct (outermost_context_base_type & outermostContextBase) [inline], [static]
Definition at line 354 of file smacc_state_base.h.
  {
    deep_construct(&outermostContextBase, outermostContextBase);
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename TEventList > static void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::iterateLogicUnitEventTypes (SmaccLogicUnitInfo & luinfo) [inline], [static]
Definition at line 251 of file smacc_state_base.h.
  {
    using boost::mpl::_1;
    using wrappedList = typename boost::mpl::transform<TEventList, _1>::type;
    AddLogicUnitEventType<wrappedList> op(luinfo);
    boost::mpl::for_each<wrappedList>(op);
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::onEntry () [inline]
Definition at line 195 of file smacc_state_base.h.
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::SmaccState().
  {
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::onExit () [inline]
Definition at line 201 of file smacc_state_base.h.
  {
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::onInitialize () [inline]
Definition at line 189 of file smacc_state_base.h.
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::SmaccState().
  {
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename SmaccComponentType > void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::requiresComponent (SmaccComponentType *& storage, bool verbose = false) [inline]
Definition at line 46 of file smacc_state_base.h.
  {
    base_type::outermost_context().requiresComponent(storage, verbose);
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename T > void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::setGlobalSMData (std::string name, T value) [inline]
Definition at line 40 of file smacc_state_base.h.
  {
    base_type::outermost_context().setGlobalSMData(name, value);
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> static inner_context_ptr_type smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::shallow_construct (const context_ptr_type & pContext, outermost_context_base_type & outermostContextBase) [inline], [static]
Definition at line 371 of file smacc_state_base.h.
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::deep_construct().
  {
    const inner_context_ptr_type pInnerContext(
        new MostDerived(
            SmaccState<MostDerived, Context, InnerInitial, historyMode>
      ::
                my_context(pContext)));
    outermostContextBase.add(pInnerContext);
    return pInnerContext;
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename TOrthogonal , typename TBehavior , typename... Args> static void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::static_configure (Args &&... args) [inline], [static]
Definition at line 206 of file smacc_state_base.h.
  {
    auto strorthogonal = demangleSymbol(typeid(TOrthogonal).name());
    auto strbehavior = demangleSymbol(typeid(TBehavior).name());
    ROS_INFO_STREAM("Orthogonal " << strorthogonal << " -> " << strbehavior);
    StateBehaviorInfoEntry bhinfo;
    bhinfo.factoryFunction = [=](ISmaccState *state) {
      //auto bh = std::make_shared<TBehavior>(args...);
      state->configure<TOrthogonal, TBehavior>(args...);
    };
    bhinfo.behaviorType = &(typeid(TBehavior));
    bhinfo.orthogonalType = &(typeid(TOrthogonal));
    const std::type_info *tindex = &(typeid(MostDerived));
    if (!SmaccStateInfo::staticBehaviorInfo.count(tindex))
      SmaccStateInfo::staticBehaviorInfo[tindex] =
      std::vector<StateBehaviorInfoEntry>();
    SmaccStateInfo::staticBehaviorInfo[tindex].push_back(bhinfo);
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename TLUnit , typename TTriggerEvent , typename TEventList , typename... TUArgs> static void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::static_createLogicUnit (TUArgs... args) [inline], [static]
Definition at line 260 of file smacc_state_base.h.
  {
    SmaccLogicUnitInfo luinfo;
    luinfo.logicUnitType = &typeid(TLUnit);
    std::string eventtypename = typeid(TTriggerEvent).name();
    auto eventType = TypeInfo::getTypeInfoFromString(eventtypename);
    if (eventType->templateParameters.size() > 1)
    {
      luinfo.objectTagType = eventType->templateParameters[1];
    }
    else
    {
      luinfo.objectTagType = nullptr;
    }
    iterateLogicUnitEventTypes<TEventList>(luinfo);
    luinfo.factoryFunction = [&, args...](ISmaccState *state) {
      auto lu = state->createLogicUnit<TLUnit, TTriggerEvent, TEventList>(args...);
      return lu;
    };
    const std::type_info *tindex = &(typeid(MostDerived));
    if (!SmaccStateInfo::logicUnitsInfo.count(tindex))
      SmaccStateInfo::logicUnitsInfo[tindex] =
      std::vector<SmaccLogicUnitInfo>();
    SmaccStateInfo::logicUnitsInfo[tindex].push_back(luinfo);
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::throwFinishEvent () [inline]
Definition at line 175 of file smacc_state_base.h.
  {
    if (!finishStateThrown)
    {
      auto *finishEvent = new EvStateFinish<MostDerived>();
      finishEvent->state = static_cast<MostDerived *>(this);
      this->postEvent(finishEvent);
      finishStateThrown = true;
    }
  }
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::throwLoopEventFromCondition (bool(MostDerived::*)() conditionFn) [inline]
Definition at line 324 of file smacc_state_base.h.
  {
    auto *thisobject = static_cast<MostDerived *>(this);
    auto condition = boost::bind(conditionFn, thisobject);
    bool conditionResult = condition();
    //ROS_INFO("LOOP EVENT CONDITION: %d", conditionResult);
    if (conditionResult)
    {
      auto evloopcontinue = new EvLoopContinue<MostDerived>();
      this->postEvent(evloopcontinue);
    }
    else
    {
      auto evloopend = new EvLoopEnd<MostDerived>();
      this->postEvent(evloopend);
    }
    ROS_INFO("POST THROW CONDITION");
  }
Member Data Documentation
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> bool smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::finishStateThrown
Definition at line 56 of file smacc_state_base.h.
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> InnerInitial* smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::smacc_inner_type
Definition at line 130 of file smacc_state_base.h.
The documentation for this class was generated from the following file:
smacc/include/smacc/smacc_state_base.h