smacc_viewer.smacc_user_data.Remapper Class Reference
Public Member Functions
def __init__ (self, ud, input_keys=[], output_keys=[], remapping={})
def update (self, other_userdata)
def __getitem__ (self, key)
def __setitem__ (self, key, item)
def keys (self)
def __contains__ (self, key)
def __getattr__ (self, name)
def __setattr__ (self, name, value)
Private Member Functions
def _remap (self, key)
Private Attributes
_ud
_input
_output
_map
__initialized
Detailed Description
Key-remapping proxy to a smacc userdata structure.
Definition at line 122 of file smacc_user_data.py.
Constructor & Destructor Documentation
def smacc_viewer.smacc_user_data.Remapper.__init__ (self, ud, input_keys = [], output_keys = [], remapping = {})
Definition at line 124 of file smacc_user_data.py.
    def __init__(self, ud, input_keys=[], output_keys=[], remapping={}):
        self._ud = ud
        self._input = input_keys
        self._output = output_keys
        self._map = remapping
        self.__initialized = True
Member Function Documentation
def smacc_viewer.smacc_user_data.Remapper.__contains__ (self, key)
Definition at line 156 of file smacc_user_data.py.
References smacc_viewer.smacc_user_data.Remapper._input, smacc_viewer.smacc_user_data.Remapper._remap(), and smacc_viewer.smacc_user_data.Remapper._ud.
    def __contains__(self,key):
        if key in self._input:
            return self._remap(key) in self._ud
        else:
            return False
def smacc_viewer.smacc_user_data.Remapper.__getattr__ (self, name)
Definition at line 162 of file smacc_user_data.py.
References smacc_viewer.smacc_user_data.Remapper._input, smacc_viewer.smacc_user_data.Remapper._output, smacc_viewer.smacc_user_data.Remapper._remap(), smacc_viewer.smacc_user_data.Remapper._ud, and smacc_viewer.smacc_user_data.get_const().
    def __getattr__(self, name):
        if name[0] == '_':
            return object.__getattr__(self, name)
        if name not in self._input:
            raise rospy.InvalidUserCodeError("Reading from smacc userdata key '%s' but the only keys that
       were declared as input to this state were: %s. This key needs to be declaread as input to this state. " % (
      name, self._input))
        if name not in self._output:
            return get_const(getattr(self._ud, self._remap(name)))
        return getattr(self._ud, self._remap(name))
def smacc_viewer.smacc_user_data.Remapper.__getitem__ (self, key)
Definition at line 140 of file smacc_user_data.py.
References smacc_viewer.smacc_user_data.Remapper._input, smacc_viewer.smacc_user_data.Remapper._output, smacc_viewer.smacc_user_data.Remapper._remap(), and smacc_viewer.smacc_user_data.get_const().
    def __getitem__(self, key):
        if key not in self._input:
            raise rospy.InvalidUserCodeError("Reading from smacc userdata key '%s' but the only keys that
       were declared as input to this state were: %s. This key needs to be declaread as input to this state. " % (
      key, self._input))
        if key not in self._output:
            return get_const(self._ud.__getitem__(self._remap(key)))
        return self._ud.__getitem__(self._remap(key))
def smacc_viewer.smacc_user_data.Remapper.__setattr__ (self, name, value)
Definition at line 171 of file smacc_user_data.py.
References smacc_viewer.smacc_user_data.Remapper._output, smacc_viewer.smacc_user_data.Remapper._remap(), and smacc_viewer.smacc_user_data.Remapper._ud.
    def __setattr__(self, name, value):
        if name[0] == '_' or '_Remapper__initialized' not in self.__dict__:
            return object.__setattr__(self, name, value)
        if name not in self._output:
            rospy.logerr("Writing to smacc userdata key '%s' but the only keys that were declared as output
       from this state were: %s." % (name, self._output))
            return None
        setattr(self._ud, self._remap(name), value)
def smacc_viewer.smacc_user_data.Remapper.__setitem__ (self, key, item)
Definition at line 147 of file smacc_user_data.py.
References smacc_viewer.smacc_user_data.Remapper._output, and smacc_viewer.smacc_user_data.Remapper._remap().
    def __setitem__(self, key, item):
        if key not in self._output:
            rospy.logerr("Writing to smacc userdata key '%s' but the only keys that were declared as output
       from this state were: %s." % (key, self._output))
            return
        self._ud.__setitem__(self._remap(key),item)
def smacc_viewer.smacc_user_data.Remapper._remap (self, key) [private]
Return either the key or it's remapped value.
Definition at line 131 of file smacc_user_data.py.
References smacc_viewer.smacc_user_data.Remapper._map.
Referenced by smacc_viewer.smacc_user_data.Remapper.__contains__(), smacc_viewer.smacc_user_data.Remapper.__getattr__(), smacc_viewer.smacc_user_data.Remapper.__getitem__(), smacc_viewer.smacc_user_data.Remapper.__setattr__(), smacc_viewer.smacc_user_data.Remapper.__setitem__(), and smacc_viewer.smacc_user_data.Remapper.keys().
    def _remap(self, key):
        """Return either the key or it's remapped value."""
        if key in self._map:
            return self._map[key]
        return key
def smacc_viewer.smacc_user_data.Remapper.keys (self)
Definition at line 153 of file smacc_user_data.py.
References smacc_viewer.smacc_user_data.Remapper._input, and smacc_viewer.smacc_user_data.Remapper._remap().
    def keys(self):
        return [self._remap(key) for key in self._ud.keys() if key in self.
      _input]
def smacc_viewer.smacc_user_data.Remapper.update (self, other_userdata)
Definition at line 137 of file smacc_user_data.py.
    def update(self, other_userdata):
        self._ud.update(other_userdata)
Member Data Documentation
smacc_viewer.smacc_user_data.Remapper.__initialized [private]
Definition at line 129 of file smacc_user_data.py.
smacc_viewer.smacc_user_data.Remapper._input [private]
Definition at line 126 of file smacc_user_data.py.
Referenced by smacc_viewer.smacc_user_data.Remapper.__contains__(), smacc_viewer.smacc_user_data.Remapper.__getattr__(), smacc_viewer.smacc_user_data.Remapper.__getitem__(), and smacc_viewer.smacc_user_data.Remapper.keys().
smacc_viewer.smacc_user_data.Remapper._map [private]
Definition at line 128 of file smacc_user_data.py.
Referenced by smacc_viewer.smacc_user_data.Remapper._remap().
smacc_viewer.smacc_user_data.Remapper._output [private]
Definition at line 127 of file smacc_user_data.py.
Referenced by smacc_viewer.smacc_user_data.Remapper.__getattr__(), smacc_viewer.smacc_user_data.Remapper.__getitem__(), smacc_viewer.smacc_user_data.Remapper.__setattr__(), and smacc_viewer.smacc_user_data.Remapper.__setitem__().
smacc_viewer.smacc_user_data.Remapper._ud [private]
Definition at line 125 of file smacc_user_data.py.
Referenced by smacc_viewer.smacc_user_data.Remapper.__contains__(), smacc_viewer.smacc_user_data.Remapper.__getattr__(), and smacc_viewer.smacc_user_data.Remapper.__setattr__().
The documentation for this class was generated from the following file:
smacc_viewer/src/smacc_viewer/smacc_user_data.py