smacc_viewer.xdot.wxxdot.WxPanAction Class Reference
Public Member Functions
def start (self)
def drag (self, deltax, deltay)
def stop (self)
Static Public Attributes
abort = stop
Additional Inherited Members
Detailed Description
Definition at line 91 of file wxxdot.py.
Member Function Documentation
def smacc_viewer.xdot.wxxdot.WxPanAction.drag (self, deltax, deltay)
Definition at line 95 of file wxxdot.py.
Referenced by smacc_viewer.xdot.xdot_qt.DragAction.on_motion_notify(), and smacc_viewer.xdot.xdot.DragAction.on_motion_notify().
  def drag(self, deltax, deltay):
    self.dot_widget.x += deltax / self.dot_widget.zoom_ratio
    self.dot_widget.y += deltay / self.dot_widget.zoom_ratio
    self.dot_widget.Refresh()
def smacc_viewer.xdot.wxxdot.WxPanAction.start (self)
Definition at line 92 of file wxxdot.py.
  def start(self):
    self.dot_widget.set_cursor(wx.CURSOR_SIZING)
def smacc_viewer.xdot.wxxdot.WxPanAction.stop (self)
Definition at line 100 of file wxxdot.py.
Referenced by smacc_viewer.xdot.xdot_qt.Animation.tick(), and smacc_viewer.xdot.xdot.Animation.tick().
  def stop(self):
    self.dot_widget.set_cursor(wx.CURSOR_ARROW)
Member Data Documentation
smacc_viewer.xdot.wxxdot.WxPanAction.abort = stop [static]
Definition at line 103 of file wxxdot.py.
The documentation for this class was generated from the following file:
smacc_viewer/src/smacc_viewer/xdot/wxxdot.py