smacc::ISmaccStateMachine Class Reference
#include <smacc_state_machine.h>
Public Member Functions
ISmaccStateMachine (SignalDetector *signalDetector)
virtual ~ISmaccStateMachine ()
virtual void Reset ()
virtual void Stop ()
virtual void EStop ()
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
const std::map< std::string, std::shared_ptr< smacc::Orthogonal > > & getOrthogonals () const
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename EventType >
void postEvent (EventType *ev)
template<typename EventType >
void postEvent ()
void getTransitionLogHistory ()
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename StateField , typename BehaviorType >
void mapBehavior ()
void updateStatusMessage ()
std::string getStateMachineName ()
void state_machine_visualization (const ros::TimerEvent &)
std::shared_ptr< smacc::SmaccStateInfo > getCurrentStateInfo ()
void publishTransition (SmaccTransitionInfo &transitionInfo)
virtual void onInitialize ()
this function should be implemented by the user to create the orthogonals
bool getTransitionLogHistory (smacc_msgs::SmaccGetTransitionHistory::Request &req, smacc_msgs::SmaccGetTransitionHistory::Response &res)
template<typename TSmaccSignal , typename TMemberFunctionPrototype , typename TSmaccObjectType >
boost::signals2::connection createSignalConnection (TSmaccSignal &signal, TMemberFunctionPrototype callback, TSmaccObjectType *object)
template<typename TSmaccSignal , typename TMemberFunctionPrototype >
boost::signals2::connection createSignalConnection (TSmaccSignal &signal, TMemberFunctionPrototype callback)
void lockStateMachine (std::string msg)
void unlockStateMachine (std::string msg)
template<typename StateType >
void notifyOnStateEntryStart (StateType *state)
template<typename StateType >
void notifyOnStateEntryEnd (StateType *state)
template<typename StateType >
void notifyOnStateExit (StateType *state)
unsigned long getCurrentStateCounter () const
ISmaccState * getCurrentState () const
Public Attributes
std::list< boost::signals2::connection > stateCallbackConnections
std::shared_ptr< SmaccStateMachineInfo > info_
Protected Member Functions
void onInitializing (std::string smshortname)
void onInitialized ()
template<typename TOrthogonal >
void createOrthogonal ()
template<typename T >
bool getParam (std::string param_name, T &param_storage)
template<typename T >
void setParam (std::string param_name, T param_val)
template<typename T >
bool param (std::string param_name, T &param_val, const T &default_val) const
Protected Attributes
ros::NodeHandle nh_
ros::NodeHandle private_nh_
ros::Timer timer_
ros::Publisher stateMachinePub_
ros::Publisher stateMachineStatusPub_
ros::Publisher transitionLogPub_
ros::ServiceServer transitionHistoryService_
ISmaccState * currentState_
std::shared_ptr< smacc::SmaccStateInfo > currentStateInfo_
smacc_msgs::SmaccStatus status_msg_
std::map< std::string, std::shared_ptr< smacc::Orthogonal > > orthogonals_
Private Member Functions
template<typename EventType >
void propagateEventToLogicUnits (ISmaccState *st, EventType *ev)
Private Attributes
std::recursive_mutex m_mutex_
std::map< std::string, std::pair< std::function< std::string()>, boost::any > > globalData_
std::vector< smacc_msgs::SmaccTransitionLogEntry > transitionLogHistory_
smacc::SMRunMode runMode_
SignalDetector * signalDetector_
unsigned long stateSeqCounter_
Friends
class ISmaccState
Detailed Description
Definition at line 36 of file smacc_state_machine.h.
Constructor & Destructor Documentation
smacc::ISmaccStateMachine::ISmaccStateMachine (SignalDetector * signalDetector)
Definition at line 14 of file smacc_state_machine.cpp.
References smacc::DEBUG, smacc::SignalDetector::initialize(), nh_, smacc::RELEASE, runMode_, and signalDetector_.
    : private_nh_("~"), currentState_(nullptr),
      stateSeqCounter_(0)
{
    ROS_INFO("Creating State Machine Base");
    signalDetector_ = signalDetector;
    signalDetector_->initialize(this);
    std::string runMode;
    if (nh_.getParam("run_mode", runMode))
    {
        if (runMode == "debug")
        {
            runMode_ = SMRunMode::DEBUG;
        }
        else if (runMode == "release")
        {
            runMode_ = SMRunMode::RELEASE;
        }
        else
        {
            ROS_ERROR("Incorrect run_mode value: %s", runMode.c_str());
        }
    }
    else
    {
        runMode_ = SMRunMode::DEBUG;
    }
}
smacc::ISmaccStateMachine::~ISmaccStateMachine () [virtual]
Definition at line 43 of file smacc_state_machine.cpp.
{
    ROS_INFO("Finishing State Machine");
}
Member Function Documentation
template<typename TOrthogonal > void smacc::ISmaccStateMachine::createOrthogonal () [protected]
Definition at line 52 of file smacc_state_machine_impl.h.
References lockStateMachine(), orthogonals_, smacc::Orthogonal::setStateMachine(), and unlockStateMachine().
Referenced by getCurrentState().
{
    this->lockStateMachine("create orthogonal");
    std::string orthogonalkey = demangledTypeName<TOrthogonal>();
    if (orthogonals_.count(orthogonalkey) == 0)
    {
        auto ret = std::make_shared<TOrthogonal>();
        orthogonals_[orthogonalkey] = dynamic_pointer_cast<
      smacc::Orthogonal>(ret);
        ret->setStateMachine(this);
        ROS_INFO("%s Orthogonal is created", orthogonalkey.c_str());
    }
    else
    {
        ROS_WARN_STREAM("There were already one existing orthogonal of type " << orthogonalkey.c_str() << "
      . Skipping creation orthogonal request. ");
        std::stringstream ss;
        ss << "The existing orthogonals are the following: " << std::endl;
        for (auto &orthogonal : orthogonals_)
        {
            ss << " - " << orthogonal.first << std::endl;
        }
        ROS_WARN_STREAM(ss.str());
    }
    this->unlockStateMachine("create orthogonal");
}
template<typename TSmaccSignal , typename TMemberFunctionPrototype , typename TSmaccObjectType > boost::signals2::connection smacc::ISmaccStateMachine::createSignalConnection (TSmaccSignal & signal, TMemberFunctionPrototype callback, TSmaccObjectType * object)
Definition at line 251 of file smacc_state_machine_impl.h.
References smacc::Bind< arity >::bindaux(), and stateCallbackConnections.
Referenced by getCurrentStateInfo(), ros_timer_client::CbTimerSingleCountdown::onTimerTick(), and ros_timer_client::CbTimerRepeatCountdown::onTimerTick().
{
    static_assert(std::is_base_of<ISmaccState, TSmaccObjectType>::value ||
      std::is_base_of<SmaccClientBehavior, TSmaccObjectType>::value || std::is_base_of<LogicUnit, TSmaccObjectType>::value ||
      std::is_base_of<ISmaccComponent, TSmaccObjectType>::value, "Only are accepted smacc types as subscribers for smacc signals");
    typedef decltype(callback) ft;
    Bind<boost::function_types::function_arity<ft>::value > binder;
    boost::signals2::connection connection = binder.bindaux(signal, callback,object);
    if (std::is_base_of<ISmaccComponent, TSmaccObjectType>::value)
    {
    }
    else // state life-time objects
    {
        ROS_WARN("[StateMachine] life-time constrained smacc signal subscription created");
        stateCallbackConnections.push_back(connection);
    }
    return connection;
}
template<typename TSmaccSignal , typename TMemberFunctionPrototype > boost::signals2::connection smacc::ISmaccStateMachine::createSignalConnection (TSmaccSignal & signal, TMemberFunctionPrototype callback)
Definition at line 271 of file smacc_state_machine_impl.h.
{
    return signal.connect(callback);
    // return signal;
}
void smacc::ISmaccStateMachine::EStop () [virtual]
Reimplemented in smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >, smacc::SmaccStateMachineBase< SmDanceBot, MsDanceBotRunMode >, smacc::SmaccStateMachineBase< SmAtomic, State1 >, smacc::SmaccStateMachineBase< SmThreeSome, StState1 >, and smacc::SmaccStateMachineBase< SmViewerSim, MsRunMode >.
Definition at line 56 of file smacc_state_machine.cpp.
Referenced by smacc::SmaccStateMachineBase< SmViewerSim, MsRunMode >::EStop().
{
}
ISmaccState* smacc::ISmaccStateMachine::getCurrentState () const [inline]
Definition at line 112 of file smacc_state_machine.h.
References createOrthogonal(), currentState_, getParam(), onInitialized(), onInitializing(), param(), and setParam().
Referenced by smacc::SignalDetector::pollOnce().
{ return this->currentState_; }
unsigned long smacc::ISmaccStateMachine::getCurrentStateCounter () const [inline]
Definition at line 110 of file smacc_state_machine.h.
References stateSeqCounter_.
Referenced by smacc::SignalDetector::pollOnce().
{ return this->stateSeqCounter_; }
std::shared_ptr<smacc::SmaccStateInfo> smacc::ISmaccStateMachine::getCurrentStateInfo () [inline]
Definition at line 80 of file smacc_state_machine.h.
References createSignalConnection(), currentStateInfo_, getTransitionLogHistory(), onInitialize(), and publishTransition().
Referenced by smacc::ISmaccState::notifyTransitionFromTransitionTypeInfo().
{ return currentStateInfo_; }
template<typename T > bool smacc::ISmaccStateMachine::getGlobalSMData (std::string name, T & ret)
Definition at line 149 of file smacc_state_machine_impl.h.
References globalData_, and m_mutex_.
Referenced by smacc::ISmaccState::getGlobalSMData(), and mapBehavior().
{
    std::lock_guard<std::recursive_mutex> lock(m_mutex_);
    //ROS_WARN("get SM Data lock acquire");
    bool success = false;
    if (!globalData_.count(name))
    {
        //ROS_WARN("get SM Data - data do not exist");
        success = false;
    }
    else
    {
        //ROS_WARN("get SM DAta -data exist. accessing");
        try
        {
            auto &v = globalData_[name];
            //ROS_WARN("get SM DAta -data exist. any cast");
            ret = boost::any_cast<T>(v.second);
            success = true;
            //ROS_WARN("get SM DAta -data exist. success");
        }
        catch (boost::bad_any_cast &ex)
        {
            ROS_ERROR("bad any cast: %s", ex.what());
            success = false;
        }
    }
    //ROS_WARN("get SM Data lock release");
    return success;
}
template<typename TOrthogonal > TOrthogonal * smacc::ISmaccStateMachine::getOrthogonal ()
Definition at line 19 of file smacc_state_machine_impl.h.
References m_mutex_, and orthogonals_.
Referenced by smacc::ISmaccState::configure().
{
    std::lock_guard<std::recursive_mutex> lock(m_mutex_);
    std::string orthogonalkey = demangledTypeName<TOrthogonal>();
    TOrthogonal* ret;
    auto it = orthogonals_.find(orthogonalkey);
    if (it != orthogonals_.end())
    {
        ROS_INFO("%s resource is required. Found resource in cache.", orthogonalkey.c_str());
        ret = dynamic_cast<TOrthogonal*>(it->second.get());
        return ret;
    }
    else
    {
        std::stringstream ss;
        ss << "Orthogonal not found " << orthogonalkey.c_str() << std::endl;
        ss << "The existing orthogonals are the following: " << std::endl;
        for (auto &orthogonal : orthogonals_)
        {
            ss << " - " << orthogonal.first << std::endl;
        }
        ROS_WARN_STREAM(ss.str());
        return nullptr;
    }
}
const std::map< std::string, std::shared_ptr< smacc::Orthogonal > > & smacc::ISmaccStateMachine::getOrthogonals () const
Definition at line 60 of file smacc_state_machine.cpp.
References orthogonals_.
Referenced by smacc::SmaccStateMachineInfo::assembleSMStructureMessage(), smacc::SignalDetector::findUpdatableBehaviors(), smacc::SignalDetector::findUpdatableClients(), and smacc::ISmaccState::requiresClient().
{
    return this->orthogonals_;
}
template<typename T > bool smacc::ISmaccStateMachine::getParam (std::string param_name, T & param_storage) [protected]
Definition at line 278 of file smacc_state_machine_impl.h.
References nh_.
Referenced by getCurrentState().
{
    return nh_.getParam(param_name, param_storage);
}
std::string smacc::ISmaccStateMachine::getStateMachineName ()
Definition at line 164 of file smacc_state_machine.cpp.
References smacc::demangleSymbol().
{
    return demangleSymbol(typeid(*this).name());
}
void smacc::ISmaccStateMachine::getTransitionLogHistory ()
Referenced by getCurrentStateInfo(), and onInitializing().
bool smacc::ISmaccStateMachine::getTransitionLogHistory (smacc_msgs::SmaccGetTransitionHistory::Request & req, smacc_msgs::SmaccGetTransitionHistory::Response & res)
Definition at line 133 of file smacc_state_machine.cpp.
References transitionLogHistory_.
{
    ROS_WARN("Requesting Transition Log History, current size: %ld", this->
      transitionLogHistory_.size());
    res.history = this->transitionLogHistory_;
    return true;
}
void smacc::ISmaccStateMachine::lockStateMachine (std::string msg)
Definition at line 152 of file smacc_state_machine.cpp.
References m_mutex_.
Referenced by createOrthogonal(), smacc::SignalDetector::pollOnce(), and smacc::SmaccState< SsrFPatternStartLoop, SS >::~SmaccState().
{
    ROS_DEBUG("locking state machine: %s", msg.c_str());
    m_mutex_.lock();
}
template<typename StateField , typename BehaviorType > void smacc::ISmaccStateMachine::mapBehavior ()
Definition at line 204 of file smacc_state_machine_impl.h.
References smacc::demangleSymbol(), getGlobalSMData(), requiresComponent(), and setGlobalSMData().
{
    std::string stateFieldName = demangleSymbol(typeid(StateField).name());
    std::string behaviorType = demangleSymbol(typeid(BehaviorType).name());
    ROS_INFO("Mapping state field '%s' to stateBehavior '%s'", stateFieldName.c_str(), behaviorType.c_str()
      );
    SmaccClientBehavior *globalreference;
    if (!this->getGlobalSMData(stateFieldName, globalreference))
    {
        // Using the requires component approach, we force a unique existence
        // of this component
        BehaviorType *behavior;
        this->requiresComponent(behavior);
        globalreference = dynamic_cast<SmaccClientBehavior *>(behavior);
        this->setGlobalSMData(stateFieldName, globalreference);
    }
}
template<typename StateType > void smacc::ISmaccStateMachine::notifyOnStateEntryEnd (StateType * state)
Definition at line 311 of file smacc_state_machine_impl.h.
References orthogonals_, and updateStatusMessage().
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::SmaccState().
{
    for (auto pair : this->orthogonals_)
    {
        ROS_INFO("ortho onentry: %s", pair.second->getName().c_str());
        auto &orthogonal = pair.second;
        orthogonal->onEntry();
    }
    this->updateStatusMessage();
}
template<typename StateType > void smacc::ISmaccStateMachine::notifyOnStateEntryStart (StateType * state)
Definition at line 298 of file smacc_state_machine_impl.h.
References currentState_, currentStateInfo_, info_, m_mutex_, orthogonals_, and stateSeqCounter_.
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::SmaccState().
{
std:
    lock_guard<std::recursive_mutex> lock(m_mutex_);
    ROS_INFO_STREAM("Notification State Entry, orthogonals:" << this->
      orthogonals_.size() << ", new state " << state);
    stateSeqCounter_++;
    currentState_ = state;
    currentStateInfo_ = info_->getState<StateType>();
}
template<typename StateType > void smacc::ISmaccStateMachine::notifyOnStateExit (StateType * state)
Definition at line 324 of file smacc_state_machine_impl.h.
References currentState_, orthogonals_, and stateCallbackConnections.
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::~SmaccState().
{
    ROS_INFO_STREAM("Notification State Exit: leaving state" << state);
    for (auto pair : this->orthogonals_)
    {
        auto &orthogonal = pair.second;
        orthogonal->onExit();
    }
    for (auto &conn : this->stateCallbackConnections)
    {
        ROS_WARN_STREAM("[StateMachine] Disconnecting scoped-lifetime SmaccSignal subscription");
        conn.disconnect();
    }
    this->stateCallbackConnections.clear();
    currentState_ = nullptr;
}
void smacc::ISmaccStateMachine::onInitialize () [virtual]
this function should be implemented by the user to create the orthogonals
Reimplemented in sm_dance_bot::SmDanceBot, sm_viewer_sim::SmViewerSim, sm_three_some::SmThreeSome, and sm_atomic::SmAtomic.
Definition at line 110 of file smacc_state_machine.cpp.
Referenced by getCurrentStateInfo(), and onInitializing().
{
}
void smacc::ISmaccStateMachine::onInitialized () [protected]
Definition at line 114 of file smacc_state_machine.cpp.
References nh_, state_machine_visualization(), and timer_.
Referenced by getCurrentState(), and smacc::SmaccStateMachineBase< SmViewerSim, MsRunMode >::initiate_impl().
{
    timer_ = nh_.createTimer(ros::Duration(0.5), &
      ISmaccStateMachine::state_machine_visualization, this);
}
void smacc::ISmaccStateMachine::onInitializing (std::string smshortname) [protected]
Definition at line 119 of file smacc_state_machine.cpp.
References getTransitionLogHistory(), nh_, onInitialize(), stateMachinePub_, stateMachineStatusPub_, transitionHistoryService_, and transitionLogPub_.
Referenced by getCurrentState(), and smacc::SmaccStateMachineBase< SmViewerSim, MsRunMode >::initiate_impl().
{
    ROS_WARN_STREAM("State machine base creation:" << shortname);
    // STATE MACHINE TOPICS
    stateMachinePub_ = nh_.advertise<smacc_msgs::SmaccStateMachine>(shortname + "
      /smacc/state_machine_description", 1);
    stateMachineStatusPub_ = nh_.advertise<smacc_msgs::SmaccStatus>(shortname + "
      /smacc/status", 1);
    transitionLogPub_ = nh_.advertise<smacc_msgs::SmaccTransitionLogEntry>(shortname +
      "/smacc/transition_log", 1);
    // STATE MACHINE SERVICES
    transitionHistoryService_ = nh_.advertiseService(shortname + "
      /smacc/transition_log_history", &ISmaccStateMachine::getTransitionLogHistory,
      this);
    this->onInitialize();
}
template<typename T > bool smacc::ISmaccStateMachine::param (std::string param_name, T & param_val, const T & default_val) const [protected]
Definition at line 292 of file smacc_state_machine_impl.h.
References nh_.
Referenced by getCurrentState().
{
    return nh_.param(param_name, param_val, default_val);
}
template<typename EventType > void smacc::ISmaccStateMachine::postEvent (EventType * ev)
Definition at line 123 of file smacc_state_machine_impl.h.
References currentState_, m_mutex_, smacc::SignalDetector::postEvent(), propagateEventToLogicUnits(), and signalDetector_.
Referenced by smacc::ISmaccClient::postEvent(), smacc::ISmaccComponent::postEvent(), smacc::SmaccClientBehavior::postEvent(), and smacc::ISmaccState::postEvent().
{
    std::lock_guard<std::recursive_mutex> lock(m_mutex_);
    // when a postting event is requested by any component, client, or client behavior
    // we reach this place. Now, we propagate the events to all the state logic units to generate
    // some more events
    ROS_DEBUG_STREAM("[PostEvent entry point] " << demangleSymbol<EventType>());
    auto currentstate = currentState_;
    if (currentstate != nullptr)
    {
        propagateEventToLogicUnits(currentstate, ev);
    }
    this->signalDetector_->postEvent(ev);
}
template<typename EventType > void smacc::ISmaccStateMachine::postEvent ()
Definition at line 142 of file smacc_state_machine_impl.h.
{
    auto *ev = new EventType();
    this->postEvent(ev);
}
template<typename EventType > void smacc::ISmaccStateMachine::propagateEventToLogicUnits (ISmaccState * st, EventType * ev) [private]
Definition at line 346 of file smacc_state_machine_impl.h.
References smacc::ISmaccState::getClassName(), smacc::ISmaccState::getLogicUnits(), and smacc::ISmaccState::getParentState().
Referenced by postEvent().
{
    ROS_DEBUG("PROPAGATING EVENT [%s] TO LUs [%s]: ", demangleSymbol<EventType>().c_str(), st->getClassName
      ().c_str());
    for (auto &lu : st->getLogicUnits())
    {
        lu->notifyEvent(ev);
    }
    auto *pst = st->getParentState();
    if (pst != nullptr)
    {
        propagateEventToLogicUnits(pst, ev);
    }
}
void smacc::ISmaccStateMachine::publishTransition (SmaccTransitionInfo & transitionInfo)
Definition at line 100 of file smacc_state_machine.cpp.
References smacc::transitionInfoToMsg(), transitionLogHistory_, and transitionLogPub_.
Referenced by getCurrentStateInfo(), and smacc::ISmaccState::notifyTransitionFromTransitionTypeInfo().
{
    smacc_msgs::SmaccTransitionLogEntry transitionLogEntry;
    transitionLogEntry.timestamp = ros::Time::now();
    transitionInfoToMsg(transitionInfo, transitionLogEntry.transition);
    this->transitionLogHistory_.push_back(transitionLogEntry);
    transitionLogPub_.publish(transitionLogEntry);
}
template<typename SmaccComponentType > void smacc::ISmaccStateMachine::requiresComponent (SmaccComponentType *& storage)
Definition at line 82 of file smacc_state_machine_impl.h.
References smacc::demangleSymbol(), m_mutex_, and orthogonals_.
Referenced by mapBehavior(), smacc::ISmaccState::requiresComponent(), and smacc::SmaccClientBehavior::requiresComponent().
{
    ROS_DEBUG("component %s is required", demangleSymbol(typeid(SmaccComponentType).name()).
      c_str());
    std::lock_guard<std::recursive_mutex> lock(m_mutex_);
    for (Orthogonal *ortho : this->orthogonals_)
    {
        for (auto &client : ortho->getClients())
        {
            storage = client->getComponent<SmaccComponentType>();
            if (storage == nullptr)
            {
                return;
            }
        }
    }
    // std::string componentkey = demangledTypeName<SmaccComponentType>();
    // SmaccComponentType *ret;
    // auto it = components_.find(componentkey);
    // if (it == components_.end())
    // {
    // ROS_DEBUG("%s smacc component is required. Creating a new instance.", componentkey.c_str());
    // ret = new SmaccComponentType();
    // ret->setStateMachine(this);
    // components_[componentkey] = static_cast<smacc::ISmaccComponent *>(ret);
    // ROS_DEBUG("%s resource is required. Done.", componentkey.c_str());
    // }
    // else
    // {
    // ROS_DEBUG("%s resource is required. Found resource in cache.", componentkey.c_str());
    // ret = dynamic_cast<SmaccComponentType *>(it->second);
    // }
    // storage = ret;
}
void smacc::ISmaccStateMachine::Reset () [virtual]
Reimplemented in smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >, smacc::SmaccStateMachineBase< SmDanceBot, MsDanceBotRunMode >, smacc::SmaccStateMachineBase< SmAtomic, State1 >, smacc::SmaccStateMachineBase< SmThreeSome, StState1 >, and smacc::SmaccStateMachineBase< SmViewerSim, MsRunMode >.
Definition at line 48 of file smacc_state_machine.cpp.
Referenced by smacc::SmaccStateMachineBase< SmViewerSim, MsRunMode >::Reset().
{
}
template<typename T > void smacc::ISmaccStateMachine::setGlobalSMData (std::string name, T value)
Definition at line 184 of file smacc_state_machine_impl.h.
References globalData_, m_mutex_, and updateStatusMessage().
Referenced by sm_dance_bot::CbNavigateGlobalPosition::goToRadialStart(), mapBehavior(), and smacc::ISmaccState::setGlobalSMData().
{
    {
        std::lock_guard<std::recursive_mutex> lock(m_mutex_);
        //ROS_WARN("set SM Data lock acquire");
        globalData_[name] = {
            [this, name]() {
                std::stringstream ss;
                auto val = any_cast<T>(globalData_[name].second);
                ss << val;
                return ss.str();
            },
            value};
    }
    this->updateStatusMessage();
}
template<typename T > void smacc::ISmaccStateMachine::setParam (std::string param_name, T param_val) [protected]
Definition at line 285 of file smacc_state_machine_impl.h.
References nh_.
Referenced by getCurrentState().
{
    return nh_.setParam(param_name, param_val);
}
void smacc::ISmaccStateMachine::state_machine_visualization (const ros::TimerEvent &)
Definition at line 140 of file smacc_state_machine.cpp.
References info_, m_mutex_, stateMachinePub_, stateMachineStatusPub_, and status_msg_.
Referenced by onInitialized().
{
    std::lock_guard<std::recursive_mutex> lock(m_mutex_);
    smacc_msgs::SmaccStateMachine state_machine_msg;
    state_machine_msg.states = info_->stateMsgs;
    this->stateMachinePub_.publish(state_machine_msg);
    status_msg_.header.stamp = ros::Time::now();
    this->stateMachineStatusPub_.publish(status_msg_);
}
void smacc::ISmaccStateMachine::Stop () [virtual]
Reimplemented in smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >, smacc::SmaccStateMachineBase< SmDanceBot, MsDanceBotRunMode >, smacc::SmaccStateMachineBase< SmAtomic, State1 >, smacc::SmaccStateMachineBase< SmThreeSome, StState1 >, and smacc::SmaccStateMachineBase< SmViewerSim, MsRunMode >.
Definition at line 52 of file smacc_state_machine.cpp.
Referenced by smacc::SmaccStateMachineBase< SmViewerSim, MsRunMode >::Stop().
{
}
void smacc::ISmaccStateMachine::unlockStateMachine (std::string msg)
Definition at line 158 of file smacc_state_machine.cpp.
References m_mutex_.
Referenced by createOrthogonal(), smacc::SignalDetector::pollOnce(), and smacc::SmaccState< SsrFPatternStartLoop, SS >::~SmaccState().
{
    ROS_DEBUG("unlocking state machine: %s", msg.c_str());
    m_mutex_.unlock();
}
void smacc::ISmaccStateMachine::updateStatusMessage ()
Definition at line 65 of file smacc_state_machine.cpp.
References currentStateInfo_, smacc::DEBUG, globalData_, m_mutex_, runMode_, stateMachineStatusPub_, and status_msg_.
Referenced by notifyOnStateEntryEnd(), and setGlobalSMData().
{
    std::lock_guard<std::recursive_mutex> lock(m_mutex_);
    if (currentStateInfo_ != nullptr)
    {
        ROS_WARN_STREAM("[StateMachine] setting state active "
                        << ": " << currentStateInfo_->getFullPath());
        if (this->runMode_ == SMRunMode::DEBUG)
        {
            status_msg_.current_states.clear();
            std::list<smacc::SmaccStateInfo::Ptr> ancestorList;
            currentStateInfo_->getAncestors(ancestorList);
            for (auto &ancestor : ancestorList)
            {
                status_msg_.current_states.push_back(ancestor->toShortName());
            }
            status_msg_.global_variable_names.clear();
            status_msg_.global_variable_values.clear();
            for (auto entry : this->globalData_)
            {
                status_msg_.global_variable_names.push_back(entry.first);
                status_msg_.global_variable_values.push_back(entry.second.first()); // <- invoke
       to_string()
            }
            status_msg_.header.stamp = ros::Time::now();
            this->stateMachineStatusPub_.publish(
      status_msg_);
        }
    }
}
Friends And Related Function Documentation
friend class ISmaccState [friend]
Definition at line 170 of file smacc_state_machine.h.
Member Data Documentation
ISmaccState* smacc::ISmaccStateMachine::currentState_ [protected]
Definition at line 146 of file smacc_state_machine.h.
Referenced by getCurrentState(), notifyOnStateEntryStart(), notifyOnStateExit(), and postEvent().
std::shared_ptr<smacc::SmaccStateInfo> smacc::ISmaccStateMachine::currentStateInfo_ [protected]
Definition at line 148 of file smacc_state_machine.h.
Referenced by getCurrentStateInfo(), notifyOnStateEntryStart(), and updateStatusMessage().
std::map<std::string, std::pair<std::function<std::string()>, boost::any> > smacc::ISmaccStateMachine::globalData_ [private]
Definition at line 159 of file smacc_state_machine.h.
Referenced by getGlobalSMData(), setGlobalSMData(), and updateStatusMessage().
std::shared_ptr<SmaccStateMachineInfo> smacc::ISmaccStateMachine::info_
Definition at line 176 of file smacc_state_machine.h.
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::getFullPathName(), smacc::SmaccStateMachineBase< SmViewerSim, MsRunMode >::initiate_impl(), notifyOnStateEntryStart(), and state_machine_visualization().
std::recursive_mutex smacc::ISmaccStateMachine::m_mutex_ [private]
Definition at line 156 of file smacc_state_machine.h.
Referenced by getGlobalSMData(), getOrthogonal(), lockStateMachine(), notifyOnStateEntryStart(), postEvent(), requiresComponent(), setGlobalSMData(), state_machine_visualization(), unlockStateMachine(), and updateStatusMessage().
ros::NodeHandle smacc::ISmaccStateMachine::nh_ [protected]
Definition at line 135 of file smacc_state_machine.h.
Referenced by getParam(), ISmaccStateMachine(), onInitialized(), onInitializing(), param(), and setParam().
std::map<std::string, std::shared_ptr<smacc::Orthogonal> > smacc::ISmaccStateMachine::orthogonals_ [protected]
Definition at line 153 of file smacc_state_machine.h.
Referenced by createOrthogonal(), getOrthogonal(), getOrthogonals(), notifyOnStateEntryEnd(), notifyOnStateEntryStart(), notifyOnStateExit(), and requiresComponent().
ros::NodeHandle smacc::ISmaccStateMachine::private_nh_ [protected]
Definition at line 136 of file smacc_state_machine.h.
smacc::SMRunMode smacc::ISmaccStateMachine::runMode_ [private]
Definition at line 163 of file smacc_state_machine.h.
Referenced by ISmaccStateMachine(), and updateStatusMessage().
SignalDetector* smacc::ISmaccStateMachine::signalDetector_ [private]
Definition at line 166 of file smacc_state_machine.h.
Referenced by ISmaccStateMachine(), and postEvent().
std::list<boost::signals2::connection> smacc::ISmaccStateMachine::stateCallbackConnections
Definition at line 95 of file smacc_state_machine.h.
Referenced by createSignalConnection(), and notifyOnStateExit().
ros::Publisher smacc::ISmaccStateMachine::stateMachinePub_ [protected]
Definition at line 139 of file smacc_state_machine.h.
Referenced by onInitializing(), and state_machine_visualization().
ros::Publisher smacc::ISmaccStateMachine::stateMachineStatusPub_ [protected]
Definition at line 140 of file smacc_state_machine.h.
Referenced by onInitializing(), state_machine_visualization(), and updateStatusMessage().
unsigned long smacc::ISmaccStateMachine::stateSeqCounter_ [private]
Definition at line 168 of file smacc_state_machine.h.
Referenced by getCurrentStateCounter(), and notifyOnStateEntryStart().
smacc_msgs::SmaccStatus smacc::ISmaccStateMachine::status_msg_ [protected]
Definition at line 150 of file smacc_state_machine.h.
Referenced by state_machine_visualization(), and updateStatusMessage().
ros::Timer smacc::ISmaccStateMachine::timer_ [protected]
Definition at line 138 of file smacc_state_machine.h.
Referenced by onInitialized().
ros::ServiceServer smacc::ISmaccStateMachine::transitionHistoryService_ [protected]
Definition at line 142 of file smacc_state_machine.h.
Referenced by onInitializing().
std::vector<smacc_msgs::SmaccTransitionLogEntry> smacc::ISmaccStateMachine::transitionLogHistory_ [private]
Definition at line 161 of file smacc_state_machine.h.
Referenced by getTransitionLogHistory(), and publishTransition().
ros::Publisher smacc::ISmaccStateMachine::transitionLogPub_ [protected]
Definition at line 141 of file smacc_state_machine.h.
Referenced by onInitializing(), and publishTransition().
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_state_machine.h
smacc/include/smacc/impl/smacc_state_machine_impl.h
smacc/src/smacc/smacc_state_machine.cpp