smacc::introspection::TypeInfo Class Reference
#include <string_type_walker.h>
Public Types
typedef std::shared_ptr< TypeInfo > Ptr
Public Member Functions
TypeInfo (std::string tkey, std::string codedtype, std::string finaltype)
std::string toString ()
std::string getNonTemplatetypename ()
const std::string & getFullName ()
Static Public Member Functions
static TypeInfo::Ptr getTypeInfoFromString (std::string inputtext)
static TypeInfo::Ptr getTypeInfoFromTypeid (const std::type_info &tid)
template<typename T >
static TypeInfo::Ptr getTypeInfoFromType ()
Public Attributes
std::vector< Ptr > templateParameters
Static Public Attributes
static std::map< std::string, Ptr > typeInfoDatabase
Private Attributes
std::string tkey
std::string codedtype
std::string finaltype
Detailed Description
Definition at line 13 of file string_type_walker.h.
Member Typedef Documentation
typedef std::shared_ptr<TypeInfo> smacc::introspection::TypeInfo::Ptr
Definition at line 16 of file string_type_walker.h.
Constructor & Destructor Documentation
smacc::introspection::TypeInfo::TypeInfo (std::string tkey, std::string codedtype, std::string finaltype) [inline]
Definition at line 20 of file string_type_walker.h.
References codedtype, finaltype, and tkey.
    {
        this->tkey = tkey;
        this->codedtype = codedtype;
        this->finaltype = finaltype;
    }
Member Function Documentation
const std::string& smacc::introspection::TypeInfo::getFullName () [inline]
Definition at line 47 of file string_type_walker.h.
References finaltype.
    {
        return this->finaltype;
    }
std::string smacc::introspection::TypeInfo::getNonTemplatetypename () [inline]
Definition at line 32 of file string_type_walker.h.
References finaltype, getTypeInfoFromString(), and getTypeInfoFromTypeid().
    {
        auto index = this->finaltype.find("<");
        return this->finaltype.substr(0, index);
    }
TypeInfo::Ptr smacc::introspection::TypeInfo::getTypeInfoFromString (std::string inputtext) [static]
Definition at line 61 of file string_type_walker.cpp.
References finaltype, smacc::introspection::replace(), smacc::introspection::replace_back(), tkey, and typeInfoDatabase.
Referenced by getNonTemplatetypename(), getTypeInfoFromTypeid(), and smacc::SmaccState< MsDanceBotRunMode, SmDanceBot, StAcquireSensors >::static_createLogicUnit().
{
    auto it = typeInfoDatabase.find(inputtext);
    if (it != typeInfoDatabase.end())
        return typeInfoDatabase[inputtext];
    bool ok = false;
    int typecount = 0;
    std::string originalinputtext = inputtext;
    std::map<std::string, std::string> typesdict;
    while (!ok)
    {
        //simpletypeRE = r"[^<>,\s]+<[^<>]+>"
        //print ("input: " + inputtext)
        const char *simpletypeRE = "[^\\<\\>,\\s]+\\<[^\\<\\>]+\\>";
        //std::cout << inputtext << std::endl;
        std::smatch matches;
        std::regex regex(simpletypeRE); // matches words beginning by "sub"
        //matches = [m for m in enumerate(re.finditer(simpletypeRE, inputtext))]
        std::regex_search(inputtext, matches, regex);
        // if len(matches) == 0:
        // if len(typesdict) == 0:
        // tkey = "$T" + str(typecount)
        // typesdict[tkey] = inputtext
        // break
        if (matches.size() == 0)
        {
            if (typesdict.size() == 0)
            {
                auto tkey = "$T" + std::to_string(typecount);
                typesdict[tkey] = inputtext;
            }
            break;
        }
        // for i, m in matches:
        // tstr = m.group(0)
        // tkey = "$T" + str(typecount)
        // inputtext = inputtext.replace(tstr, tkey)
        // print("updating input text: " + inputtext)
        // typecount += 1
        // typesdict[tkey] = tstr
        int i = 0;
        for (auto &m : matches)
        {
            std::string tstr = m;
            auto tkey = "$T" + std::to_string(typecount);
            replace(inputtext, tstr, tkey);
            //std::cout << "updating input text:" << inputtext << std::endl;
            typecount++;
            typesdict[tkey] = tstr;
            i++;
        }
    }
    // allbasetypes = set()
    // for tkey in typesdict.keys():
    // flat = typesdict[tkey]
    // print flat
    // startindex = flat.index("<")
    // flat = flat[startindex + 1:-1]
    // basetypes = [t.strip() for t in flat.split(",")]
    // for b in basetypes:
    // if not "$" in b:
    // allbasetypes.add(b)
    std::set<std::string> allbasetypes;
    for (auto &tkey : typesdict)
    {
        auto flat = tkey.second;
        //std::cout << flat << std::endl;
        size_t startindex = flat.find("<");
        size_t endindex = flat.find(">");
        if (startindex != std::string::npos)
        {
            flat = flat.substr(startindex + 1, endindex - startindex - 1);
            std::vector<std::string> basetypes;
            std::istringstream iss(flat);
            std::string token;
            while (std::getline(iss, token, ','))
            {
                boost::trim(token);
                basetypes.push_back(token);
                //std::cout << "base type: " << token << std::endl;
            }
            for (auto &b : basetypes)
            {
                size_t found = b.find("$");
                if (found == std::string::npos)
                {
                    allbasetypes.insert(b);
                }
            }
        }
        // for b in allbasetypes:
        // typesdict[b] = b
        for (auto &b : allbasetypes)
        {
            typesdict[b] = b;
        }
    }
    // types = []
    // for tkey in typesdict:
    // finaltype = replace_back(typesdict[tkey], typesdict)
    // t = TypeInfo(tkey, typesdict[tkey], finaltype)
    // types.append(t)
    // print t
    //std::cout << "---------- TYPES -------" << std::endl;
    std::vector<TypeInfo::Ptr> types;
    
    for (auto t : typesdict)
    {
        //auto t = *it;
        auto &tkey = t.first;
        auto &tval = t.second;
        auto finaltype = replace_back(tval, typesdict);
        auto tinfo = std::make_shared<TypeInfo>(tkey, tval, finaltype);
        types.push_back(tinfo);
        //std::cout << "replacing back: " << finaltype << std::endl;
    }
    TypeInfo::Ptr roottype = nullptr;
    for (auto &t : types)
    {
        if (t->finaltype == originalinputtext)
        {
            roottype = t;
            break;
        }
    }
    std::sort(types.begin(), types.end(),[](auto& a, auto& b)
    {
        return a->getFullName().size() > b->getFullName().size();
    });
    /*
    std::cout<<"types order:" << std::endl;
    for(auto t: types)
    {
        std::cout<< t->codedtype << std::endl;
    }
    std::cout<<"---------" << std::endl;
    std::cout<<"types order:" << std::endl;
    for(auto t: types)
    {
        std::cout<< t->finaltype << std::endl;
    }
    std::cout<<"---------" << std::endl;
    */
    for (auto t: types)
    {
        //auto t = types[it1];
        std::vector<std::pair<int, TypeInfo::Ptr>> unorderedTemplateParameters;
        auto codedtypecopy = t->codedtype;
        //std::cout << "original typestr: " << codedtypecopy << std::endl;
        size_t startindex = codedtypecopy.find("<");
        size_t endindex = codedtypecopy.find(">");
        if (startindex != std::string::npos)
        {
            codedtypecopy = codedtypecopy.substr(startindex + 1, endindex - startindex - 1);
        }
        //std::cout << "original typestr: " << codedtypecopy << std::endl;
        for (auto &t2 : types)
        //for (auto it2= types.size() -1; it2 >=0; it2--)
        {
            //std::cout << it2 << std::endl;
            //auto t2 = types[it2];
            //std::cout << t2->getFullName() << std::endl;
            if (t == t2)
                continue;
            auto index = codedtypecopy.find(t2->tkey);
            if (index != std::string::npos)
            {
                //auto pair = std::make_pair(index, t2);
                auto pair = std::make_pair(0, t2);
                //std::cout << "matches: " << t2->tkey <<std::endl;
                unorderedTemplateParameters.push_back(pair);
                replace(codedtypecopy,t2->tkey,""); // consume token
                //std::cout << "codedtypecopy: " << codedtypecopy << std::endl;
            }
        }
        std::sort(unorderedTemplateParameters.begin(), unorderedTemplateParameters.end(),
                  [](auto &a, auto &b) -> bool {
                      return a.first <= b.first;
                  });
        ROS_DEBUG_STREAM("------------------");
        ROS_DEBUG_STREAM("CREATING TYPE:" << t->getFullName());
        for (auto &item : unorderedTemplateParameters)
        {
            ROS_DEBUG_STREAM(" - template paramter: " << item.second->getFullName());
            t->templateParameters.push_back(item.second);
        }
        ROS_DEBUG_STREAM("------------------");
    }
    ROS_DEBUG_STREAM("ADDING TYPE TO DATABASE: " << inputtext);
    ROS_DEBUG_STREAM("Current Database");
    for (auto &en : typeInfoDatabase)
    {
        ROS_DEBUG_STREAM("- " << en.first);
    }
    typeInfoDatabase[originalinputtext] = roottype;
    return roottype;
}
template<typename T > static TypeInfo::Ptr smacc::introspection::TypeInfo::getTypeInfoFromType () [inline], [static]
Definition at line 42 of file string_type_walker.h.
References getTypeInfoFromTypeid().
    {
        return TypeInfo::getTypeInfoFromTypeid(typeid(T));
    }
TypeInfo::Ptr smacc::introspection::TypeInfo::getTypeInfoFromTypeid (const std::type_info & tid) [static]
Definition at line 56 of file string_type_walker.cpp.
References smacc::introspection::demangleSymbol(), and getTypeInfoFromString().
Referenced by getNonTemplatetypename(), getTypeInfoFromType(), and smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::AddLogicUnitEventType< TTransition >::operator()().
{
    return TypeInfo::getTypeInfoFromString(
      demangleSymbol(tid.name()));
}
std::string smacc::introspection::TypeInfo::toString () [inline]
Definition at line 27 of file string_type_walker.h.
References finaltype, and tkey.
    {
        return this->tkey + ":" + this->finaltype;
    }
Member Data Documentation
std::string smacc::introspection::TypeInfo::codedtype [private]
Definition at line 56 of file string_type_walker.h.
Referenced by TypeInfo().
std::string smacc::introspection::TypeInfo::finaltype [private]
Definition at line 57 of file string_type_walker.h.
Referenced by getFullName(), getNonTemplatetypename(), getTypeInfoFromString(), toString(), and TypeInfo().
std::vector<Ptr> smacc::introspection::TypeInfo::templateParameters
Definition at line 18 of file string_type_walker.h.
std::string smacc::introspection::TypeInfo::tkey [private]
Definition at line 55 of file string_type_walker.h.
Referenced by getTypeInfoFromString(), toString(), and TypeInfo().
std::map< std::string, TypeInfo::Ptr > smacc::introspection::TypeInfo::typeInfoDatabase [static]
Definition at line 52 of file string_type_walker.h.
Referenced by getTypeInfoFromString(), and smacc::introspection::replace_back().
The documentation for this class was generated from the following files:
smacc/include/smacc/introspection/string_type_walker.h
smacc/src/smacc/introspection/string_type_walker.cpp