sm_dance_bot::CbNavigateGlobalPosition Class Reference
#include <cb_navigate_global_position.h>
Public Member Functions
CbNavigateGlobalPosition ()
CbNavigateGlobalPosition (float x, float y, float yaw)
virtual void onEntry ()
void goToRadialStart ()
void readStartPoseFromParameterServer (smacc::ClMoveBaseZ::Goal &goal)
virtual void onExit () override
CbNavigateGlobalPosition ()
CbNavigateGlobalPosition (float x, float y, float yaw)
virtual void onEntry ()
void goToRadialStart ()
void readStartPoseFromParameterServer (smacc::ClMoveBaseZ::Goal &goal)
virtual void onExit () override
Public Attributes
boost::optional< geometry_msgs::Point > initialPoint
boost::optional< float > initialYaw
Private Attributes
smacc::ClMoveBaseZ * moveBaseClient_
odom_tracker::OdomTracker * odomTracker_
Detailed Description
Definition at line 13 of file cb_navigate_global_position.h.
Constructor & Destructor Documentation
sm_dance_bot::CbNavigateGlobalPosition::CbNavigateGlobalPosition () [inline]
Definition at line 19 of file cb_navigate_global_position.h.
  {
  }
sm_dance_bot::CbNavigateGlobalPosition::CbNavigateGlobalPosition (float x, float y, float yaw) [inline]
Definition at line 23 of file cb_navigate_global_position.h.
  {
    auto p = geometry_msgs::Point();
    p.x = x;
    p.y = y;
    initialPoint = p;
    initialYaw = yaw;
  }
sm_dance_bot::CbNavigateGlobalPosition::CbNavigateGlobalPosition () [inline]
Definition at line 19 of file cb_navigate_global_position.h.
  {
  }
sm_dance_bot::CbNavigateGlobalPosition::CbNavigateGlobalPosition (float x, float y, float yaw) [inline]
Definition at line 23 of file cb_navigate_global_position.h.
  {
    auto p = geometry_msgs::Point();
    p.x = x;
    p.y = y;
    initialPoint = p;
    initialYaw = yaw;
  }
Member Function Documentation
void sm_dance_bot::CbNavigateGlobalPosition::goToRadialStart () [inline]
Definition at line 50 of file cb_navigate_global_position.h.
References moveBaseClient_, readStartPoseFromParameterServer(), smacc::SmaccActionClientBase< ActionType >::sendGoal(), smacc::ISmaccStateMachine::setGlobalSMData(), and smacc::SmaccClientBehavior::stateMachine.
Referenced by onEntry().
  {
    ROS_INFO("Sending Goal to MoveBase");
    smacc::ClMoveBaseZ::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    readStartPoseFromParameterServer(goal);
    // store the start pose on the state machine storage so that it can
    // be referenced from other states (for example return to radial start)
    this->stateMachine->setGlobalSMData("radial_start_pose", goal.target_pose);
    moveBaseClient_->sendGoal(goal);
  }
void sm_dance_bot::CbNavigateGlobalPosition::goToRadialStart () [inline]
Definition at line 50 of file cb_navigate_global_position.h.
References moveBaseClient_, readStartPoseFromParameterServer(), smacc::SmaccActionClientBase< ActionType >::sendGoal(), smacc::ISmaccStateMachine::setGlobalSMData(), and smacc::SmaccClientBehavior::stateMachine.
  {
    ROS_INFO("Sending Goal to MoveBase");
    smacc::ClMoveBaseZ::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    readStartPoseFromParameterServer(goal);
    // store the start pose on the state machine storage so that it can
    // be referenced from other states (for example return to radial start)
    this->stateMachine->setGlobalSMData("radial_start_pose", goal.target_pose);
    moveBaseClient_->sendGoal(goal);
  }
virtual void sm_dance_bot::CbNavigateGlobalPosition::onEntry () [inline], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 32 of file cb_navigate_global_position.h.
References goToRadialStart(), moveBaseClient_, odomTracker_, smacc::ClMoveBaseZ::plannerSwitcher_, odom_tracker::RECORD_PATH_FORWARD, smacc::SmaccClientBehavior::requiresClient(), smacc::SmaccClientBehavior::requiresComponent(), and odom_tracker::OdomTracker::setWorkingMode().
  {
    ROS_INFO("Entering Navigate Global position");
    // this substate will need access to the "MoveBase" resource or plugin. In this line
    // you get the reference to this resource.
    this->requiresClient(moveBaseClient_);
    this->requiresComponent(odomTracker_);
    ROS_INFO("Component requirements completed");
    moveBaseClient_->plannerSwitcher_->setDefaultPlanners();
    this->odomTracker_->setWorkingMode(
      odom_tracker::WorkingMode::RECORD_PATH_FORWARD);
    goToRadialStart();
  }
virtual void sm_dance_bot::CbNavigateGlobalPosition::onEntry () [inline], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 32 of file cb_navigate_global_position.h.
References goToRadialStart(), moveBaseClient_, odomTracker_, smacc::ClMoveBaseZ::plannerSwitcher_, odom_tracker::RECORD_PATH_FORWARD, smacc::SmaccClientBehavior::requiresClient(), smacc::SmaccClientBehavior::requiresComponent(), and odom_tracker::OdomTracker::setWorkingMode().
  {
    ROS_INFO("Entering Navigate Global position");
    // this substate will need access to the "MoveBase" resource or plugin. In this line
    // you get the reference to this resource.
    this->requiresClient(moveBaseClient_);
    this->requiresComponent(odomTracker_);
    ROS_INFO("Component requirements completed");
    moveBaseClient_->plannerSwitcher_->setDefaultPlanners();
    this->odomTracker_->setWorkingMode(
      odom_tracker::WorkingMode::RECORD_PATH_FORWARD);
    goToRadialStart();
  }
virtual void sm_dance_bot::CbNavigateGlobalPosition::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 87 of file cb_navigate_global_position.h.
  {
    ROS_INFO("Exiting move goal Action Client");
  }
virtual void sm_dance_bot::CbNavigateGlobalPosition::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 87 of file cb_navigate_global_position.h.
References moveBaseClient_, and odomTracker_.
  {
    ROS_INFO("Exiting move goal Action Client");
  }
void sm_dance_bot::CbNavigateGlobalPosition::readStartPoseFromParameterServer (smacc::ClMoveBaseZ::Goal & goal) [inline]
Definition at line 65 of file cb_navigate_global_position.h.
References smacc::SmaccClientBehavior::currentState, smacc::ISmaccState::getParam(), and initialPoint.
Referenced by goToRadialStart().
  {
    if (!initialPoint)
    {
      this->currentState->getParam("start_position_x", goal.target_pose.pose.position.x
      );
      this->currentState->getParam("start_position_y", goal.target_pose.pose.position.y
      );
      double yaw;
      this->currentState->getParam("start_position_yaw", yaw);
      goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(yaw);
    }
    else
    {
      goal.target_pose.pose.position = *initialPoint;
      goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(*
      initialYaw);
    }
    ROS_INFO_STREAM("start position read from parameter server: " << goal.target_pose.pose.position);
  }
void sm_dance_bot::CbNavigateGlobalPosition::readStartPoseFromParameterServer (smacc::ClMoveBaseZ::Goal & goal) [inline]
Definition at line 65 of file cb_navigate_global_position.h.
References smacc::SmaccClientBehavior::currentState, smacc::ISmaccState::getParam(), and initialPoint.
  {
    if (!initialPoint)
    {
      this->currentState->getParam("start_position_x", goal.target_pose.pose.position.x
      );
      this->currentState->getParam("start_position_y", goal.target_pose.pose.position.y
      );
      double yaw;
      this->currentState->getParam("start_position_yaw", yaw);
      goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(yaw);
    }
    else
    {
      goal.target_pose.pose.position = *initialPoint;
      goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(*
      initialYaw);
    }
    ROS_INFO_STREAM("start position read from parameter server: " << goal.target_pose.pose.position);
  }
Member Data Documentation
boost::optional< geometry_msgs::Point > sm_dance_bot::CbNavigateGlobalPosition::initialPoint
Definition at line 16 of file cb_navigate_global_position.h.
Referenced by readStartPoseFromParameterServer().
boost::optional< float > sm_dance_bot::CbNavigateGlobalPosition::initialYaw
Definition at line 17 of file cb_navigate_global_position.h.
smacc::ClMoveBaseZ * sm_dance_bot::CbNavigateGlobalPosition::moveBaseClient_ [private]
Definition at line 95 of file cb_navigate_global_position.h.
Referenced by goToRadialStart(), onEntry(), and onExit().
odom_tracker::OdomTracker * sm_dance_bot::CbNavigateGlobalPosition::odomTracker_ [private]
Definition at line 97 of file cb_navigate_global_position.h.
Referenced by onEntry(), and onExit().
The documentation for this class was generated from the following file:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_navigate_global_position.h