sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition Class Reference
#include <cb_navigate_global_position.h>
Public Member Functions
CbNavigateGlobalPosition ()
CbNavigateGlobalPosition (float x, float y, float yaw)
virtual void onEntry ()
void goToRadialStart ()
void readStartPoseFromParameterServer (smacc::ClMoveBaseZ::Goal &goal)
virtual void onExit () override
Public Attributes
boost::optional< geometry_msgs::Point > initialPoint
boost::optional< float > initialYaw
Private Attributes
smacc::ClMoveBaseZ * moveBaseClient_
Detailed Description
Definition at line 15 of file cb_navigate_global_position.h.
Constructor & Destructor Documentation
sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::CbNavigateGlobalPosition () [inline]
Definition at line 21 of file cb_navigate_global_position.h.
  {
  }
sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::CbNavigateGlobalPosition (float x, float y, float yaw) [inline]
Definition at line 25 of file cb_navigate_global_position.h.
  {
    auto p = geometry_msgs::Point();
    p.x = x;
    p.y = y;
    initialPoint = p;
    initialYaw = yaw;
  }
Member Function Documentation
void sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::goToRadialStart () [inline]
Definition at line 52 of file cb_navigate_global_position.h.
References moveBaseClient_, readStartPoseFromParameterServer(), smacc::SmaccActionClientBase< ActionType >::sendGoal(), smacc::ISmaccStateMachine::setGlobalSMData(), and smacc::SmaccClientBehavior::stateMachine_.
Referenced by onEntry().
  {
    ROS_INFO("Sending Goal to MoveBase");
    smacc::ClMoveBaseZ::Goal goal;
    goal.target_pose.header.frame_id = "/odom";
    goal.target_pose.header.stamp = ros::Time::now();
    readStartPoseFromParameterServer(goal);
    // store the start pose on the state machine storage so that it can
    // be referenced from other states (for example return to radial start)
    this->stateMachine_->setGlobalSMData("radial_start_pose", goal.target_pose)
      ;
    moveBaseClient_->sendGoal(goal);
  }
virtual void sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::onEntry () [inline], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 34 of file cb_navigate_global_position.h.
References smacc::ISmaccClient::getComponent(), goToRadialStart(), moveBaseClient_, smacc::ClMoveBaseZ::plannerSwitcher_, odom_tracker::RECORD_PATH_FORWARD, and smacc::SmaccClientBehavior::requiresClient().
  {
    ROS_INFO("Entering Navigate Global position");
    // this substate will need access to the "MoveBase" resource or plugin. In this line
    // you get the reference to this resource.
    this->requiresClient(moveBaseClient_);
    auto *odomTracker = moveBaseClient_->getComponent<
      odom_tracker::OdomTracker>();
    ROS_INFO("Component requirements completed");
    moveBaseClient_->plannerSwitcher_->setDefaultPlanners();
    odomTracker->setWorkingMode(odom_tracker::WorkingMode::RECORD_PATH_FORWARD
      );
    goToRadialStart();
  }
virtual void sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::onExit () [inline], [override], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 89 of file cb_navigate_global_position.h.
  {
    ROS_INFO("Exiting move goal Action Client");
  }
void sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::readStartPoseFromParameterServer (smacc::ClMoveBaseZ::Goal & goal) [inline]
Definition at line 67 of file cb_navigate_global_position.h.
References smacc::SmaccClientBehavior::currentState, smacc::ISmaccState::getParam(), and initialPoint.
Referenced by goToRadialStart().
  {
    if (!initialPoint)
    {
      this->currentState->getParam("start_position_x", goal.target_pose.pose.position.x
      );
      this->currentState->getParam("start_position_y", goal.target_pose.pose.position.y
      );
      double yaw;
      this->currentState->getParam("start_position_yaw", yaw);
      goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(yaw);
    }
    else
    {
      goal.target_pose.pose.position = *initialPoint;
      goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(*
      initialYaw);
    }
    ROS_INFO_STREAM("start position read from parameter server: " << goal.target_pose.pose.position);
  }
Member Data Documentation
boost::optional<geometry_msgs::Point> sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::initialPoint
Definition at line 18 of file cb_navigate_global_position.h.
Referenced by readStartPoseFromParameterServer().
boost::optional<float> sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::initialYaw
Definition at line 19 of file cb_navigate_global_position.h.
smacc::ClMoveBaseZ* sm_dance_bot::move_base_z_client::CbNavigateGlobalPosition::moveBaseClient_ [private]
Definition at line 97 of file cb_navigate_global_position.h.
Referenced by goToRadialStart(), and onEntry().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/clients/move_base_z_client/client_behaviors/cb_navigate_global_position.h