smacc_viewer.xdot.xdot.Shape Class Reference
Public Member Functions
def __init__ (self)
def draw (self, cr, highlight=False)
def select_pen (self, highlight)
Public Attributes
highlight_pen
Detailed Description
Abstract base class for all the drawing shapes.
Definition at line 75 of file xdot.py.
Constructor & Destructor Documentation
def smacc_viewer.xdot.xdot.Shape.__init__ (self)
Definition at line 78 of file xdot.py.
    def __init__(self):
        pass
Member Function Documentation
def smacc_viewer.xdot.xdot.Shape.draw (self, cr, highlight = False)
Draw this shape with the given cairo context
Definition at line 81 of file xdot.py.
    def draw(self, cr, highlight=False):
        """Draw this shape with the given cairo context"""
        raise NotImplementedError
def smacc_viewer.xdot.xdot.Shape.select_pen (self, highlight)
Definition at line 85 of file xdot.py.
Referenced by smacc_viewer.xdot.xdot_qt.TextShape.draw(), smacc_viewer.xdot.xdot_qt.EllipseShape.draw(), smacc_viewer.xdot.xdot_qt.PolygonShape.draw(), smacc_viewer.xdot.xdot_qt.LineShape.draw(), smacc_viewer.xdot.xdot.EllipseShape.draw(), smacc_viewer.xdot.xdot_qt.BezierShape.draw(), smacc_viewer.xdot.xdot.PolygonShape.draw(), smacc_viewer.xdot.xdot.LineShape.draw(), and smacc_viewer.xdot.xdot.BezierShape.draw().
    def select_pen(self, highlight):
        if highlight:
            if not hasattr(self, 'highlight_pen'):
                self.highlight_pen = self.pen.highlighted()
            return self.highlight_pen
        else:
            return self.pen
Member Data Documentation
smacc_viewer.xdot.xdot.Shape.highlight_pen
Definition at line 88 of file xdot.py.
The documentation for this class was generated from the following file:
smacc_viewer/src/smacc_viewer/xdot/xdot.py