SbUndoPathBackwards Class Reference
#include <sb_undo_path_backwards.h>
Private Member Functions
virtual void onEntry () override
Private Attributes
tf::TransformListener listener
smacc::SmaccMoveBaseActionClient * moveBaseClient_
smacc_odom_tracker::OdomTracker * odomTracker_
smacc_planner_switcher::PlannerSwitcher * plannerSwitcher_
Additional Inherited Members
Detailed Description
Definition at line 8 of file sb_undo_path_backwards.h.
Member Function Documentation
virtual void SbUndoPathBackwards::onEntry () [inline], [override], [private], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 18 of file sb_undo_path_backwards.h.
References smacc_odom_tracker::CLEAR_PATH_BACKWARD, smacc_odom_tracker::OdomTracker::getPath(), smacc::SmaccSubStateBehavior::requiresComponent(), smacc::SmaccActionClientBase< ActionType >::sendGoal(), smacc_planner_switcher::PlannerSwitcher::setBackwardPlanner(), and smacc_odom_tracker::OdomTracker::setWorkingMode().
  {
    this->requiresComponent(moveBaseClient_ ,ros::NodeHandle("move_base"));
    this->requiresComponent(odomTracker_);
    this->requiresComponent(plannerSwitcher_ , ros::NodeHandle("move_base"
      ));
    nav_msgs::Path forwardpath = this->odomTracker_->getPath();
    this->odomTracker_->setWorkingMode(
      smacc_odom_tracker::WorkingMode::CLEAR_PATH_BACKWARD);
    
    smacc::SmaccMoveBaseActionClient::Goal goal;
    if (forwardpath.poses.size()>0)
    {
      goal.target_pose = forwardpath.poses.front();
      this->plannerSwitcher_->setBackwardPlanner();
      moveBaseClient_->sendGoal(goal);
    }
  }
Member Data Documentation
tf::TransformListener SbUndoPathBackwards::listener [private]
Definition at line 10 of file sb_undo_path_backwards.h.
smacc::SmaccMoveBaseActionClient* SbUndoPathBackwards::moveBaseClient_ [private]
Definition at line 12 of file sb_undo_path_backwards.h.
smacc_odom_tracker::OdomTracker* SbUndoPathBackwards::odomTracker_ [private]
Definition at line 14 of file sb_undo_path_backwards.h.
smacc_planner_switcher::PlannerSwitcher* SbUndoPathBackwards::plannerSwitcher_ [private]
Definition at line 16 of file sb_undo_path_backwards.h.
The documentation for this class was generated from the following file:
smacc_sm_examples/sm_dance_bot/include/sm_dance_bot/substate_behaviors/navigation/sb_undo_path_backwards.h