SbNavigateBackwards Class Reference
#include <sb_navigate_backward.h>
Public Member Functions
SbNavigateBackwards (float backwardDistance)
SbNavigateBackwards ()
virtual void onEntry () override
virtual bool onExit ()
Public Attributes
boost::optional< float > backwardDistance
boost::optional< float > backwardSpeed
tf::TransformListener listener
smacc::SmaccMoveBaseActionClient * moveBaseClient_
smacc_odom_tracker::OdomTracker * odomTracker_
smacc_planner_switcher::PlannerSwitcher * plannerSwitcher_
Detailed Description
Definition at line 10 of file sb_navigate_backward.h.
Constructor & Destructor Documentation
SbNavigateBackwards::SbNavigateBackwards (float backwardDistance) [inline]
Definition at line 26 of file sb_navigate_backward.h.
References backwardDistance.
    {
        if(backwardDistance <0)
        {
            ROS_ERROR("sb backward: distance must be greater or equal than 0");
            this->backwardDistance = 0;
        }
        this->backwardDistance = backwardDistance;
    }
SbNavigateBackwards::SbNavigateBackwards () [inline]
Definition at line 36 of file sb_navigate_backward.h.
    {
    }
Member Function Documentation
virtual void SbNavigateBackwards::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 40 of file sb_navigate_backward.h.
References backwardDistance, smacc_odom_tracker::OdomTracker::clearPath(), smacc::SmaccSubStateBehavior::currentState, smacc::ISmaccState::param(), smacc_odom_tracker::RECORD_PATH_FORWARD, smacc::SmaccSubStateBehavior::requiresComponent(), smacc::SmaccActionClientBase< ActionType >::sendGoal(), smacc_planner_switcher::PlannerSwitcher::setBackwardPlanner(), smacc_odom_tracker::OdomTracker::setStartPoint(), and smacc_odom_tracker::OdomTracker::setWorkingMode().
    {
        // straight motion distance
        double dist;
        if (!backwardDistance)
        {
            this->currentState->param("straight_motion_distance", dist, 3.5);
        }
        else
        {
            dist = *backwardDistance;
        }
        ROS_INFO_STREAM("Straight motion distance: " << dist);
        this->requiresComponent(moveBaseClient_, ros::NodeHandle("move_base
      "));
        
        this->requiresComponent(odomTracker_);
        this->requiresComponent(plannerSwitcher_, ros::NodeHandle("
      move_base"));
        //this should work better with a coroutine and await
        ros::Rate rate(10.0);
        tf::StampedTransform currentPose;
        while (ros::ok())
        {
            try
            {
                listener.lookupTransform("/odom", "/base_link",
                                         ros::Time(0), currentPose);
                break;
            }
            catch (tf::TransformException ex)
            {
                ROS_ERROR("%s", ex.what());
                ros::Duration(1.0).sleep();
            }
        }
        tf::Transform forwardDeltaTransform;
        forwardDeltaTransform.setIdentity();
        forwardDeltaTransform.setOrigin(tf::Vector3(-dist, 0, 0));
        tf::Transform targetPose = currentPose * forwardDeltaTransform;
        smacc::SmaccMoveBaseActionClient::Goal goal;
        goal.target_pose.header.frame_id = "/odom";
        goal.target_pose.header.stamp = ros::Time::now();
        tf::poseTFToMsg(targetPose, goal.target_pose.pose);
        ROS_INFO_STREAM("TARGET POSE FORWARD: " << goal.target_pose.pose);
        ros::Duration(10).sleep();
        this->odomTracker_->clearPath();
        geometry_msgs::PoseStamped currentPoseMsg;
        currentPoseMsg.header.frame_id = "/odom";
        currentPoseMsg.header.stamp = ros::Time::now();
        tf::poseTFToMsg(currentPose, currentPoseMsg.pose);
        this->odomTracker_->setStartPoint(currentPoseMsg);
        this->odomTracker_->setWorkingMode(
      smacc_odom_tracker::WorkingMode::RECORD_PATH_FORWARD);
        this->plannerSwitcher_->setBackwardPlanner();
        moveBaseClient_->sendGoal(goal);
    }
virtual bool SbNavigateBackwards::onExit () [inline], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 108 of file sb_navigate_backward.h.
References smacc_odom_tracker::IDLE, and smacc_odom_tracker::OdomTracker::setWorkingMode().
    {
        this->odomTracker_->setWorkingMode(
      smacc_odom_tracker::WorkingMode::IDLE);
    }
Member Data Documentation
boost::optional<float> SbNavigateBackwards::backwardDistance
Definition at line 13 of file sb_navigate_backward.h.
Referenced by onEntry(), and SbNavigateBackwards().
boost::optional<float> SbNavigateBackwards::backwardSpeed
Definition at line 16 of file sb_navigate_backward.h.
tf::TransformListener SbNavigateBackwards::listener
Definition at line 18 of file sb_navigate_backward.h.
smacc::SmaccMoveBaseActionClient* SbNavigateBackwards::moveBaseClient_
Definition at line 20 of file sb_navigate_backward.h.
smacc_odom_tracker::OdomTracker* SbNavigateBackwards::odomTracker_
Definition at line 22 of file sb_navigate_backward.h.
smacc_planner_switcher::PlannerSwitcher* SbNavigateBackwards::plannerSwitcher_
Definition at line 24 of file sb_navigate_backward.h.
The documentation for this class was generated from the following file:
smacc_sm_examples/sm_dance_bot/include/sm_dance_bot/substate_behaviors/navigation/sb_navigate_backward.h