smacc::KeyboardClient Class Reference
#include <keyboard_client.h>
Public Member Functions
KeyboardClient ()
virtual ~KeyboardClient ()
virtual void initialize (std::string topicName, int queueSize) override
void onKeyboardMessage (const std_msgs::UInt16 &unicode_keychar)
template<typename TEv >
void postKeyEvent ()
Public Attributes
boost::signals2::signal< void(char keypress)> OnKeyPress
boost::signals2::scoped_connection c_
Private Attributes
bool initialized_
Additional Inherited Members
Detailed Description
Definition at line 153 of file keyboard_client.h.
Constructor & Destructor Documentation
smacc::KeyboardClient::KeyboardClient () [inline]
Definition at line 159 of file keyboard_client.h.
        {
                initialized_ = false;
        }
virtual smacc::KeyboardClient::~KeyboardClient () [inline], [virtual]
Definition at line 164 of file keyboard_client.h.
        {
        }
Member Function Documentation
virtual void smacc::KeyboardClient::initialize (std::string topicName, int queueSize) [inline], [override], [virtual]
Reimplemented from smacc::SmaccTopicSubscriberClient< std_msgs::UInt16 >.
Definition at line 169 of file keyboard_client.h.
References keyboard_node::msg.
Referenced by smacc::SbKeyboard::onEntry().
        {
                SmaccTopicSubscriberClient<std_msgs::UInt16>::initialize
      (topicName, queueSize);
                if(!this->initialized_)
                {
                        c_ = this->onMessageReceived.connect([this](auto
      msg) {
                                this->onKeyboardMessage(msg);
                        this->initialized_ = true;
                }
                );
                }
        }
void smacc::KeyboardClient::onKeyboardMessage (const std_msgs::UInt16 & unicode_keychar) [inline]
Definition at line 184 of file keyboard_client.h.
        {
                char character = (char)unicode_keychar.data;
                ROS_WARN("detected keyboard: %c", character);
                if (character == 'a')
                        postKeyEvent<EvKeyPressA<KeyboardClient>>();
                else if (character == 'b')
                        postKeyEvent<EvKeyPressB<KeyboardClient>>();
                else if (character == 'c')
                        postKeyEvent<EvKeyPressC<KeyboardClient>>();
                else if (character == 'd')
                        postKeyEvent<EvKeyPressD<KeyboardClient>>();
                else if (character == 'e')
                        postKeyEvent<EvKeyPressE<KeyboardClient>>();
                else if (character == 'f')
                        postKeyEvent<EvKeyPressF<KeyboardClient>>();
                else if (character == 'g')
                        postKeyEvent<EvKeyPressG<KeyboardClient>>();
                else if (character == 'h')
                        postKeyEvent<EvKeyPressH<KeyboardClient>>();
                else if (character == 'y')
                        postKeyEvent<EvKeyPressI<KeyboardClient>>();
                else if (character == 'j')
                        postKeyEvent<EvKeyPressJ<KeyboardClient>>();
                else if (character == 'k')
                        postKeyEvent<EvKeyPressK<KeyboardClient>>();
                else if (character == 'l')
                        postKeyEvent<EvKeyPressL<KeyboardClient>>();
                else if (character == 'm')
                        postKeyEvent<EvKeyPressM<KeyboardClient>>();
                else if (character == 'n')
                        postKeyEvent<EvKeyPressN<KeyboardClient>>();
                else if (character == 'o')
                        postKeyEvent<EvKeyPressO<KeyboardClient>>();
                else if (character == 'p')
                        postKeyEvent<EvKeyPressP<KeyboardClient>>();
                else if (character == 'q')
                        postKeyEvent<EvKeyPressQ<KeyboardClient>>();
                else if (character == 'r')
                        postKeyEvent<EvKeyPressR<KeyboardClient>>();
                else if (character == 's')
                        postKeyEvent<EvKeyPressS<KeyboardClient>>();
                else if (character == 't')
                        postKeyEvent<EvKeyPressT<KeyboardClient>>();
                else if (character == 'u')
                        postKeyEvent<EvKeyPressU<KeyboardClient>>();
                else if (character == 'v')
                        postKeyEvent<EvKeyPressV<KeyboardClient>>();
                else if (character == 'w')
                        postKeyEvent<EvKeyPressW<KeyboardClient>>();
                else if (character == 'x')
                        postKeyEvent<EvKeyPressX<KeyboardClient>>();
                else if (character == 'y')
                        postKeyEvent<EvKeyPressY<KeyboardClient>>();
                else if (character == 'z')
                        postKeyEvent<EvKeyPressZ<KeyboardClient>>();
                OnKeyPress(character);
        }
template<typename TEv > void smacc::KeyboardClient::postKeyEvent () [inline]
Definition at line 246 of file keyboard_client.h.
References demangleSymbol().
        {
                ROS_WARN("KeyboardClient ev: %s", demangleSymbol(typeid(TEv).name()).c_str())
      ;
                auto event = new TEv();
                this->postEvent(event);
        }
Member Data Documentation
boost::signals2::scoped_connection smacc::KeyboardClient::c_
Definition at line 157 of file keyboard_client.h.
bool smacc::KeyboardClient::initialized_ [private]
Definition at line 254 of file keyboard_client.h.
boost::signals2::signal<void(char keypress)> smacc::KeyboardClient::OnKeyPress
Definition at line 156 of file keyboard_client.h.
Referenced by smacc::SbKeyboard::onEntry().
The documentation for this class was generated from the following file:
smacc_sm_examples/sm_dance_bot/include/sm_dance_bot/substate_behaviors/keyboard/keyboard_client.h