sm_three_some::CbKeyboard Class Reference
#include <cb_keyboard_behavior.h>
Public Member Functions
void onEntry ()
template<typename TDerived , typename TObjectTag >
void assignToOrthogonal ()
void OnKeyPress (char character)
template<typename TEv >
void postKeyEvent ()
Public Attributes
KeyboardClient * keyboardClient_
boost::signals2::scoped_connection c_
std::function< void(char)> postEventKeyPress
Detailed Description
Definition at line 10 of file cb_keyboard_behavior.h.
Member Function Documentation
template<typename TDerived , typename TObjectTag > void sm_three_some::CbKeyboard::assignToOrthogonal () [inline]
Definition at line 29 of file cb_keyboard_behavior.h.
        {
                postEventKeyPress = [=](char character) {
                        if (character == 'a')
                                postKeyEvent<EvKeyPressA<CbKeyboard, TObjectTag>>();
                        else if (character == 'b')
                                postKeyEvent<EvKeyPressB<CbKeyboard, TObjectTag>>();
                        else if (character == 'c')
                                postKeyEvent<EvKeyPressC<CbKeyboard, TObjectTag>>();
                        else if (character == 'd')
                                postKeyEvent<EvKeyPressD<CbKeyboard, TObjectTag>>();
                        else if (character == 'e')
                                postKeyEvent<EvKeyPressE<CbKeyboard, TObjectTag>>();
                        else if (character == 'f')
                                postKeyEvent<EvKeyPressF<CbKeyboard, TObjectTag>>();
                        else if (character == 'g')
                                postKeyEvent<EvKeyPressG<CbKeyboard, TObjectTag>>();
                        else if (character == 'h')
                                postKeyEvent<EvKeyPressH<CbKeyboard, TObjectTag>>();
                        else if (character == 'y')
                                postKeyEvent<EvKeyPressI<CbKeyboard, TObjectTag>>();
                        else if (character == 'j')
                                postKeyEvent<EvKeyPressJ<CbKeyboard, TObjectTag>>();
                        else if (character == 'k')
                                postKeyEvent<EvKeyPressK<CbKeyboard, TObjectTag>>();
                        else if (character == 'l')
                                postKeyEvent<EvKeyPressL<CbKeyboard, TObjectTag>>();
                        else if (character == 'm')
                                postKeyEvent<EvKeyPressM<CbKeyboard, TObjectTag>>();
                        else if (character == 'n')
                                postKeyEvent<EvKeyPressN<CbKeyboard, TObjectTag>>();
                        else if (character == 'o')
                                postKeyEvent<EvKeyPressO<CbKeyboard, TObjectTag>>();
                        else if (character == 'p')
                                postKeyEvent<EvKeyPressP<CbKeyboard, TObjectTag>>();
                        else if (character == 'q')
                                postKeyEvent<EvKeyPressQ<CbKeyboard, TObjectTag>>();
                        else if (character == 'r')
                                postKeyEvent<EvKeyPressR<CbKeyboard, TObjectTag>>();
                        else if (character == 's')
                                postKeyEvent<EvKeyPressS<CbKeyboard, TObjectTag>>();
                        else if (character == 't')
                                postKeyEvent<EvKeyPressT<CbKeyboard, TObjectTag>>();
                        else if (character == 'u')
                                postKeyEvent<EvKeyPressU<CbKeyboard, TObjectTag>>();
                        else if (character == 'v')
                                postKeyEvent<EvKeyPressV<CbKeyboard, TObjectTag>>();
                        else if (character == 'w')
                                postKeyEvent<EvKeyPressW<CbKeyboard, TObjectTag>>();
                        else if (character == 'x')
                                postKeyEvent<EvKeyPressX<CbKeyboard, TObjectTag>>();
                        else if (character == 'y')
                                postKeyEvent<EvKeyPressY<CbKeyboard, TObjectTag>>();
                        else if (character == 'z')
                                postKeyEvent<EvKeyPressZ<CbKeyboard, TObjectTag>>();
                };
        }
void sm_three_some::CbKeyboard::onEntry () [inline], [virtual]
Reimplemented from smacc::SmaccClientBehavior.
Definition at line 16 of file cb_keyboard_behavior.h.
References OnKeyPress(), sm_three_some::KeyboardClient::OnKeyPress, and smacc::SmaccClientBehavior::requiresClient().
        {
                this->requiresClient(keyboardClient_);
                c_ = this->keyboardClient_->OnKeyPress.connect(
                    [this](char character) {
                            this->OnKeyPress(character);
                    });
        }
void sm_three_some::CbKeyboard::OnKeyPress (char character) [inline]
Definition at line 87 of file cb_keyboard_behavior.h.
References postEventKeyPress.
Referenced by onEntry().
        {
                postEventKeyPress(character);
        }
template<typename TEv > void sm_three_some::CbKeyboard::postKeyEvent () [inline]
Definition at line 93 of file cb_keyboard_behavior.h.
References smacc::demangleSymbol(), and smacc::SmaccClientBehavior::postEvent().
        {
                ROS_WARN("CbKeyboard %ld ev: %s", (long)(void *)this,
      smacc::demangleSymbol(typeid(TEv).name()).c_str());
                auto event = new TEv();
                this->postEvent(event);
        }
Member Data Documentation
boost::signals2::scoped_connection sm_three_some::CbKeyboard::c_
Definition at line 14 of file cb_keyboard_behavior.h.
KeyboardClient* sm_three_some::CbKeyboard::keyboardClient_
Definition at line 13 of file cb_keyboard_behavior.h.
std::function<void(char)> sm_three_some::CbKeyboard::postEventKeyPress
Definition at line 26 of file cb_keyboard_behavior.h.
Referenced by OnKeyPress().
The documentation for this class was generated from the following file:
smacc_sm_reference_library/sm_three_some/include/sm_three_some/client_behaviors/keyboard/cb_keyboard_behavior.h