SbRotate Class Reference
#include <sb_rotate.h>
Public Member Functions
SbRotate ()
SbRotate (float rotate_degree)
virtual void onEntry () override
Public Attributes
tf::TransformListener listener
smacc::SmaccMoveBaseActionClient * moveBaseClient_
smacc_planner_switcher::PlannerSwitcher * plannerSwitcher_
boost::optional< float > rotateDegree
Detailed Description
Definition at line 11 of file sb_rotate.h.
Constructor & Destructor Documentation
SbRotate::SbRotate () [inline]
Definition at line 22 of file sb_rotate.h.
    {
    }
SbRotate::SbRotate (float rotate_degree) [inline]
Definition at line 26 of file sb_rotate.h.
    {
        rotateDegree = rotate_degree;
    }
Member Function Documentation
virtual void SbRotate::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 31 of file sb_rotate.h.
References smacc::SmaccSubStateBehavior::currentState, smacc::ISmaccState::param(), smacc::SmaccSubStateBehavior::requiresComponent(), rotateDegree, smacc::SmaccActionClientBase< ActionType >::sendGoal(), and smacc_planner_switcher::PlannerSwitcher::setDefaultPlanners().
    {
        double angle_increment_degree;
        if (!rotateDegree)
        {
            this->currentState->param("angle_increment_degree", angle_increment_degree, 45
      .0);
        }
        else
        {
            angle_increment_degree = *rotateDegree;
        }
        
        this->requiresComponent(moveBaseClient_, ros::NodeHandle("move_base
      "));
        this->requiresComponent(plannerSwitcher_, ros::NodeHandle("
      move_base"));
        //this should work better with a coroutine and await
        //this->plannerSwitcher_->setForwardPlanner();
        this->plannerSwitcher_->setDefaultPlanners();
        ros::Rate rate(10.0);
        geometry_msgs::Pose currentPoseMsg;
        while (ros::ok())
        {
            tf::StampedTransform currentPose;
            try
            {
                listener.lookupTransform("/odom", "/base_link",
                                         ros::Time(0), currentPose);
                tf::poseTFToMsg(currentPose, currentPoseMsg);
                break;
            }
            catch (tf::TransformException ex)
            {
                ROS_ERROR("%s", ex.what());
                ros::Duration(1.0).sleep();
            }
        }
        smacc::SmaccMoveBaseActionClient::Goal goal;
        goal.target_pose.header.frame_id = "/odom";
        goal.target_pose.header.stamp = ros::Time::now();
        auto currentAngle = tf::getYaw(currentPoseMsg.orientation);
        auto targetAngle = currentAngle + angle_increment_degree * M_PI / 180.0;
        goal.target_pose.pose.position = currentPoseMsg.position;
        goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(targetAngle);
        ROS_INFO_STREAM("current pose: " << currentPoseMsg);
        ROS_INFO_STREAM("goal pose: " << goal.target_pose.pose);
        moveBaseClient_->sendGoal(goal);
    }
Member Data Documentation
tf::TransformListener SbRotate::listener
Definition at line 14 of file sb_rotate.h.
smacc::SmaccMoveBaseActionClient* SbRotate::moveBaseClient_
Definition at line 16 of file sb_rotate.h.
smacc_planner_switcher::PlannerSwitcher* SbRotate::plannerSwitcher_
Definition at line 18 of file sb_rotate.h.
boost::optional<float> SbRotate::rotateDegree
Definition at line 20 of file sb_rotate.h.
Referenced by onEntry().
The documentation for this class was generated from the following file:
smacc_sm_examples/sm_dance_bot/include/sm_dance_bot/substate_behaviors/navigation/sb_rotate.h