AllEventAggregator Class Reference
#include <all_event_aggregator.h>
Public Member Functions
void setTriggerEventTypesCount (int event_types_count)
template<typename T >
bool notify ()
template<typename T >
bool notify (const T &ev)
bool isTriggered ()
Public Attributes
std::map< const char *, bool > events
Private Attributes
int event_types_count
Detailed Description
Definition at line 5 of file all_event_aggregator.h.
Member Function Documentation
bool AllEventAggregator::isTriggered () [inline]
Definition at line 32 of file all_event_aggregator.h.
References event_types_count.
Referenced by notify().
    {
      return events.size() >= event_types_count;
    }
template<typename T > bool AllEventAggregator::notify () [inline]
Definition at line 18 of file all_event_aggregator.h.
References isTriggered().
Referenced by StAcquireSensors::react().
    {
      auto* name = typeid(T).name();
      events[name] = true;
      return isTriggered();
    }
template<typename T > bool AllEventAggregator::notify (const T & ev) [inline]
Definition at line 27 of file all_event_aggregator.h.
    {
      return this->notify<T>();
    }
void AllEventAggregator::setTriggerEventTypesCount (int event_types_count) [inline]
Definition at line 10 of file all_event_aggregator.h.
References event_types_count.
Referenced by StAcquireSensors::onInitialize().
    {
      this->event_types_count = event_types_count;
    }
Member Data Documentation
int AllEventAggregator::event_types_count [private]
Definition at line 7 of file all_event_aggregator.h.
Referenced by isTriggered(), and setTriggerEventTypesCount().
std::map<const char*,bool> AllEventAggregator::events
Definition at line 15 of file all_event_aggregator.h.
The documentation for this class was generated from the following file:
smacc/include/smacc/all_event_aggregator.h