smacc::SmaccStateInfo Class Reference
#include <smacc_state_info.h>
Public Member Functions
SmaccStateInfo (std::shared_ptr< SmaccStateInfo > parentState, std::shared_ptr< SmaccStateMachineInfo > stateMachineInfo)
int depth () const
void getAncestors (std::list< std::shared_ptr< SmaccStateInfo >> &ancestorsList)
std::string getFullPath ()
template<typename StateType >
std::shared_ptr< SmaccStateInfo > createChildState ()
template<typename EvType >
void declareTransition (std::shared_ptr< SmaccStateInfo > &dstState)
const std::string & toShortName () const
Public Attributes
bool active_
std::string fullStateName
std::string demangledStateName
std::shared_ptr< SmaccStateMachineInfo > stateMachine_
std::shared_ptr< SmaccStateInfo > parentState_
std::map< std::string, std::shared_ptr< SmaccStateInfo > > transitions_
std::vector< std::shared_ptr< SmaccStateInfo > > children_
int depth_
Detailed Description
Definition at line 8 of file smacc_state_info.h.
Constructor & Destructor Documentation
smacc::SmaccStateInfo::SmaccStateInfo (std::shared_ptr< SmaccStateInfo > parentState, std::shared_ptr< SmaccStateMachineInfo > stateMachineInfo) [inline]
Definition at line 22 of file smacc_state_info.h.
    {
        parentState_ = parentState;
        stateMachine_ = stateMachineInfo;
        if(parentState_!=nullptr)
            depth_ = parentState->depth_ +1;
    }
Member Function Documentation
template<typename StateType > std::shared_ptr< SmaccStateInfo > smacc::SmaccStateInfo::createChildState ()
Definition at line 269 of file smacc_state_machine_info.h.
Referenced by getFullPath().
{
    auto childState = this->stateMachine_->createState<StateType>(shared_from_this());
    //this->stateMachine_->addState(childState);
    //stateMachineInfo.addState(stateMachineInfo)
    //stateNames.push_back(currentname);
    //ROS_INFO("------------");
    //ROS_INFO_STREAM("** STATE state: "<< this->demangledStateName);
    return childState;
}
template<typename EvType > void smacc::SmaccStateInfo::declareTransition (std::shared_ptr< SmaccStateInfo > & dstState)
Definition at line 171 of file smacc_state_machine_info.h.
Referenced by getFullPath().
{
    auto evtype = demangledTypeName<EvType>();
    transitions_[evtype] = dstState;
}
int smacc::SmaccStateInfo::depth () const [inline]
Definition at line 31 of file smacc_state_info.h.
References depth_.
{return depth_;}
void smacc::SmaccStateInfo::getAncestors (std::list< std::shared_ptr< SmaccStateInfo >> & ancestorsList) [inline]
Definition at line 33 of file smacc_state_info.h.
    {
        ancestorsList.push_front(shared_from_this());
        if(parentState_!=nullptr)
        {
            this->parentState_->getAncestors(ancestorsList);
            
        }
    }
std::string smacc::SmaccStateInfo::getFullPath () [inline]
Definition at line 43 of file smacc_state_info.h.
References createChildState(), declareTransition(), and toShortName().
    {
        if(parentState_==nullptr)
            return this->toShortName();
        else
            return this->parentState_->getFullPath() + "/" + this->
      toShortName();
    }
const std::string& smacc::SmaccStateInfo::toShortName () const [inline]
Definition at line 57 of file smacc_state_info.h.
References demangledStateName.
Referenced by getFullPath().
    {
        return this->demangledStateName;
    }
Member Data Documentation
bool smacc::SmaccStateInfo::active_
Definition at line 11 of file smacc_state_info.h.
std::vector<std::shared_ptr<SmaccStateInfo> > smacc::SmaccStateInfo::children_
Definition at line 19 of file smacc_state_info.h.
std::string smacc::SmaccStateInfo::demangledStateName
Definition at line 13 of file smacc_state_info.h.
Referenced by toShortName().
int smacc::SmaccStateInfo::depth_
Definition at line 20 of file smacc_state_info.h.
Referenced by depth().
std::string smacc::SmaccStateInfo::fullStateName
Definition at line 12 of file smacc_state_info.h.
std::shared_ptr<SmaccStateInfo> smacc::SmaccStateInfo::parentState_
Definition at line 16 of file smacc_state_info.h.
std::shared_ptr<SmaccStateMachineInfo> smacc::SmaccStateInfo::stateMachine_
Definition at line 15 of file smacc_state_info.h.
std::map<std::string,std::shared_ptr<SmaccStateInfo> > smacc::SmaccStateInfo::transitions_
Definition at line 17 of file smacc_state_info.h.
The documentation for this class was generated from the following files:
smacc/include/smacc/smacc_state_info.h
smacc/include/smacc/smacc_state_machine_info.h