smacc/include/smacc/common.h File Reference
#include <ros/ros.h>
*
#include <boost/statechart/state.hpp>
*
#include <boost/statechart/simple_state.hpp>
*
#include <boost/statechart/event.hpp>
*
#include <boost/statechart/fifo_scheduler.hpp>
*
#include <boost/statechart/asynchronous_state_machine.hpp>
*
#include <boost/statechart/custom_reaction.hpp>
*
#include <boost/config.hpp>
*
#include <boost/intrusive_ptr.hpp>
*
#include <boost/mpl/list.hpp>
*
#include <boost/function.hpp>
*
#include <boost/signals2.hpp>
*
#include <actionlib/client/simple_action_client.h>
*
#include <boost/statechart/termination.hpp>
*
#include <boost/statechart/transition.hpp>
*
#include <boost/any.hpp>
*
#include <boost/algorithm/string.hpp>
*
Classes
struct smacc::IActionResult
struct smacc::EvActionResult< ActionResult >
struct smacc::EvActionSucceded< ActionResult >
struct smacc::EvActionAborted< ActionResult >
struct smacc::EvActionPreempted< ActionResult >
struct smacc::EvActionRejected< ActionResult >
struct smacc::EvStateFinish< StateType >
struct smacc::EvActionFeedback< ActionFeedback >
Namespaces
 smacc
Typedefs
typedef sc::fifo_scheduler SmaccScheduler
typedef std::allocator< void > SmaccAllocator
typedef boost::statechart::processor_container< boost::statechart::fifo_scheduler<>, boost::function0< void >, std::allocator< void > >::processor_context my_context
Enumerations
enum smacc::SMRunMode { smacc::SMRunMode::DEBUG,
smacc::SMRunMode::RELEASE
 }
Functions
template<class T >
auto optionalNodeHandle (boost::intrusive_ptr< T > &obj) -> decltype(obj->nh)
template<class T >
auto optionalNodeHandle (T *) -> ros::NodeHandle
std::string smacc::cleanShortTypeName (const std::type_info &tinfo)
template<typename StateMachineType >
void smacc::run ()
std::string demangleSymbol (const char *name)
template<class T >
std::string demangledTypeName ()
Typedef Documentation
typedef boost::statechart::processor_container<boost::statechart::fifo_scheduler<>, boost::function0<void>, std::allocator<void> >::processor_context my_context
Definition at line 58 of file common.h.
typedef std::allocator<void> SmaccAllocator
Definition at line 36 of file common.h.
typedef sc::fifo_scheduler SmaccScheduler
Definition at line 34 of file common.h.
Function Documentation
template<class T > std::string demangledTypeName () [inline]
Definition at line 155 of file common.h.
References demangleSymbol().
{
  return demangleSymbol(typeid(T).name());
}
std::string demangleSymbol (const char * name) [inline]
Definition at line 137 of file common.h.
Referenced by smacc::cleanShortTypeName(), demangledTypeName(), smacc::SmaccState< StNavigateForward1, SmDanceBot >::getFullName(), smacc::Orthogonal::getName(), smacc::ISmaccComponent::getName(), smacc::SmaccSubStateBehavior::getName(), smacc::ISmaccStateMachine::getStateMachineName(), smacc::ISmaccStateMachine::mapBehavior(), smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::postEvent(), smacc::SbKeyboard::postKeyEvent(), smacc::KeyboardClient::postKeyEvent(), smacc::processTransition(), smacc::ISmaccStateMachine::requiresComponent(), smacc::SmaccState< StNavigateForward1, SmDanceBot >::SmaccState(), smacc::ISmaccStateMachine::updateCurrentState(), and smacc::SmaccState< StNavigateForward1, SmDanceBot >::~SmaccState().
{
#if (__GNUC__ && __cplusplus && __GNUC__ >= 3)
  int status;
  char *res = abi::__cxa_demangle(name, 0, 0, &status);
  if (res)
  {
    const std::string demangled_name(res);
    std::free(res);
    return demangled_name;
  }
  // Demangling failed, fallback to mangled name
  return std::string(name);
#else
  return std::string(name);
#endif
}
template<class T > auto optionalNodeHandle (boost::intrusive_ptr< T > & obj) -> decltype(obj->nh)
Definition at line 39 of file common.h.
Referenced by smacc::SmaccState< StNavigateForward1, SmDanceBot >::SmaccState().
{
  return obj->nh;
}
template<class T > auto optionalNodeHandle (T *) -> ros::NodeHandle
Definition at line 46 of file common.h.
{
  return ros::NodeHandle("");
}