rosdoc_lite.python_paths Namespace Reference
Functions
def get_non_catkin_depends (package, rospack)
def append_package_paths (manifest, paths, pkg_dir)
def generate_python_path (pkg, rospack, m)
Function Documentation
def rosdoc_lite.python_paths.append_package_paths (manifest, paths, pkg_dir)
Added paths for package to paths
:param manifest_: package manifest, ``Manifest``
:param pkg_dir: package's filesystem directory path, ``str``
:param paths: list of paths, ``[str]``
Definition at line 43 of file python_paths.py.
Referenced by rosdoc_lite.python_paths.generate_python_path().
def append_package_paths(manifest, paths, pkg_dir):
    """
    Added paths for package to paths
    :param manifest_: package manifest, ``Manifest``
    :param pkg_dir: package's filesystem directory path, ``str``
    :param paths: list of paths, ``[str]``
    """
    exports = manifest.get_export('python', 'path')
    if exports:
        for export in exports:
            if ':' in export:
                export = export.split(':')
            else:
                export = [export]
            for e in export:
                paths.append(e.replace('${prefix}', pkg_dir))
    else:
        dirs = [os.path.join(pkg_dir, d) for d in ['src', 'lib']]
        print("Trying to put %s on python path" % dirs)
        paths.extend([d for d in dirs if os.path.isdir(d)])
def rosdoc_lite.python_paths.generate_python_path (pkg, rospack, m)
Recursive subroutine for building dependency list and python path
Definition at line 65 of file python_paths.py.
References rosdoc_lite.python_paths.append_package_paths(), and rosdoc_lite.python_paths.get_non_catkin_depends().
def generate_python_path(pkg, rospack, m):
    """
    Recursive subroutine for building dependency list and python path
    """
    # short-circuit if this is a catkin-ized package
    if m.is_catkin:
        print("Catkin package, no need to generate python paths")
        return []
    packages = get_non_catkin_depends(pkg, rospack)
    packages.append(pkg)
    print("Packages to create python paths for %s" % packages)
    paths = []
    try:
        for p in packages:
            m = rospack.get_manifest(p)
            d = rospack.get_path(p)
            append_package_paths(m, paths, d)
    except:
        raise
    return paths
def rosdoc_lite.python_paths.get_non_catkin_depends (package, rospack)
Definition at line 38 of file python_paths.py.
Referenced by rosdoc_lite.python_paths.generate_python_path().
def get_non_catkin_depends(package, rospack):
    vals = rospack.get_depends(package, implicit=True)
    return [v for v in vals if not rospack.get_manifest(v).is_catkin]