smacc_viewer.smacc_user_data Namespace Reference
Classes
class Const
class Remapper
class UserData
Functions
def get_const (obj)
Variables
list __all__ = ['UserData','Remapper']
Function Documentation
def smacc_viewer.smacc_user_data.get_const (obj)
Get a const reference to an object if it has "user-defined" attributes.
Definition at line 83 of file smacc_user_data.py.
Referenced by smacc_viewer.smacc_user_data.Const.__getattr__(), smacc_viewer.smacc_user_data.Remapper.__getattr__(), smacc_viewer.smacc_user_data.Const.__getitem__(), and smacc_viewer.smacc_user_data.Remapper.__getitem__().
def get_const(obj):
    """Get a const reference to an object if it has "user-defined" attributes."""
    if hasattr(obj,'__dict__'):
        rospy.logdebug("Making const '%s'" % str(obj))
        return Const(obj)
    else:
        return obj
Variable Documentation
list smacc_viewer.smacc_user_data.__all__ = ['UserData','Remapper'] [private]
Definition at line 6 of file smacc_user_data.py.