rosdoc_lite.rdcore Namespace Reference
Classes
class PackageInformation
Functions
def convert_manifest_export (man_export)
def html_path (package, docdir)
def get_templates_dir ()
def load_tmpl (filename)
def instantiate_template (tmpl, tempvars)
Variables
string _TEMPLATES_DIR = 'templates'
string _PACKAGE_NAME = 'rosdoc_lite'
Function Documentation
def rosdoc_lite.rdcore.convert_manifest_export (man_export)
Definition at line 46 of file rdcore.py.
Referenced by rosdoc_lite.rdcore.PackageInformation.create_from_manifest().
def convert_manifest_export(man_export):
    e = Export(man_export.tag, man_export.str)
    e.attributes = man_export.attrs
    return e
def rosdoc_lite.rdcore.get_templates_dir ()
Definition at line 125 of file rdcore.py.
Referenced by rosdoc_lite.rdcore.load_tmpl().
def get_templates_dir():
    return os.path.join(os.path.dirname(__file__), _TEMPLATES_DIR)
def rosdoc_lite.rdcore.html_path (package, docdir)
Definition at line 112 of file rdcore.py.
def html_path(package, docdir):
    return os.path.join(docdir, package, 'html')
def rosdoc_lite.rdcore.instantiate_template (tmpl, tempvars)
looks up file within rosdoc_lite package, return its content, may sys.exit on error
Definition at line 149 of file rdcore.py.
def instantiate_template(tmpl, tempvars):
    """
    looks up file within rosdoc_lite package, return its content, may sys.exit on error
    """
    for k, v in tempvars.items():
        tmpl = tmpl.replace(k, kitchen.text.converters.to_unicode(v))
    return tmpl
def rosdoc_lite.rdcore.load_tmpl (filename)
looks up file within rosdoc ROS package,
return its content, may sys.exit on error.
Contents are cached with filename as key.

:returns: cached file contents
Definition at line 129 of file rdcore.py.
References rosdoc_lite.rdcore.get_templates_dir().
def load_tmpl(filename):
    """
    looks up file within rosdoc ROS package,
    return its content, may sys.exit on error.
    Contents are cached with filename as key.
    :returns: cached file contents
    """
    filename = os.path.join(get_templates_dir(), filename)
    if not os.path.isfile(filename):
        sys.stderr.write("Cannot locate template file '%s'\n" % (filename))
        sys.exit(1)
    with open(filename, 'r') as f:
        content = f.read()
        if not content:
            sys.stderr.write("Template file '%s' is empty\n" % (filename))
            sys.exit(1)
        return content
Variable Documentation
string rosdoc_lite.rdcore._PACKAGE_NAME = 'rosdoc_lite' [private]
Definition at line 122 of file rdcore.py.
string rosdoc_lite.rdcore._TEMPLATES_DIR = 'templates' [private]
Definition at line 121 of file rdcore.py.