rosdoc_lite.landing_page Namespace Reference
Functions
def _href (location, text)
def link_name (rd_config)
def output_location (config)
def generate_links (package, manifest, rd_configs)
def generate_landing_page (package, manifest, rd_configs, output_dir)
Function Documentation
def rosdoc_lite.landing_page._href (location, text) [private]
Definition at line 44 of file landing_page.py.
Referenced by rosdoc_lite.landing_page.generate_links().
def _href(location, text):
    return '<a href="%(location)s">%(text)s</a>' % locals()
def rosdoc_lite.landing_page.generate_landing_page (package, manifest, rd_configs, output_dir)
Generate landing page in the event that there are multiple documentation sets
:returns: list of packages for which there are landing pages generated
Definition at line 104 of file landing_page.py.
References rosdoc_lite.landing_page.generate_links().
def generate_landing_page(package, manifest, rd_configs, output_dir):
    """
    Generate landing page in the event that there are multiple documentation sets
    :returns: list of packages for which there are landing pages generated
    """
    template = rdcore.load_tmpl('landing.template')
    #print("landing_page: packages are", ctx.packages.keys())
    try:
        links = generate_links(package, manifest, rd_configs)
        # if links is empty, it means that the rd_configs builds
        # to the base directory and no landing page is required
        # (or it means that the config is corrupt)
        if not links:
            #print("ignoring landing page for", package)
            return
        html_dir = output_dir
        #print("generating landing page", html_dir)
        if not os.path.isdir(html_dir):
            os.makedirs(html_dir)
        links_html = '\n'.join(['<li class="landing-li">%s</li>' % l for l in links])
        date = str(time.strftime('%a, %d %b %Y %H:%M:%S'))
        tempvars = {
            '$package': package,
            '$links': links_html,
            '$date': date,
                }
        with open(os.path.join(html_dir, 'index.html'), 'w') as f:
            f.write(rdcore.instantiate_template(template, tempvars))
    except Exception as e:
        print("Unable to generate landing_page for [%s]:\n\t%s" % (package, str(e)), file=sys.stderr)
        raise
def rosdoc_lite.landing_page.generate_links (package, manifest, rd_configs)
:param package: str packagename
:param manifest: manifest object
:param rd_configs: [dict] package manifest rosdoc configs
:returns: [str] list of html snippets
Definition at line 78 of file landing_page.py.
References rosdoc_lite.landing_page._href(), rosdoc_lite.landing_page.link_name(), and rosdoc_lite.landing_page.output_location().
Referenced by rosdoc_lite.landing_page.generate_landing_page().
def generate_links(package, manifest, rd_configs):
    """
    :param package: str packagename
    :param manifest: manifest object
    :param rd_configs: [dict] package manifest rosdoc configs
    :returns: [str] list of html snippets
    """
    config_list = [c for c in rd_configs.values() if c['builder'] != 'rosmake']
    output_dirs = [output_location(c) for c in config_list]
    # filter out empties
    output_dirs = [d for d in output_dirs if d and d != '.']
    # length check. if these are unequal, cannot generate landing
    # page. this is often true if the config is merely generating
    # local.
    if len(output_dirs) != len(config_list):
        return None
    links = [_href(d, link_name(c)) for c, d in zip(config_list, output_dirs)]
    url = manifest.url
    if url:
        links.append(_href(url, '%s Package Documentation' % package))
    return links
def rosdoc_lite.landing_page.link_name (rd_config)
returns the name to display as for the generated kind of API.
:param rdconfig: dict as parsed from manifest.xml
:returns: label, ``str``
Definition at line 48 of file landing_page.py.
Referenced by rosdoc_lite.landing_page.generate_links().
def link_name(rd_config):
    """
    returns the name to display as for the generated kind of API.
    :param rdconfig: dict as parsed from manifest.xml
    :returns: label, ``str``
    """
    if 'name' in rd_config:
        n = rd_config['name']
    else:
        if rd_config['builder'] == 'doxygen':
            return 'C++ API'
        elif rd_config['builder'] in ['epydoc', 'sphinx']:
            return 'Python API'
        elif rd_config['builder'] in ['external']:
            return rd_config.get('external_label', 'External')
        else:
            return rd_config['builder']
    return n
def rosdoc_lite.landing_page.output_location (config)
:returns: uri, ``str``
Definition at line 68 of file landing_page.py.
Referenced by rosdoc_lite.landing_page.generate_links().
def output_location(config):
    """
    :returns: uri, ``str``
    """
    if config['builder'] == 'external':
        return config.get('external_url', None)
    else:
        return config.get('output_dir', None)