smacc_viewer Namespace Reference
Namespaces
 introspection_container
 smacc_user_data
 xdot
Classes
class ContainerNode
class SmaccViewerFrame
Functions
def import_non_local (name, custom_name=None)
this import system (or ros-released) xdot import xdot need to import currnt package, but not to load this file http://stackoverflow.com/questions/6031584/importing-from-builtin-library-when-module-with-same-name-exists
def graph_attr_string (attrs)
Helper Functions.
def attr_string (attrs)
def get_parent_path (path)
def get_label (path)
def hex2t (color_str)
def main ()
Variables
string STATUS_TOPIC = '/smacc/container_status'
string INIT_TOPIC = '/smacc/container_init'
string STRUCTURE_TOPIC = '/smacc/container_structure'
smacc_viewer = import_non_local('smacc_viewer')
anonymous
False
disable_signals
True
log_level
argv
Function Documentation
def smacc_viewer.attr_string (attrs)
Generate an xdot node attribute string.
Definition at line 94 of file smacc_viewer.py.
Referenced by smacc_viewer.ContainerNode.get_dotcode().
def attr_string(attrs):
    """Generate an xdot node attribute string."""
    attrs_strs = ['"'+str(k)+'"="'+str(v)+'"' for k,v in attrs.iteritems()]
    return ' ['+(', '.join(attrs_strs))+']'
def smacc_viewer.get_label (path)
Get the label of an xdot node.
Definition at line 108 of file smacc_viewer.py.
Referenced by smacc_viewer.SmaccViewerFrame.add_to_tree(), and smacc_viewer.SmaccViewerFrame.on_set_initial_state().
def get_label(path):
    """Get the label of an xdot node."""
    path_tokens = path.split('/')
    return path_tokens[-1]
def smacc_viewer.get_parent_path (path)
Get the parent path of an xdot node.
Definition at line 99 of file smacc_viewer.py.
Referenced by smacc_viewer.SmaccViewerFrame._status_msg_update(), smacc_viewer.SmaccViewerFrame.on_set_initial_state(), and smacc_viewer.SmaccViewerFrame.selection_changed().
def get_parent_path(path):
    """Get the parent path of an xdot node."""
    path_tokens = path.split('/')
    if len(path_tokens) > 2:
        parent_path = '/'.join(path_tokens[0:-1])
    else:
        parent_path = '/'.join(path_tokens[0:1])
    return parent_path
def smacc_viewer.graph_attr_string (attrs)
Helper Functions.
Generate an xdot graph attribute string.
Definition at line 89 of file smacc_viewer.py.
Referenced by smacc_viewer.ContainerNode.get_dotcode().
def graph_attr_string(attrs):
    """Generate an xdot graph attribute string."""
    attrs_strs = ['"'+str(k)+'"="'+str(v)+'"' for k,v in attrs.iteritems()]
    return ';\n'.join(attrs_strs)+';\n'
def smacc_viewer.hex2t (color_str)
Convert a hexadecimal color strng into a color tuple.
Definition at line 113 of file smacc_viewer.py.
Referenced by smacc_viewer.ContainerNode.set_styles().
def hex2t(color_str):
    """Convert a hexadecimal color strng into a color tuple."""
    color_tuple = [int(color_str[i:i+2],16)/255.0 for i in range(1,len(color_str),2)]
    return color_tuple
def smacc_viewer.import_non_local (name, custom_name = None)
this import system (or ros-released) xdot import xdot need to import currnt package, but not to load this file http://stackoverflow.com/questions/6031584/importing-from-builtin-library-when-module-with-same-name-exists
Definition at line 68 of file smacc_viewer.py.
References smacc_viewer.xdot.xdot_qt.filter.
def import_non_local(name, custom_name=None):
    import imp, sys
    custom_name = custom_name or name
    path = filter(lambda x: x != os.path.dirname(os.path.abspath(__file__)), sys.path)
    f, pathname, desc = imp.find_module(name, path)
    module = imp.load_module(custom_name, f, pathname, desc)
    if f:
        f.close()
    return module
def smacc_viewer.main ()
Definition at line 1047 of file smacc_viewer.py.
def main():
    from argparse import ArgumentParser
    p = ArgumentParser()
    p.add_argument('-f', '--auto-focus',
                 action='store_true',
                 help="Enable 'AutoFocus to subgraph' as default",
                 dest='enable_auto_focus')
    args = p.parse_args()
    app = wx.App()
    frame = SmaccViewerFrame()
    frame.set_filter('dot')
    frame.Show()
    if args.enable_auto_focus:
        frame.toggle_auto_focus(None)
    app.MainLoop()
Variable Documentation
smacc_viewer.anonymous
Definition at line 1068 of file smacc_viewer.py.
smacc_viewer.argv
Definition at line 1069 of file smacc_viewer.py.
smacc_viewer.disable_signals
Definition at line 1068 of file smacc_viewer.py.
smacc_viewer.False
Definition at line 1068 of file smacc_viewer.py.
string smacc_viewer.INIT_TOPIC = '/smacc/container_init'
Definition at line 61 of file smacc_viewer.py.
smacc_viewer.log_level
Definition at line 1068 of file smacc_viewer.py.
smacc_viewer.smacc_viewer = import_non_local('smacc_viewer')
Definition at line 82 of file smacc_viewer.py.
string smacc_viewer.STATUS_TOPIC = '/smacc/container_status'
Definition at line 60 of file smacc_viewer.py.
string smacc_viewer.STRUCTURE_TOPIC = '/smacc/container_structure'
Definition at line 62 of file smacc_viewer.py.
smacc_viewer.True
Definition at line 1068 of file smacc_viewer.py.