keyboard_node Namespace Reference
Functions
def getKey ()
Variables
settings = termios.tcgetattr(sys.stdin)
pub = rospy.Publisher('keyboard_unicode', UInt16, queue_size = 1)
key = getKey()
msg = UInt16()
data
Function Documentation
def keyboard_node.getKey ()
Definition at line 12 of file keyboard_node.py.
def getKey():
    tty.setraw(sys.stdin.fileno())
    select.select([sys.stdin], [], [], 0)
    key = sys.stdin.read(1)
    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key
Variable Documentation
keyboard_node.data
Definition at line 30 of file keyboard_node.py.
keyboard_node.key = getKey()
Definition at line 27 of file keyboard_node.py.
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >.getFullPathName().
keyboard_node.msg = UInt16()
Definition at line 29 of file keyboard_node.py.
Referenced by backward_global_planner::BackwardGlobalPlanner.commandServiceCall(), smacc::SensorClient< LaserSensor, sensor_msgs::LaserScan >.initialize(), sm_dance_bot::KeyboardClient.initialize(), main(), smacc::SensorTopic< SbLidarSensor, sensor_msgs::LaserScan, LaserSensor >.onEntry(), smacc_odom_tracker::OdomTracker.rtPublishPaths(), and sm_dance_bot::SbStringPublisher.SbStringPublisher().
keyboard_node.pub = rospy.Publisher('keyboard_unicode', UInt16, queue_size = 1)
Definition at line 22 of file keyboard_node.py.
Referenced by main().
keyboard_node.settings = termios.tcgetattr(sys.stdin)
Definition at line 20 of file keyboard_node.py.