smacc Namespace Reference
Classes
struct ABORT
struct add_type_wrapper
struct AddSubState
struct AddTransition
struct CheckType
class ClMoveBaseZ
struct CONTINUELOOP
struct DEFAULT
struct default_object_tag
struct default_transition_name
struct empty_object_tag
struct ENDLOOP
struct EvActionAborted
struct EvActionFeedback
struct EvActionPreempted
struct EvActionRejected
struct EvActionResult
struct EvActionSucceeded
struct EvAll
struct EvCountdownEnd
class EventFactory
struct EvLoopContinue
struct EvLoopEnd
struct EvStateFinish
struct EvTopicInitialMessage
struct EvTopicMessage
struct EvTopicMessageTimeout
struct EvTrue
struct EvWaypoint0
struct EvWaypoint1
struct EvWaypoint10
struct EvWaypoint100
struct EvWaypoint101
struct EvWaypoint102
struct EvWaypoint103
struct EvWaypoint104
struct EvWaypoint105
struct EvWaypoint106
struct EvWaypoint107
struct EvWaypoint108
struct EvWaypoint109
struct EvWaypoint11
struct EvWaypoint110
struct EvWaypoint111
struct EvWaypoint112
struct EvWaypoint113
struct EvWaypoint114
struct EvWaypoint115
struct EvWaypoint116
struct EvWaypoint117
struct EvWaypoint118
struct EvWaypoint119
struct EvWaypoint12
struct EvWaypoint120
struct EvWaypoint121
struct EvWaypoint122
struct EvWaypoint123
struct EvWaypoint124
struct EvWaypoint125
struct EvWaypoint126
struct EvWaypoint127
struct EvWaypoint128
struct EvWaypoint129
struct EvWaypoint13
struct EvWaypoint130
struct EvWaypoint131
struct EvWaypoint132
struct EvWaypoint133
struct EvWaypoint134
struct EvWaypoint135
struct EvWaypoint136
struct EvWaypoint137
struct EvWaypoint138
struct EvWaypoint139
struct EvWaypoint14
struct EvWaypoint140
struct EvWaypoint141
struct EvWaypoint142
struct EvWaypoint143
struct EvWaypoint144
struct EvWaypoint145
struct EvWaypoint146
struct EvWaypoint147
struct EvWaypoint148
struct EvWaypoint149
struct EvWaypoint15
struct EvWaypoint150
struct EvWaypoint151
struct EvWaypoint152
struct EvWaypoint153
struct EvWaypoint154
struct EvWaypoint155
struct EvWaypoint156
struct EvWaypoint157
struct EvWaypoint158
struct EvWaypoint159
struct EvWaypoint16
struct EvWaypoint160
struct EvWaypoint161
struct EvWaypoint162
struct EvWaypoint163
struct EvWaypoint164
struct EvWaypoint165
struct EvWaypoint166
struct EvWaypoint167
struct EvWaypoint168
struct EvWaypoint169
struct EvWaypoint17
struct EvWaypoint170
struct EvWaypoint171
struct EvWaypoint172
struct EvWaypoint173
struct EvWaypoint174
struct EvWaypoint175
struct EvWaypoint176
struct EvWaypoint177
struct EvWaypoint178
struct EvWaypoint179
struct EvWaypoint18
struct EvWaypoint180
struct EvWaypoint181
struct EvWaypoint182
struct EvWaypoint183
struct EvWaypoint184
struct EvWaypoint185
struct EvWaypoint186
struct EvWaypoint187
struct EvWaypoint188
struct EvWaypoint189
struct EvWaypoint19
struct EvWaypoint190
struct EvWaypoint191
struct EvWaypoint192
struct EvWaypoint193
struct EvWaypoint194
struct EvWaypoint195
struct EvWaypoint196
struct EvWaypoint197
struct EvWaypoint198
struct EvWaypoint199
struct EvWaypoint2
struct EvWaypoint20
struct EvWaypoint200
struct EvWaypoint201
struct EvWaypoint202
struct EvWaypoint203
struct EvWaypoint204
struct EvWaypoint205
struct EvWaypoint206
struct EvWaypoint207
struct EvWaypoint208
struct EvWaypoint209
struct EvWaypoint21
struct EvWaypoint210
struct EvWaypoint211
struct EvWaypoint212
struct EvWaypoint213
struct EvWaypoint214
struct EvWaypoint215
struct EvWaypoint216
struct EvWaypoint217
struct EvWaypoint218
struct EvWaypoint219
struct EvWaypoint22
struct EvWaypoint220
struct EvWaypoint221
struct EvWaypoint222
struct EvWaypoint223
struct EvWaypoint224
struct EvWaypoint225
struct EvWaypoint226
struct EvWaypoint227
struct EvWaypoint228
struct EvWaypoint229
struct EvWaypoint23
struct EvWaypoint230
struct EvWaypoint231
struct EvWaypoint232
struct EvWaypoint233
struct EvWaypoint234
struct EvWaypoint235
struct EvWaypoint236
struct EvWaypoint237
struct EvWaypoint238
struct EvWaypoint239
struct EvWaypoint24
struct EvWaypoint240
struct EvWaypoint241
struct EvWaypoint242
struct EvWaypoint243
struct EvWaypoint244
struct EvWaypoint245
struct EvWaypoint246
struct EvWaypoint247
struct EvWaypoint248
struct EvWaypoint249
struct EvWaypoint25
struct EvWaypoint250
struct EvWaypoint251
struct EvWaypoint252
struct EvWaypoint253
struct EvWaypoint254
struct EvWaypoint255
struct EvWaypoint256
struct EvWaypoint26
struct EvWaypoint27
struct EvWaypoint28
struct EvWaypoint29
struct EvWaypoint3
struct EvWaypoint30
struct EvWaypoint31
struct EvWaypoint32
struct EvWaypoint33
struct EvWaypoint34
struct EvWaypoint35
struct EvWaypoint36
struct EvWaypoint37
struct EvWaypoint38
struct EvWaypoint39
struct EvWaypoint4
struct EvWaypoint40
struct EvWaypoint41
struct EvWaypoint42
struct EvWaypoint43
struct EvWaypoint44
struct EvWaypoint45
struct EvWaypoint46
struct EvWaypoint47
struct EvWaypoint48
struct EvWaypoint49
struct EvWaypoint5
struct EvWaypoint50
struct EvWaypoint51
struct EvWaypoint52
struct EvWaypoint53
struct EvWaypoint54
struct EvWaypoint55
struct EvWaypoint56
struct EvWaypoint57
struct EvWaypoint58
struct EvWaypoint59
struct EvWaypoint6
struct EvWaypoint60
struct EvWaypoint61
struct EvWaypoint62
struct EvWaypoint63
struct EvWaypoint64
struct EvWaypoint65
struct EvWaypoint66
struct EvWaypoint67
struct EvWaypoint68
struct EvWaypoint69
struct EvWaypoint7
struct EvWaypoint70
struct EvWaypoint71
struct EvWaypoint72
struct EvWaypoint73
struct EvWaypoint74
struct EvWaypoint75
struct EvWaypoint76
struct EvWaypoint77
struct EvWaypoint78
struct EvWaypoint79
struct EvWaypoint8
struct EvWaypoint80
struct EvWaypoint81
struct EvWaypoint82
struct EvWaypoint83
struct EvWaypoint84
struct EvWaypoint85
struct EvWaypoint86
struct EvWaypoint87
struct EvWaypoint88
struct EvWaypoint89
struct EvWaypoint9
struct EvWaypoint90
struct EvWaypoint91
struct EvWaypoint92
struct EvWaypoint93
struct EvWaypoint94
struct EvWaypoint95
struct EvWaypoint96
struct EvWaypoint97
struct EvWaypoint98
struct EvWaypoint99
class HasAutomaticTransitionTag
class HasAutomaticTransitionType
class HasEventLabel
class HasOnDefinition
struct IActionResult
class IEventFactory
class ISmaccActionClient
class ISmaccClient
class ISmaccComponent
class ISmaccState
class ISmaccStateMachine
class ISmaccUpdatable
class LogicUnit
class LuAllEventsGo
class LuConditional
class LuEventCountdown
class Orthogonal
struct Pose2D
struct PREEMPT
struct REJECT
class SensorClient
class SensorTopic
class SignalDetector
class SmaccActionClientBase
class SmaccClientBehavior
struct SmaccEventInfo
struct SmaccLogicUnitInfo
class SmaccPublisherClient
class SmaccServiceClient
class SmaccSignal
class SmaccState
class SmaccStateInfo
struct SmaccStateMachineBase
State Machine.
class SmaccStateMachineInfo
class SmaccSubscriberClient
class SmaccToolActionClient
struct SmaccTransitionInfo
struct StateBehaviorInfoEntry
struct SUCCESS
class transition
struct type_
class TypeInfo
struct typelist
struct WalkStatesExecutor
class WaypointEventDispatcher
class WaypointNavigator
Typedefs
typedef std::allocator< void > SmaccAllocator
typedef boost::mpl::list< SUCCESS, ABORT, PREEMPT, CONTINUELOOP, ENDLOOP > DEFAULT_TRANSITION_TYPES
Enumerations
enum SMRunMode { SMRunMode::DEBUG,
SMRunMode::RELEASE
 }
enum SmaccStateType { SmaccStateType::SUPERSTATE = 2,
SmaccStateType::STATE = 1,
SmaccStateType::SUPERSTATE_ROUTINE = 1
 }
Functions
std::string cleanShortTypeName (const std::type_info &tinfo)
template<typename StateMachineType >
void run ()
void transitionInfoToMsg (const SmaccTransitionInfo &transition, smacc_msgs::SmaccTransition &transitionMsg)
template<class T >
auto optionalNodeHandle (boost::intrusive_ptr< T > &obj) -> decltype(obj->nh)
template<class T >
auto optionalNodeHandle (T *) -> ros::NodeHandle
std::string demangleSymbol (const std::string &name)
std::string demangleSymbol (const char *name)
template<typename T >
std::string demangleSymbol ()
template<class T >
std::string demangledTypeName ()
std::string demangleType (const std::type_info &tinfo)
template<typename T >
std::enable_if< HasEventLabel< T >::value, void >::type EventLabel (std::string &label)
template<typename T >
std::enable_if<!HasEventLabel< T >::value, void >::type EventLabel (std::string &label)
template<typename T >
std::enable_if< HasAutomaticTransitionTag< T >::value, void >::type automaticTransitionTag (std::string &transition_name)
template<typename T >
std::enable_if<!HasAutomaticTransitionTag< T >::value, void >::type automaticTransitionTag (std::string &transition_name)
template<typename T >
std::enable_if< HasAutomaticTransitionType< T >::value, void >::type automaticTransitionType (std::string &transition_type)
template<typename T >
std::enable_if<!HasAutomaticTransitionType< T >::value, void >::type automaticTransitionType (std::string &transition_type)
template<typename TTransition >
static std::string getTransitionType ()
template<typename T >
disable_if< boost::mpl::is_sequence< T > >::type processSubState (std::shared_ptr< SmaccStateInfo > &parentState)
template<typename T >
enable_if< boost::mpl::is_sequence< T > >::type processSubState (std::shared_ptr< SmaccStateInfo > &parentState)
template<typename T >
enable_if< boost::mpl::is_sequence< T > >::type processTransitions (std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev , typename Dst , typename Tag >
void processTransition (smacc::transition< Ev, boost::statechart::deep_history< Dst >, Tag > *, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev , typename Dst , typename Tag >
void processTransition (smacc::transition< Ev, Dst, Tag > *t, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev , typename Dst , typename Tag >
void processTransitionAux (smacc::transition< Ev, Dst, Tag > *, std::shared_ptr< SmaccStateInfo > &sourceState, bool history, smacc::TypeInfo::Ptr &transitionTypeInfo)
template<typename Ev , typename Dst >
void processTransition (statechart::transition< Ev, Dst > *, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev >
void processTransition (statechart::custom_reaction< Ev > *, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename T >
disable_if< boost::mpl::is_sequence< T > >::type processTransitions (std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename T >
std::enable_if< HasOnDefinition< T >::value, void >::type CallOnDefinition ()
template<typename T >
std::enable_if<!HasOnDefinition< T >::value, void >::type CallOnDefinition ()
bool replace (std::string &str, const std::string &from, const std::string &to)
std::string replace_back (std::string roottype, std::map< std::string, std::string > &typesdict)
template<typename TEv >
void configurePostEvWaypoint (std::function< void()> *fntarget, ClMoveBaseZ *client, int index)
Typedef Documentation
typedef boost::mpl::list<SUCCESS, ABORT, PREEMPT, CONTINUELOOP, ENDLOOP> smacc::DEFAULT_TRANSITION_TYPES
Definition at line 191 of file introspection.h.
typedef std::allocator<void> smacc::SmaccAllocator
Definition at line 28 of file introspection.h.
Enumeration Type Documentation
enum smacc::SmaccStateType [strong]
Enumerator
SUPERSTATE
STATE
SUPERSTATE_ROUTINE
Definition at line 62 of file smacc_state_info.h.
{
    SUPERSTATE = 2,
    STATE = 1,
    SUPERSTATE_ROUTINE = 1
};
enum smacc::SMRunMode [strong]
Enumerator
DEBUG
RELEASE
Definition at line 46 of file common.h.
{
  DEBUG,
  RELEASE
};
Function Documentation
template<typename T > std::enable_if<HasAutomaticTransitionTag<T>::value, void>::type smacc::automaticTransitionTag (std::string & transition_name)
Definition at line 144 of file introspection.h.
{
    transition_name = T::getDefaultTransitionTag();
}
template<typename T > std::enable_if<!HasAutomaticTransitionTag<T>::value, void>::type smacc::automaticTransitionTag (std::string & transition_name)
Definition at line 151 of file introspection.h.
{
    transition_name = "";
}
template<typename T > std::enable_if<HasAutomaticTransitionType<T>::value, void>::type smacc::automaticTransitionType (std::string & transition_type)
Definition at line 178 of file introspection.h.
{
    transition_type = T::getDefaultTransitionType();
}
template<typename T > std::enable_if<!HasAutomaticTransitionType<T>::value, void>::type smacc::automaticTransitionType (std::string & transition_type)
Definition at line 185 of file introspection.h.
{
    transition_type = demangledTypeName<DEFAULT>();
}
template<typename T > std::enable_if<HasOnDefinition<T>::value, void>::type smacc::CallOnDefinition ()
Definition at line 340 of file smacc_state_machine_info.h.
References demangleSymbol().
{
    /* something when T has toString ... */
    ROS_INFO_STREAM("EXECUTING ONDEFINITION: " << demangleSymbol(typeid(T).name()));
    T::onDefinition();
}
template<typename T > std::enable_if<!HasOnDefinition<T>::value, void>::type smacc::CallOnDefinition ()
Definition at line 349 of file smacc_state_machine_info.h.
References demangleSymbol().
{
    ROS_INFO_STREAM("static OnDefinition: dont exist for " << demangleSymbol(typeid(T).name()
      ));
    /* something when T has toString ... */
}
std::string smacc::cleanShortTypeName (const std::type_info & tinfo)
Definition at line 16 of file common.cpp.
References demangleSymbol().
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::getShortName(), smacc::SmaccStateMachineBase< SmAtomicStateMachine, State1 >::initiate_impl(), and smacc::SmaccState< SsrFPatternStartLoop, SS >::SmaccState().
{
    std::string fullclassname = demangleSymbol(tinfo.name());
    //ROS_INFO("State full classname: %s", fullclassname.c_str());
    std::vector<std::string> strs;
    boost::split(strs,fullclassname,boost::is_any_of("::"));
    std::string classname = strs.back();
    //ROS_INFO("State classname: %s", classname.c_str());
    return classname;
}
template<typename TEv > void smacc::configurePostEvWaypoint (std::function< void()> * fntarget, ClMoveBaseZ * client, int index)
Definition at line 1567 of file waypoints_event_dispatcher.h.
{
    fntarget[index] = [=]() {
        client->template postEvent<TEv>();
    };
}
template<class T > std::string smacc::demangledTypeName () [inline]
Definition at line 73 of file introspection.h.
References demangleSymbol().
{
    return demangleSymbol(typeid(T).name());
}
std::string smacc::demangleSymbol (const std::string & name) [inline]
Definition at line 43 of file introspection.h.
Referenced by smacc::SmaccStateMachineInfo::assembleSMStructureMessage(), CallOnDefinition(), cleanShortTypeName(), demangledTypeName(), demangleSymbol(), demangleType(), smacc::ISmaccState::getClassName(), smacc::SmaccStateInfo::getDemangledFullName(), smacc::SensorTopic< ClTemperatureSensor >::getEventLabel(), smacc::SmaccEventInfo::getEventSourceName(), smacc::SmaccEventInfo::getEventTypeName(), smacc::SmaccState< SsrFPatternStartLoop, SS >::getFullName(), smacc::Orthogonal::getName(), smacc::SmaccClientBehavior::getName(), smacc::ISmaccClient::getName(), smacc::ISmaccComponent::getName(), smacc::SmaccEventInfo::getObjectTagName(), smacc::ISmaccStateMachine::getStateMachineName(), smacc::TypeInfo::getTypeInfoFromTypeid(), smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::initialize(), smacc::ISmaccStateMachine::mapBehavior(), smacc::LuAllEventsGo::onEventNotified(), smacc::LuEventCountdown::onEventNotified(), sm_three_some::CbKeyboard::postKeyEvent(), sm_three_some::ClKeyboard::postKeyEvent(), smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::postResultEvent(), processTransitionAux(), smacc::ISmaccStateMachine::requiresComponent(), smacc::SmaccState< SsrFPatternStartLoop, SS >::SmaccState(), smacc::SmaccState< SsrFPatternStartLoop, SS >::static_configure(), and smacc::SmaccState< SsrFPatternStartLoop, SS >::~SmaccState().
{
    return demangleSymbol(name.c_str());
}
std::string smacc::demangleSymbol (const char * name) [inline]
Definition at line 48 of file introspection.h.
{
#if (__GNUC__ && __cplusplus && __GNUC__ >= 3)
    int status;
    char *res = abi::__cxa_demangle(name, 0, 0, &status);
    if (res)
    {
        const std::string demangled_name(res);
        std::free(res);
        return demangled_name;
    }
    // Demangling failed, fallback to mangled name
    return std::string(name);
#else
    return std::string(name);
#endif
}
template<typename T > std::string smacc::demangleSymbol () [inline]
Definition at line 67 of file introspection.h.
References demangleSymbol().
{
    return demangleSymbol(typeid(T).name());
}
std::string smacc::demangleType (const std::type_info & tinfo) [inline]
Definition at line 78 of file introspection.h.
References demangleSymbol().
Referenced by smacc::SmaccActionClientBase< move_base_msgs::MoveBaseAction >::configureEventSourceTypes(), smacc::Orthogonal::createClient(), smacc::SignalDetector::findUpdatableBehaviors(), smacc::SignalDetector::findUpdatableClients(), and smacc::SignalDetector::pollOnce().
{
    return demangleSymbol(tinfo.name());
}
template<typename T > std::enable_if<HasEventLabel<T>::value, void>::type smacc::EventLabel (std::string & label)
Definition at line 110 of file introspection.h.
{
    label = T::getEventLabel();
}
template<typename T > std::enable_if<!HasEventLabel<T>::value, void>::type smacc::EventLabel (std::string & label)
Definition at line 117 of file introspection.h.
{
    label = "";
}
template<typename TTransition > static std::string smacc::getTransitionType () [static]
Definition at line 230 of file introspection.h.
{
    std::string output;
    CheckType<TTransition> op(&output);
    using boost::mpl::_1;
    using wrappedList = typename boost::mpl::transform<DEFAULT_TRANSITION_TYPES, _1>::type;
    boost::mpl::for_each<wrappedList>(op);
    return output;
};
template<class T > auto smacc::optionalNodeHandle (boost::intrusive_ptr< T > & obj) -> decltype(obj->nh)
Definition at line 31 of file introspection.h.
Referenced by smacc::SmaccState< SsrFPatternStartLoop, SS >::SmaccState().
{
    return obj->nh;
}
template<class T > auto smacc::optionalNodeHandle (T *) -> ros::NodeHandle
Definition at line 38 of file introspection.h.
{
    return ros::NodeHandle("");
}
template<typename T > disable_if<boost::mpl::is_sequence<T> >::type smacc::processSubState (std::shared_ptr< SmaccStateInfo > & parentState)
Definition at line 107 of file smacc_state_machine_info.h.
References smacc::WalkStatesExecutor< InitialStateType >::walkStates().
{
    WalkStatesExecutor<T>::walkStates(parentState, false);
}
template<typename T > enable_if<boost::mpl::is_sequence<T> >::type smacc::processSubState (std::shared_ptr< SmaccStateInfo > & parentState)
Definition at line 115 of file smacc_state_machine_info.h.
{
    using boost::mpl::_1;
    using wrappedList = typename boost::mpl::transform<T, add_type_wrapper<_1>>::type;
    boost::mpl::for_each<wrappedList>(AddSubState(parentState));
}
template<typename Ev , typename Dst , typename Tag > void smacc::processTransition (smacc::transition< Ev, boost::statechart::deep_history< Dst >, Tag > * , std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 136 of file smacc_state_machine_info.h.
References processTransitionAux().
Referenced by processTransitions().
{
    auto transitionTypeInfo = smacc::TypeInfo::getTypeInfoFromType<smacc::transition<Ev,
       boost::statechart::deep_history<Dst>, Tag>>();
    smacc::transition<Ev, Dst, Tag> *mock;
    processTransitionAux(mock, sourceState, true, transitionTypeInfo);
}
template<typename Ev , typename Dst , typename Tag > void smacc::processTransition (smacc::transition< Ev, Dst, Tag > * t, std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 144 of file smacc_state_machine_info.h.
References processTransitionAux().
{
    auto transitionTypeInfo = smacc::TypeInfo::getTypeInfoFromType<smacc::transition<Ev, Dst, Tag>>();
    processTransitionAux(t, sourceState, false, transitionTypeInfo);
}
template<typename Ev , typename Dst > void smacc::processTransition (statechart::transition< Ev, Dst > * , std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 247 of file smacc_state_machine_info.h.
{
    //ROS_INFO_STREAM("GOTCHA");
}
template<typename Ev > void smacc::processTransition (statechart::custom_reaction< Ev > * , std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 253 of file smacc_state_machine_info.h.
{
    //ROS_INFO_STREAM("GOTCHA");
}
template<typename Ev , typename Dst , typename Tag > void smacc::processTransitionAux (smacc::transition< Ev, Dst, Tag > * , std::shared_ptr< SmaccStateInfo > & sourceState, bool history, smacc::TypeInfo::Ptr & transitionTypeInfo)
Definition at line 151 of file smacc_state_machine_info.h.
References demangleSymbol(), and smacc::WalkStatesExecutor< InitialStateType >::walkStates().
Referenced by processTransition().
{
    ROS_INFO("State %s Walker transition: %s", sourceState->toShortName().c_str(),
      demangleSymbol(typeid(Ev).name()).c_str());
    std::string transitionTag;
    std::string transitionType;
    if (typeid(Tag) != typeid(smacc::default_transition_name))
    {
        transitionTag = demangleSymbol<Tag>();
        transitionType = getTransitionType<Tag>();
        ROS_ERROR_STREAM("TRANSITION TYPE:" << transitionType);
    }
    else
    {
        transitionTag = "";
        automaticTransitionTag<Ev>(transitionTag);
        automaticTransitionType<Ev>(transitionType);
    }
    ROS_INFO_STREAM("Transition tag: " << transitionTag);
    if (!sourceState->stateMachine_->containsState<Dst>())
    {
        auto realparentState = sourceState->stateMachine_->getState<typename Dst::TContext>();
        auto siblingnode = sourceState->stateMachine_->createState<Dst>(realparentState);
        //auto siblingnode = sourceState->stateMachine_->createState<Dst>(sourceState->parentState_);
        WalkStatesExecutor<Dst>::walkStates(siblingnode, true);
        sourceState->declareTransition<Ev>(siblingnode, transitionTag, transitionType, history,
      transitionTypeInfo);
    }
    else
    {
        //auto realparentState = sourceState->stateMachine_->getState<typename Dst::TContext>();
        //auto siblingnode = sourceState->stateMachine_->createState<Dst>(realparentState);
        auto siblingnode = sourceState->stateMachine_->getState<Dst>();
        sourceState->declareTransition<Ev>(siblingnode, transitionTag, transitionType, history,
      transitionTypeInfo);
    }
}
template<typename T > enable_if<boost::mpl::is_sequence<T> >::type smacc::processTransitions (std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 126 of file smacc_state_machine_info.h.
{
    ROS_INFO_STREAM("State %s Walker has transition list");
    using boost::mpl::_1;
    using wrappedList = typename boost::mpl::transform<T, add_type_wrapper<_1>>::type;
    boost::mpl::for_each<wrappedList>(AddTransition(sourceState));
}
template<typename T > disable_if<boost::mpl::is_sequence<T> >::type smacc::processTransitions (std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 263 of file smacc_state_machine_info.h.
References processTransition().
{
    //ROS_INFO_STREAM("state transition from: " << sourceState->demangledStateName << " of type: " <<
       demangledTypeName<T>());
    T *dummy;
    processTransition(dummy, sourceState);
}
bool smacc::replace (std::string & str, const std::string & from, const std::string & to)
Definition at line 17 of file string_type_walker.cpp.
Referenced by smacc::TypeInfo::getTypeInfoFromString(), and replace_back().
{
    size_t start_pos = str.find(from);
    if (start_pos == std::string::npos)
        return false;
    str.replace(start_pos, from.length(), to);
    return true;
}
std::string smacc::replace_back (std::string roottype, std::map< std::string, std::string > & typesdict)
Definition at line 26 of file string_type_walker.cpp.
References replace(), and smacc::TypeInfo::typeInfoDatabase.
Referenced by regex_template::getRootTypeInfo(), and smacc::TypeInfo::getTypeInfoFromString().
{
    while (roottype.find("$") != std::string::npos)
    {
        for (auto &t : typesdict)
        {
            auto &tkey = t.first;
            auto &tval = t.second;
            replace(roottype, tkey, tval);
        }
    }
    return roottype;
    // def replace_back(roottype, typesdict):
    // # replace back
    // while "$" in roottype:
    // #print roottype
    // for tkey in typesdict:
    // tval = typesdict[tkey]
    // roottype = roottype.replace(tkey, tval)
    // return roottype
}
template<typename StateMachineType > void smacc::run ()
Definition at line 79 of file smacc_signal_detector.h.
References smacc::SignalDetector::pollingLoop(), and smacc::SignalDetector::setProcessorHandle().
{
    // create the asynchronous state machine scheduler
    SmaccFifoScheduler scheduler1(true);
    // create the signalDetector component
    SignalDetector signalDetector(&scheduler1);
    // create the asynchronous state machine processor
    SmaccFifoScheduler::processor_handle sm =
        scheduler1.create_processor<StateMachineType>(&signalDetector);
    // initialize the asynchronous state machine processor
    signalDetector.setProcessorHandle(sm);
    scheduler1.initiate_processor(sm);
    //create a thread for the asynchronous state machine processor execution
    boost::thread otherThread(boost::bind(&sc::fifo_scheduler<>::operator(), &scheduler1, 0));
    // use the main thread for the signal detector component (waiting actionclient requests)
    signalDetector.pollingLoop();
}
void smacc::transitionInfoToMsg (const SmaccTransitionInfo & transition, smacc_msgs::SmaccTransition & transitionMsg)
Definition at line 6 of file reflection.cpp.
References smacc::SmaccTransitionInfo::destinyState, smacc::SmaccTransitionInfo::eventInfo, smacc::SmaccTransitionInfo::historyNode, smacc::SmaccTransitionInfo::index, smacc::SmaccTransitionInfo::sourceState, smacc::SmaccTransitionInfo::transitionTag, and smacc::SmaccTransitionInfo::transitionType.
Referenced by smacc::SmaccStateMachineInfo::assembleSMStructureMessage(), and smacc::ISmaccStateMachine::publishTransition().
{
    transitionMsg.index = transition.index;
    transitionMsg.event.event_type = transition.eventInfo->getEventTypeName();
    transitionMsg.source_state_name = transition.sourceState->demangledStateName;
    
    transitionMsg.transition_name = transition.transitionTag;
    transitionMsg.transition_type = transition.transitionType;
    transitionMsg.event.event_source = transition.eventInfo->getEventSourceName();
    transitionMsg.event.event_object_tag = transition.eventInfo->getObjectTagName();
    transitionMsg.event.label = transition.eventInfo->label;
    transitionMsg.history_node = transition.historyNode;
    if (transition.historyNode)
    {
        if (transition.destinyState->parentState_ != nullptr)
            transitionMsg.destiny_state_name = transition.destinyState->parentState_->demangledStateName;
        else
            transitionMsg.destiny_state_name = "";
    }
    else
    {
        transitionMsg.destiny_state_name = transition.destinyState->demangledStateName;
    }
}