Ssr1 Struct Reference
#include <ssr_1.h>
Public Types
typedef smacc::transition< EvLoopContinue< Ssr1 >, Ssr2, CONTINUELOOP > reactions
Public Member Functions
void onInitialize ()
bool loopWhileCondition ()
void onEntry ()
Static Public Member Functions
static void onDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 1 of file ssr_1.h.
Member Typedef Documentation
typedef smacc::transition<EvLoopContinue<Ssr1>, Ssr2, CONTINUELOOP> Ssr1::reactions
Definition at line 6 of file ssr_1.h.
Member Function Documentation
bool Ssr1::loopWhileCondition () [inline]
Definition at line 18 of file ssr_1.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    ROS_INFO("Loop start, current iterations: %d, total iterations: %d", superstate.iteration_count,
      superstate.total_iterations());
    return superstate.iteration_count++ < superstate.total_iterations();
  }
static void Ssr1::onDefinition () [inline], [static]
Definition at line 9 of file ssr_1.h.
  {
  }
void Ssr1::onEntry () [inline]
Definition at line 26 of file ssr_1.h.
References loopWhileCondition(), and smacc::SmaccState< Ssr1, SS >::throwLoopEventFromCondition().
  {
    ROS_INFO("LOOP START ON ENTRY");
    throwLoopEventFromCondition(&
      Ssr1::loopWhileCondition);
  }
void Ssr1::onInitialize () [inline]
Definition at line 14 of file ssr_1.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_three_some/include/sm_three_some/superstate_routines/ss_superstate_1/ssr_1.h