SsrRadialLoopStart Struct Reference
#include <ssr_radial_loop_start.h>
Public Types
typedef smacc::transition< EvLoopContinue< SsrRadialLoopStart >, SsrRadialRotate, CONTINUELOOP > reactions
Public Member Functions
void onInitialize ()
bool loopWhileCondition ()
void onEntry ()
Static Public Member Functions
static void onDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 1 of file ssr_radial_loop_start.h.
Member Typedef Documentation
typedef smacc::transition<EvLoopContinue<SsrRadialLoopStart>, SsrRadialRotate, CONTINUELOOP> SsrRadialLoopStart::reactions
Definition at line 4 of file ssr_radial_loop_start.h.
Member Function Documentation
bool SsrRadialLoopStart::loopWhileCondition () [inline]
Definition at line 15 of file ssr_radial_loop_start.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    ROS_INFO("Loop start, current iterations: %d, total iterations: %d", superstate.iteration_count,
      superstate.total_iterations());
    return superstate.iteration_count++ < superstate.total_iterations();
  }
static void SsrRadialLoopStart::onDefinition () [inline], [static]
Definition at line 6 of file ssr_radial_loop_start.h.
  {
  }
void SsrRadialLoopStart::onEntry () [inline]
Definition at line 23 of file ssr_radial_loop_start.h.
References loopWhileCondition(), and smacc::SmaccState< SsrRadialLoopStart, SS >::throwLoopEventFromCondition().
  {
    ROS_INFO("LOOP START ON ENTRY");
    throwLoopEventFromCondition(&
      SsrRadialLoopStart::loopWhileCondition);
  }
void SsrRadialLoopStart::onInitialize () [inline]
Definition at line 11 of file ssr_radial_loop_start.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/superstate_routines/radial_motion/ssr_radial_loop_start.h