smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType > Struct Template Reference
State Machine.
#include <smacc_state_machine_base.h>
Public Member Functions
virtual void Reset ()
virtual void Stop ()
virtual void EStop ()
SmaccStateMachineBase (my_context ctx, SignalDetector *signalDetector)
virtual ~SmaccStateMachineBase ()
virtual void initiate_impl () override
template<typename T >
bool getParam (std::string param_name, T &param_storage)
template<typename T >
void setParam (std::string param_name, T param_val)
template<typename T >
bool param (std::string param_name, T &param_val, const T &default_val) const
void createStructureMessage (std::shared_ptr< SmaccStateInfo > container, std::string currentPath, std::vector< smacc_msgs::SmaccContainerStructure > &structure_msgs, int deep)
void recursivePublishStatus (std::shared_ptr< SmaccStateInfo > parentstate)
void state_machine_visualization (const ros::TimerEvent &)
Public Attributes
ros::NodeHandle nh
ros::Timer timer_
ros::Publisher stateMachineStructurePub_
ros::Publisher stateMachineStatePub_
Additional Inherited Members
Detailed Description
template<typename DerivedStateMachine, typename InitialStateType>
*
struct smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >
State Machine.
Definition at line 22 of file smacc_state_machine_base.h.
Constructor & Destructor Documentation
template<typename DerivedStateMachine, typename InitialStateType> smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::SmaccStateMachineBase (my_context ctx, SignalDetector * signalDetector) [inline]
Definition at line 53 of file smacc_state_machine_base.h.
       :ISmaccStateMachine(signalDetector),
        sc::asynchronous_state_machine<DerivedStateMachine, InitialStateType, SmaccScheduler,
       SmaccAllocator >(ctx)
    {
        ROS_ERROR("State machine base creation");
        nh = ros::NodeHandle(cleanShortTypeName(typeid(DerivedStateMachine)));
        info_ = std::make_shared<SmaccStateMachineInfo>();
        info_->buildStateMachineInfo<InitialStateType>();
        
        InitialStateType* test;
        updateCurrentState<InitialStateType>(true,test);
        
        info_->printAllStates();
    }
template<typename DerivedStateMachine, typename InitialStateType> virtual smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::~SmaccStateMachineBase () [inline], [virtual]
Definition at line 69 of file smacc_state_machine_base.h.
    {
        //updateCurrentState<InitialStateType>(false);
    }
Member Function Documentation
template<typename DerivedStateMachine, typename InitialStateType> void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::createStructureMessage (std::shared_ptr< SmaccStateInfo > container, std::string currentPath, std::vector< smacc_msgs::SmaccContainerStructure > & structure_msgs, int deep) [inline]
Definition at line 108 of file smacc_state_machine_base.h.
Referenced by smacc::SmaccStateMachineBase< SensorStateMachine, SensorState >::createStructureMessage(), and smacc::SmaccStateMachineBase< SensorStateMachine, SensorState >::state_machine_visualization().
    {
        if(deep ==0)
        {
            return;
        }
        smacc_msgs::SmaccContainerStructure structure_msg;
        structure_msg.header.stamp = ros::Time::now();
        std::string currentpathprefix;
        
        // ROOT STATE
        if(container==nullptr)
        {
            // THE NAME OF THE STATE MACHINE WITH A PREFIX '/' CHARACTER
            currentpathprefix = "/" + currentPath;
            structure_msg.path= currentpathprefix;
        }
        else // IT IS A SUBSTATE
        {
            if(currentPath!="")
                currentpathprefix = currentPath + "/" ;
            else
                currentpathprefix = "/";
            structure_msg.path = currentpathprefix + container->demangledStateName;
        }
        static int i =0;
        for(auto& val: info_->states)
        {
            // childstate
            auto state = val.second;
            std::stringstream ss;
            if(state->parentState_== container)
            {
                structure_msg.children.push_back(state->toShortName());
                for(auto& transition: state->transitions_)
                {
                    structure_msg.internal_outcomes.push_back("success");//transition.first);
                    structure_msg.outcomes_to.push_back(transition.destinyState->toShortName());
                    structure_msg.outcomes_from.push_back(state->toShortName()); // or
       transition.sourceState
                }
                if(state->parentState_!=nullptr)
                {
                    structure_msg.outcomes_to.push_back("success");
                    structure_msg.outcomes_from.push_back(state->toShortName());
                    structure_msg.container_outcomes.push_back("success");
                }
                /*
                if(state->transitions_.size() > 0)
                    structure_msg.container_outcomes.push_back(state->transitions_.begin()->first);
                else if(state->parentState_!=nullptr && state->parentState_->transitions_.size()>0)
       structure_msg.container_outcomes.push_back(state->parentState_->transitions_.begin()->first);
                */
                
                createStructureMessage(state, structure_msg.path, structure_msgs,
      deep -1);
            }
        }
        structure_msgs.push_back(structure_msg);
    }
template<typename DerivedStateMachine, typename InitialStateType> virtual void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::EStop () [inline], [virtual]
Reimplemented from smacc::ISmaccStateMachine.
Definition at line 47 of file smacc_state_machine_base.h.
    {
        ISmaccStateMachine::EStop();
        this->terminate();
    }
template<typename DerivedStateMachine, typename InitialStateType> template<typename T > bool smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::getParam (std::string param_name, T & param_storage) [inline]
Definition at line 89 of file smacc_state_machine_base.h.
    {
        return nh.getParam(param_name, param_storage);
    }
template<typename DerivedStateMachine, typename InitialStateType> virtual void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::initiate_impl () [inline], [override], [virtual]
Definition at line 75 of file smacc_state_machine_base.h.
    {
        ROS_INFO("initiate_impl");
        sc::state_machine< DerivedStateMachine, InitialStateType, SmaccAllocator >::initiate();
        timer_= nh.createTimer(ros::Duration(0.1),&
      SmaccStateMachineBase<DerivedStateMachine,InitialStateType>::state_machine_visualization
      , this);
        auto stateMachineName = this->getStateMachineName();
        stateMachineStructurePub_=nh.advertise<
      smacc_msgs::SmaccContainerStructure>("/"+ stateMachineName + "/smacc/container_structure",1);
        stateMachineStatePub_ = nh.advertise<smacc_msgs::SmaccContainerStatus>("/"+
      stateMachineName + "/smacc/container_status",1);
    }
template<typename DerivedStateMachine, typename InitialStateType> template<typename T > bool smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::param (std::string param_name, T & param_val, const T & default_val) const [inline]
Definition at line 103 of file smacc_state_machine_base.h.
    {
        return nh.param(param_name, param_val, default_val);
    }
template<typename DerivedStateMachine, typename InitialStateType> void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::recursivePublishStatus (std::shared_ptr< SmaccStateInfo > parentstate) [inline]
Definition at line 175 of file smacc_state_machine_base.h.
Referenced by smacc::SmaccStateMachineBase< SensorStateMachine, SensorState >::recursivePublishStatus(), and smacc::SmaccStateMachineBase< SensorStateMachine, SensorState >::state_machine_visualization().
    {
        //ROS_WARN_STREAM("*" + parentstate->toShortName());
        smacc_msgs::SmaccContainerStatus status_msg;
        status_msg.header.stamp = ros::Time::now();
        auto stateMachineName = this->getStateMachineName();
        if(parentstate==nullptr)
        {
            status_msg.path = "/" + stateMachineName;
            for(auto& val: info_->states)
            {
                auto state = val.second;
                if(state->parentState_!=nullptr // only root elements
                    || !state->active_)
                        continue;
                //ROS_WARN_STREAM("active root state: " << state->toShortName());
                status_msg.active_states.push_back(state->toShortName());
            }
            status_msg.info = "HEART BEAT";
    
            status_msg.local_data.resize(6);
            status_msg.local_data[0] = 0x80;
            status_msg.local_data[1] = 0x02;
            status_msg.local_data[2] = 0x7d;
            status_msg.local_data[3] = 0x71;
            status_msg.local_data[4] = 0x00;
            status_msg.local_data[5] = 0x2e;
            stateMachineStatePub_.publish(status_msg);
            for(auto& val: info_->states)
            {
                auto state = val.second;
                if(state->parentState_!=nullptr // only root elements
                    || !state->active_)
                        continue;
                recursivePublishStatus(state);
            }
        }
        else
        {
            status_msg.path = "/" + stateMachineName + "/" + parentstate->getFullPath();
            //status_msg.initial_states.push_back("NavigateToRadialStart");
            for(auto& child: parentstate->children_)
            {
                if(child->active_)
                {
                    //ROS_WARN_STREAM("active child state ("<< parentstate->toShortName()<<"): " <<
       child->toShortName());
                    status_msg.active_states.push_back(child->toShortName());
                }
            }
             status_msg.info = "HEART BEAT";
        
            status_msg.local_data.resize(6);
            status_msg.local_data[0] = 0x80;
            status_msg.local_data[1] = 0x02;
            status_msg.local_data[2] = 0x7d;
            status_msg.local_data[3] = 0x71;
            status_msg.local_data[4] = 0x00;
            status_msg.local_data[5] = 0x2e;
            stateMachineStatePub_.publish(status_msg);
            for(auto& child: parentstate->children_)
            {
                if(child->active_ && !child->children_.empty())
                {
                    recursivePublishStatus(child);
                }
            }
        }
    }
template<typename DerivedStateMachine, typename InitialStateType> virtual void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::Reset () [inline], [virtual]
Reimplemented from smacc::ISmaccStateMachine.
Definition at line 34 of file smacc_state_machine_base.h.
    {
        ISmaccStateMachine::Reset();
        this->terminate();
        smacc::run<DerivedStateMachine>();
    }
template<typename DerivedStateMachine, typename InitialStateType> template<typename T > void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::setParam (std::string param_name, T param_val) [inline]
Definition at line 96 of file smacc_state_machine_base.h.
    {
        return nh.setParam(param_name, param_val);
    }
template<typename DerivedStateMachine, typename InitialStateType> void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::state_machine_visualization (const ros::TimerEvent &) [inline]
Definition at line 258 of file smacc_state_machine_base.h.
    {
    /*
    header:
    seq: 24
    stamp:
        secs: 1545148095
        nsecs: 148165941
    frame_id: ''
    path: "/SM_ROOT"
    children: [FOO, BAR]
    internal_outcomes: [outcome1, outcome2, outcome2]
    outcomes_from: [FOO, FOO, BAR]
    outcomes_to: [BAR, outcome4, FOO]
    container_outcomes: [outcome4, outcome5]
    */
    std::vector<smacc_msgs::SmaccContainerStructure> structure_msgs;
    auto stateMachineName = this->getStateMachineName();
    createStructureMessage(nullptr, stateMachineName , structure_msgs,-1);
    /*
    structure_msg.children.push_back("NavigateToEndPoint");
    structure_msg.children.push_back("NavigateToRadialStart");
    structure_msg.children.push_back("ReturnToRadialStart");
    structure_msg.children.push_back("RotateDegress");
    */
    /*
    structure_msg.container_outcomes.push_back("ev1");
    structure_msg.container_outcomes.push_back("ev2");
    structure_msg.container_outcomes.push_back("ev3");
    structure_msg.container_outcomes.push_back("ev4");
    */
    
    /*structure_msg.internal_outcomes.push_back("ev1");
    structure_msg.internal_outcomes.push_back("ev2");
    structure_msg.internal_outcomes.push_back("ev2");
    structure_msg.internal_outcomes.push_back("ev2");
    structure_msg.outcomes_from.push_back("NavigateToEndPoint");
    structure_msg.outcomes_from.push_back("NavigateToRadialStart");
    structure_msg.outcomes_from.push_back("ReturnToRadialStart");
    structure_msg.outcomes_from.push_back("RotateDegress");
    structure_msg.outcomes_to.push_back("ReturnToRadialStart");
    structure_msg.outcomes_to.push_back("NavigateToEndPoint");
    structure_msg.outcomes_to.push_back("RotateDegress");
    structure_msg.outcomes_to.push_back("NavigateToEndPoint");
*/
    for(int i= structure_msgs.size() -1 ; i >= 0 ; i--)
    {
        for(auto& structure_msg: structure_msgs)
        {
            stateMachineStructurePub_.publish(structure_msgs[i]);
        }
    }
    
    recursivePublishStatus(nullptr);
    
    /*
    if(currentState_ !=nullptr && currentState_->parentState_==nullptr)
    {
        smacc_msgs::SmaccContainerStatus status_msg;
        status_msg.header.stamp = ros::Time::now();
        status_msg.path = "/RadialMotion";
        status_msg.initial_states.push_back("NavigateToRadialStart");
        status_msg.active_states.push_back(currentState_->toShortName());
        status_msg.info = "HEART BEAT";
        status_msg.local_data.resize(6);
        status_msg.local_data[0] = 0x80;
        status_msg.local_data[1] = 0x02;
        status_msg.local_data[2] = 0x7d;
        status_msg.local_data[3] = 0x71;
        status_msg.local_data[4] = 0x00;
        status_msg.local_data[5] = 0x2e;
        stateMachineStatePub_.publish(status_msg);
    }*/
//
    /*
    ---
    header:
    seq: 316
    stamp:
        secs: 1545154196
        nsecs: 289685964
    frame_id: ''
    path: "/SM_ROOT"
    initial_states: [FOO]
    active_states: [None]
    local_data: !!binary |
    gAJ9cQAu
    info: "HEART BEAT"
    */
    
}
template<typename DerivedStateMachine, typename InitialStateType> virtual void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::Stop () [inline], [virtual]
Reimplemented from smacc::ISmaccStateMachine.
Definition at line 41 of file smacc_state_machine_base.h.
    {
        ISmaccStateMachine::Stop();
        this->terminate();
    }
Member Data Documentation
template<typename DerivedStateMachine, typename InitialStateType> ros::NodeHandle smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::nh
Definition at line 26 of file smacc_state_machine_base.h.
template<typename DerivedStateMachine, typename InitialStateType> ros::Publisher smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::stateMachineStatePub_
Definition at line 30 of file smacc_state_machine_base.h.
template<typename DerivedStateMachine, typename InitialStateType> ros::Publisher smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::stateMachineStructurePub_
Definition at line 29 of file smacc_state_machine_base.h.
template<typename DerivedStateMachine, typename InitialStateType> ros::Timer smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::timer_
Definition at line 28 of file smacc_state_machine_base.h.
The documentation for this struct was generated from the following file:
smacc/include/smacc/smacc_state_machine_base.h