smacc::WalkStatesExecutor< InitialStateType > Struct Template Reference
#include <smacc_state_machine_info.h>
Static Public Member Functions
static void walkStates (std::shared_ptr< SmaccStateInfo > &currentState, bool rootInitialNode)
Detailed Description
template<typename InitialStateType>
*
struct smacc::WalkStatesExecutor< InitialStateType >
Definition at line 91 of file smacc_state_machine_info.h.
Member Function Documentation
template<typename InitialStateType > void smacc::WalkStatesExecutor< InitialStateType >::walkStates (std::shared_ptr< SmaccStateInfo > & currentState, bool rootInitialNode) [static]
Definition at line 363 of file smacc_state_machine_info.h.
Referenced by smacc::SmaccStateMachineInfo::buildStateMachineInfo(), smacc::AddSubState::operator()(), smacc::processSubState(), and smacc::processTransitionAux().
{
    //ros::Duration(1).sleep();
    auto currentname = demangledTypeName<InitialStateType>();
    std::shared_ptr<SmaccStateInfo> targetState;
    if (!rootInitialNode)
    {
        if (parentState->stateMachine_->containsState<InitialStateType>())
        {
            // it already exist: break;
            return;
        }
        targetState = parentState->createChildState<InitialStateType>();
    }
    else
    {
        targetState = parentState;
    }
    CallOnDefinition<InitialStateType>();
    typedef typename std::remove_pointer<decltype(InitialStateType::smacc_inner_type)>::type InnerType;
    processSubState<InnerType>(targetState);
    // -------------------- REACTIONS --------------------
    typedef typename InitialStateType::reactions reactions;
    //ROS_INFO_STREAM("state machine initial state reactions: "<< demangledTypeName<reactions>());
    processTransitions<reactions>(targetState);
}
The documentation for this struct was generated from the following file:
smacc/include/smacc/introspection/smacc_state_machine_info.h