sm_dance_bot_2::radial_motion_states::SsrRadialEndPoint Struct Reference
#include <ssr_radial_end_point.h>
Public Types
typedef mpl::list< smacc::transition< EvActionSucceeded< ClMoveBaseZ, OrNavigation >, SsrRadialReturn, SUCCESS >, smacc::transition< EvActionAborted< ClMoveBaseZ, OrNavigation >, SsrRadialRotate, ABORT > > reactions
Public Member Functions
void onInitialize ()
Static Public Member Functions
static void onDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file ssr_radial_end_point.h.
Member Typedef Documentation
typedef mpl::list< smacc::transition<EvActionSucceeded<ClMoveBaseZ, OrNavigation>, SsrRadialReturn, SUCCESS>, smacc::transition<EvActionAborted<ClMoveBaseZ, OrNavigation>, SsrRadialRotate, ABORT> > sm_dance_bot_2::radial_motion_states::SsrRadialEndPoint::reactions
Definition at line 13 of file ssr_radial_end_point.h.
Member Function Documentation
static void sm_dance_bot_2::radial_motion_states::SsrRadialEndPoint::onDefinition () [inline], [static]
Definition at line 15 of file ssr_radial_end_point.h.
  {
    ROS_INFO("ssr radial end point, distance in meters: %lf", SS::ray_length_meters());
    static_configure<OrNavigation, CbNavigateForward>();
  }
void sm_dance_bot_2::radial_motion_states::SsrRadialEndPoint::onInitialize () [inline]
Definition at line 21 of file ssr_radial_end_point.h.
References smacc::ISmaccClient::getComponent(), smacc::ISmaccStateMachine::getOrthogonal(), smacc::SmaccState< SsrRadialEndPoint, SS >::getStateMachine(), and smacc::ISmaccState::requiresClient().
  {
    cl_lidar::ClLaserSensor *lidarClient;
    this->requiresClient(lidarClient);
    auto lidarData = lidarClient->getComponent<CpLidarSensorData>();
    auto forwardBehavior = this->getStateMachine()
                               .getOrthogonal<OrNavigation>()
                               ->getClientBehavior<CbNavigateForward>();
    double forwarddist = 10;
    if (lidarData->forwardObstacleDistance == std::numeric_limits<float>::infinity() || lidarData->
      forwardObstacleDistance != lidarData->forwardObstacleDistance) // check not is a nan (sensor max dist)
    {
      ROS_INFO("Distance to forward obstacle is not a number, setting default value to: %lf", forwarddist);
    }
    else
    {
      forwarddist = lidarData->forwardObstacleDistance - 0.8 /*meters*/;
    }
    forwardBehavior->forwardDistance = forwarddist;
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot_2/include/sm_dance_bot_2/states/radial_motion_states/ssr_radial_end_point.h