SsrFPatternStartLoop Struct Reference
#include <ssr_fpattern_loop_start.h>
Public Types
typedef smacc::transition< EvLoopContinue< SsrFPatternStartLoop >, SsrFPatternRotate1, CONTINUELOOP > reactions
Public Member Functions
bool loopCondition ()
void onEntry ()
Static Public Member Functions
static void onDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 1 of file ssr_fpattern_loop_start.h.
Member Typedef Documentation
typedef smacc::transition<EvLoopContinue<SsrFPatternStartLoop>, SsrFPatternRotate1, CONTINUELOOP> SsrFPatternStartLoop::reactions
Definition at line 5 of file ssr_fpattern_loop_start.h.
Member Function Documentation
bool SsrFPatternStartLoop::loopCondition () [inline]
Definition at line 11 of file ssr_fpattern_loop_start.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    return ++superstate.iteration_count < SS::total_iterations();
  }
static void SsrFPatternStartLoop::onDefinition () [inline], [static]
Definition at line 7 of file ssr_fpattern_loop_start.h.
  {
  }
void SsrFPatternStartLoop::onEntry () [inline]
Definition at line 17 of file ssr_fpattern_loop_start.h.
References loopCondition(), and smacc::SmaccState< SsrFPatternStartLoop, SS >::throwLoopEventFromCondition().
  {
    throwLoopEventFromCondition(&
      SsrFPatternStartLoop::loopCondition);
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/superstate_routines/f_pattern/ssr_fpattern_loop_start.h