sm_dance_bot_2::StNavigateToWaypointsX Struct Reference
#include <st_navigate_to_waypoints_x.h>
Classes
struct TRANSITION_1
struct TRANSITION_2
struct TRANSITION_3
struct TRANSITION_4
struct TRANSITION_5
Public Types
typedef mpl::list< smacc::Transition< EvWaypoint0< ClMoveBaseZ, OrNavigation >, SS1::SsRadialPattern1, TRANSITION_1 >, smacc::Transition< EvWaypoint1< ClMoveBaseZ, OrNavigation >, SS1::SsRadialPattern1, TRANSITION_2 >, smacc::Transition< EvWaypoint2< ClMoveBaseZ, OrNavigation >, SS1::SsRadialPattern1, TRANSITION_3 >, smacc::Transition< EvActionAborted< ClMoveBaseZ, OrNavigation >, StNavigateToWaypointsX > > reactions
Public Member Functions
void onInitialize ()
void loadWaypointsFirstTime (WaypointNavigator *waypointsNavigator)
Static Public Member Functions
static void onDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 9 of file st_navigate_to_waypoints_x.h.
Member Typedef Documentation
typedef mpl::list< smacc::Transition<EvWaypoint0<ClMoveBaseZ, OrNavigation>, SS1::SsRadialPattern1, TRANSITION_1>, smacc::Transition<EvWaypoint1<ClMoveBaseZ, OrNavigation>, SS1::SsRadialPattern1, TRANSITION_2>, smacc::Transition<EvWaypoint2<ClMoveBaseZ, OrNavigation>, SS1::SsRadialPattern1, TRANSITION_3>, smacc::Transition<EvActionAborted<ClMoveBaseZ, OrNavigation>, StNavigateToWaypointsX> > sm_dance_bot_2::StNavigateToWaypointsX::reactions
Definition at line 38 of file st_navigate_to_waypoints_x.h.
Member Function Documentation
void sm_dance_bot_2::StNavigateToWaypointsX::loadWaypointsFirstTime (WaypointNavigator * waypointsNavigator) [inline]
Definition at line 59 of file st_navigate_to_waypoints_x.h.
References move_base_z_client::WaypointNavigator::getWaypoints(), and move_base_z_client::WaypointNavigator::loadWayPointsFromFile().
  {
    // if it is the first time and the waypoints navigator is not configured
    if (waypointsNavigator->getWaypoints().size() == 0)
    {
      std::string planfilepath;
      ros::NodeHandle nh("~");
      if (nh.getParam("/sm_dance_bot_2/waypoints_plan", planfilepath))
      {
        waypointsNavigator->loadWayPointsFromFile(planfilepath);
      }
    }
  }
static void sm_dance_bot_2::StNavigateToWaypointsX::onDefinition () [inline], [static]
Definition at line 42 of file st_navigate_to_waypoints_x.h.
  {
    //static_configure<OrObstaclePerception, CbLidarSensor>();
  }
void sm_dance_bot_2::StNavigateToWaypointsX::onInitialize () [inline]
Definition at line 47 of file st_navigate_to_waypoints_x.h.
References smacc::ISmaccClient::getComponent().
  {
    ClMoveBaseZ *move_base;
    this->requiresClient(move_base);
    auto waypointsNavigator = move_base->getComponent<
      WaypointNavigator>();
    loadWaypointsFirstTime(waypointsNavigator);
    waypointsNavigator->sendNextGoal();
    ROS_INFO("current iteration waypoints x: %ld", waypointsNavigator->getCurrentWaypointIndex());
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot_2/include/sm_dance_bot_2/states/st_navigate_to_waypoints_x.h