smacc::introspection::SmaccEventInfo Struct Reference
#include <smacc_state_info.h>
Public Member Functions
SmaccEventInfo (std::shared_ptr< TypeInfo > eventType)
std::string getEventTypeName ()
std::string getEventSourceName ()
std::string getObjectTagName ()
Public Attributes
std::string label
std::shared_ptr< TypeInfo > eventType
Detailed Description
Definition at line 19 of file smacc_state_info.h.
Constructor & Destructor Documentation
smacc::SmaccEventInfo::SmaccEventInfo (std::shared_ptr< TypeInfo > eventType)
Definition at line 67 of file smacc_state_info.cpp.
{
    ROS_INFO_STREAM("CREATING EVENT INFO: " << eventType->getFullName());
    this->eventType = eventType;
}
Member Function Documentation
std::string smacc::SmaccEventInfo::getEventSourceName ()
Definition at line 74 of file smacc_state_info.cpp.
References smacc::introspection::demangleSymbol().
{
    if (eventType->templateParameters.size() > 0)
    {
        auto eventsourcename = demangleSymbol(eventType->templateParameters[0]->
      getFullName().c_str());
        return eventsourcename;
    }
    else
    {
        return "";
    }
}
std::string smacc::SmaccEventInfo::getEventTypeName ()
Definition at line 87 of file smacc_state_info.cpp.
References smacc::introspection::demangleSymbol().
{
    return demangleSymbol(eventType->getNonTemplatetypename().c_str());
}
std::string smacc::SmaccEventInfo::getObjectTagName ()
Definition at line 92 of file smacc_state_info.cpp.
References smacc::introspection::demangleSymbol().
{
    if (eventType->templateParameters.size() > 1)
    {
        return demangleSymbol(eventType->templateParameters[1]->getFullName().c_str(
      ));
    }
    else
    {
        return "";
    }
}
Member Data Documentation
std::shared_ptr<TypeInfo> smacc::introspection::SmaccEventInfo::eventType
Definition at line 31 of file smacc_state_info.h.
std::string smacc::introspection::SmaccEventInfo::label
Definition at line 29 of file smacc_state_info.h.
The documentation for this struct was generated from the following files:
smacc/include/smacc/introspection/smacc_state_info.h
smacc/src/smacc/smacc_state_info.cpp