sm_atomic::SbState1 Struct Reference
#include <sb_state_1.h>
Public Member Functions
virtual void onEntry () override
void goToEndPoint ()
Public Attributes
smacc::SmaccMoveBaseActionClient * moveBaseClient_
Detailed Description
Definition at line 7 of file sb_state_1.h.
Member Function Documentation
void sm_atomic::SbState1::goToEndPoint () [inline]
Definition at line 18 of file sb_state_1.h.
References smacc::SmaccActionClientBase< TDerived, ActionType >::sendGoal().
Referenced by onEntry().
    {
        geometry_msgs::PoseStamped radialStartPose;
        smacc::SmaccMoveBaseActionClient::Goal goal;
        goal.target_pose.header.stamp = ros::Time::now();
        goal.target_pose = radialStartPose;
        goal.target_pose.pose.position.x = 10;
        goal.target_pose.pose.position.y = 10;
        goal.target_pose.pose.orientation =
            tf::createQuaternionMsgFromRollPitchYaw(0, 0, M_PI);
        moveBaseClient_->sendGoal(goal);
    }
virtual void sm_atomic::SbState1::onEntry () [inline], [override], [virtual]
Reimplemented from smacc::SmaccSubStateBehavior.
Definition at line 11 of file sb_state_1.h.
References goToEndPoint(), and smacc::SmaccSubStateBehavior::requiresClient().
    {
        ROS_INFO("Entering State1");
        this->requiresClient(moveBaseClient_);
        goToEndPoint();
    }
Member Data Documentation
smacc::SmaccMoveBaseActionClient* sm_atomic::SbState1::moveBaseClient_
Definition at line 9 of file sb_state_1.h.
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_atomic/include/sm_atomic/substate_behaviors/sb_state_1.h