sm_dance_bot::StNavigateToWaypointsX Struct Reference
#include <st_navigate_to_waypoints_x.h>
Classes
struct TRANSITION_1
struct TRANSITION_2
struct TRANSITION_3
struct TRANSITION_4
struct TRANSITION_5
Public Types
typedef mpl::list< smacc::transition< EvWaypoint0< ClMoveBaseZ, OrNavigation >, SS1::SsRadialPattern1, TRANSITION_1 >, smacc::transition< EvWaypoint1< ClMoveBaseZ, OrNavigation >, SS2::SsRadialPattern2, TRANSITION_2 >, smacc::transition< EvWaypoint2< ClMoveBaseZ, OrNavigation >, SS3::SsRadialPattern3, TRANSITION_3 >, smacc::transition< EvWaypoint3< ClMoveBaseZ, OrNavigation >, SS4::SsFPattern1, TRANSITION_4 >, smacc::transition< EvWaypoint4< ClMoveBaseZ, OrNavigation >, SS5::SsSPattern1, TRANSITION_5 >, smacc::transition< EvActionAborted< smacc::ClMoveBaseZ, OrNavigation >, StNavigateToWaypointsX > > reactions
Public Member Functions
void onInitialize ()
void loadWaypointsFirstTime (WaypointNavigator *waypointsNavigator)
Static Public Member Functions
static void onDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 6 of file st_navigate_to_waypoints_x.h.
Member Typedef Documentation
typedef mpl::list< smacc::transition<EvWaypoint0<ClMoveBaseZ, OrNavigation>, SS1::SsRadialPattern1, TRANSITION_1>, smacc::transition<EvWaypoint1<ClMoveBaseZ, OrNavigation>, SS2::SsRadialPattern2, TRANSITION_2>, smacc::transition<EvWaypoint2<ClMoveBaseZ, OrNavigation>, SS3::SsRadialPattern3, TRANSITION_3>, smacc::transition<EvWaypoint3<ClMoveBaseZ, OrNavigation>, SS4::SsFPattern1, TRANSITION_4>, smacc::transition<EvWaypoint4<ClMoveBaseZ, OrNavigation>, SS5::SsSPattern1, TRANSITION_5>, smacc::transition<EvActionAborted<smacc::ClMoveBaseZ, OrNavigation>, StNavigateToWaypointsX> > sm_dance_bot::StNavigateToWaypointsX::reactions
Definition at line 37 of file st_navigate_to_waypoints_x.h.
Member Function Documentation
void sm_dance_bot::StNavigateToWaypointsX::loadWaypointsFirstTime (WaypointNavigator * waypointsNavigator) [inline]
Definition at line 59 of file st_navigate_to_waypoints_x.h.
References smacc::ISmaccState::nh.
Referenced by onInitialize().
  {
    // if it is the first time and the waypoints navigator is not configured
    if (waypointsNavigator->getWaypoints().size() == 0)
    {
      std::string planfilepath;
      ros::NodeHandle nh("~");
      if (nh.getParam("/sm_dance_bot/waypoints_plan", planfilepath))
      {
        waypointsNavigator->loadWayPointsFromFile(planfilepath);
      }
    }
  }
static void sm_dance_bot::StNavigateToWaypointsX::onDefinition () [inline], [static]
Definition at line 41 of file st_navigate_to_waypoints_x.h.
  {
    static_configure<OrTool, CbToolStart>();
    static_configure<OrObstaclePerception, CbLidarSensor>();
  }
void sm_dance_bot::StNavigateToWaypointsX::onInitialize () [inline]
Definition at line 47 of file st_navigate_to_waypoints_x.h.
References loadWaypointsFirstTime(), and smacc::ISmaccState::requiresClient().
  {
    ClMoveBaseZ *move_base;
    this->requiresClient(move_base);
    auto waypointsNavigator = move_base->getComponent<WaypointNavigator>();
    loadWaypointsFirstTime(waypointsNavigator);
    waypointsNavigator->sendNextGoal();
    ROS_INFO("current iteration waypoints x: %ld", waypointsNavigator->getCurrentWaypointIndex());
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/states/st_navigate_to_waypoints_x.h