SsrSPatternLoopStart Struct Reference
#include <ssr_spattern_loop_start.h>
Public Types
typedef mpl::list< smacc::transition< EvLoopContinue< SsrSPatternLoopStart >, SsrSPatternRotate1, CONTINUELOOP > > reactions
Public Member Functions
void onInitialize ()
bool loopCondition ()
void onEntry ()
Static Public Member Functions
static void onDefinition ()
Additional Inherited Members
Detailed Description
Definition at line 1 of file ssr_spattern_loop_start.h.
Member Typedef Documentation
typedef mpl::list<smacc::transition<EvLoopContinue<SsrSPatternLoopStart>, SsrSPatternRotate1, CONTINUELOOP> > SsrSPatternLoopStart::reactions
Definition at line 5 of file ssr_spattern_loop_start.h.
Member Function Documentation
bool SsrSPatternLoopStart::loopCondition () [inline]
Definition at line 16 of file ssr_spattern_loop_start.h.
Referenced by onEntry().
  {
    auto &superstate = this->context<SS>();
    return ++superstate.iteration_count == superstate.total_iterations();
  }
static void SsrSPatternLoopStart::onDefinition () [inline], [static]
Definition at line 7 of file ssr_spattern_loop_start.h.
  {
  }
void SsrSPatternLoopStart::onEntry () [inline]
Definition at line 22 of file ssr_spattern_loop_start.h.
References loopCondition(), and smacc::SmaccState< SsrSPatternLoopStart, SS >::throwLoopEventFromCondition().
  {
    throwLoopEventFromCondition(&
      SsrSPatternLoopStart::loopCondition);
  }
void SsrSPatternLoopStart::onInitialize () [inline]
Definition at line 12 of file ssr_spattern_loop_start.h.
  {
  }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_dance_bot/include/sm_dance_bot/states/s_pattern/ssr_spattern_loop_start.h