Navigate Struct Reference
Public Types
typedef mpl::list< sc::transition< EvActionResult< SmaccMoveBaseActionClient::Result >, ExecuteToolState > > reactions
typedef mpl::list< sc::custom_reaction< EvActionResult< SmaccMoveBaseActionClient::Result > > > reactions
Public Member Functions
Navigate (my_context ctx)
void goToEndPoint ()
Navigate (my_context ctx)
void goToEndPoint ()
Navigate (my_context ctx)
void goToEndPoint ()
sc::result react (const EvActionResult< SmaccMoveBaseActionClient::Result > &ev)
Public Attributes
smacc::SmaccMoveBaseActionClient * moveBaseClient_
Additional Inherited Members
Detailed Description
Definition at line 22 of file example2.cpp.
Member Typedef Documentation
typedef mpl::list<sc::transition<EvActionResult<SmaccMoveBaseActionClient::Result>, ExecuteToolState> > Navigate::reactions
Definition at line 28 of file example3.cpp.
typedef mpl::list<sc::custom_reaction<EvActionResult<SmaccMoveBaseActionClient::Result> > > Navigate::reactions
Definition at line 28 of file example4.cpp.
Constructor & Destructor Documentation
Navigate::Navigate (my_context ctx) [inline]
Definition at line 32 of file example2.cpp.
                          :
    SmaccState<Navigate, SimpleStateMachine> (
      ctx)
  {
    ROS_INFO("Entering Navigate");
    // this substate will need access to the "MoveBase" resource or plugin. In this line
    // you get the reference to this resource.
    context<SimpleStateMachine>().requiresComponent<smacc::SmaccMoveBaseActionClient>(
      moveBaseClient_, ros::NodeHandle("move_base"));
    goToEndPoint();
  }
Navigate::Navigate (my_context ctx) [inline]
Definition at line 37 of file example3.cpp.
                          :
    SmaccState<Navigate, SimpleStateMachine> (
      ctx)
  {
    ROS_INFO("Entering Navigate");
    // this substate will need access to the "MoveBase" resource or plugin. In this line
    // you get the reference to this resource.
    context<SimpleStateMachine>().requiresComponent<smacc::SmaccMoveBaseActionClient>(
      moveBaseClient_ , ros::NodeHandle("move_base"));
    goToEndPoint();
  }
Navigate::Navigate (my_context ctx) [inline]
Definition at line 37 of file example4.cpp.
                          :
    SmaccState<Navigate, SimpleStateMachine> (
      ctx)
  {
    ROS_INFO("Entering Navigate");
    // this substate will need access to the "MoveBase" resource or plugin. In this line
    // you get the reference to this resource.
    context<SimpleStateMachine>().requiresComponent<smacc::SmaccMoveBaseActionClient>(
      moveBaseClient_, ros::NodeHandle("move_base"));
    goToEndPoint();
  }
Member Function Documentation
void Navigate::goToEndPoint () [inline]
Definition at line 44 of file example2.cpp.
References smacc::SmaccActionClientBase< ActionType >::sendGoal().
                      {
    geometry_msgs::PoseStamped radialStartPose;
    this->getGlobalSMData("radial_start_pose", radialStartPose);
    smacc::SmaccMoveBaseActionClient::Goal goal;
    goal.target_pose.header.stamp = ros::Time::now();
    goal.target_pose = radialStartPose;
    goal.target_pose.pose.position.x = 10;
    goal.target_pose.pose.position.y = 10;
    goal.target_pose.pose.orientation =
        tf::createQuaternionMsgFromRollPitchYaw(0, 0, M_PI);
    moveBaseClient_->sendGoal(goal);
  }
void Navigate::goToEndPoint () [inline]
Definition at line 49 of file example3.cpp.
References smacc::SmaccActionClientBase< ActionType >::sendGoal().
                      {
    geometry_msgs::PoseStamped radialStartPose;
    this->getGlobalSMData("radial_start_pose", radialStartPose);
    smacc::SmaccMoveBaseActionClient::Goal goal;
    goal.target_pose.header.stamp = ros::Time::now();
    goal.target_pose = radialStartPose;
    goal.target_pose.pose.position.x = 10;
    goal.target_pose.pose.position.y = 10;
    goal.target_pose.pose.orientation =
        tf::createQuaternionMsgFromRollPitchYaw(0, 0, M_PI);
    moveBaseClient_->sendGoal(goal);
  }
void Navigate::goToEndPoint () [inline]
Definition at line 49 of file example4.cpp.
References smacc::SmaccActionClientBase< ActionType >::sendGoal().
                      {
    geometry_msgs::PoseStamped radialStartPose;
    this->getGlobalSMData("radial_start_pose", radialStartPose);
    smacc::SmaccMoveBaseActionClient::Goal goal;
    goal.target_pose.header.stamp = ros::Time::now();
    goal.target_pose = radialStartPose;
    goal.target_pose.pose.position.x = 10;
    goal.target_pose.pose.position.y = 10;
    goal.target_pose.pose.orientation =
        tf::createQuaternionMsgFromRollPitchYaw(0, 0, M_PI);
    moveBaseClient_->sendGoal(goal);
  }
sc::result Navigate::react (const EvActionResult< SmaccMoveBaseActionClient::Result > & ev) [inline]
Definition at line 65 of file example4.cpp.
References smacc::IActionResult::getResult().
  {
      // we only will react when the result is succeeded
      if (ev.getResult() == actionlib::SimpleClientGoalState::SUCCEEDED)
      {
        // ev.resultMessage provides access to the move_base action server result structure
        ROS_INFO("Received event to movebase: %s",ev.getResult().toString().c_str());
        return transit<ExecuteToolState>();
      }
      else
      {
        return forward_event(); // do nothing, the default behavior if you do not specify any return value
      }
  }
Member Data Documentation
smacc::SmaccMoveBaseActionClient * Navigate::moveBaseClient_
Definition at line 28 of file example2.cpp.
The documentation for this struct was generated from the following files:
smacc_sm_examples/sm_smacc_tutorial_examples/src/example2.cpp
smacc_sm_examples/sm_smacc_tutorial_examples/src/example3.cpp
smacc_sm_examples/sm_smacc_tutorial_examples/src/example4.cpp