StAcquireSensors Struct Reference
#include <st_acquire_sensors.h>
Public Types
typedef mpl::list< sc::transition< EvStateFinish< StAcquireSensors >, StNavigateToWaypointsX >, sc::transition< EvKeyPressN< SbKeyboard >, StNavigateToWaypointsX >, sc::custom_reaction< EvTopicMessage< LidarSensor > >, sc::custom_reaction< EvTopicMessage< smacc::SensorTopic< sensor_msgs::Temperature > > > > reactions
Public Member Functions
void onInitialize ()
sc::result react (const EvTopicMessage< LidarSensor > &ev)
sc::result react (const EvTopicMessage< smacc::SensorTopic< sensor_msgs::Temperature >> &ev)
Public Attributes
AllEventAggregator allSensorsReady
Additional Inherited Members
Detailed Description
Definition at line 3 of file st_acquire_sensors.h.
Member Typedef Documentation
typedef mpl::list< sc::transition<EvStateFinish<StAcquireSensors>, StNavigateToWaypointsX>, sc::transition<EvKeyPressN<SbKeyboard>, StNavigateToWaypointsX>, sc::custom_reaction<EvTopicMessage<LidarSensor> >, sc::custom_reaction<EvTopicMessage<smacc::SensorTopic<sensor_msgs::Temperature> > > > StAcquireSensors::reactions
Definition at line 20 of file st_acquire_sensors.h.
Member Function Documentation
void StAcquireSensors::onInitialize () [inline]
Definition at line 24 of file st_acquire_sensors.h.
References SERVICE3_ON, and AllEventAggregator::setTriggerEventTypesCount().
   {
      this->configure<ObstaclePerceptionOrthogonal>(std::make_shared<LidarSensor>());
      this->configure<SensorOrthogonal>(std::make_shared<SbConditionTemperatureSensor>());
      this->configure<KeyboardOrthogonal>(std::make_shared<SbKeyboard>());
      this->configure<PublisherOrthogonal>(std::make_shared<SbStringPublisher>("Hello World!"));
      this->configure<Service3Orthogonal>(std::make_shared<Service3Behavior>(
      Service3Command::SERVICE3_ON));
      allSensorsReady.setTriggerEventTypesCount(2);
   }
sc::result StAcquireSensors::react (const EvTopicMessage< LidarSensor > & ev) [inline]
Definition at line 36 of file st_acquire_sensors.h.
References AllEventAggregator::notify().
   {
      ROS_INFO_ONCE("Lidar sensor is ready");
      if (allSensorsReady.notify(ev))
         this->throwFinishEvent();
      return discard_event();
   }
sc::result StAcquireSensors::react (const EvTopicMessage< smacc::SensorTopic< sensor_msgs::Temperature >> & ev) [inline]
Definition at line 46 of file st_acquire_sensors.h.
References AllEventAggregator::notify().
   {
      ROS_INFO_ONCE("Temperature sensor is ready");
      if (allSensorsReady.notify(ev))
         this->throwFinishEvent();
      return discard_event();
   }
Member Data Documentation
AllEventAggregator StAcquireSensors::allSensorsReady
Definition at line 22 of file st_acquire_sensors.h.
The documentation for this struct was generated from the following file:
smacc_sm_examples/sm_dance_bot/include/sm_dance_bot/states/st_acquire_sensors.h